### ISSUE TITLE
ECONNRESET cпустя минут 5-10 после начала получения свечей из стрима

### ISSUE THREAD

**Issue by NikitaMelnikov** [TinkoffCreditSystems/invest-openapi#1]
{ Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECO
NNRESET', code: 'ECONNRESET', syscall: 'read' }

Спустя минут 5-10 после начала получения свечей из стрима

**Comment by koshkoshka** [comment]
Подписка у меня при этом на 13 свечей (по количеству интервалов) на одну акцию.

**Comment by NikitaMelnikov** [comment]
Можете привести код как воспроизвести? Возможно сетевая проблема и ваша библиотека не обрабатывает переподключение

**Comment by koshkoshka** [comment]
`
const WebSocketClient = require('websocket');
const axios = require('axios');
const readline = require('readline');
const mysql = require('mysql2');
const mysqlUtilities = require('mysql-utilities');
const delay = require('delay');
  
let url='wss://api-invest.tinkoff.ru/openapi/md/v1/md-openapi/ws';
let sandbox="https://api-invest.tinkoff.ru/openapi/sandbox";
let intervals=["1min","2min","3min","5min","10min","15min","30min","hour","2hour","4hour","day","week","month"];

let headers={"Authorization": "Bearer ТУТВСТАВЬТЕТОКЕНSANDBOX"};

let useinstrument='BBG000R607Y3';

let ws = new WebSocketClient.client();
ws.connect(url,[],'',headers);
ws.on('connect',ws1 => {
    ws1.on('message', message => {
        let msg=JSON.parse(message.utf8Data);
        console.log(msg);
        switch(msg.event){
          case 'instrument_info':
            //ТУТ я работаю с SQL
            break;
          case 'candle':
            with(msg.payload){
              let time1=new Date(time).getTime()/1000;
              //тут я работаю с SQL
              
            }
            break;
        }
    });
    ws1.on('error',err => {
      console.log(err);
    });
const orderbook_subscribe=(figi,depth=1)=>{
      ws1.send(JSON.stringify({"event": "orderbook:subscribe","figi": figi,"depth":depth}));
    }
    
    const orderbook_unsubscribe=(figi,depth=1)=>{
      ws1.send(JSON.stringify({"event": "orderbook:unsubscribe","figi": figi,"depth":depth}));
    }
    
    const info_subscribe=(figi)=>{
      ws1.send(JSON.stringify({"event": "instrument_info:subscribe","figi": figi}));
    }
    
    const info_unsubscribe=(figi)=>{
      ws1.send(JSON.stringify({"event": "instrument_info:unsubscribe","figi": figi}));
    }
    
    const candle_subscribe=(figi,interval)=>{
      if(intervals.indexOf(interval)>-1){
        ws1.send(JSON.stringify({"event": "candle:subscribe","figi": figi,"interval":interval}));
      }
    }
    
    const candle_unsubscribe=(figi,interval)=>{
      if(intervals.indexOf(interval)>-1){
        ws1.send(JSON.stringify({"event": "candle:unsubscribe","figi": figi,"interval":interval}));
      }
    }
    intervals.forEach(element =>{
      candle_subscribe(useinstrument,element);
    });
});
ws.on('connectFailed',ws=>{
    console.log(ws);
});
`

**Comment by koshkoshka** [comment]
> Можете привести код как воспроизвести? Возможно сетевая проблема и ваша библиотека не обрабатывает переподключение

Скинул пример кода в Node JS

**Comment by NikitaMelnikov** [comment]
На сколько я понимаю, ваш клиент автоматически не пересоздает подключение, попробуйте этот вариант:  https://github.com/websockets/ws/wiki/Websocket-client-implementation-for-auto-reconnect

**Comment by Gordondalos** [comment]
Спасибо за выложенный пример!!! он работает
