### ISSUE TITLE
Рыночная заявка

### ISSUE THREAD

**Issue by wooloodya** [TinkoffCreditSystems/invest-openapi#103]
Возможно ли с помощью метода `/orders/limit-order` имитировать поведение рыночной заявки, выставив лимит выше рынка?

**Comment by NikitaMelnikov** [comment]
Да, так получится сделать, но в ответе `/orders/limit-order` все равно количество исполненных лотов будет `0`.
При рыночной заявке мы планируем сразу возвращать количество исполненных лотов
