### ISSUE TITLE
Ошибка в sandbox при создании лимитного ордера

### ISSUE THREAD

**Issue by finico** [TinkoffCreditSystems/invest-openapi#104]
`curl -X POST "https://api-invest.tinkoff.ru/openapi/sandbox/orders/limit-order?figi=BBG000C5Z1S3" -H "accept: application/json" -H "Authorization: Bearer <token>" -H "Content-Type: application/json" -d "{\"lots\":1,\"operation\":\"Buy\",\"price\":55.4}"`

```
{
  "trackingId": "39045dde07132edb",
  "payload": {
    "message": "INTERNAL_ERROR",
    "code": "INTERNAL_ERROR"
  },
  "status": "Error"
}
```

**Comment by NikitaMelnikov** [comment]
Починили, проверьте, пожалуйста

**Comment by finico** [comment]
@NikitaMelnikov Работает, спасибо
