### ISSUE TITLE
Версионирование api

### ISSUE THREAD

**Issue by daxartio** [TinkoffCreditSystems/invest-openapi#105]
Предполагается сделать версионирование api?
Последний PR сломал совместимость, это недопустимо!)

**Comment by maksim77** [comment]
Согласен. Например у меня слетел расчет цен облигаций. Да, раньше был баг, сейчас он исправлен и это хорошо, но всё-таки должно быть версионирование.

**Comment by NikitaMelnikov** [comment]
>  Последний PR сломал совместимость, это недопустимо!)

Как именно сломал? Обязательные параметры нигде не добавлялись, урлы не менялись, поля из ответа не добавлялись

**Comment by NikitaMelnikov** [comment]
@maksim77 версионировать API из-за бага, чтобы гарантировать обратное поведение (то есть воспроизведение) не хочется :)

**Comment by maksim77** [comment]
@NikitaMelnikov не согласен.
Смотри, допустим, что у меня с момента выхода API (квартал примерно) работал какой-то бот. Цену по облигациям он учитывал исходя из "/10". Да, это был баг но у меня УЖЕ работал код который этот баг обходил. Вы позавчера изменили API и цена всех облигаций резко выросла в десять раз, что вполне могло послужить триггером на продажу всех бумаг. Да, про это обновление прошёл анонс в телеграмме. Но нельзя же полагаться на то, что все его читают в реальном времени и обладают быстрым доступом к консоли или среде выполнения для внесения изменений в свой код. А если это сервис для третьих лиц то получится, что пока я внесу изменения, пока мои клиенты узнают об этом и обновят или хотя бы остановят свои приложения...

P.S. Пример теоретический – у меня нет торговых ботов, и я не пострадал от этих изменений. Я лишь хочу показать что даже исправление бага (особенно старого) не должно вредить пользователям.

**Comment by NikitaMelnikov** [comment]
Принято, подумаем как версионировать подобные ситуации
