### ISSUE TITLE
Правила sell/short/buy при взаимодействии через API

### ISSUE THREAD

**Issue by ruzzzz6312** [TinkoffCreditSystems/invest-openapi#106]
Здравствуйте коллеги!
Столкнулся с тем, что после включения маржинальной торговли классический алгоритм продажи актива, не смог произвести продажу получив ошибку, ошибка была следующей:
"Недостаточно активов для маржинальной сделки", хотя я собирался продать акцию, купленную ранее (в лонг, за свои деньги), не могли бы вы пожалуйста разъяснить, как продать актив, а как шортить? (соответственно, как докупить, и как покрыть шорт, выкупив его)

**Comment by NikitaMelnikov** [comment]
Обратитесь, пожалуйста, в поддержку через чат приложения. Так будет быстрее, чем тут :)
