### ISSUE TITLE
Добавление доступных бумаг в API с появлением их в мобильном приложении.

### ISSUE THREAD

**Issue by fxpester** [TinkoffCreditSystems/invest-openapi#109]
Сейчас бумаги появляются в API спустя несколько недель после их добавления в мобильное приложение, можно ли убрать/сократить этот срок ?

**Comment by NikitaMelnikov** [comment]
Добрый день,

Сейчас добавление бумаг в OpenApi происходит после 1-3 дней после публикации в мобильном приложении.

Могли бы привести пример  бумаги, которая добавлялась несколько недель?

**Comment by fxpester** [comment]
У меня нет точных данных т.к. я не могу отслеживать точное появление бумаг в приложении.
пример1:
Облигации АФК Система выпуск 12 точно были в приложении на 25.11.2019
В API по https://api-invest.tinkoff.ru/openapi/market/bonds появились только 4.12.2019

пример2:
Облигации Лизинг Трейд точно были в приложении на 3.02.2020
В API нет до сих пор.

**Comment by GUSAR1T0** [comment]
Доброго времени суток,
При запросе на получение портфеля или списка ETF через API столкнулся с тем, что не получаю информацию по новым инструментам от FinEx – **FXRW** и **FXWO**. Хотя в приложении их отслеживать точно можно уже больше 3х дней.

**Comment by swytman** [comment]
Фонд VTBB вроде старый, но его тоже нет нигде, и сделки по нему не отображаются

**Comment by NikitaMelnikov** [comment]
Нашли в чем проблема, поправим

**Comment by NikitaMelnikov** [comment]
Связано с #115
