### ISSUE TITLE
Ограничение 36 свечей для 15-минуток и 45 свечей для часового интервала

### ISSUE THREAD

**Issue by ww33** [TinkoffCreditSystems/invest-openapi#110]
Смущает ограничение на количество возвращаемых свечей — для 15минутки это 36 свечей всего(9часов *4), в то время как для применения инструментов теханализа нужно как минимум 100 и больше. 
Bad candle interval:expected from 15 minutes to 1 day
 
На 36 свечах (9часов *4) нельзя построить Ema (например, 26 и 12) и изучать их пересечение.
Нельзя и отобразить данные в виде графика - он получается слишком короткий.

**Comment by NikitaMelnikov** [comment]
Мы можете запросить нужный промежуток времени несколькими запросами
