### ISSUE TITLE
Не получилось обновить версию SDK

### ISSUE THREAD

**Issue by ILikeGoland** [TinkoffCreditSystems/invest-openapi#111]
После go get github.com/TinkoffCreditSystems/invest-openapi-go-sdk
Написанный код перестал работать в строчке 
   	portfolio, err := api.Portfolio(ctx)

Попытался сделать пример :

        client := sdk.NewRestClient(*token)

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	log.Println("Получение всех брокерских счетов")
	accounts, err := client.Accounts(ctx)
	if err != nil {
		log.Fatalln(errorHandle(err))
	}
	log.Printf("%+v\n", accounts)

	ctx, cancel = context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

Но Accounts - оказался неизвестным методом. Проверил пути, откуда берется код программы rest_client.go - оказалось из старой версии SDK.  Заменил старую версию вручную - скопировал туда все файлы из новой версии. Теперь не понимает errorHandle.

Как сделать пакет работоспособным?

**Comment by maksim77** [comment]
Модули или классический GOPATH?

**Comment by ILikeGoland** [comment]
Я прописал GOPATH

**Comment by NikitaMelnikov** [comment]
@ILikeGoland вы можете один раз запросить https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/user/get_user_accounts и сохранить account.id по типу счета с которым вы работаете, эти id не изменяются

**Comment by NikitaMelnikov** [comment]
Про go.mod и вопросы по go-sdk есть отдельный репозиторий, в котором быстрее получить правильный ответ https://github.com/TinkoffCreditSystems/invest-openapi-go-sdk :)

**Comment by ILikeGoland** [comment]
Мне нужен боевой accountID

**Comment by ILikeGoland** [comment]
И все таки непонятно - как запросить accountID - ввести в свагер токен песочницы или боевой? 
accountID разный для песочницы и боя или это считается один клиент и его счет 
Запутанно как то все

**Comment by ILikeGoland** [comment]
Запросил по токену песочницы. Получил :
 "payload": {
    "message": "Invalid token scopes",
    "code": "GATEWAY_REQUEST_DATA_ERROR"
  },
  "status": "Error"

**Comment by ILikeGoland** [comment]
stream, err := sdk.NewStreamingClient(logger, *token);if err != nil {log.Fatalln(err)};defer stream.Close()
Дает ошибку : 020/02/07 14:40:48 can't connect to wss://api-invest.tinkoff.ru/openapi/md/v1/md-openapi/ws: websocket: bad handshake
