### ISSUE TITLE
Не понял - почему закрыли предытущий мой вопрос об обновлении?

### ISSUE THREAD

**Issue by ILikeGoland** [TinkoffCreditSystems/invest-openapi#112]
Где можно получить ответы?  Если Вы закрываете тему?

stream, err := sdk.NewStreamingClient(logger, *token);if err != nil {log.Fatalln(err)};defer stream.Close()
Дает ошибку : 020/02/07 14:40:48 can't connect to wss://api-invest.tinkoff.ru/openapi/md/v1/md-openapi/ws: websocket: bad handshake

Подозреваю, что это тоже в связи с обновлением

**Comment by ILikeGoland** [comment]
По поводу accountID хотелось бы понять - как его получить.  В закрытой теме я написал результат запроса в свагере

**Comment by maksim77** [comment]
В прошлой теме ведь дали совет где можно получить ответы на вопросы по go-sdk.
Зачем плодить зря темы?

**Comment by ILikeGoland** [comment]
Я не получил ответов на свои вопросы по обновлению API. 
Я предлагал сделать одну тему в которой можно было бы задать любой вопрос, но мне написали что лучше если будет много тем. 
Напишите конкретно - не ссылаясь на закрытую тему - где можно получить ответы.

**Comment by maksim77** [comment]
Вас ответили в каком репозитории следует задавать вопросы по go-sdk.

**Comment by ILikeGoland** [comment]
Вы написали что по поводу go.mod можно получить ответы по адресу который привели. Зашел туда - там ни одной темы. Создал тему по поводу go.mod, получил совет. И все. На остальные вопросы по поводу accountID ответов не получил

**Comment by ILikeGoland** [comment]
Ок. Я так понял, что там можно по поводу SDK спрашивать.  Сейчас продублирую свои вопросы туда
