### ISSUE TITLE
Получение полного портфеля для анализа

### ISSUE THREAD

**Issue by v0id24** [TinkoffCreditSystems/invest-openapi#113]
Добрый день.
Предполагается ли добавление в API выдачи полного текущего портфеля?
Сейчас можно только получить часть портфеля, состоящую из инструментов из основного списка. Также нет и истории сделок по инструментам из расширенного списка, как будто эти сделки не проводились.
Получается, нет полной картины, чтобы проанализировать портфель и посчитать расширенную статистику - для принятия решений.

**Comment by NikitaMelnikov** [comment]
Добрый день,

В OpenApi добавлены только инструменты из общего списка, в ближайшее время не планируем добавлять инструменты из расширенного каталога.

**Comment by griddic** [comment]
А где можно посмотреть что в общем, а что в расширенном списке?

**Comment by NikitaMelnikov** [comment]
В мобильном приложении в каталоге нужно выбрать «премиум», так же все премиум-бумаги помечены золотым Львом 
![Uploading 74409955...]()

**Comment by v0id24** [comment]
может, подскажете, как сейчас проще всего получить портфель?
парсить .xlsx пока самый простой вариант, что я нашёл.
парсить .html личного кабинета проще, но менее безопасно, особенно если пытаться автоматизировать процедуру логина в кабинет.
