### ISSUE TITLE
Нет информации по инструменту ticker=USD000UTSTOM

### ISSUE THREAD

**Issue by paillechat** [TinkoffCreditSystems/invest-openapi#115]
Ранее по этому тикеру была доступна информация о валюте USD, теперь возвращается пустой ответ.

**Comment by NikitaMelnikov** [comment]
Поправили, спасибо

Будет отдельно доработка чтобы ситуация не повторилась. Пока что не закрываю задачу

**Comment by swytman** [comment]
У TCS Group (Tinkoff Bank holder) исчез везде тикер TCS, остался только TCSG

**Comment by swytman** [comment]
О, появился тинькофф
