### ISSUE TITLE
Какие методы в api предназначены для маржинальной торговли?

### ISSUE THREAD

**Issue by proairat** [TinkoffCreditSystems/invest-openapi#122]
Здравствуйте.

Я задал эти же вопросы в https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/issues/16, и получил совет о том, что нужно написать здесь.

Не нашёл в документации методы для маржинальной торговли. Как использовать возможность торговли с плечом посредством вашего api? Я в терминале Тинкофф инвестиции мог включить опцию "Маржинальная торговля" и торговать в шорт или торговать в лонг с плечом. Как мне, используя методы вашего api, сделать это?
https://user-images.githubusercontent.com/48524499/74668369-e83e6880-51c6-11ea-99e0-bdea060ea695.png

**Comment by NikitaMelnikov** [comment]
Добрый день,

Логика выставления заявок соответствует вашей настройке маржинальной торговли, т.е. если маржинальная торговля включена, то вы можете выставлять соответствующие заявки.
В данный момент методов, которые возвращают ликвидный портфель и прочее, нет. О датах добавления пока не могу соориентировать
