### ISSUE TITLE
Хотелось бы чтоб ваше API могло работать на NETCore 2 чтоб писать роботов кроссплатформенных

### ISSUE THREAD

**Issue by cibermax** [TinkoffCreditSystems/invest-openapi#123]
Хотелось бы чтоб ваше API могло работать на NETCore 2 чтоб писать роботов кроссплатформенных

**Comment by NikitaMelnikov** [comment]
Добрый день, наше апи никак не связано с NETCore, мы предоставляем http-интерфейс, вопрос только в реализации протокола.
В качестве ориентира, вы можете использовать https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk
