### ISSUE TITLE
Проблемы с акциями TSCG

### ISSUE THREAD

**Issue by V-B-F** [TinkoffCreditSystems/invest-openapi#124]
У меня в портфеле присутствуют акции TSCG. Какое-то время назад все было хорошо, invest-openapi показывал портфель с этими акциями и /market/search возвращал JSON:
	{
		"figi": "BBGFAKETCSXX",
		"ticker": "TCSG",
		"isin": "TCS7238U2033",
		"minPriceIncrement": 0.2,
		"lot": 1,
		"currency": "RUB",
		"name": "TCS Group (Tinkoff Bank holder)",
		"type": "stock"
	}
В мобильном приложении акции по-прежнему видны,  но в invest-openapi проблемы.
- /portfolio  возвращает список без этих акций
- /market/search/by-figi?figi=BBGFAKETCSXX   -  404 not found HTTP error
- /market/search/by-ticker?ticker=TCSG  - просто ничего не находит, пустой массив.

Очень неприятный баг.
С уважением,
Вадим

**Comment by V-B-F** [comment]
Немного больше информации:

/operations за период дат возвращает покупку акций с  figi BBG005DXJS36.  JSON инструмента:
	{
		"figi": "BBG005DXJS36",
		"ticker": "TCS",
		"isin": "US87238U2033",
		"minPriceIncrement": 0.01,
		"lot": 1,
		"currency": "USD",
		"name": "TCS Group (Tinkoff Bank holder)",
		"type": "stock"
	}
Это неверно. Currency должна быть RUR и ticker TCSG. Именно эта бумага торгуется на московской бирже под ISIN US87238U2033. 
https://www.moex.com/ru/issue.aspx?board=TQBR&code=TCSG

**Comment by lightning95** [comment]
Спасибо за обращение, инструмент TCSG / BBG00QPYJ5H0 был исправлен.
Проверьте, пожалуйста, все ли корректно отображается?

**Comment by V-B-F** [comment]
Да, все поправилось.
Большое спасибо.
