### ISSUE TITLE
Ошибка при получении списка активных заявок

### ISSUE THREAD

**Issue by mmkeeper** [TinkoffCreditSystems/invest-openapi#127]
При наличии заявок на первичное размещение облигаций API не возвращает список текущих заявок

![Screenshot tinkoff investing](https://user-images.githubusercontent.com/2668664/75382502-a78fcf00-58eb-11ea-8da4-7fa8b9e2d371.jpg)

В вызове orders.orders_get происходит ошибка

(500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Wed, 26 Feb 2020 19:50:36 GMT', 'Content-Type': 'application/json', 'Content-Length': '113', 'Cache-Control': 'no-store, no-cache, must-revalidate', 'access-control-allow-methods': 'GET,HEAD,POST,DELETE,OPTIONS,PUT,PATCH', 'access-control-allow-headers': 'accept, content-type, authorization, access-control-allow-headers, x-requested-with', 'access-control-allow-origin': '*'})
HTTP response body: {"trackingId":"-------------","payload":{"message":"INTERNAL_ERROR","code":"INTERNAL_ERROR"},"status":"Error"}

Использую python api, но думаю ошибка общая для всех

**Comment by zlumyo** [comment]
Здравствуйте!
Мы уже обнаружили эту "особенность" и занимаемся её устранением.
@lightning95 проследишь за этой issue ?

**Comment by NikitaMelnikov** [comment]
Поправим на этой неделе

**Comment by lightning95** [comment]
проверьте, пожалуйста, воспроизводится ли теперь эта проблема?
@mmkeeper

**Comment by mmkeeper** [comment]
Спасибо! Проблема решена, список заявок приходит без ошибок, в том же виде как и раньше. Заявки на размещение облигаций в нем отсутствуют.
