### ISSUE TITLE
Информация о цене последней сделки инструмента (rest)

### ISSUE THREAD

**Issue by V-B-F** [TinkoffCreditSystems/invest-openapi#129]
Как мне кажется, текущий API  не предоставляет удобного способа получить цену последней сделки для инструмента. Цена часто бывает нужна чтобы отображать изменения цены в таблице инструментов (например в Tinkoff Investments Terminal это для меня главное окно).

Сейчас в каком-то виде это можно получить  используя /market/candles. Но есть проблемы. Во первых, меньше чем за час не возвращает. Затем, candle  за промежуток времени это не совсем то что нужно. Ну и главное, figi параметер может быть только 1. Учитывая ограничение на количество запросов в минуту, нельзя нормально отображать информацию например для таблицы из 50 инструментов раз в пол-минуты.

Было бы просто замечательно, если бы было что-то вроде /market/lastdeals , где figi параметер мог бы быть множественным, ну или принимать список (значения через запятую). Возвращать, например value (цена последней сделки) и time (время последней сделки).  Ограничить что максимум 100 значений figi может быть. Ну и т.д.

Надеюсь, заинтересуетесь подобным улучшением,
С уважением,
Вадим

**Comment by lightning95** [comment]
Здравствуйте, 
openapi предоставляет возможность получать цены по инструментам в реальном времени, 
https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/#orderbooksubscribe.
Поддерживается подписка на цены по нескольким инструментам.

**Comment by triamazikamno** [comment]
Есть одно некрасивое решение за рамками openapi - долбить каждые пол-минуты https://api.tinkoff.ru/trading/stocks/list?sortType=ByName&orderType=Asc&country=All :)

**Comment by Grapaf** [comment]
> Здравствуйте,
> openapi предоставляет возможность получать цены по инструментам в реальном времени,
> https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/#orderbooksubscribe.
> Поддерживается подписка на цены по нескольким инструментам.

Если я не ошибаюсь там только стакан без цены последней сделки?!

**Comment by V-B-F** [comment]
> Здравствуйте,
> openapi предоставляет возможность получать цены по инструментам в реальном времени,
> https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/#orderbooksubscribe.
> Поддерживается подписка на цены по нескольким инструментам.

Предыдущий автор справедливо заметил что стакан не содержит информацию о последней сделке.  Плюс у меня вопрос, как много подписок можно сделать? Например если 50 инструментов, это нормально?  (можно и на свечи подписаться...)

В целом, получение информации о последней сделки через подписку, мне представляется "как из пушки по воробьям". Нагрузка по производительности для сервера гораздо больше. Как и количество ненужной информации получаемой на клиенте.

Я бы на вашем месте все таки подумал о специальном запросе по последним данным рынка.  В MOEX ISS API , например, такое есть. Я бы сказал "must be" функционал (кстати сейчас именно оттуда я эти данные и беру, но увы, бесплатно данные даются с 15 минутным опозданием).

С уважением,
Вадим

**Comment by V-B-F** [comment]
> 
> 
> Есть одно некрасивое решение за рамками openapi - долбить каждые пол-минуты https://api.tinkoff.ru/trading/stocks/list?sortType=ByName&orderType=Asc&country=All :)

Вот-вот-вот. Не сомневаюсь, близкий к нужному функционал есть. Здесь бы фильтр по тикеру, ну и вишенкой на торте был бы фильтр по полям. А так да, скачивать каждый раз 5М дла 1300 инструментов, это некрасиво. Но в принципе тоже вариант.

**Comment by IncompletableFuture** [comment]
> > Здравствуйте,
> > openapi предоставляет возможность получать цены по инструментам в реальном времени,
> > https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/#orderbooksubscribe.
> > Поддерживается подписка на цены по нескольким инструментам.
> 
> Предыдущий автор справедливо заметил что стакан не содержит информацию о последней сделке. Плюс у меня вопрос, как много подписок можно сделать? Например если 50 инструментов, это нормально? (можно и на свечи подписаться...)
> 
> В целом, получение информации о последней сделки через подписку, мне представляется "как из пушки по воробьям". Нагрузка по производительности для сервера гораздо больше. Как и количество ненужной информации получаемой на клиенте.
> 
> Я бы на вашем месте все таки подумал о специальном запросе по последним данным рынка. В MOEX ISS API , например, такое есть. Я бы сказал "must be" функционал (кстати сейчас именно оттуда я эти данные и беру, но увы, бесплатно данные даются с 15 минутным опозданием).
> 
> С уважением,
> Вадим

Простите, а не ткнете носом, какие энд-поинты отвечают в MOEX ISS API за получение последней цены? Мне всего-то нужен курс доллара и евро последний, но я честно говоря, запутался в их документации.

**Comment by V-B-F** [comment]
Например:
https://iss.moex.com/iss/engines/currency/markets/index/securities.json?iss.meta=off&iss.json=extended

'marketdata' раздел содержит данные по курсам валютам. Примерно с 15 минутным опазданием.
