### ISSUE TITLE
История котировок

### ISSUE THREAD

**Issue by mvkasatkin** [TinkoffCreditSystems/invest-openapi#13]
Очень требуется метод получения истории котировок по определенному инструменту, за определенный промежуток времени, с определенным интервалом (1min, 5min, часовики и тд). Так как подписка на изменение котировки (candle:subscribe) дает только информацию по текущей цене, но нет данных для графика и технического анализа. Очень не хочется для этой цели использовать сторонние api помимо вашего:)

**Comment by NikitaMelnikov** [comment]
Привет! Будет в следующем релизе: https://github.com/TinkoffCreditSystems/invest-openapi/pull/3

**Comment by NikitaMelnikov** [comment]
Добавно в https://github.com/TinkoffCreditSystems/invest-openapi/releases/tag/19.2
