### ISSUE TITLE
Пропали вечные портфели отовсюду

### ISSUE THREAD

**Issue by triamazikamno** [TinkoffCreditSystems/invest-openapi#131]
Добрый день.
До недавнего времени вечные портфели присутствовали в `/portfolio`, `/market/etfs`, `/market/search/by-ticker` и т.д.
Теперь их нет нигде.

**Comment by NikitaMelnikov** [comment]
Добрый день, в данный момент фонды убраны из OpenApi по техническим причинам.
Вернем отображение в `/portfolio` на следующей неделе
