### ISSUE TITLE
Неверный статус торгов после закрытия биржи в Streaming API

### ISSUE THREAD

**Issue by Fatal1ty** [TinkoffCreditSystems/invest-openapi#133]
13 марта после закрытия биржи в 01:45 еще минут 5 по Streaming API приходил InstrumentInfo со статусом "normal_trading". И я даже говорю не о том, что по существующему вебсокету просто не приходило новое событие, а о том, что при новом подключении к вебсокету первым событием приходило событие с неправильным статусом. Через Rest API статус с 01:45 приходил корректный - "NotAvailableForTrading".

Вот что приходило после 01:45:
```json
{"figi": "BBG000B9XRY4", "min_price_increment": 0.01, "lot": 1.0, "trade_status": "normal_trading", "accrued_interest": null, "limit_up": 256.84, "limit_down": 224.8}
```

Где-то в 01:50 событие уже начало приходить с правильным статусом:
```json
{"figi": "BBG000B9XRY4", "min_price_increment": 0.01, "lot": 1.0, "trade_status": "not_available_for_trading", "accrued_interest": null, "limit_up": 257.42, "limit_down": 225.38}
```

**Comment by NikitaMelnikov** [comment]
@necryin

**Comment by necryin** [comment]
В стриме отдаются честные статусы напрямую из биржи, (https://spbexchange.ru/ru/stocks/inostrannye/raspisanie/) Биржа работает до 2:00 но выставить заявку простым смертным можно только до 1:45 . При этом бирже ничто не мешает отдавать статус normal_trading все это время ✝️ . В рестовой части отдаются статусы в соответствии с возможностью брокера выставить заявку.

**Comment by Fatal1ty** [comment]
Придется долбить REST каждую секунду.

**Comment by necryin** [comment]
По статусу из стрима вы можете понять потенциальную возможность выставить заявку. При попытке выстапвить заявку вы можете получить ошибку что торги закрыты от рест части и корректно ее обработать. Зачем долбить рест каждую секунду не понял

**Comment by Fatal1ty** [comment]
> По статусу из стрима вы можете понять потенциальную возможность выставить заявку. При попытке выставить заявку вы можете получить ошибку что торги закрыты от рест части и корректно ее обработать. Зачем долбить рест каждую секунду не понял

Да, вы правы, так проще.
