### ISSUE TITLE
Нулевая цена совершенной сделки

### ISSUE THREAD

**Issue by Fatal1ty** [TinkoffCreditSystems/invest-openapi#135]
Есть очень старый баг, который появляется практически всегда.

При выполнении рыночных сделок API отдает нулевую цену в первые несколько минут после совершения сделки. Заметил это торгуя как через приложение, так и напрямую через API.

К примеру, отправил запрос в `/orders/market-order` на продажу 8 акций AAPL в `2020-03-20T11:22:26+03:00`.
После этого `/operations` несколько минут ничего нового не отдавал. Спустя какое-то время он начал отдавал такой ответ:
```json
{
  "trackingId": "fa0e9456a488983b",
  "payload": {
    "operations": [
      {
        "operationType": "Sell",
        "date": "2020-03-20T11:22:27.423966+03:00",
        "isMarginCall": false,
        "instrumentType": "Stock",
        "figi": "BBG000B9XRY4",
        "quantity": 8,
        "price": 0,
        "payment": 0,
        "currency": "USD",
        "status": "Done",
        "id": "111460890970"
      }
    ]
  },
  "status": "Ok"
}
```
как видим, `price` здесь нулевой. Вот что видит пользователь в приложении:

![IMG_2895](https://user-images.githubusercontent.com/323962/77148997-b9efc980-6aa1-11ea-954c-d2e684f5f22c.png)

еще через несколько минут `/operations` стал отдавать уже другой ответ, причем ID операции тот же:
```json
{
  "trackingId": "358451dc1ccbf861",
  "payload": {
    "operations": [
      {
        "operationType": "Sell",
        "date": "2020-03-20T11:22:27.423966+03:00",
        "isMarginCall": false,
        "instrumentType": "Stock",
        "figi": "BBG000B9XRY4",
        "quantity": 8,
        "price": 0,
        "payment": 0,
        "currency": "USD",
        "commission": {
          "currency": "USD",
          "value": -1.03
        },
        "trades": [
          {
            "tradeId": "375171460",
            "date": "2020-03-20T11:22:27.423966+03:00",
            "quantity": 8,
            "price": 256.71
          }
        ],
        "status": "Done",
        "id": "111460890970"
      },
      {
        "operationType": "BrokerCommission",
        "date": "2020-03-20T11:22:27.423966+03:00",
        "isMarginCall": false,
        "instrumentType": "Stock",
        "figi": "BBG000B9XRY4",
        "payment": -1.03,
        "currency": "USD",
        "status": "Done",
        "id": "-1"
      }
    ]
  },
  "status": "Ok"
}
```
но и тут все еще `price` нулевой. Вот что теперь видит пользователь в приложении:

![IMG_2897](https://user-images.githubusercontent.com/323962/77149115-eefc1c00-6aa1-11ea-950c-c1ee8a6ba985.png)

Этому багу уже несколько месяцев, все пользователи ждут с нетерпением, когда это будет исправлено.

**Comment by Fatal1ty** [comment]
Спустя три часа `/operations` и мобильное приложение на iOS стали показывать нормальную цену:
```json
{
  "trackingId": "c9a7f030d970b83f",
  "payload": {
    "operations": [
      {
        "operationType": "Sell",
        "date": "2020-03-20T11:22:27.423966+03:00",
        "isMarginCall": false,
        "instrumentType": "Stock",
        "figi": "BBG000B9XRY4",
        "quantity": 8,
        "price": 256.71,
        "payment": 2053.68,
        "currency": "USD",
        "commission": {
          "currency": "USD",
          "value": -1.03
        },
        "trades": [
          {
            "tradeId": "375171460",
            "date": "2020-03-20T11:22:27.423966+03:00",
            "quantity": 8,
            "price": 256.71
          }
        ],
        "status": "Done",
        "id": "111460890970"
      },
      {
        "operationType": "BrokerCommission",
        "date": "2020-03-20T11:22:27.423966+03:00",
        "isMarginCall": false,
        "instrumentType": "Stock",
        "figi": "BBG000B9XRY4",
        "payment": -1.03,
        "currency": "USD",
        "status": "Done",
        "id": "-1"
      }
    ]
  },
  "status": "Ok"
}
```
![IMG_2901](https://user-images.githubusercontent.com/323962/77161290-558d3400-6aba-11ea-8ba0-6730c0610607.png)

**Comment by ivanchikhina** [comment]
У меня было то же самое 17.03.2020 16:34 на продаже SEDG

**Comment by NikitaMelnikov** [comment]
Добрый день,
Подскажите, вы обращались в нашу поддержку с этой информацией?

**Comment by Fatal1ty** [comment]
@NikitaMelnikov нет, это же касается API, а скриншоты я просто для наглядности привел.

**Comment by NikitaMelnikov** [comment]
@Fatal1ty напишите пожалуйста в нашу поддержку, при исправлении ситуации вас оповестят.
Проблема не совсем относится к OpenApi, поэтому закрываю тикет
