### ISSUE TITLE
Возможность подписаться на тиковые данные?

### ISSUE THREAD

**Issue by ProgrammingLife** [TinkoffCreditSystems/invest-openapi#136]
Есть ли возможность подписаться на тиковые данные? Либо каким-то образом получать их.

Возможность интересует относительно node.js реализации.

**Comment by sergeykorobeynikov** [comment]
Очевидно, нужно как-то подписаться на интересуемые ценные бумаги по FIGI, но как это сделать не совсем ясно, либо этот функционал, по крайней мере в C# версии не реализован. Поддерживаю вопрос.

**Comment by sergeykorobeynikov** [comment]
static void Main(string[] args)
        {
            var sandboxToken = "t.XXXXX";
            var connection = ConnectionFactory.GetSandboxConnection(sandboxToken);
            var context = connection.Context;
            
            context.StreamingEventReceived += Context_StreamingEventReceived;

            string figi = "BBG004731489";
            int depth = 1;
            
            var candleSubscribeRequest = new CandleSubscribeRequest(figi, CandleInterval.Minute);
            var candleUnsubscribeRequest = new CandleUnsubscribeRequest(figi, CandleInterval.Minute);
            var orderbookSubscribeRequest = new OrderbookSubscribeRequest(figi, depth);
            var orderbookUnsubscribeRequest = new OrderbookUnsubscribeRequest(figi, depth);
            var instrumentInfoSubscribeRequest = new InstrumentInfoSubscribeRequest(figi);
            var InstrumentInfoUnsubscribeRequest = new InstrumentInfoUnsubscribeRequest(figi);

            context.SendStreamingRequestAsync(candleSubscribeRequest);

            Console.WriteLine("Running...");
            Console.ReadLine();
        }

        private static void Context_StreamingEventReceived(object sender, StreamingEventReceivedEventArgs e)
        {
            switch (e.Response.Event)
            {
                case "candle":
                    var candleResp = ((CandleResponse)e.Response).Payload;
                    Console.WriteLine("{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t{6}\t{7}", candleResp.Figi, candleResp.Interval, candleResp.Time, candleResp.Volume, candleResp.Open, candleResp.Low, candleResp.High, candleResp.Close);
                    break;

                default:
                    break;
            }
        }

**Comment by ProgrammingLife** [comment]
@sergeykorobeynikov, неплохо, но там же подписка на свечи? А их минимальный интервал: 1 минута, т.о. котировки будут получаться раз в минуту?

**Comment by ProgrammingLife** [comment]
В идеале бы добавить в orderBook параметр lastPrice

**Comment by mvkasatkin** [comment]
@ProgrammingLife, в candle subscribe вы получаете данные каждый тик, то есть ohlcv обновляются в рамках текущего периода (например минуты или часа). В следующий период, high, low и volume начинают считаться заново

**Comment by sergeykorobeynikov** [comment]
т.е. в CandleInterval.Minute нужен для расчёта Low/High
Вообще это крайне странно и неразумно выглядит.
Вы бы только тиковые и объём гнали, и то в бинарном виде, а не "всю аналитику" по JSON.
В таком духе никаких мощностей может не хватить.
