### ISSUE TITLE
Генерация C# SDK

### ISSUE THREAD

**Issue by cia76** [TinkoffCreditSystems/invest-openapi#141]
Хочу сгенерировать в Swagger из YAML C# SDK. Генерирует, но полученные классы отличаются от тех, что у вас в репозитарии https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk

Для чего это нужно. В спецификации есть функция получения номера счета. В nuget package ее нет. Можно собрать SDK из исходников, но получается модель отличная от вашей.

Подскажите, пожалуйста, с какими параметрами было генерирование SDK.

**Comment by cia76** [comment]
Для чего это нужно. В спецификации есть функция получения номера счета. В nuget package ее нет. Можно собрать SDK из исходников, но получается модель отличная от вашей.

**Comment by NikitaMelnikov** [comment]
Добрый день,

c#-sdk не был сгенерирован, поэтому классы отличаются
