### ISSUE TITLE
неверное значение quantity для исполненной заявки

### ISSUE THREAD

**Issue by zcoder** [TinkoffCreditSystems/invest-openapi#147]
для исполненной заявки в интерфейсе все верно (купил Ford 12 шт по $5.7), а в получаемых через api данных видно quantity == 1000, при этом в trades 12. При этом точно помню что конкретно эта сделка была на 12 акций.
Из интересного и непонятного: Почему не была взята комиссия ?

вот данные:

`{"operationType":"Buy","date":"2020-03-12T10:44:50.254161+03:00","isMarginCall":false,"instrumentType":"Stock","figi":"BBG000BQPC32","quantity":1000,"price":5.7,"payment":-68.4,"currency":"USD","trades":[{"tradeId":"348537680","date":"2020-03-12T10:45:12.398845+03:00","quantity":12,"price":5.7}],"status":"Done","id":"108017785800"}`

_Originally posted by @zcoder in https://github.com/TinkoffCreditSystems/invest-openapi/issues/18#issuecomment-602232902_

**Comment by deniro98** [comment]
Так в trades и написано, что 12 акций.
Trades - это по факту проведенные сделки с вашей заявкой.

**Comment by zcoder** [comment]
почему "quantity":1000 если я давал заявку на 12 ?

**Comment by NikitaMelnikov** [comment]
@zcoder обратитесь в поддержку через сайт или мобильное приложение, коллеги подскажут почему так
