### ISSUE TITLE
Какой командой посмотреть минимальную и макс цену?

### ISSUE THREAD

**Issue by okosoft** [TinkoffCreditSystems/invest-openapi#149]
Какой командой посмотреть минимальную и макс цену по инструменту на текущий день/время?

**Comment by NikitaMelnikov** [comment]
Добрый день, 
https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_candles

**Comment by okosoft** [comment]
Вопрос не в OHLC.
Допустим по API пытаемся поставить цену продажи 90 рублей, а она выше 84 рублей не принимает. И то же самое на покупку ниже 57 рублей не принимает, а мы хотим поставить 40. Как границы min max можно узнать которые в данный момент принимает биржа?

**Comment by NikitaMelnikov** [comment]
https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/


payload.limit_up | double | - | Верхняя граница заявки. Возвращается только для RTS инструментов
-- | -- | -- | --
payload.limit_down | double | - | Нижняя граница заявки. Возвращается только для RTS инструментов

**Comment by okosoft** [comment]
А для других инструментов она не устанавливается биржами? Или она есть, но её невозможно получить?

**Comment by okosoft** [comment]
Эти данные только через подписку через websocket получаются? Через REST запрос можно как то получить?

**Comment by NikitaMelnikov** [comment]
> А для других инструментов она не устанавливается биржами? Или она есть, но её невозможно получить?

Все верно, MOEX такие данные, к сожалению не отдает

**Comment by NikitaMelnikov** [comment]
> Эти данные только через подписку через websocket получаются? Через REST запрос можно как то получить?

В REST так же есть https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_orderbook

Но там по сути те же данные, что и в стриминге
