### ISSUE TITLE
Новые методы в C# SDK + вопрос по привязке позиций к счету

### ISSUE THREAD

**Issue by cia76** [TinkoffCreditSystems/invest-openapi#152]
В SDK реализовал методы выставления лимитных заявок и получение номера счета. Если хотите, могу отправить изменения.

Немного непонятна привязка позиций к счету. Как я понял, счетов может быть несколько. Например, обычный и ИИС. Мы получаем оба. По обоим есть 3 валюты: рубли, доллары и евро. Как понять, к какому счету привязана каждая позиция?

**Comment by NikitaMelnikov** [comment]
> В SDK реализовал методы выставления лимитных заявок и получение номера счета. Если хотите, могу отправить изменения.

Было бы отлично :)

> Немного непонятна привязка позиций к счету.

Каждый запрос к OpenApi работает одновременно только с одним счетом, т.е. вы получаете данные только по выбранному счету. Если не указан `brokerAccountId`, то работа происходит с обычным брокерским счетом

**Comment by cia76** [comment]
Тогда что-то не сходится. В документации на /portfolio есть опциональный параметр brokerAccountId. В C# SDK вижу другое:

`        public async Task<Portfolio> PortfolioAsync()
        {
            var response = await Connection.SendGetRequestAsync<Portfolio>(Endpoints.Portfolio).ConfigureAwait(false);
            return response?.Payload;
        }`

Никаких параметров не предусмотрено. Чему верить?

Как передать изменения? Делаю push в Git, но у меня полномочий нет.

**Comment by NikitaMelnikov** [comment]
В C# пока что не добавили прокидывание параметра `brokerAccountId`

**Comment by doonay** [comment]
В Python очевидно тоже? Полдня ломал голову, как прикрутить brokerAccountId, не могу получить данные ИИС, а в Swagger при этом отрабатывается нормально. Может я как то не правильно пытаюсь задать параметр?
Пробовал:
client.portfolio.portfolio_get(brokerAccountId='201821878')
client.portfolio.portfolio_get('201821878')
и даже (извиняюсь) так: client.portfolio.portfolio_get(201821878)

**Comment by doonay** [comment]
> В C# пока что не добавили прокидывание параметра `brokerAccountId`
В Python очевидно тоже? Полдня ломал голову, как прикрутить brokerAccountId, не могу получить данные ИИС, а в Swagger при этом отрабатывается нормально. Может я как то не правильно пытаюсь задать параметр?
Пробовал:
client.portfolio.portfolio_get(brokerAccountId='201821878')
client.portfolio.portfolio_get('201821878')
и даже (извиняюсь) так: client.portfolio.portfolio_get(201821878)
Может надо первоначально как то хитро клиента завести с привязкой к ИИС? Но там тоже принимается только один параметр - токен.

**Comment by NikitaMelnikov** [comment]
@doonay у нас нет официального python-sdk, лучше узнать у авторов вашей библиотеки когда они поддержат новые параметры :)

**Comment by daxartio** [comment]
Посмотри на мою реализацию)
