### ISSUE TITLE
500 ошибка при вызове /market/candles

### ISSUE THREAD

**Issue by okosoft** [TinkoffCreditSystems/invest-openapi#153]
Делаю запрос 
/market/candles/figi=AAPL&to=2020-03-25T19:04:10-04:00&from=2020-03-28T19:04:10-04:00&interval=15min

/market/candles/figi=BBG004S683W7&to=2020-03-25T19:04:10-04:00&from=2020-03-28T19:04:10-04:00&interval=15min

получаю 500 ошибку. в чем может быть ошибка?

**Comment by okosoft** [comment]
Ваш пример https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_candles кстати тоже не отдаёт свечи. Проверьте пожалуйста.

**Comment by NikitaMelnikov** [comment]
Могли бы привести текст ошибки?

**Comment by okosoft** [comment]
500 Internal Service Error

**Comment by NikitaMelnikov** [comment]
В описании схемы в сваггере указаны интервалы

```

    1min [1 minute, 1 day]
    2min [2 minutes, 1 day]
    3min [3 minutes, 1 day]
    5min [5 minutes, 1 day]
    10min [10 minutes, 1 day]
    15min [15 minutes, 1 day]
    30min [30 minutes, 1 day]
    hour [1 hour, 7 days]
    day [1 day, 1 year]
    week [7 days, 2 years]
    month [1 month, 10 years]
```
