### ISSUE TITLE
Перестает обновляться orderbook , streamingevent, C#

### ISSUE THREAD

**Issue by llotar** [TinkoffCreditSystems/invest-openapi#154]
Добрый день,
Перестают приходить события для orderbook. Причем если попыться отписаться от события для того чтобы подписаться снова, то получают WebSocketException - ...socket is in aborted state.. 
Вопрос - если вдруг что то случилось с соединением, восстанавливается коннект автоматически?
Или надо пересоздавать Context?

**Comment by NikitaMelnikov** [comment]
Задайте вопрос в репозитории c#-sdk, пожалуйста
