### ISSUE TITLE
Заявка отклонена. [SPBEX][1217]: Неверный параметр time_in_force для инструмента.

### ISSUE THREAD

**Issue by svetlyak40wt** [TinkoffCreditSystems/invest-openapi#156]
Сейчас пытался выставить market-order на Ford через API и словил такую ошибку:

```lisp
(:|status| "Ok" :|payload|
 (:|executedLots| 0 :|requestedLots| 10 :|message|
  "Заявка отклонена. [SPBEX][1217]: Неверный параметр time_in_force для инструмента."
  :|rejectReason| "Unknown" :|status| "Rejected" :|operation| "Buy" :|orderId|
  "807035150648364695")
 :|trackingId| "435750ba8a0e4a34")
```

Поиском в интернете [нашёл, что это возможно какие-то проблемы с Спб биржей](https://forum.quik.ru/forum1/topic3646/) и возможно им нужно какой-то дополнительный параметр прокидывать. В API тинькова такого нет.

Можно это как-то починить?

**Comment by svetlyak40wt** [comment]
Кстати, и наверное не круто, что несмотря на отклонённую заявку, ручка вернула HTTP код `200` и `status = "Ok"`?

**Comment by svetlyak40wt** [comment]
Так, ну а теперь, после 16:00, попытка выставить market ордер заканчивается не ошибкой, а 
 статусом "Cancelled":

```lisp
(:|status| "Ok" :|payload|
 (:|commission| (:|value| 0 :|currency| "USD") :|executedLots| 0
  :|requestedLots| 1 :|status| "Cancelled" :|operation| "Buy" :|orderId|
  "116569874130")
 :|trackingId| "cc96982d79466f1d")
200
```

Это у чему вообще? Почему так? Что делать?

**Comment by svetlyak40wt** [comment]
А 10 лотов – купилось.

**Comment by svetlyak40wt** [comment]
Так, теперь пытаюсь 5 лотов продать по рыночной цене.

Попытка номер 1 "сфелилась", как Canceled:

```lisp
(:|status| "Ok" :|payload|
 (:|commission| (:|value| 0 :|currency| "USD") :|executedLots| 0
  :|requestedLots| 5 :|status| "Cancelled" :|operation| "Sell" :|orderId|
  "116574481970")
 :|trackingId| "8cc2ca121c40ed75")
```

Вторая такая же попытка – прошла как надо:

```lisp
(:|status| "Ok" :|payload|
 (:|commission| (:|value| 0 :|currency| "USD") :|executedLots| 5
  :|requestedLots| 5 :|status| "Fill" :|operation| "Sell" :|orderId|
  "116574606460")
 :|trackingId| "b25bc530ba3f0bd0")
```

Как с таким API можно работать?

**Comment by NikitaMelnikov** [comment]
Дело не в OpenApi, обратитесь, пожалуйста, в нашу поддержку на сайте или через мобильное приложение. Коллеги помогут

**Comment by svetlyak40wt** [comment]
@NikitaMelnikov  но почему же тогда сегодня после 16:00 всё заработало?

**Comment by NikitaMelnikov** [comment]
@svetlyak40wt коллеги из поддержки смогут детальней предоставить более подробную информацию по причине :)
