### ISSUE TITLE
Токен на чтение

### ISSUE THREAD

**Issue by singleton11** [TinkoffCreditSystems/invest-openapi#157]
Привет, хочу сделать аналитический сервис, и хочу пользоваться им не один, как минимум друзей и семью позвать, но токен предоставляет полный доступ к БС, хотелось бы, для того, чтобы люди чувствовали себя безопасно, чтобы была возможность выписать себе токен только на чтение, чтобы сервис мог его использовать без риска для пользователей получить неожиданные сделки

**Comment by NikitaMelnikov** [comment]
https://github.com/TinkoffCreditSystems/invest-openapi/issues/12

**Comment by singleton11** [comment]
Спасибо!
