### ISSUE TITLE
Как правильно активировать Subscription? java API

### ISSUE THREAD

**Issue by shockerface** [TinkoffCreditSystems/invest-openapi#160]
Здравствуйте,
Для того, чтобы начать получать объекты из StreamingContext нам необходимо вызвать метод org.reactivestreams.Subscription.request(n), где n - общее кол-во сообщений с объектами подписки, которое нам надо получить. Объект с интерфейсом org.reactivestreams.Subscription мы получаем в методе onSubscribe нашей реализации интерфейса org.reactivestreams.Subscriber. Казалось бы onSubscribe - это удобное место для вызова Subscription.request(n), но так не работает: если это сделать, то onSubscribe зацикливается. 
Вопрос: в какой момент правильнее всего вызывать Subscription.request(n)?

Максим.

**Comment by zlumyo** [comment]
Здравствуйте!
Вопрос связанный с Java SDK лучше, конечно, задать на [странице самого проекта](https://github.com/TinkoffCreditSystems/invest-openapi-java-sdk). Однако, я всё равно отвечу.
Данный вопрос больше затрагивает устройство [reactive-streams библиотеки и её правил](https://github.com/reactive-streams/reactive-streams-jvm/blob/master/README.md), которые она устанавливает.
Реализация интерфейсов этой библиотеки в текущем проекте "вдохновлена" [примерами](https://github.com/reactive-streams/reactive-streams-jvm/tree/master/examples/src/main/java/org/reactivestreams/example/unicast), которые представлены в коде самой библиотеки. Там очень подробные комментарии, которые объясн.т суть происходящего.
