### ISSUE TITLE
Поддержка более безопасных способов авторизации чем Bearer

### ISSUE THREAD

**Issue by homm** [TinkoffCreditSystems/invest-openapi#161]
Ни в документации, ни в других библиотеках я не нашел более безопасного способа авторизации чем через Authorization: Bearer с незашифрованной передачей токена.

Я понимаю, что токен шифруется на уровне HTTPS-соединения, однако при такой передаче он виден в значительно большем количестве мест (стек и локальные переменные клиента, фронтенд-сервера со стороны API) и подвержен значительно большему количеству атак.

Подпись запроса с помощью токена без его передачи позволит:
1. в принципе исключить перехват токена на участке от приложения клиента до конца цепочки запроса.
2. даже если запрос каким-то образом перехвачен, исключается использование скомпрометированного запроса для совершения других запросов.
3. если в подписи используется дата отправки запроса, исключается так же повторная отправка перехваченного запроса.

Вопрос, какую авторизация выбрать, требует дальнейшего изучения, варианты можно найти тут: https://developer.mozilla.org/ru/docs/Web/HTTP/Авторизация#Authentication_schemes
Как пример простой и эффективной авторизации: https://uploadcare.com/docs/api_reference/rest/requests_auth/#auth-uploadcare

**Comment by NikitaMelnikov** [comment]
Добрый день,

Из перечисленных вами примеров ничего не является стандартом.
Bearer-токен является https://tools.ietf.org/html/rfc6750

**Comment by homm** [comment]
Ну во-первых, вы используете Bearer токен не по стандарту.

> In the general case, before a client can access a protected resource, it must first obtain an authorization grant from the resource owner and then exchange the authorization grant for an access token.  The access token represents the grant's scope, duration, and other attributes granted by the authorization grant.

> In some cases, a client can directly present its own credentials to an authorization server to obtain an access token without having to first obtain an authorization grant from a resource owner.

> This abstraction enables issuing access tokens valid for a short time period

У вас нет Authorization Server, а токены живут не короткое время, а выдаются не клиенту, а пользователю в сыром виде, в виде текста.

Во-вторых многое из списка на MDN все же является стандартом, так как входит в регистр схем аутентификации.

https://tools.ietf.org/html/rfc7235#section-5

> 5.1.  Authentication Scheme Registry

The "Hypertext Transfer Protocol (HTTP) Authentication Scheme Registry" defines the namespace for the authentication schemes in challenges and credentials.  It has been created and is now maintained at <http://www.iana.org/assignments/http-authschemes>.

И более того, я пока не вижу указаний на то, что использование каких-то своих схем противоречит стандарту.

**Comment by NikitaMelnikov** [comment]
@homm 

> У вас нет Authorization Server

Есть :)

> а токены живут не короткое время

Все так, токены живут год, отозвать их можно https://id.tinkoff.ru/account.
Это сделано для простоты выпуска токена.
В процессе задача на выпуск refresh_token для OpenApi и обмена его на access_token для работы.

> и выдаются не клиенту, а пользователю в сыром виде, в виде текста.

Все так, это так же сделано для облегчения процесса интеграции. 
Токен можно перехватить, только подменив сертификат и перехватим трафик между клиентом и сервером.

**Comment by enlait** [comment]
> и выдаются не клиенту, а пользователю в сыром виде, в виде текста

Уточню что тут технически происходит: токены выдаются клиенту, только это клиент на стороне бекенда опен апи. Дальше клиент, вместо того чтобы фиксировать токен к user agent (например поставить куку браузера) - выдает токен на руки конечному пользователю для использования как API Key.

**Comment by homm** [comment]
@enlait внутренняя кухня не имеет никакого отношения к делу. Клиент — это приложение на стороне пользователя, которое обращается к серверу OpenApi. Не путайте понятия и не вводите в заблуждение пожалуйста )

**Comment by NikitaMelnikov** [comment]
Менять способ авторизации пока не планируем
