### ISSUE TITLE
Streaming: инвалидный instrument_info:subscribe не выдаёт ошибки

### ISSUE THREAD

**Issue by lolpoi** [TinkoffCreditSystems/invest-openapi#163]
`{"event": "instrument_info:subscribe", "figi": "NOOOOOOO", request_id": "123"}`

Да и на валидный ничего не приходит. Он вообще работает, или присылает что-то только при изм. статуса инструмента?

**Comment by lolpoi** [comment]
О боже мой, только сейчас заметил недостающую двойную кавычку...

Добавьте нормальный бинарный протокол пожалуйста. :(

**Comment by NikitaMelnikov** [comment]
Бинарный протокол очень сильно повышает порог входа, но сейчас мы в процессе рассмотрения v2 на основе grpc
