### ISSUE TITLE
Выставление баланса в RUB

### ISSUE THREAD

**Issue by antaresm** [TinkoffCreditSystems/invest-openapi#165]
После выполнения запроса /sandbox/currencies/balance с данными
_{
  "currency": "RUB",
  "balance": 100000
}_
Приходит положительный ответ
_{
    "trackingId": "48d910bd124818b0",
    "payload": {},
    "status": "Ok"
}_

Но в запросе портфеля рубли не отображаются
_{
    "trackingId": "60ab9426db1c9d95",
    "payload": {
        "positions": []
    },
    "status": "Ok"
}_

**Comment by KirillKaverin** [comment]
@antaresm 
Вы делаете запрос на получение портфеля по адресу /portfolio (вернёт портфель бумаг), для получения балансов нужно обращаться по адресу /portfolio/currencies 
Подробней на официальной документации: https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/
