### ISSUE TITLE
Лента сделок

### ISSUE THREAD

**Issue by felixrap** [TinkoffCreditSystems/invest-openapi#167]
Добрый день. Тут где-то был пост с вопросом о ленте сделок, но не смог его найти. Подскажите, удалось реализовать ленту в api?

**Comment by NikitaMelnikov** [comment]
Добрый день, пока что эта функциональность на холде. Пока что не буду закрывать тикет, потом свяжу с оригинальным

**Comment by ProgrammingLife** [comment]
Очень было бы полезно, если бы удалось.

**Comment by brainmosk** [comment]
Присоединяюсь к просьбе

**Comment by NikitaMelnikov** [comment]
https://github.com/TinkoffCreditSystems/invest-openapi/issues/22
