### ISSUE TITLE
История изменения портфеля (стоимость купленных акций)

### ISSUE THREAD

**Issue by v-crys** [TinkoffCreditSystems/invest-openapi#168]
Добрый день!
В приложении возможно посмотреть историю покупок/продаж определенного актива. Возможно ли это как то сделать через Api?
В первую очередь интересует получение информации о цене, за которую были куплены акции.

**Comment by KirillKaverin** [comment]
@v-crys 
Можно через /portfolio получить текущий портфель с ценами, а также через /operations получить сделки по определенному FIGI и промежутку дат.
Подробнее с примерами запросов и ответов: https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/
