### ISSUE TITLE
Отсутствие имён активов в результатах GET /portfolio

### ISSUE THREAD

**Issue by yutkin** [TinkoffCreditSystems/invest-openapi#17]
Сейчас в результатах `GET /portfolio` отсутствуют имена активов. Чтобы их получить, приходится делать дополнительные запросы в API (например в `GET /market/search/by-figi`). Если добавлять имена активов в результат `/portfolio`, то это упростит клиентский код и снизит нагрузку на ваш backend.

**Comment by NikitaMelnikov** [comment]
https://github.com/TinkoffCreditSystems/invest-openapi/releases/tag/20.1
