### ISSUE TITLE
Вопрос по WebSocket

### ISSUE THREAD

**Issue by SergeyBruhanov** [TinkoffCreditSystems/invest-openapi#171]
Как передать токен в заголовок при подключении через WebSocket на JavaScript?

**Comment by KirillKaverin** [comment]
@SergeyBruhanov есть официальный SDK для JS https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk
Подробней можно посмотреть:
Заголовки: https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/6da81140c83d14d239050d6c0039b09158a4c9ad/src/OpenAPI.ts#L63-L65
Создание подключения с заголовками: https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/6da81140c83d14d239050d6c0039b09158a4c9ad/src/OpenAPI.ts#L77-L80
