### ISSUE TITLE
Объем свечей в лотах, а не в акциях.

### ISSUE THREAD

**Issue by pkosukhin** [TinkoffCreditSystems/invest-openapi#179]
Отдавать объем свечи в лотах - глупость. Цена же отдается за акцию, а не за лот. Как оказывается, в терминале то же самое, т.е. это не косяк API, а системы в целом. Я понимаю, что есть размер лота, только лотность может меняться.
https://www.moex.com/n24501/?nt=111
Что и требовалось доказать
Новатэк (NVTK, figi BBG00475KKY8)
![image](https://user-images.githubusercontent.com/7215420/79751000-8a3f1600-831a-11ea-8265-2b3468292be5.png)

Через API то же самое видим
![image](https://user-images.githubusercontent.com/7215420/79751519-629c7d80-831b-11ea-9dd5-6985e72595db.png)

Лот увеличили в 10 раз - объемы выросли в 10 раз. Истории лотности нет в API.

**Comment by NikitaMelnikov** [comment]
Меня это в данный момент не планируем
