### ISSUE TITLE
Увеличение периода запроса из-за нерабочих дней

### ISSUE THREAD

**Issue by Vassiliev99** [TinkoffCreditSystems/invest-openapi#181]
Если запросить недельные свечи с 2018-4-1 до 2020-4-1, получаю ответ "Bad candle interval: from=2018-04-02T00:00:00Z to=2020-04-06T00:00:00Z expected from 7 days to 2 years". 
А запрос с 2018-4-20 по 2020-4-20 обрабатывается корректно.
То есть запрашиваемый период увеличивается из-за нерабочих дней и поэтому получаю ошибку, хотя в обоих запросах длина периода одинаковая.
Не лучше было бы уменьшать период?

**Comment by deniro98** [comment]
Попробуйте уменьшить период на своей стороне, увеличив количество запросов

**Comment by Vassiliev99** [comment]
> Попробуйте уменьшить период на своей стороне, увеличив количество запросов

Это понятно. Тут вопрос в том, что мне, как пользователю, было бы удобней не думать о том, на какие дни приходятся концы периода, когда я задаю корректный период в 2 года

**Comment by NikitaMelnikov** [comment]
Пока не планируем менять логику
