### ISSUE TITLE
В истории операций песочницы нет сделок по заявкам Buy

### ISSUE THREAD

**Issue by SergeyBruhanov** [TinkoffCreditSystems/invest-openapi#183]
Заявки, исполняемые в песочнице, в истории операций есть только если это заявки с видом операции "продать", а "покупок" не сохраняется. 
Можно ли добавить? То хотелось бы проверять операции для отладки демо-счета в песочнице.

**Comment by NikitaMelnikov** [comment]
Можете подробней описать кейс? Какие запросы делаете и какие данные ожидаете

**Comment by SergeyBruhanov** [comment]
1. Устанавливаю баланс валюты Рубль в песочнице
2. Покупаю акцию российской компании через лимитную заявку
3. Продаю акцию этой компании через лимитную заявку
4. Получаю список операций по счету песочницы, в нем нет операций по покупке

**Comment by SergeyBruhanov** [comment]
Писал в техподдержку - ответили, что исправили. Пересоздал тестовый счет, проверил, сейчас операции с типом "покупка" в списке операций присутствуют.
