### ISSUE TITLE
Список избранных инструментов

### ISSUE THREAD

**Issue by sunr1ze** [TinkoffCreditSystems/invest-openapi#185]
Есть ли возможность получить список инструментов, добавленных в избранное? Если нет, то планируется ли такой функционал?

**Comment by NikitaMelnikov** [comment]
Пока что не планируем добавлять

**Comment by Tauxxx** [comment]
Изменилась ли позиция в настоящий момент?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, пока нет
