### ISSUE TITLE
Курс одной валюты по отношению к другой

### ISSUE THREAD

**Issue by Anton-Cherepkov** [TinkoffCreditSystems/invest-openapi#187]
Добрый день.

Есть ли возможность через API получить курс валюты к другой валюте? Необходимо, чтобы получить долларовый эквивалент для позиций по кэшу.

**Comment by NikitaMelnikov** [comment]
Добрый день, если речь про курс на бирже, то можно получить FIGI https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_currencies
и потом запросить свечи https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_candles
