### ISSUE TITLE
У операций PayIn в поле date прилетает дата без секунд а это не по RFC

### ISSUE THREAD

**Issue by svetlyak40wt** [TinkoffCreditSystems/invest-openapi#19]
Прилетает вот такое:

```
2019-05-24T12:58+03:00
```

Тут нет секунд.

У меня на этом библиотека для парсинга дат ломается.

**Comment by NikitaMelnikov** [comment]
Добрый день, о каком RFC речь?

**Comment by ZergsLaw** [comment]
Известно примерная дата починки?

**Comment by ZergsLaw** [comment]
Есть примерная информация по времени починки?

**Comment by NikitaMelnikov** [comment]
На этой неделе постараемся 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NikitaMelnikov** [comment]
Пофиксили https://github.com/TinkoffCreditSystems/invest-openapi/releases/tag/19.2.2
