### ISSUE TITLE
Что есть averagePositionPrice?

### ISSUE THREAD

**Issue by Anton-Cherepkov** [TinkoffCreditSystems/invest-openapi#191]
Добрый день. 

В документации не смог найти, что означает поле `averagePositionPrice` в `/portfolio`?
Это средняя цена **во время покупки**? Если да, то как получить текущую рыночную цену?

**Comment by recoshet** [comment]
Приветствую. Я так понимаю, это как в мобильном приложении. Средняя стоимость бумаги в портфеле

**Comment by KirillKaverin** [comment]
@Anton-Cherepkov `averagePositionPriceNoNkd` (по крайней мере в облигациях) является средней ценой всех текущих покупок (например, ордер на покупку 1 лот сработал по цене 100 и ещё один ордер на покупку 2 лота сработал по цене 85, `averagePositionPriceNoNkd` будет равен 90 `((100+85*2)/3)`. ). Возможно в других инструментах `averagePositionPriceNoNkd` равняется `averagePositionPrice` (не смотрел)

**Comment by NikitaMelnikov** [comment]
averagePositionPrice - это средняя цена позиции в портфеле, считается через FIFO
https://yourbusiness.azcentral.com/fifo-vs-average-cost-method-14366.html
