### ISSUE TITLE
Ошибка биржи time_in_force

### ISSUE THREAD

**Issue by recoshet** [TinkoffCreditSystems/invest-openapi#192]
Сейчас пытаюсь создать заявку по рынку, в коде ответа получаю 200, что всё ок. А в теле запроса: 
`payload=PlacedMarketOrder(order_id='-6314350948464767592', operation=<OperationType.buy: 'Buy'>, status=<OrderStatus.rejected: 'Rejected'>, reject_reason='Unknown', message='Заявка отклонена. [SPBEX][1217]: Неверный параметр time_in_force для инструмента.', requested_lots=1, executed_lots=0, commission=None) status='Ok' tracking_id='05d71257881feb32'`
Т.е. тут даже status='Ok', и про переменную time_in_force в доках ни слова

**Comment by recoshet** [comment]
В мобильном приложении при этом рыночная заявка проходит в обе стороны. Инструмент RIG

**Comment by NikitaMelnikov** [comment]
Обратитесь, пожалуйста, в поддержку через мобильное приложение или сайт
