### ISSUE TITLE
Одновременное получение обновлений стакана по всем тикерам

### ISSUE THREAD

**Issue by irivertime** [TinkoffCreditSystems/invest-openapi#193]
Добрый день.
Не нашел прямого ответа на мой кейс в документации или sdk.
Кейс: Нужно получать данные в реальном времени по определенному набору тикеров (10, 100, 1000)
https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/
Можно подписаться на стакан по figi. Я использую python websocket, но посмотрел также nodejs sdk и прочие доступные либы, но наблюдается явный недостаток информации, а примеры и доки не всегда полные особенно по вебсокетам. Ну и апи постоянно меняется.
1. Как подписаться сразу на, допустим, 1000 тикеров?
Это нужно для оперативного отслеживания изменения цены и быстрой реакции.
Есть ли какие ограничения в данном случае? я читал на 6 одновременных соединений и 120 запросов в минуту по rest, как они тут применяются?
2. Какие есть задерки в стриме, т.е. пуш сразу при изменении любого поля или по интервалу?
3. Видел проблему что в стакане могут приходить сообщения в разном порядке, т.е. старые после новых, сохранилась ли у кого такая проблема? В целом таймстапм решает проблему
4. Rest - market/orderbook - lastPrice = это та цена которая отображается в приложении и терминале в данный момент? Интересует как эта цифра определяется, типа рыночная цена из max bid / min ask = mid(spread)?
5. figi - ticker - one-to-one всегда? Почему в ответах сервера всегда figi, а тикер нужно узнавать отдельным рест методом, конечно это не трудно и можно закешировать все тикеры при условии что figi не меняются.

Спасибо!

**Comment by KirillKaverin** [comment]
@irivertime думаю сотрудники ТФ лучше подскажут, но попробую ответить по своему опыту:
1) Как подписаться сразу на, допустим, 1000 тикеров? -- достаточно открыть 1 вебсокет и сделать 1000 подписок на разные символы. Ограничений не замечал, 6 одновременных соединений -- это про вебсокет подключения, а не количество подписок в них. Rest вообще не участвует здесь, поэтому его ограничения тоже можно не учитывать.
2) Могу сказать что задержки ооочень минимальные, но так же зависит от вашей геолокации. Если сравнивать серверное время и моё локальное, то задержки в среднем 2-3мс, иногда даже меньше. По моим наблюдениям сообщения от сервера приходят: одно сообщение сразу при подписке (последний стакан) и при каждом последующем изменении цены или объёма в стакане. Иногда бывают странности в стакане, например выставляешь ордер, а в стакане его не видно :(
3) Таймстамп решает проблему, но я анализировал стаканы за неделю, у меня проблемы с разным порядком сообщений не встречалось, может данный баг и существует на более волатильных инструментах
4) LastPrice должен быть равен цене последней исполненной сделки. В терминалах на графиках обычно (ТФ терминала у меня нет, но во всех других точно) отображается текущий Bid.
5) figi - ticker - one-to-one всегда? -- вроде бы да. Почему в ответах сервера всегда figi -- figi более универсальный формат и думаю в ТФ изначально сделали все привязки именно к figi. Можете изначально предзагрузить все торгуемые в ТФ инструменты (я так и делаю) через `/market/stocks` или `/market/bonds` или `/market/etfs` (в зависимости от нужных вам иструментов), там будут FIGI, Ticker и ISIN

**Comment by NikitaMelnikov** [comment]
@KirillKaverin спасибо за ответ, все верно :)

**Comment by irivertime** [comment]
@KirillKaverin
Благодарю за такой подробный ответ!

@NikitaMelnikov Меня еще интересует важный момент:
Как рассчитывается текущая цена которая показывается в моб. приложении и терминале? она меняется очень часто, это просто максимальный bid?
С moex понятно, но, например, если брать питерскую биржу, то с заходом амер. бирж которые и составляют основной объем продаж скачки наблюдаются большие. Да, роботы подтягивают заранее объемы торгов, премаркет и тд, но какой механизм отображения цены в такие моменты тоже?
понятно что (рыночная) сделка будет совершена по цене минимального ask и в зависимости от объема. 
1. Oбычно на всех графиках указывается цена последней сделки lastPrice (тк их бывает много, то цена видимо усредняется с задержкой) или max bid или есть формула? (a может из candles берется?)
2. На это влияет спред или нет?
3. Как учитываются стаканы и цены других бирж при подключении? (есть возможность сделки "через биржу" напрямую, но этот механизм неясен, тк мы не видим чужие стаканы, но влияние амер бирж существенное, как тут усредняется цена при подключении?)

**Comment by irivertime** [comment]
@NikitaMelnikov Все еще очень интересует момент с ценой. Если коротко, то как рассчитать текущую цену которая показывается в приложении и терминале по стрим или rest данным? Нужна прям та самая цифра, быстро меняющаяся и по которой строится график и она не всегда равна max bid or min ask.

Спасибо!

**Comment by NikitaMelnikov** [comment]
> Если коротко, то как рассчитать текущую цену которая показывается в приложении и терминале по стрим или rest данным? Нужна прям та самая цифра, быстро меняющаяся и по которой строится график и она не всегда равна max bid or min ask.

Цена, которая отображается в мобильном приложение самым большим шрифтом на экране бумаги - это подписка на candles и оттуда забирается поле `c` - close


> Как учитываются стаканы и цены других бирж при подключении? (есть возможность сделки "через биржу" напрямую, но этот механизм неясен, тк мы не видим чужие стаканы, но влияние амер бирж существенное, как тут усредняется цена при подключении?)

Взаимодействие с биржей только через нашего брокера, данные мы получаем с MOEX и SPB и транслируем напрямую.
Про американские биржи сложнее, так как взаимодействие идет через SPB, соответственно их реализацию тяжело учитывать

**Comment by NikitaMelnikov** [comment]
> На это влияет спред или нет?

Спред, не влияет
