### ISSUE TITLE
Добавить в метод /operations дату исполнения на бирже(Т+2) и/или курс валюты, по которому сделка исполнилась на бирже.

### ISSUE THREAD

**Issue by laperuz92** [TinkoffCreditSystems/invest-openapi#194]
Сейчас увидеть, в какую дату заявка исполнилась на бирже(с учетом расчетов Т+2), можно только по брокерскому отчету. Соответственно нет возможности через OpenAPI рассчитать НДФЛ/доходность в рублях по иностранным бумагам.

**Comment by NikitaMelnikov** [comment]
Добрый день,

Не планируем эту функциональность в OpenApi
