### ISSUE TITLE
Перестала находиться бумага RU000A0JXPU3

### ISSUE THREAD

**Issue by vslinko** [TinkoffCreditSystems/invest-openapi#195]
Привет.

Какое-то время назад перестал находится figi по бумаге RU000A0JXPU3.

Начал дебажить, обнаружил такое:
запрос:
```
https://api-invest.tinkoff.ru/openapi/sandbox/market/search/by-ticker?ticker=RU000A0JXPU3
```

ответ:
```
{
  "trackingId": "5826b82655c134f8",
  "payload": {
    "instruments": [],
    "total": 0
  },
  "status": "Ok"
}
```

**Comment by vslinko** [comment]
А что это означает? Почему отключена? Включится ли? Что мне с этим можно сделать?

**Comment by NikitaMelnikov** [comment]
Лучше обратиться в поддержку по этому вопросу
