### ISSUE TITLE
Critical Socket Error code 423

### ISSUE THREAD

**Issue by BusinessDuck** [TinkoffCreditSystems/invest-openapi#196]
Постоянно получаю такую ошибку. Раза 4 за минуту.

16:59:45  connection closed
Error: Unexpected server response: 423
    at ClientRequest.<anonymous> (/Users/BusinessDuck/dev/bot-tinkoff/node_modules/ws/lib/websocket.js:579:7)
    at ClientRequest.emit (events.js:316:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:610:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:479:22)
    at TLSSocket.emit (events.js:316:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
16:59:45  connection closed

**Comment by KirillKaverin** [comment]
@BusinessDuck такое часто случается. Скорей всего сам сервер рвёт принудительно соединения (без правильного фрейма завершения), либо ТФ команда деплоит новые версии и обрывают все коннекты. У меня такое случается раз 40 на дню. Поэтому рекомендую сделать Keep Alive небольшим (если это возможно) и при любой ошибке с вебсокетов пересоздавать подключение и пересоздавать все подписки

**Comment by BusinessDuck** [comment]
Так и делается. Просто у меня это сегодня началось и в течении всего дня продолжается, именно в проде. В песочнице все ок. 
Если это и правда команда Тинькофф Инвестиций, грустно, что в торговой сессии апдейт, а не ночью или утром.

**Comment by BusinessDuck** [comment]
Каждую секунду уже рвется!

`17:37:23  connection closed
17:37:23  connection closed
17:37:23  connection closed
17:37:24  connection closed
17:37:24  connection closed
17:37:24  connection closed
17:37:24  connection closed
17:37:24  connection closed
17:37:24  connection closed
17:37:25  connection closed
17:37:25  connection closed
17:37:25  connection closed
17:37:25  connection closed
17:37:25  connection closed
17:37:25  connection closed
17:37:26  connection closed
17:37:26  connection closed
17:37:26  connection closed
17:37:26  connection closed
17:37:26  connection closed
17:37:26  connection closed
17:37:26  connection closed
17:37:27  connection closed
17:37:27  connection closed
17:37:27  connection closed
17:37:27  connection closed
17:37:27  connection closed`

**Comment by Fatal1ty** [comment]
Да, сегодня вечером такого больше обычного :)
![image](https://user-images.githubusercontent.com/323962/80521866-61f78d00-8994-11ea-8330-0d808b751e36.png)

**Comment by NikitaMelnikov** [comment]
Добрый день, дело не в релизах и не деплоях
Можете снять дамп трафика?

**Comment by BusinessDuck** [comment]
отправляем получаем, у меня не удается даже подключиться к сокету, в данный момент. Не отрабатывает ивент open на сокете, сразу в error

**Comment by BusinessDuck** [comment]
В песочнице все прекрасно при этом

**Comment by berzhok** [comment]
@BusinessDuck  Такая же проблема сегодня с нодой(

**Comment by BusinessDuck** [comment]
Может быть связано с 20 одновременно открытыми сокетами, тк имею пул ботов, и транспорт у каждого свой?

**Comment by BusinessDuck** [comment]
Как часто нужно слать пинг?

**Comment by BusinessDuck** [comment]
Проверил, ошибки начинают валится после коннекта 6ой раз с одного сервера.

**Comment by YuriyIlyin** [comment]
> Проверил, ошибки начинают валится после коннекта 6ой раз с одного сервера.

Доступно 6 tcp-соединений на одного пользователя.
https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/

**Comment by irivertime** [comment]
Я так понимаю, что если открыть одно соединение и пересоздавать его в случае ошибок, перезаписываясь на обновления, то ошибки на 6-ое одновременное соединение не будет.

Извините за оффтоп, кто-нибудь знает как рассчитать текущую цену которая показывается в приложении и терминале по стакану или свечам? Нужна прям та самая цифра, быстро меняющаяся и она не всегда равна max bid or min ask.
