### ISSUE TITLE
RequestValidation: Цена не попадает в допустимый интервал от 121.5 до 121.5

### ISSUE THREAD

**Issue by olsh** [TinkoffCreditSystems/invest-openapi#197]
Пару раз получал такую ошибку при выставлении лимитной заявки.

`RequestValidation: Цена не попадает в допустимый интервал от 121.5 до 121.5`

Прозошло 2 раза:
April 13 2020 12:52:13 MSK - `T`
April 29 2020 18:47:07 MSK - `MOEX`

Ошибка в запросе или в апи?

**Comment by NikitaMelnikov** [comment]
Биржа выставляет определенные требования при выставлении заявки, посмотреть ограничения можно в https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/#instrument_infosubscribe
поля limit_up, limit_down
Они так же являются опциональными и биржа не всегда их передает

**Comment by olsh** [comment]
Но почему именно 121.5? Что у `T` что у `MOEX` цена не такая.

**Comment by NikitaMelnikov** [comment]
Выглядит странно, напишите пожалуйста в поддержку с логами запросов / ответов, будем смотреть что пошло не так
