### ISSUE TITLE
OrderCancelError: Ошибка отмены поручения

### ISSUE THREAD

**Issue by olsh** [TinkoffCreditSystems/invest-openapi#198]
При отмене заявки иногда получаю такую ошибку

`OrderCancelError: Ошибка отмены поручения`

Последние пару раз произошла сегодня:
April 28 2020 17:06:05 MSK - `F`
April 29 2020 17:08:03 MSK - `GPS`

**Comment by NikitaMelnikov** [comment]
Возможно поручение уже было исполнено в этот момент?

**Comment by olsh** [comment]
Сложно сказать. Вся информация которая есть у меня, это то что API сразу же перед отменой, отдавал эти поручения.

Было бы супер, если бы ошибка была более точной.

**Comment by NikitaMelnikov** [comment]
В тексте ошибки есть подробности?

**Comment by olsh** [comment]
Все что есть в ошибке
```
OrderCancelError: Ошибка отмены поручения (69fc3d808bffa583).
```

Возможно, ситуацию бы улучшило реализация этой issue
https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/issues/32

**Comment by olsh** [comment]
За последний месяц ошибка не воспроизводилась, думаю что можно закрыть.
