### ISSUE TITLE
averagePositionPrice считается неправильно

### ISSUE THREAD

**Issue by olsh** [TinkoffCreditSystems/invest-openapi#199]
`averagePositionPrice` при выполнении запроса к `/portfolio` считается неправильно, есть предположение что какое-то время используется предыдущее значение `averagePositionPrice`. Пример:

0. Покупка бумаги по 1.25
1. averagePositionPrice = 1.25
2. Продажа бумаги
3. Покупка бумаги по 1.30
4. averagePositionPrice = 1.25 (хотя должен быть 1.30)

--
Возможно, не связано, но сегодня еще и в ленте вот такая интересная картина:

![photo_2020-04-30_12-18-05](https://user-images.githubusercontent.com/3613592/80694823-b6f2ea80-8add-11ea-8015-a950b9349a6b.jpg)

**Comment by okosoft** [comment]
с рублями также. что то они навертели за ночь в API. в итоге сегодня всё счетается неправильно. одна акция нормально отдает данные, другая не отдает половину. и закономерности где сломалось не видно. выключил роботов чтобы не продавали в минус.

**Comment by olsh** [comment]
Проблему бы могла решить реализация изменения статуса ордера в стриминге. Тогда бы можно было бы самому считать average. https://github.com/TinkoffCreditSystems/invest-openapi/issues/87

**Comment by okosoft** [comment]
только вебсокет не интересен! текущее состояние должно отдаваться по REST тоже!

**Comment by NikitaMelnikov** [comment]
Была ситуация с отставанием информации в ленте и расчете доходностей, вопрос не совсем к OpenApi, если данные так же отображались и в мобильном приложении.
Обратитесь, пожалуйста, в поддержку за подробностями
