### ISSUE TITLE
Сегодня API пятисотит с самого утра

### ISSUE THREAD

**Issue by svetlyak40wt** [TinkoffCreditSystems/invest-openapi#20]
Сначала просто пятисотки были, а теперь вот 503 service unavailable.

**Comment by svetlyak40wt** [comment]
@NikitaMelnikov у меня https://api-invest.tinkoff.ru/openapi/operations?from=2019-09-18&interval=1day стабильно отдаёт 503.

Посмотри почему так, пожалуйста!

**Comment by NikitaMelnikov** [comment]
Привет, сегодня наблюдались проблемы на сервисе операций с 10:00 утра и в 16:30 при открытии бирж.

По остальному времени уточню

**Comment by NikitaMelnikov** [comment]
Нашли проблему, поправили, будем разбираться почему не заметили раньше
Спасибо

**Comment by NikitaMelnikov** [comment]
По 500 нашли проблему, выкатим фикс в течение часа
