### ISSUE TITLE
Странный figi Benefytt Technologies (TCS003QRSQD3)

### ISSUE THREAD

**Issue by Vassiliev99** [TinkoffCreditSystems/invest-openapi#201]
У всех инструментов, возвращаемых по /market/stocks, figi начинается на BBG и только у Benefytt Technologies - TCS. Интересно, с чем это связано?
[Здесь](https://www.openfigi.com/about/figi) написано, что 3 символ всегда должен быть G.

**Comment by NikitaMelnikov** [comment]
В результате корпоративных действий FIGI еще не был добавлен, в ближайшее время исправится на https://www.openfigi.com/id/BBG003QRSQD3
