### ISSUE TITLE
rest /operations добавить опциональный параметр operation id

### ISSUE THREAD

**Issue by ddmrtc** [TinkoffCreditSystems/invest-openapi#202]
Добрый день,

сейчас для отслеживания выполнения ордера приходится получать все операции по figi за какой то период, в нем искать нужную operation id, было бы удобнее получить результат по operation id и не передавать время при этом

**Comment by NikitaMelnikov** [comment]
Добрый день,

Это будет сделано через получение информации по заявке https://github.com/TinkoffCreditSystems/invest-openapi/issues/51

**Comment by polkila** [comment]
> Добрый день,
> 
> Это будет сделано через получение информации по заявке #51

Можно будет указывать список orderId?

**Comment by AlexanderVolkovTCS** [comment]
@polkila
> Можно будет указывать список orderId?
да
