### ISSUE TITLE
ticker: TCSG не возвращаются операции в истории

### ISSUE THREAD

**Issue by ddmrtc** [TinkoffCreditSystems/invest-openapi#204]
`https://api-invest.tinkoff.ru:443 "GET /openapi/operations?from=2019-05-03T22%3A18%3A35.134138%2B00%3A00&to=2020-05-02T22%3A18%3A35.134138%2B00%3A00&figi=BBG00QPYJ5H0"
{"trackingId":"206df190fa7b34ee","payload":{"operations":[]},"status":"Ok"}`
в принципе не отдаются операции по тикеру TCSG "TCS Group" (рублевые акции Тинькофф)

в приложении тоже, операции по тикеру TCSG отображаются в тикере TCS

**Comment by NikitaMelnikov** [comment]
Добрый день,

О этой ситуации известно, не связано с OpenApi. Если вы хотите следить за ситуацией и ее исправлением, рекомендую обратиться в поддержку
