### ISSUE TITLE
rest /candles интервал для hour

### ISSUE THREAD

**Issue by mvkasatkin** [TinkoffCreditSystems/invest-openapi#205]
Увеличьте пожалуйста допустимый интервал для hour с 7 дней хотя бы до месяца. На данный момент запрос по hour отдает очень мало баров (~50), особенно если через выходные, по сравнению с дневкой (~250 баров) или минутными (более 400).

**Comment by NikitaMelnikov** [comment]
Добрый день,

К сожалению, это не настройка системы, рекомендую построить свое приложение для получения свечей со скользящим окном
