### ISSUE TITLE
Получение информации о максимальном ордере при торговле с плечом

### ISSUE THREAD

**Issue by Antitesla** [TinkoffCreditSystems/invest-openapi#206]
Не нашел в документации по api такой возможности: получение информации о максимальном ордере при торговле с плечом. Т.е. перед отправкой ордера на покупку инструмента необходимо понимать, какое кол-во лотов я могу купить. Правила, как я понимаю, разные для разных бирж, валют, акций в зависимости от ликвидности. Так в мобильном приложении по каждому инструменту отображается, какое кол-во лотов доступно для покупки. Как мне получить эту информацию через api?

**Comment by NikitaMelnikov** [comment]
В OpenApi в данный момент нет возможности получить ликвидный портфель
