### ISSUE TITLE
Как получить текущую стоимость на весь список акций?

### ISSUE THREAD

**Issue by na88git** [TinkoffCreditSystems/invest-openapi#207]
Доброый день!

Пользовался документацией на странице Swagger
[https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_orderbook](url)

Правильно ли я понимаю, что для получения текущей цены на акции нужно воспользоваться следующим инструментом?
GET /market​/orderbook Получение исторических стакана по FIGI

Если я хочу получить цену на список разных акций (например 1200штук), то мне придется делать 1200 запросов изменяя значение figi? Можно ли это сделать как то в один запрос, передав список интересующих акций ('figi') и получить один ответ? (Если да то какой будет формат?) Пока что, получается, что с ограничением 120 запросов за 1 минуту, я могу получить интересующий параметр 1200 шт только через 10 минут?

**Comment by na88git** [comment]
Дополню, что я использую Python. И текущий вызов делаю следующим образом:

`
import requests
import json

api_url_base = 'https://api-invest.tinkoff.ru/openapi/'
api_token = '***'
api_headers = {'Content-Type': 'application/json', 'Authorization': 'Bearer {0}'.format(api_token)}

# Get info by FIGI
def get_market_search_by_ticker(ticker):
    api_url = '{0}/market/search/by-ticker'.format(api_url_base)
    params = {'ticker': '{0}'.format(ticker)}
    return requests.get(api_url, headers=api_headers, params=params)


get_market_search_by_ticker('AAPL')
`

**Comment by NikitaMelnikov** [comment]
Добрый день,

Чтобы получить свечи, нужно использовать операцию https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_candles

> Можно ли это сделать как то в один запрос, передав список интересующих акций ('figi') и получить один ответ?

Нет, получение данных идет по конкретной бумаге

> Пока что, получается, что с ограничением 120 запросов за 1 минуту, я могу получить интересующий параметр 1200 шт только через 10 минут?

Все верно

**Comment by na88git** [comment]
Тогда у меня однозначно предложение, объединить!

Сделать на подобии портфеля пользователя, но где пользователь передает интересующие его наборы акций. (А вообще я бы сделал, что бы пользователь сам формировал запросы только с теми параметрами которые его интересуют, универсальный запрос)

 Для вывода любой таблицы сводной, совсем неоптимально делать запрос к каждой акции отдельно. А тем более если я хочу ее смотреть в реальном времени...это тьма запросов и нагрузка на сервер. В то время как можно было бы получить одним пакетом и периодичность опроса сократится в разы. Да даже просто сравнить цены двух бумаг...уже два отдельных обращения к каждой. Платформа же рассчитывается на автоматизацию процесса и на торговых роботов. А пока я аналитику всю собиру до алгоритмов не успею дойти у меня уже все данные устаревшие.

**Comment by YuriyIlyin** [comment]
> А тем более если я хочу ее смотреть в реальном времени

Посмотрите на streaming протокол.
https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/
