### ISSUE TITLE
Структура openapi.api_client

### ISSUE THREAD

**Issue by MaximChernyak98** [TinkoffCreditSystems/invest-openapi#209]
Здравствуйте, только начал знакомиться с api.
Где я могу посмотреть структуру openapi.api_client?
Пишу на python

**Comment by NikitaMelnikov** [comment]
Добрый день,
Если речь идет о каком-то SDK, то в его репозитории

**Comment by NikitaMelnikov** [comment]
https://github.com/daxartio/tinvest
https://github.com/Awethon/open-api-python-client
https://github.com/Fatal1ty/tinkoff-api
