### ISSUE TITLE
Rejected при создании ордера на продажу через API

### ISSUE THREAD

**Issue by deflopian** [TinkoffCreditSystems/invest-openapi#21]
Сегодня с утра при попытке создания ордера на продажу (RBCM, в частности) через API получаю в ответе 
"status":"Rejected",
"rejectReason":"Unknown"

Параметры в запросе передаю валидные, вчера точно такой же ордер создавался без проблем. Вручную через терминал ордер выставляется нормально.

**Comment by NikitaMelnikov** [comment]
Привет, а есть trackingId? Вчера в почте видел подобную ситуацию, проблема была в том, что был передан не тот шаг цены https://tinkoffcreditsystems.github.io/invest-openapi/faq/#_2

**Comment by deflopian** [comment]
Действительно, проблема была в шаге цены. Большое спасибо за помощь!
