### ISSUE TITLE
Отсутствие комиссии в единичных операциях

### ISSUE THREAD

**Issue by vrubanov** [TinkoffCreditSystems/invest-openapi#210]
Никак не мог понять, почему не бьются цифры. Оказалось в списке операций GET operations  для двух конкретных операций покупки валюты (ID "19858640710" и ID "19763248169") возвращается нулевая комиссия в поле Operation.commission, хотя реально она есть. Соответствующие операции списания комиссии (BrokerCommission) также в спике отсутствуют. С другими несколькими сотнями операций таких проблем нет. Как это исправить?

**Comment by deniro98** [comment]
@vrubanov комиссии в некоторых случаях появляются как отдельная операция

**Comment by vrubanov** [comment]
@deniro98 в моем списке комиссии по всем операциям, кроме этих двух, пердставалены отдельными операциями. То есть инфо о комиссии есть и в поле Operation.commission операции покупки, и как отдельная операция. Но для этих двух нет НИ инфо в Operation.commission, НИ отдельной операции.

**Comment by deniro98** [comment]
> @deniro98 в моем списке комиссии по всем операциям, кроме этих двух, представлены отдельными операциями. То есть инфо о комиссии есть и в поле Operation.commission операции покупки, и как отдельная операция. Но для этих двух нет НИ инфо в Operation.commission, НИ отдельной операции.

Попробуйте подождать 2 рабочих дня , позднее появится , у меня так же было

**Comment by NikitaMelnikov** [comment]
Иногда комиссии долетают позже, @deniro98 все верно отметил

**Comment by vrubanov** [comment]
Коллеги, а сколько ждать? Комиссия по этим двум операциям так и не проявляется. Первая операция 20 апреля, вторая 08 мая... Как-то это не очень нормально в любом случае.

**Comment by NikitaMelnikov** [comment]
@vrubanov странно что не появилась, обратите, пожалуйста в нашу поддержку с ссылкой на этот issue и указанием, чтобы просто передали разработчикам, будем разбираться детальней в причине
