### ISSUE TITLE
Маржинальная торговля

### ISSUE THREAD

**Issue by bondarevs** [TinkoffCreditSystems/invest-openapi#211]
Добрый день.

Подскажите, как через API реализовать короткую сделку?
Есть ли этот функционал?

**Comment by ddmrtc** [comment]
Добрый, разместите ордер на продажу и откроется короткая сделка, если по
этому инструменту она поддерживается

В sandbox не работает

пн, 11 мая 2020 г. в 10:43, bondarevs <notifications@github.com>:
