### ISSUE TITLE
No trades in /operations for delisted securities

### ISSUE THREAD

**Issue by S3RK** [TinkoffCreditSystems/invest-openapi#213]
В приложении все операции показываются без исключения. Было бы замечательно если бы данные приложения и OpenApi сходились. Та же самая проблема касается сделок в валютах отличных от RUB/USD.

**Comment by NikitaMelnikov** [comment]
Новые валюты сейчас отключены, ждем доработок на SDK, чтобы не сломать клиентов

**Comment by S3RK** [comment]
@NikitaMelnikov прошу прощения, я видимо двусмысленно высказался. Проблема касается бумаг которые торговались в рублях но прошли процесс делистинга. Кажется, что этот баг не связан с внедрением новых валют.

Сделки в новых валютах я упомянул просто как еще один пример расхождения API и официального приложения банка. Я считаю, что было бы гораздо лучше если бы они выдавали одинаковые результаты. Очевидно, что если мобильное приложение показывает все сделки без проблем, то уже существует какая-то инфраструктура и API которые его поддерживают. Я понимаю, что не все так просто, но в виду многочисленных проблем и расхождений возможно стоит прояснить как они взаимосвязаны и, возможно, пересмотреть прежние технические решения.

**Comment by NikitaMelnikov** [comment]
Существует разница между нашим приложением и OpenApi в том, что мобильное приложение, терминал и веб пишется нами и мы можем гарантировать обратную совместимость для старых клиентов, при этом для новых версий, которые поддерживают новые валюты, мы можем возвращать все данные.

В OpenApi же клиентов очень много и много SDK, которые завязались на название валют, как на ENUM, соответственно при десериализации ответа они будут падать с ошибкой.
