### ISSUE TITLE
FIGI vs tickers

### ISSUE THREAD

**Issue by pdyachen** [TinkoffCreditSystems/invest-openapi#214]
Добрый день.
Подскажите пожалуйста каким образом можно получать актуальный FIGI для нужного тикера ? Ведь при выставлении заявок или получении котировок мы оперируем тикерами, а АПИ требует FIGI....
Пробовал достать из опен АПИ, вроде бы там есть метод для этого, но он не работает, точнее я так и не смог заставить его заработать ?))

Спасибо заранее!

**Comment by KirillKaverin** [comment]
@pdyachen всё в API крутится на FIGI (выставление заявок и получение котировок тоже). Также для одного тикера может быть несколько FIGI (зависит от используемого инструмента и биржи). Вы можете попробовать `/market/stocks` или `/market/bonds` или `/market/etfs` (в зависимости от нужных торговых инструментов, документация: https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/) и получить список всех доступных пар FIGI и тикеров

**Comment by pdyachen** [comment]
@KirillKaverin принял, спасибо. Разобрался вроде бы !
