### ISSUE TITLE
Swagger order book

### ISSUE THREAD

**Issue by own2pwn** [TinkoffCreditSystems/invest-openapi#218]
В описании получение "исторических стакана" (опечатка) по смыслу ждёшь, что можно будет выбрать произвольный период времени, но указать его нельзя. Хотелось бы узнать, будет ли это доступно, и хорошо бы подкорректировать описание, чтобы не сбивало сразу

**Comment by NikitaMelnikov** [comment]
Да, это баг, описание поправим

**Comment by lightning95** [comment]
исправлено #228
