### ISSUE TITLE
Instrument is disabled for trading, INSTRUMENT_ERROR

### ISSUE THREAD

**Issue by Griff19** [TinkoffCreditSystems/invest-openapi#222]
Пытался создать рыночную заявку на "Вечный портфель RUB" получил ошибку
"Instrument is disabled for trading, INSTRUMENT_ERROR"
Проверил в оф.приложении - все торгуется.
Создал заявку на другую бумагу - все прошло нормально.
Подскажите есть ли какие то ограничения на торговлю через API на конкретные бумаги?

**Comment by lightning95** [comment]
торговля "Вечными портфелями" временно приостановлена через OpenAPI

будет возобновлена в одном из следующих релизов
