### ISSUE TITLE
Пример использования API C#

### ISSUE THREAD

**Issue by EgorCrane** [TinkoffCreditSystems/invest-openapi#224]
Прошу поделиться примером использования API C#.
Получение данных и выставление ордеров.

**Comment by KirillKaverin** [comment]
@EgorCrane [C# SDK](https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk#%D0%B1%D1%8B%D1%81%D1%82%D1%80%D1%8B%D0%B9-%D1%81%D1%82%D0%B0%D1%80%D1%82) (раздел "Быстрый старт"). Все реализованные методы в C# SDK можно посмотреть [тут](https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/blob/master/src/Tinkoff.Trading.OpenApi/Network/IContext.cs). А дальше уже зависит от нужной вам логики.

**Comment by EgorCrane** [comment]
Спасибо, документацию видел.

Создаю запрос:
```req = StreamingRequest.SubscribeCandle(yandex.Figi, CandleInterval.Minute);
context.SendStreamingRequestAsync<StreamingRequest>(req).Wait();
```
Подписываюсь на событие:
`context.StreamingEventReceived += Context_StreamingEventReceived;`

Событие срабатывает только один раз и больше данных не поступает.
Повторная отправка запроса не помогает.

Подскажите в чем ошибка?

**Comment by KirillKaverin** [comment]
```// токен аутентификации
var token = "my.token";
// для работы в песочнице используйте GetSandboxConnection
var connection = ConnectionFactory.GetConnection(token);
var context = connection.Context;
//сначала подписываемся на событие от EventHandler
context.StreamingEventReceived += (sender, eventArgs) =>
{
    Console.WriteLine("Event");
}
//потом запрашиваем подписку у API
await context.SendStreamingRequestAsync(new StreamingRequest.SubscribeCandle(yandex.Figi, CandleInterval.Minute));
//потом не даём программе завершиться
while (true)
{
  Thread.Sleep(10); //10 мс
}

**Comment by EgorCrane** [comment]
Спасибо, за пример.
Разобрался.
В оконном приложении пришлось прикрутить инвокер для синхронизации с окном и выводом данных.
Для лимитов метод PlaceLimitOrderAsync.
Стопы еще не реализованы.
А как отправить рыночную заявку?

**Comment by KirillKaverin** [comment]
@EgorCrane в API рыночные ордера есть, а в C# SDK ещё нет. Но PR уже [есть](https://github.com/TinkoffCreditSystems/invest-openapi-csharp-sdk/pull/34)

**Comment by EgorCrane** [comment]
Спасибо, ждем.

**Comment by exvion** [comment]
> В оконном приложении пришлось прикрутить инвокер для синхронизации с окном и выводом данных.

Поделитесь примером как вы это сделали. Спасибо.

**Comment by EgorCrane** [comment]
> > В оконном приложении пришлось прикрутить инвокер для синхронизации с окном и выводом данных.
> 
> Поделитесь примером как вы это сделали. Спасибо.

       /// <summary>
        /// Подписка на StreamingEventReceived
        /// </summary>
        private void Context_StreamingEventReceived(object sender, StreamingEventReceivedEventArgs e)
        {
            if (e.Response is CandleResponse resp)
            {
                var txt = $"{resp.Payload.Time} - {resp.Payload.Close}";
                AppendTextBoxThreadSafe(txt);
            }
        }

        /// <summary>
        /// Самосинхронизирующийся рекурсивный метод
        /// </summary>
        /// <param name="txt"></param>
        private void AppendTextBoxThreadSafe(string txt)
        {
            if (!Dispatcher.CheckAccess()) // CheckAccess returns true if you're on the dispatcher thread
            {
                Dispatcher.Invoke(new AppendTextBoxMethodInvoker(AppendTextBoxThreadSafe), txt);
                return;
            }
            textBox.Text += txt + "\n";
            textBox.Focus();
            textBox.CaretIndex = textBox.Text.Length;
            textBox.ScrollToEnd();
        }

        private delegate void AppendTextBoxMethodInvoker(string txt);
