### ISSUE TITLE
Не хватает полей в ответном json-е при запросе к /sandbox/portfolio

### ISSUE THREAD

**Issue by s0501007** [TinkoffCreditSystems/invest-openapi#225]
Пример того, что приходит в ответ
![image](https://user-images.githubusercontent.com/3153408/82470102-9232d700-9acd-11ea-8eb9-75bc3ca68b41.png)

Вот что должно приходить согласно документации
![image](https://user-images.githubusercontent.com/3153408/82470273-cc9c7400-9acd-11ea-8f32-017887f9a1e9.png)

**Comment by lightning95** [comment]
поля не обязательные (не помечены красной звездочкой)
в сендбоксе пока не реализовано оценка средней цены и доходности

**Comment by s0501007** [comment]
1) Когда планируется?
2) Как можно узнать среднюю стоимость позиции в сендбоксе?
В ответ на запрос к sandbox/orders приходит json с пустым payload.
3) Вопрос вдогонку: /orders возвращает список ордеров в рамках торгового дня?

**Comment by recoshet** [comment]
@s0501007, тестируйте на дешёвых акциях. По личному опыту, так меньше нервов потратите.
На среднюю цену в портфеле лучше не ориентироваться, что в моб. приложении, что в API показывает не верно, если усредняться и покупать/продавать частями.
/orders показывает активные лимитные заявки, на сколько я помню. Так как в сэндбоксе заявки исполняются моментально, там будет пусто.

Я ориентируюсь по информации из /operations

**Comment by s0501007** [comment]
Спасибо. Информативно.
Кстати, действительно, написано "получение списка **активных** заявок". Но там же, в документации, фигурируют такие статусы ордера, как Rejected, Cancelled
![image](https://user-images.githubusercontent.com/3153408/82521612-cb039800-9b2f-11ea-8467-ba4620f3ea85.png)

Нет деталей о значении статусов, но судя по названиям - полагаю, что это уже не активные заявки.

Как вообще отслеживать изменение стоимости активов в портфеле, если
1) средняя цена в /portfolio некорректа
2) истории ордеров нет (можно было бы хоть по ней самим посчитать)
?

**Comment by s0501007** [comment]
@recoshet 
Спросонья не обратил внимание на /operations.
Спасибо!

**Comment by lightning95** [comment]
> Когда планируется?
точной информации пока нет
