### ISSUE TITLE
Вопрос по рыночным заявкам в песочнице

### ISSUE THREAD

**Issue by SergeyBruhanov** [TinkoffCreditSystems/invest-openapi#226]
Если выполнить orders/market-order в песочинице, то в операциях стоимость акции по заявке будет равна не рыночной, а числу 100. С чем это связано ?

**Comment by SergeyBruhanov** [comment]
На счете песочницы 1 млн руб,
Cannot process request, not enough balance on security=RUB
Ошибка и на маржинальную и на лимитную заявку

**Comment by SergeyBruhanov** [comment]
Еще и при отправке заявки возвращает orderid = ec3800cf-67e8-4553-a284-1f82d059e7dd, а в операциях он уже 3499274. С чем это связано?

**Comment by SergeyBruhanov** [comment]
Будет ли ответ на вопрос ? Я сейчас это обошел, через получение текущих ask из стакана и формированием лимитной заявки вместо рыночной, но хотелось бы понять, что не так с рыночной ?

**Comment by NikitaMelnikov** [comment]
> Еще и при отправке заявки возвращает orderid = ec3800cf-67e8-4553-a284-1f82d059e7dd, а в операциях он уже 3499274. С чем это связано?

В протоколе ID является строкой, не нужно считать это чем-то осмысленным и завязываться, то ID всегда будет числовой

**Comment by NikitaMelnikov** [comment]
>  Если выполнить orders/market-order в песочинице, то в операциях стоимость акции по заявке будет равна не рыночной, а числу 100. С чем это связано ?

Sandbox не исполняет сделки на бирже и не поключен к потоку цен (в данный момент), поэтому все рыночные заявки исполняются с ценой 100
