### ISSUE TITLE
Вопрос по курсам

### ISSUE THREAD

**Issue by SergeyBruhanov** [TinkoffCreditSystems/invest-openapi#227]
Какой курс валюты будет взят при продаже акций, считающихся в USD, в шорт, если на балансе было 0 USD ? Интересует рублевая оценка USD на балансе.

**Comment by ddmrtc** [comment]
Для расчета налога? Всегда будет использоваться курс ЦБ со смещением t+2,
даже если в портфеле есть USD.

Для расчета размера маржинального портфеля будет использоваться опять же
либо курс ЦБ, либо биржевой курс, но не курс USD в портфеле

чт, 21 мая 2020 г. в 04:31, SergeyBruhanov <notifications@github.com>:

**Comment by SergeyBruhanov** [comment]
Не для расчета надо, а для расчета оценки портфеля USD в рублях и средней цены себестоимости в рублях. Вот, к примеру, я продал 10 акции по 1 USD, у меня USD стал +10 USD, а в рублевом выражении на сколько будет плюс ? Мне это надо для проверки вашей средней цены USD, которую вы мне показываете в портфеле.

**Comment by NikitaMelnikov** [comment]
По подобным вопросам лучше обратиться в поддержку через чат в веб или мобильном приложении
