### ISSUE TITLE
Не работает шорт на учебном счете

### ISSUE THREAD

**Issue by SergeyBruhanov** [TinkoffCreditSystems/invest-openapi#229]
Пытаюсь продать Боинг (шорт по акции разрешен) на учебном счете в шорт, пишет ошибку: недостаточно баланса по акции.

**Comment by Sergio1C** [comment]
Да, @SergeyBruhanov также столкнулся с той же ситуацией и то же с Боингом.

**Comment by lightning95** [comment]
#34
