### ISSUE TITLE
Orderbook streaming stuck (PHP SDK)

### ISSUE THREAD

**Issue by ayurushev** [TinkoffCreditSystems/invest-openapi#23]
Добрый день!

Пытаюсь использоваться SDK для PHP
[](https://github.com/jamesRUS52/tinkoff-invest)

там есть функция подписки на получение стрима стакана
```
$client->subscribeGettingOrderBook($sber->getFigi(), 2);
$client->startGetting('action', 1000, null);
```

Все работает и данные по WebSocket получаю ОК, но все длится примерно секунд 10, за это время по Сберу, например, прилетает 20-28 ответов от вашего API. После чего периодичность получения данных ответов резко снижается (один ответ в 15 сек) и каждый новый ответ дублирует данные предыдущего (последнего).

например:
сначала ответы идут очень быстро (1-3 в сек)
```
Order. BBG004730N88 | 50 Buy: 238.73 | 125 Sell: 238.66
Order. BBG004730N88 | 125 Buy: 238.74 | 146 Sell: 238.66
Order. BBG004730N88 | 51 Buy: 238.74 | 146 Sell: 238.66
Order. BBG004730N88 | 1 Buy: 238.74 | 126 Sell: 238.68
Order. BBG004730N88 | 1 Buy: 238.74 | 126 Sell: 238.69
```

а через ~10 сек. происходит «залипание» и ответы начинают сыпаться однотипные раз в 15 сек.
```
Order. BBG004730N88 | 375 Buy: 238.85 | 225 Sell: 238.77
Order. BBG004730N88 | 375 Buy: 238.85 | 225 Sell: 238.77
Order. BBG004730N88 | 375 Buy: 238.85 | 225 Sell: 238.77
Order. BBG004730N88 | 375 Buy: 238.85 | 225 Sell: 238.77
```
и так до бесконечности.

Использую режим sandbox.

Проверьте, пожалуйста. Это некое ограничение в API, баг, так и должно быть, или надо копать в сторону PHP SDK?

Спасибо:)

**Comment by ayurushev** [comment]
Путем отладки удалось выяснить, что API Streaming просто перестает что либо присылать через 150-20 сек, следовательно, в PHP (WebSocket) получаю exception:

`WebSocket\ConnectionException: Empty read; connection dead?  Stream state: {"crypto":{"protocol":"UNKNOWN","cipher_name":"TLS_AES_256_GCM_SHA384","cipher_bits":256,"cipher_version":"TLSv1.3"},"timed_out":false,"blocked":true,"eof":true,"stream_type":"tcp_socket\/ssl","mode":"r+","unread_bytes":0,"seekable":false} in /var/www/default/html/tib/vendor/textalk/websocket/lib/Base.php:269
Stack trace:
#0 /var/www/default/html/tib/vendor/textalk/websocket/lib/Base.php(143): WebSocket\Base->read(2)
#1 /var/www/default/html/tib/vendor/textalk/websocket/lib/Base.php(135): WebSocket\Base->receive_fragment()
#2 /var/www/default/html/tib/vendor/james.rus52/tinkoffinvest/src/TIClient.php(617): WebSocket\Base->receive()`

**Comment by necryin** [comment]
php sdk использует под капотом https://github.com/Textalk/websocket-php , которая не шлет pong на ping от сервера. Сервер streaming не получив pong-ов на свои сообщения закрывает соединение. https://github.com/Textalk/websocket-php/pull/24 так и не вмерджили :)
