### ISSUE TITLE
Как продать 1 USD на учебном счете  ?

### ISSUE THREAD

**Issue by SergeyBruhanov** [TinkoffCreditSystems/invest-openapi#230]
Не дает продать меньше, чем 1000 USD, воспринимает 1 USD только как 1 лот, который равен 1000 USD. При этом в приложении нормально продается в заявке даже 1 доллар. Как продать 1 доллар через api ?

**Comment by YuriyIlyin** [comment]
Попробуйте рыночной заявкой. У лимитной 1 лот = 1000 шт.

**Comment by NikitaMelnikov** [comment]
1 лот для доллара - это 1000шт, 1шт продать нельзя
