### ISSUE TITLE
Short позиции 

### ISSUE THREAD

**Issue by dobrobro8** [TinkoffCreditSystems/invest-openapi#231]
Как открывать short позицию через openApi

**Comment by KirillKaverin** [comment]
@dobrobro8 https://github.com/TinkoffCreditSystems/invest-openapi/issues/211

**Comment by dobrobro8** [comment]
Благодарю за ссылку ,но она не открывается пишет что не для вашей учетной записи(

**Comment by KirillKaverin** [comment]
@dobrobro8 что-то не так с вашей стороны, так как ссылка публичная и на публичный репозиторий и на публичную issue. Даже в режими инкогнито работает.

**Comment by dobrobro8** [comment]
![DB1ADBCC-2E78-4735-99E2-FE283ECD11B9](https://user-images.githubusercontent.com/65777863/82694133-63526780-9c6b-11ea-9018-76b375a2fac4.png)

**Comment by NikitaMelnikov** [comment]
>  ddmrtc commented 12 days ago
> Добрый, разместите ордер на продажу и откроется короткая сделка, если по
> этому инструменту она поддерживается

> В sandbox не работает
