### ISSUE TITLE
Заявка Token Real не исполняется

### ISSUE THREAD

**Issue by dobrobro8** [TinkoffCreditSystems/invest-openapi#232]
Я занимаюсь разработкой не большой программы.
При работе в sandbox вроде все было ок.
Но после подключение с рабочим токеном после создания LimitOrder в портфолио он не появляется. Ответ на await contextSandbox.PlaceLimitOrderAsyn
image.png
Ошибок видимо нет. Exception тоже. В портфолио видно свои счета. В ответ на  await context.OrdersAsyn приходит пустой список.Подскажите может что-то нужно добавить/поправить?

**Comment by KirillKaverin** [comment]
@dobrobro8 ваша картинка не работает :( 

По какому инструменту пытались открыть ордер? В какой время (часть инструментов торгуется на MOEX и торговля по ним работает с 10.00 до 18.45 МСК)?

**Comment by dobrobro8** [comment]
По AFKS в течение всего дня)

**Comment by dobrobro8** [comment]
Но он не открывает не для чего(

**Comment by NikitaMelnikov** [comment]
> Но после подключение с рабочим токеном после создания LimitOrder в портфолио он не появляется. Ответ на await contextSandbox.PlaceLimitOrderAsyn

Подозреваю, что тут дело в том, что вы используете SandboxContext

**Comment by dobrobro8** [comment]
Благодарю будем пробывать)но теперь не раньше понедельника)

**Comment by dobrobro8** [comment]
Доброго времени!)Никита благодарю за обратную связь сделки пошли 

> > После создания LimitOrder он не доступен. Ответ на await contextSandbox.PlaceLimitOrderAsyn
> 
> SandboxContext Подозреваю, что тут дело в том, что вы используете

Доброго времени!)Сделки пошли,Никита благодарю за обратную связь!)но теперь встал вопрос с открытием позиций в шорт:на балансе 1 акция в Лонг надо перевернуться в шорт ставим на продажу 2 акции но он исполняет только 1 и получаеться не открывает шорт, как исправить подскажите?

**Comment by dobrobro8** [comment]
подскажите ещё по стоп лоссу и тейк профиту как можно прописать

**Comment by KirillKaverin** [comment]
@dobrobro8 
1) шорты не по всем инструментам возможны, может вы именно по ним пытаетесь выставить ордер
2) стопов и тейк профиты не реализованы, можете у себя кодом следить за позициями/ордерами и эмулировать стоп и тейк (issue: https://github.com/TinkoffCreditSystems/invest-openapi/issues/145). Конечно, эмуляция будет не то, что серверная реализация, но пока только так

**Comment by dobrobro8** [comment]
Кирилл вам конечно огромная благодарность за отзывчивость и обратную связь!)но если api прикручивать пытаемся то  Шорты на что одеваться представления имеются))здесь в чем то другом загвоздка пока не можем понять в чем(

**Comment by dobrobro8** [comment]
Кажется решили вопрос)😊
