### ISSUE TITLE
Когда приходят новые данные по WS?

### ISSUE THREAD

**Issue by it-efrem** [TinkoffCreditSystems/invest-openapi#235]
Есть возможность подписаться на свечи "candle:subscribe" и стакан "orderbook:subscribe".

Вопрос - когда приходят новые данные? Что является тиком? Если свечи могут меняться при каждой совершенной сделке (что уже может происходить сотни раз в секунду), то стакан может изменяться тысячи раз в секунду, мне же не будет приходить тысяча сообщений в секунду, тогда как часто? Что является тригером для отправки сообщения клиенту, то есть мне? 

В доках не нашел - https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/

**Comment by ZigGreen** [comment]
duplicates: #234
