### ISSUE TITLE
500е ошибки

### ISSUE THREAD

**Issue by parksuser** [TinkoffCreditSystems/invest-openapi#236]
Попробовал клиенты для C# 
( ошибка клиента апи при любом запросе - Object Reference Not Set to an Instance of an Object )
 и NodeJs (либо ошибки о том что такого пути нет, либо ошибки без какого-либо текста от сервера), ни один хеллоу ворлдный пример не завелся.
Попробовал в постмане, импортировал yml как коллекцию, 
подставил токен в поле authorization, 500я ошибка на запрос получения счетов, убираю токен - 401 unauthorized.
Подскажите, может быть кто-нибудь сталкивался с такой проблемой?

Токены пробовал и песочные и обычные.

**Comment by lightning95** [comment]
https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/
попробуйте здесь с вашим токеном

**Comment by parksuser** [comment]
![image](https://user-images.githubusercontent.com/16019243/83142721-8cef1100-a0f9-11ea-98b0-359f87c80e18.png)
Попробовал, к сожалению тоже самое, возможно проблема с самими выданными токенами или с какими-то настройками, подтверждение действий смс кодом у меня отключено

**Comment by NikitaMelnikov** [comment]
Могли бы предоставить текст ответа сервера?

**Comment by parksuser** [comment]
Проблема как раз в том, что сервер не возвращает никакого ответа, просто 500я ошибка.
Инсомния
![image](https://user-images.githubusercontent.com/16019243/83242344-eb24fe00-a1a4-11ea-947f-c8f777ee2297.png)
Браузерный сваггер
![image](https://user-images.githubusercontent.com/16019243/83242438-1871ac00-a1a5-11ea-8f81-24fc2c86d92d.png)

Попробовал перевыпустить токен и попробовать - тот же результат.
Пробовал и на винде, и на линуксе, и на макоси.

**Comment by NikitaMelnikov** [comment]
Вижу эти ошибки в логах, напишите, пожалуйста, в поддержку с ссылкой на этот Issue, нам это нужно чтобы посмотреть на внутренние данные, которые тут не хочется передавать :)
Разберемся из-за чего такое происходит.
