### ISSUE TITLE
Серверные ошибки

### ISSUE THREAD

**Issue by EJohnF** [TinkoffCreditSystems/invest-openapi#237]
При попытках отправки лимитированных заявок, переодически прилетают ошибки:

```
message: 'Error executing HTTP request to Tariff module',
     code: 'TariffModuleError' 
```

```
message: 'Сделка невозможна. Попробуйте, пожалуйста, позже.',
     code: 'OrderNotAvailable'
```

```
message: 'Response has unknown status',
     code: 'TariffModuleError'
```

При том, что время рабочее (все биржы открыты), средства/акции есть достаточно. 
Что самое странное - это происходит рандомно. Т.е. в какой то момент выпадает такая ошибка, тогда как минутой раньше или позже - исполняется успешно.

**Comment by IvanAgafonov** [comment]
Думаю это связано в принципе с общим сервером, потому что в приложении на телефоне тоже периодически приходят неизвестные ошибки сервиса при работе с заявками.

**Comment by NikitaMelnikov** [comment]
По подобным вопросам лучше обращаться в поддержку через мобильное приложение или веб
