### ISSUE TITLE
Сервер отвечает 500, а заявка создана! Нужен ключ идемпотентности.

### ISSUE THREAD

**Issue by kirill-znamenskiy** [TinkoffCreditSystems/invest-openapi#239]
Регулярно (2-3 раза в неделю) сталкиваюсь с такой ситуацией - при создании лимитной заявки ваш сервер отвечает 500ю ошибку, а заявка в итоге создана ну и соответственно она исполняется, а я об этом не в курсе! Ну и вот сегодня утром ситуация снова повторилась, только теперь у меня уже есть полный-полный лог произошедшего, вот он:

первый запрос и ответ на него:

> POST /openapi/orders/limit-order?figi=BBG000N9MNX3 HTTP/1.1
> Content-Length: 43
> User-Agent: GuzzleHttp/6.5.3 curl/7.64.0 PHP/7.3.14-1~deb10u1
> Host: api-invest.tinkoff.ru
> Date: Mon, 01 Jun 2020 07:13:04 GMT
> Authorization: Bearer t.xxxxxxxxxxxxxxxxxxxxxxxxx
> Content-Type: application/json;charset=UTF-8
> Accept: application/json
> 
> {"lots":1,"operation":"Buy","price":878.99}

> HTTP/1.1 500 Internal Server Error
> Server: nginx
> Date: Mon, 01 Jun 2020 07:13:24 GMT
> Transfer-Encoding: chunked
> Cache-Control: no-store, no-cache, must-revalidate

соответственно повторный запрос (из-за 500го ответа)

> POST /openapi/orders/limit-order?figi=BBG000N9MNX3 HTTP/1.1
> Content-Length: 43
> User-Agent: GuzzleHttp/6.5.3 curl/7.64.0 PHP/7.3.14-1~deb10u1
> Host: api-invest.tinkoff.ru
> Date: Mon, 01 Jun 2020 07:13:24 GMT
> Authorization: Bearer t.xxxxxxxxxxxxxxxxxxxxxxxxx
> Content-Type: application/json;charset=UTF-8
> Accept: application/json
> 
> {"lots":1,"operation":"Buy","price":878.99}

> HTTP/1.1 200 OK
> Server: nginx
> Date: Mon, 01 Jun 2020 07:13:32 GMT
> Content-Type: application/json
> Content-Length: 194
> Cache-Control: no-store, no-cache, must-revalidate
> access-control-allow-methods: GET,HEAD,POST,DELETE,OPTIONS,PUT,PATCH
> access-control-allow-headers: accept, content-type, authorization, access-control-allow-headers, x-requested-with
> access-control-allow-origin: *
> 
> {"trackingId":"e2e4f10014b68cbf","payload":{"orderId":"131847939190","operation":"Buy","status":"New","requestedLots":1,"executedLots":0,"commission":{"currency":"USD","value":0}},"status":"Ok"}

ну и собственно по итогу обе заявки создались и обе исполнились!

Кажется хорошим выходом будет внедрение ключа идемпотентности https://kassa.yandex.ru/developers/using-api/basics#idempotence

А в идеале чтобы он(ключ идемпотентности) еще и к заявке привязывался и отдавался потом как одно из полей через GET /orders

Ну и на самом деле это поможет решить еще и ситуацию с таймаутами - иногда у вас сервера подвисают и долго отвечают (20 секунд как в этом примере - еще норм), а выставляя таймаут на своей стороне - получается по-сути такая же ситуация что неизвестно создалась заявка или нет, только уже по собственному выбору как бы.

**Comment by kirill-znamenskiy** [comment]
И еще, совсем забыл
На первый взгляд кажется что есть же простой вариант - проверить создалась заявка или нет через GET /orders 
Только вот очень часто заявка ставится близко к текущей цене и исполнятся по-сути сразу же после выставления, так что в GET /orders ее уже просто нет, а вот понять почему нет - потому что она уже исполнилась или потому что она так и не создалась - возможности нет :((

Это кстати еще одна проблема - хотелось бы иметь возможность всегда получить инфу по конкретной заявке, в том числе и если она уже исполнена!
А запрашивать эту конкретную заявку идеально если можно будет через orderId и/или IdempotenceKey

**Comment by BusinessDuck** [comment]
Возможно связано, https://github.com/TinkoffCreditSystems/invest-openapi/issues/158

Господа разработчики API, обратите внимание на эту проблему! У меня также повторяется 500 ответ от сервера, но уже с маркет заявкой. Повторилось одновременно на 3х разных счетах. На разные суммы. (Тикер один). 

Вот время 2020-06-03T16:30:21.055Z  происшествия (прибавьте 3 часа до московского)

При всем при этом приходит в приложение вот такой пуш

![image](https://user-images.githubusercontent.com/10143411/83665703-73a40400-a5d4-11ea-82ef-1ae0cc9697c5.png)

Можно было бы проверить как говорит @kirill-znamenskiy наличие ордеров в истории, если бы они там появлялись сразу, а не болтались черт знает где в течении получаса...

**Comment by berzhok** [comment]
Ошибка валится каждый день(  причем с таким же сообщением в приложении как у @BusinessDuck

**Comment by berzhok** [comment]
Сегодня снова в 16:35  и 16:45 на 9 разных валютах получил эту ошибку, кто-нибудь собирается что-то делать с этим? при этом ордера создаются(иногда), но я об этом ничего знаю

**Comment by kirill-znamenskiy** [comment]
да, у меня сегодня с утра уже 4 таких ситуации (разработчики API, если нужны логи - скину)
я конечно добавил перепроверку через GET /orders перед повторным выставлением заявки, и 1 раз это даже помогло, но в целом, как и писал выше, это почти бесполезно

вообще нашел еще одну перепроверку - можно через GET /portfolio получить текущее состояние портфеля, и вот именно в нем поле lots обновляется максимально быстро (в отличие от averagePositionPrice), ну и соответственно если внимательно учитывать какое было количество lots до заявки, а после 500 ответа проверить и GET /orders и lots в GET /portfolio и правильно их сопоставить, то чисто теоретически можно выяснить была ли заявка или нет
есть конечно проблемный нюанс что между GET /orders и GET /portfolio ситуация уже изменится и тогда никаких выводов сделать не получится

у себя я пока такого еще не реализовал, но похоже придется...

а так ситуация конечно абсолютно тупиковая - с нашей стороны (пользователей API) уже больше ничего невозможно сделать, остается только ждать надеяться и верить :((

**Comment by scythargon** [comment]
Ребята, невозможно так работать, почините эту ошибку, пожалуйста!

**Comment by BusinessDuck** [comment]
Сегодня уже около 10 сделок с такими ошибками, срочно чинить!

**Comment by NikitaMelnikov** [comment]
Привет, дело совсем не в опенапи.

Я прекрасно понимаю что это совсем не то поведение системы, которое ожидается и это очень страшная ситуация.

Пока не точных результатах разбора, у кого случилась такая ситуация, прошу обратиться в поддержку, будем разбираться в причинах.

Я закрою этот тикет, надеюсь на ваше понимание, я и коллеги будем разбирать случаи и работать над исправлением ситуации. 
Как вы можете знать, на SPB бирже так же последние 2 дня идет сбой, что усложняет поиск причины и исправления.

**Comment by NikitaMelnikov** [comment]
https://spbexchange.ru/ru/about/news.aspx?bid=25&news=20774

**Comment by kirill-znamenskiy** [comment]
@NikitaMelnikov, здравствуйте!

> Привет, дело совсем не в опенапи.
В корне с вами не согласен - дело как раз таки именно в OpenAPI!

Вы говорите про разбор ситуации и про поиск причины ошибок и их исправлении, НО!
При чем тут причины возникновения ошибок? Это API, мы все тут разработчики, мы все знаем что работая с любым API нельзя полагаться на его 100% доступность и отсутствие ошибок. Самая банальная ситуация о которой кажется пишут в любом учебнике - ответ от вашего API может просто не дойти из-за сетевых проблем, то есть по вообще не зависящим от вас причинам. И это совершенно нормально! Если мы полагаемся на 100% ответ от API - значит это уже мы, клиенты, не правильно строим свою логику. Работая с любым API надо быть к этому готовым, это одна из причин почему сейчас по-сути побеждают stateless API.
И по-сути единственное что нам нужно - иметь хоть какую-то возможность обрабатывать **любые** ошибочные ситуации. 
И откровенно говоря ваша внутренняя причина ошибки меня, как пользователя API, вообще не касается. Собирайте свои ошибки в свои логи, анализируйте, разбирайтесь, ищите причины, исправляйте. Но не надо на нас перекладывать эти проблемы, дайте нам возможность работать с ошибочными ситуациями.

Теперь к конкретике - я вижу 2 способа:

1. как я вас и попросил выше, внедрить принцип идемпотентности в ваше API, мое предположение что это не так уж и просто сделать, поэтому прошу вас всетаки прокомментировать возможность и сроки такого решения
2. добавить в GET /orders возможность получать вообще все заявки, а не только активные, даже судя по вашему описанию API, предполагается что статус у заявки может быть один из [ New, PartiallyFill, Fill, Cancelled, Replaced, PendingCancel, Rejected, PendingReplace, PendingNew ], но вы отдаете нам не все заявки, а только активные. Лично мне кажется что у вас перед отдачей заявок в этом методе стоит фильтр, который отбрасывает неактивные заявки, и вот уж что-то, а ослабить этот фильтр, или выдать его нам в качестве параметра statuses например - выглядит вообще задачей часа на 4. А вот нам, пользователям API, это даст **реальную возможность** не зависеть от того - дошел ответ или нет!
А еще у меня есть предположение что где-то внутри еще есть и дата/время создания заявки, потому что в приложении оно как раз отображается, и если вы еще и это поле добавите в выдачу GET /orders - это еще улучшит ситуацию.

В общем очень прошу ответить о возможности реализовать хотя бы одно из двух предложенных решений.

**Comment by NikitaMelnikov** [comment]
@kirill-znamenskiy про добавление идемпотентности я с вами согласен, она нужна на openapi. 
Но тут возникают и другие проблемы, о которых нужно думать. OpenApi и брокер не работают сами в себе, они общаются с внешними сервисами, в частности с биржей. Из-за чего наш стейт, каким бы он не было консистентным, не может гарантировать консистентность данных с биржей, если у них есть внутренние проблемы.
Так что это защитит только от ошибок на брокере.
Вероятно добавим сразу с v2-протоколом. Сроки не могу назвать.

Про получение любой заявки:
> это даст реальную возможность не зависеть от того - дошел ответ или нет!

Это нужно, но это не спасло бы в текущей ситуации.
Так как для нас этих заявок так же не существовало из-за ситуации, которую я описал выше про то, почему идемпотентность не всегда спасает.

**Comment by kirill-znamenskiy** [comment]
@NikitaMelnikov, благодарю вас за ответы!

Очень буду ждать v2 протокол с идемпотентностью, с удовольствием выступлю его бета-тестером)

Тикет изначально открывался из-за проблемы случившейся 1го июня и регулярно (хоть и не часто) случавшейся ранее. И проблема эта больше похожа не перегрузку именно ваших (брокера) сервисов - просто nginx сбрасывает лишние соединения.
Да, конечно, 4го и 5го числа проблем стало явно больше, и вы вполне четко и ясно объяснили причину произошедшего и объснили почему тут ничего не поделаешь.
То что выдача всех заявок никак не поможет при проблемах на самой бирже - это ясно и понятно, в таких ситуацих кажется вообще ничего не поможет, увы.

Но моя просьба реализовать выдачу всех возможных заявок все еще очень актуальна.
Это позволит клиентам исправлять состояние в следующих случаях:
 - сетевые проблемы при доставке ответа от биржи к вам, от вас к нам
 - ваши внутренние ошибки связанные с проксированием ответа от биржи, например перегрузка сервисов
 - ответ не пришел из-за выставленного таймаута

 Согласитесь - это уже совсем немало! По-сути это дает все те же плюсы которые даст внедрением идемпотентности, только без удобства использования.

 В общем очень прошу реализовать выдачу всех заявок, например в новом методе GET /orders/all,  желательно с полем дата/время создания и с доступной фильтрацией по статусу и дате.

**Comment by NikitaMelnikov** [comment]
> Согласитесь - это уже совсем немало! По-сути это дает все те же плюсы которые даст внедрение идемпотентности, только без удобства использования.

Я с вами согласен, о необходимости написал выше, просто решил озвучить что этим не решить все проблемы :)

**Comment by kirill-znamenskiy** [comment]
Наш мир, к сожалению, не идеален - всех проблем не решить ;)
Благодарю вас за подробные ответы!
Буду очень ждать изменений в OpenAPI
