### ISSUE TITLE
В портфеле не отображается VTB1020

### ISSUE THREAD

**Issue by griddic** [TinkoffCreditSystems/invest-openapi#240]
При запросе портфеля  `/portfolio` 
в позициях нет позиции по еврооблигации VTB1020.

**Comment by NikitaMelnikov** [comment]
Добрый день, 

В мобильном приложении они доступны?

**Comment by griddic** [comment]
![Screenshot_20200609_085303](https://user-images.githubusercontent.com/9092509/84111014-aadc4000-aa2e-11ea-8e77-4ed4f29427e1.jpg)
@NikitaMelnikov

**Comment by NikitaMelnikov** [comment]
Для OpenApi данный инструмент отключен из-за технических особенностей
