### ISSUE TITLE
Торговля валютой

### ISSUE THREAD

**Issue by dobrobro8** [TinkoffCreditSystems/invest-openapi#241]
Доброго времени!не могу найти в списках тикер usd,eur и возможна ли вообще Торговля через api валютой?

**Comment by dobrobro8** [comment]
Может отдельный токен нужен?

**Comment by kirill-znamenskiy** [comment]
USD: 
> FIGI=BBG0013HGFT4
> TICKER=USD000UTSTOM

EUR: 
> FIGI=BBG0013HJJ31
> TICKER=EUR_RUB__TOM

в свое время через GET /portfolio их нашел

**Comment by dobrobro8** [comment]
Благодарю

**Comment by lightning95** [comment]
здесь список всех доступных валютных пар
https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_currencies

в OpenAPI можно торговать только полными лотами валюты
