### ISSUE TITLE
/openapi/operations: некорректное значение если ордер не был выполнен в полном объеме

### ISSUE THREAD

**Issue by pendyurinandrey** [TinkoffCreditSystems/invest-openapi#242]
Здравствуйте.
Обнаружил следующую проблему с endpoint `/openapi/operations`.
Выполнив запрос,
```
curl --request GET 'https://api-invest.tinkoff.ru/openapi/operations?from=2020-01-01T00%3A00%3A00%2B03%3A00&to=2020-02-01T00%3A00%3A00%2B03%3A00' \
--header 'Authorization: Bearer <my token>'
```
я нашел следующую операцию:
```
{
  "operationType": "Buy",
  "date": "2020-01-22T16:57:29.877928+03:00",
  "isMarginCall": false,
  "instrumentType": "Bond",
  "figi": "BBG00QXGQYZ9",
  "quantity": 50,
  "price": 1009.2,
  "payment": -4144.56,
  "currency": "RUB",
  "commission": {
    "currency": "RUB",
    "value": -2.01
  },
  "trades": [
    {
      "tradeId": "3078314323",
      "date": "2020-01-22T18:22:32.542282+03:00",
      "quantity": 1,
      "price": 1009.2
    },
    {
      "tradeId": "3078313703",
      "date": "2020-01-22T18:22:16.377908+03:00",
      "quantity": 1,
      "price": 1009.2
    },
    {
      "tradeId": "3078225999",
      "date": "2020-01-22T17:43:18.88644+03:00",
      "quantity": 2,
      "price": 1009.2
    }
  ],
  "status": "Done",
  "id": "<id>"
}
```
То есть:
1. Была выставлена лимитная заявка на покупку 50 облигаций по цене 1009.2
2. За торговую сессию было куплено только 4 облигации

В итоге:
1. payment: -4144.56 -> верное значение (с учетом НКД)
2. commission.value: -2.01 -> верное значение
3. quantity: 50 -> неверное (неконсистентное) значение. Судя по-всему, данное поле операции должно содержать фактическое количество купленных/проданных инструментов (по крайней мере, payment и commission.value содержат именно такие значения). То есть, в данном примере quantity должно быть равно 4.

Пожалуйста, рассмотрите возможность исправить данную проблему.

**Comment by lightning95** [comment]
#18
