### ISSUE TITLE
Как запросить информацию по тикеры текущей рыночной цены?

### ISSUE THREAD

**Issue by MightyBlow** [TinkoffCreditSystems/invest-openapi#243]
Я новичок. И я в ужасе.

Может кто-нибудь подсказать с какой стороны подойти к освоению API?
Для начала хотелось бы максимально упрощёно придти к понимаю как возможно реализовать по точечному запросу, по тикеру, какая рыночная цена сейчас у инструмента.

**Comment by lightning95** [comment]
Документация:
https://tinkoffcreditsystems.github.io/invest-openapi/
1) список акций
https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_stocks
взять у интересующего инструмента figi
2) выставление рыночной заявки
https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/orders/post_orders_market_order

**Comment by MightyBlow** [comment]
Спасибо большое, добрый человек!

1. А что такое figi? И почему не искать по ticker'у? Странная реализация.
2. Есть что-нибудь, если бы я хотел строить отчёты по активам? Прирост за неделю например?

**Comment by NikitaMelnikov** [comment]
1. FIGI - это глобальный идентификатор бумаги. Так как тикер уникален только в рамках одной биржи, невозможно однозначно понять о какой бумаге идет речь. FIGI решает эту проблему. 
2. Отчеты вы можете реализовать на свой стороне через поиск операций :)
