### ISSUE TITLE
При запросе /sandbox/market/candles в ответ попадают свечи вне from-to

### ISSUE THREAD

**Issue by fxfoxy** [TinkoffCreditSystems/invest-openapi#244]
При запросе /sandbox/market/candles по некоторым инструментам в ответ попадают свечи вне интервала from-to, пример:

https://api-invest.tinkoff.ru/openapi/sandbox/market/candles?figi=BBG004S689R0&from=2020-05-23T00%3A00%3A00%2B03%3A00&to=2020-06-02T23%3A59%3A59%2B03%3A00&interval=day. Response code: 200 {"queryData":{"figi":"BBG004S689R0","from":"**2020-05-23**T00:00:00+03:00","to":"**2020-06-02T23:59:59**+03:00","interval":"day"},"postData":[],"response":{"trackingId":"9c1c1e960e7fd515","payload":{"candles":[{"o":2789,"c":2796,"h":2813,"l":2760,"v":58604,"time":"2020-05-25T07:00:00Z","interval":"day","figi":"BBG004S689R0"},{"o":2795,"c":2800,"h":2825,"l":2783,"v":78984,"time":"2020-05-26T07:00:00Z","interval":"day","figi":"BBG004S689R0"},{"o":2801,"c":2812,"h":2833,"l":2797,"v":59433,"time":"2020-05-27T07:00:00Z","interval":"day","figi":"BBG004S689R0"},{"o":2805,"c":2875,"h":2880,"l":2805,"v":120497,"time":"2020-05-28T07:00:00Z","interval":"day","figi":"BBG004S689R0"},{"o":2860,"c":2788,"h":2893,"l":2785,"v":144775,"time":"2020-05-29T07:00:00Z","interval":"day","figi":"BBG004S689R0"},{"o":2786,"c":2802,"h":2819,"l":2724,"v":100129,"time":"2020-06-01T07:00:00Z","interval":"day","figi":"BBG004S689R0"},{"o":2816,"c":2819,"h":2830,"l":2787,"v":52576,"time":"2020-06-02T07:00:00Z","interval":"day","figi":"BBG004S689R0"},{"o":2819,"c":2819,"h":2819,"l":2819,"v":7,"time":"**2020-06-03**T07:00:00Z","interval":"day","figi":"BBG004S689R0"}],"interval":"day","figi":"BBG004S689R0"},"status":"Ok"},"time_ms":45} []

**Comment by fxfoxy** [comment]
При этом, если взять это же запрос, но подставить, например, figi BBG004S68BH6, то всё будет корректно.

**Comment by lightning95** [comment]
при передаче _2020-06-02T23:59:59+03:00_, дата округляется в 2020-06-03
и тогда возвращается не закрытая свеча

**Comment by fxfoxy** [comment]
Хорошо, хотя звучит странно и не очевидно в использовании. Ниже кейс на туже тему, время 18:40, всё равно появляется сегодняшняя свеча. Тоже округление?

Такая проблем возникает только с крайней дневной свечой за вчера. Тот же запрос, но с интервалом на день меньше даёт правильные результаты.

request https://api-invest.tinkoff.ru/openapi/sandbox/market/candles?figi=BBG004S689R0&from=2020-05-24T00%3A00%3A00%2B03%3A00&to=2020-06-03T18%3A40%3A00%2B03%3A00&interval=day. Response code: 200 {"queryData":{"figi":"BBG004S689R0","from":"2020-05-24T00:00:00+03:00","to":"**2020-06-03T18:40:00+03:00**","interval":"day"},"postData":[],"response":{"trackingId":"5ea0c6fafb2b873d","payload":{"candles":[{"o":2789,"c":2796,"h":2813,"l":2760,"v":58604,"time":"2020-05-25T07:00:00Z","interval":"day","figi":"BBG004S689R0"},{"o":2795,"c":2800,"h":2825,"l":2783,"v":78984,"time":"2020-05-26T07:00:00Z","interval":"day","figi":"BBG004S689R0"},{"o":2801,"c":2812,"h":2833,"l":2797,"v":59433,"time":"2020-05-27T07:00:00Z","interval":"day","figi":"BBG004S689R0"},{"o":2805,"c":2875,"h":2880,"l":2805,"v":120497,"time":"2020-05-28T07:00:00Z","interval":"day","figi":"BBG004S689R0"},{"o":2860,"c":2788,"h":2893,"l":2785,"v":144775,"time":"2020-05-29T07:00:00Z","interval":"day","figi":"BBG004S689R0"},{"o":2786,"c":2802,"h":2819,"l":2724,"v":100129,"time":"2020-06-01T07:00:00Z","interval":"day","figi":"BBG004S689R0"},{"o":2816,"c":2819,"h":2830,"l":2787,"v":52576,"time":"2020-06-02T07:00:00Z","interval":"day","figi":"BBG004S689R0"},{"o":2819,"c":2839,"h":2844,"l":2778,"v":71253,"time":"2020-06-03T07:00:00Z","interval":"day","figi":"BBG004S689R0"},{"o":2837,"c":2837,"h":2837,"l":2837,"v":7,"time":"**2020-06-04T07:00:00Z**","interval":"day","figi":"BBG004S689R0"}],"interval":"day","figi":"BBG004S689R0"},"status":"Ok"},"time_ms":44} []
