### ISSUE TITLE
Unknown account: GATEWAY_REQUEST_DATA_ERROR

### ISSUE THREAD

**Issue by Dronablo** [TinkoffCreditSystems/invest-openapi#245]
Внезапно начал получать вот такое на любой запрос:
```
{'trackingId': '2295136b185b64ac', 
 'payload': {'message': 'Unknown account', 
                   'code': 'GATEWAY_REQUEST_DATA_ERROR'}, 
 'status': 'Error'}
```
Попробовал перевыпустить токен - тоже самое. Как чинить?

**Comment by lightning95** [comment]
возможно, вы перепутали токен от биржи и сендбокса?

**Comment by Dronablo** [comment]
Я сендбоксом никогда не пользовался и токена для него у меня нет.
В итоге выходит вот так:
- в API вижу вот эту ошибку
- в мобильном приложении при попытке продать бумагу получаю internal error
- через какое-то время всё, конечно, заработало
- при обращении в саппорт на тарифе Премиум был послан в гитхаб
- в гитхабе просто никто на это не отвечает
- получается что API, фактически, поддержки не имеет

**Comment by ddmrtc** [comment]
11:14:53.595 - get_operations - ERROR - get_operations failed: {"trackingId":"9b9f7db48766bed1","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:15:54.408 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"49fad6fd64d86b85","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:16:55.423 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"141d729a09ba8c01","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:17:56.392 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"27d17e19b82beb13","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:18:57.377 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"b35224920451e02b","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:19:58.486 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"ace1618ec54f0083","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:20:59.548 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"131caf433b28fe94","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:22:00.423 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"4b9ccba07c7fdf70","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:23:01.517 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"91ec1d3fb2be091e","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:24:02.502 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"c585de859d760b86","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:25:03.595 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"99b90412628cdcbc","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:26:04.392 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"7ee70c98eef8e5d1","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:27:05.377 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"6425759c2a048c06","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:28:06.470 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"3362c5638d159ad0","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:29:07.376 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"aef8d61f2f103665","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:30:08.423 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"49ddc0da2db979ca","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:31:09.439 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"dc75222f616d3c0a","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:32:10.392 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"2369c1a02fc27692","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:33:11.345 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"05ee302bb6a63059","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:34:12.361 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"58eb26ce83c83885","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:35:13.361 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"71b5cd07f6734822","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:36:14.345 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"9fe79337187ebaee","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:37:15.486 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"495f8730a7ba8d1c","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
11:37:37.067 - get_portfolio - ERROR - get_portfolio failed: {"trackingId":"3b9da1af210bd8eb","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}
до 11:14 ошибок не было

**Comment by Yuryi1806** [comment]
Ошибка повторяется. Ничего не менялось

{"trackingId":"13af29c84e7ff2d9","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}

**Comment by luckman** [comment]
Только что началось то же самое.
Попробовал запрос на /user/accounts - не возвращает ни одного аккаунта для реального ключа.
С ключом на песочницу 1 аккаунт вернулся

**Comment by borovskyav** [comment]
Поддерживаю, в 13:10 судя по логам, запросы содержащие AccoundId начали падать с такой ошибкой

**Comment by Yuryi1806** [comment]
Заявки на покупку тоже не срабатывают. Что делать?

**Comment by luckman** [comment]
Только что заработало
для проверки можно использовать запрос на /user/accounts, сейчас стал возвращать нужный аккаунт

**Comment by Yuryi1806** [comment]
Да, все на месте. Теперь работает

**Comment by borovskyav** [comment]
```
2020-06-05 14:24:41,836 ERROR [Operations updater] [38] [Scheduler] Scheduled action threw an exception.
Tinkoff.Trading.OpenApi.Network.OpenApiException: GATEWAY_REQUEST_DATA_ERROR: Unknown account (6d7e449778c68fe7).
   в Tinkoff.Trading.OpenApi.Network.Connection`1.<HandleResponseAsync>d__14`1.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Tinkoff.Trading.OpenApi.Network.Connection`1.<SendGetRequestAsync>d__11`1.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Tinkoff.Trading.OpenApi.Network.Context.<OperationsAsync>d__21.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в TinkoffBot.Tinkoff.Tinkoff.<GetOperations>d__6.MoveNext() в 
```
=(

**Comment by NikitaMelnikov** [comment]
@borovskyav для разрабора нам понадобятся детали по вашему счету и аккаунту, напишите пожалуйста в поддержку с ссылкой на этот ISSUE

**Comment by Dronablo** [comment]
@NikitaMelnikov Что делать всем остальным? Что делать в такой ситуации в будущем?

**Comment by NikitaMelnikov** [comment]
Так же обращаться в поддержку, так как ваши данные на гитхабе ни вам, ни нам, наверно, светить не хочется :)
