### ISSUE TITLE
Портфель, операции других пользователей

### ISSUE THREAD

**Issue by panslava** [TinkoffCreditSystems/invest-openapi#246]
Есть ли возможность получить портфель и операции других пользователей (из пульса)?  В мобильном приложении это приходит с запросов на /social... но в текущем открытом api этого нет...

В /portfolio можно указывать номер счет (brokerAccountId) но не знаю, как его получить для других пользователей

**Comment by ogronome** [comment]
Справедливости ради, в мобильном приложении показывает полную ахинею (предположительно с опозданием в сутки или даже несколько), плюс совершенно не показывает шорт-позиции. Про подсчёт статистики молчу... 

В итоге, попытки копировать успешных трейдеров через пульс маловероятны )

push-и со сделками были бы полезны, но они и в моб приложении часто прилетают с жутким лагом.

**Comment by AlexanderVolkovTCS** [comment]
Такая функция пока не планируется

**Comment by ogronome** [comment]
На самом деле уже 100 лет как есть comon.ru давно свалил туда из бажного тинька )
