### ISSUE TITLE
Из портфолио исчезло averagePositionPrice?

### ISSUE THREAD

**Issue by betslus** [TinkoffCreditSystems/invest-openapi#248]
Добрый день.
В портфолио больше не будет показываться averagePositionPrice??? Или это временный баг какой-то? По всему СПБ рынку
{
  figi: 'BBG000PCNQN7',
  ticker: 'CHA',
  isin: 'US1694261033',
  instrumentType: 'Stock',
  balance: 5,
  lots: 5,
  expectedYield: { currency: 'USD', value: 0 },
  name: 'China Telecom'
}

PS.
Появилось, с очень большой задержкой.

**Comment by NikitaMelnikov** [comment]
Добрый день, averagePositionPrice может появляться иногда с задержкой из-за технических особенностей взаимодействия с биржей
