### ISSUE TITLE
Некоторые инструменты не доступны для торговли через OpenAPI?

### ISSUE THREAD

**Issue by kirill-znamenskiy** [TinkoffCreditSystems/invest-openapi#249]
По некоторым инструментам невозможно выставить лимитную заявку через OpenAPI. Пробовал в разные дни, в разное время, разные цены - по этим инструментам всегда один и тот же ответ: Instrument is disabled for trading
Речь идет о следующих инструментах:
1. TCSG (BBG00QPYJ5H0)
2. TRUR (BBG000000001)
3. TUSD (BBG000000000)
4. TEUR (BBG000000002)

Вот пример:
> POST /openapi/orders/limit-order?figi=BBG000000000 HTTP/1.1
> Content-Length: 46
> User-Agent: GuzzleHttp/6.5.3 curl/7.67.0 PHP/7.3.11
> Host: api-invest.tinkoff.ru
> Date: Tue, 09 Jun 2020 09:55:05 GMT
> Authorization: Bearer t.xxxxxxxxxxx
> Content-Type: application/json;charset=UTF-8
> Accept: application/json
> 
> {"lots":2000,"operation":"Buy","price":0.0949}

> HTTP/1.1 500 Internal Server Error
> Server: nginx
> Date: Tue, 09 Jun 2020 09:55:05 GMT
> Content-Type: application/json
> Content-Length: 135
> Cache-Control: no-store, no-cache, must-revalidate
> access-control-allow-methods: GET,HEAD,POST,DELETE,OPTIONS,PUT,PATCH
> access-control-allow-headers: accept, content-type, authorization, access-control-allow-headers, x-requested-with
> access-control-allow-origin: *
> 
> {"trackingId":"45b035210f681613","payload":{"message":"Instrument is disabled for trading","code":"INSTRUMENT_ERROR"},"status":"Error"}

Подскажите это вообще ошибка или фича? 
Если фича - то так всегда будет или они когда-нибудь станут доступны для торговли через OpenAPI? 
Есть какой-то полный список таких инструментов?

**Comment by NikitaMelnikov** [comment]
Добрый день, 

1. По TRUB и остальным фондам у нас временное ограничение на торговлю через OpenApi
2. TCSG выключен в OpenApi из-за технических особенностей

Все остальные инструменты из базового каталога должны быть доступны.

**Comment by kirill-znamenskiy** [comment]
Благодарю за информацию!
