### ISSUE TITLE
Streaming market-data поддержка массивов

### ISSUE THREAD

**Issue by prigornitskiy** [TinkoffCreditSystems/invest-openapi#25]
Пример:
`{"event": "candle:subscribe", "figi": "{{FIGI1}},{{FIGI2}},{{FIGI3}}", "interval": "{{INTERVAL1}},{{INTERVAL2}}" }`

**Comment by NikitaMelnikov** [comment]
Подписаться можно в цикле

```scala
Seq("FIGI1", "FIGI2").foreach { figi =>
  streaming.subscribe(figi, interval)
}
```

Пока что не готовы менять протокол
