### ISSUE TITLE
REST GET /orders добавьте ticker в тело ответа

### ISSUE THREAD

**Issue by denismosolov** [TinkoffCreditSystems/invest-openapi#251]
Как разработчик навыка для голосового помощника Алиса, я хочу иметь возможность извлечь ticker из тела ответа `GET /orders`, чтобы передать пользователям моего навыка, чтобы они смогли распознать это на слух.

https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/orders/get_orders
Сейчас в теле ответа `GET /orders` есть только figi
```
{
  "trackingId": "string",
  "status": "string",
  "payload": [
    {
      "orderId": "string",
      "figi": "string",
      "operation": "Buy",
      "status": "New",
      "requestedLots": 0,
      "executedLots": 0,
      "type": "Limit",
      "price": 0
    }
  ]
}
```
И вот как звучит figi, думаю ticker или другое человеко-воспринимаемое название инструмента будет звучать информативнее.
https://youtu.be/L2xlz6MCMm0

p.s.
Ещё хочется получить в этом же ответе по какой цене была выставлена заявка. Для этого лучше отдельный issue завести? Или тут дописать?

**Comment by KirillKaverin** [comment]
@denismosolov figi уникален для каждой биржи, а тикер нет, поэтому почти всё api на figi крутится. Вы можете попробывать взять все доступные пары figi-ticker через `/market/stocks` или `/market/bonds` или `/market/etfs` и потом, зная figi у ордера, получать и тикер.

> p.s.
Ещё хочется получить в этом же ответе по какой цене была выставлена заявка. Для этого лучше отдельный issue завести? Или тут дописать?

по идее поле Price должно показывать именно нужную вам цену

**Comment by denismosolov** [comment]
Благодарю за ответ, последую вашему совету. Видимо у меня глаз замылился и Price не заметил :)

У вас отличная команда, уверен вы станете лучшей компанией в финтех, а может уже и стали :). В этом репозитории я два раза пишу, и два раза получаю оперативный ответ. Спасибо вам за это. Для сравнения в БКС мне никто не ответил за неделю(
