### ISSUE TITLE
Сервера OpenAPI перестали отвечать

### ISSUE THREAD

**Issue by vrubanov** [TinkoffCreditSystems/invest-openapi#254]
При вызове
accounts, err := client.Accounts(ctx)

стало выдавать ошибку:
can't do request to : Get "https://api-invest.tinkoff.ru/openapi/user/accounts": dial tcp 178.248.239.55:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Неделю назад все работало, не менял ни строчки кода. Что изменилось?

**Comment by vrubanov** [comment]
По ходу у вас там с серверами происходит какая-то вакханалия, потому что теперь стало сыпать совсем другие ошибки про bad response... Я в коде ничего не трогаю при этом.

**Comment by vrubanov** [comment]
Товарищи, вчера похоже была масштабная авария, не работали ни мобильное приложение, ни терминал в браузере. Сегодня приложение и терминал починили, но OpenAPI по-прежнему не работает корректно...

В цикле при поиске свечи начинают сыпаться ответы такого плана:
bad response to https://api-invest.tinkoff.ru/openapi/market/candles?figi=BBG004S686W0&from=2017-04-26T21%3A37%3A00Z&interval=day&to=2020-06-14T21%3A37%3A00Z code=429, body=

После нескольких сотен таких неудавшихся запросов утыкаемся в:
can't do request to : Get "https://api-invest.tinkoff.ru/openapi/market/candles?figi=BBG004S686W0&from=2017-04-23T21%3A37%3A00Z&interval=day&to=2020-06-14T21%3A37%3A00Z": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

и вишенкой на торте:
can't do request to : Get "https://api-invest.tinkoff.ru/openapi/market/candles?figi=BBG004S686W0&from=2017-04-22T21%3A37%3A00Z&interval=day&to=2020-06-14T21%3A37%3A00Z": dial tcp 178.248.239.55:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Когда починится это?

**Comment by klakovsky** [comment]
Присоединяюсь к автору вопроса, сегодня (2020.06.10) утром API работала, но к 11:00 на запросы получают только 
запрос через swagger-UI:

curl -X GET "https://api-invest.tinkoff.ru/openapi/portfolio" -H "accept: application/json" -H "Authorization: Bearer ########"

Результат:
TypeError: Failed to fetch

**Comment by kitMP** [comment]
Сегодня какая-то проблема общая на серверах. Не могу зайти через терминал, а в мобильном клиенте не могу выставить подписку.

**Comment by u35tpus** [comment]
IT персонал уже походу не заглядывает сюда.  Багрепорты мы пишем сами для себя. Тинькова больше интересуют живые клиенты. Саппорт в чате только обещает исправить ошибки, а по сути ничего не поменялось с февраля как я сынтегрировался с Тиньковым: нет ни развития OpenAPI, ни исправления старых багов, зато падения стали чаще типа как сегодня, OpenAPI опять перестал  работать, прекрасное начало недели перед экспирацией опционов:

```
github.com/TinkoffCreditSystems/invest-openapi-go-sdk.(*RestClient).doRequest
	/home/oleg/go/pkg/mod/github.com/!tinkoff!credit!systems/invest-openapi-go-sdk@v0.5.0/rest_client.go:508
github.com/TinkoffCreditSystems/invest-openapi-go-sdk.(*RestClient).PositionsPortfolio
	/home/oleg/go/pkg/mod/github.com/!tinkoff!credit!systems/invest-openapi-go-sdk@v0.5.0/rest_client.go:210
github.com/TinkoffCreditSystems/invest-openapi-go-sdk.(*RestClient).Portfolio
	/home/oleg/go/pkg/mod/github.com/!tinkoff!credit!systems/invest-openapi-go-sdk@v0.5.0/rest_client.go:182
fn/internal/listener.getPortfolioInternal
```

**Comment by NikitaMelnikov** [comment]
**По сегодняшней ситуации**
@u35tpus @kitMP @klakovsky 

Сегодня были проблемы частичной недоступности инфраструктуры, ситуация была не только со стороны OpenApi.
Со своей стороны мы примем все меры для предотвращения подобной ситуации в дальшейнем

**По старту треда**
@vrubanov 

Нужно понять на каком этапе происходит ошибка, это могут быть как проблемы с DNS, так и с глобальными маршрутами. Очень помогла бы информация traceroute

**Comment by kirill-znamenskiy** [comment]
> $ date
> Mon Jun 15 09:21:55 UTC 2020
> $ traceroute api-invest.tinkoff.ru
> traceroute to api-invest.tinkoff.ru (178.248.239.55), 30 hops max, 60 byte packets
>  1  10.149.244.1 (10.149.244.1)  0.387 ms  0.375 ms  0.361 ms
>  2  92.53.93.62 (92.53.93.62)  1.114 ms  1.006 ms  1.088 ms
>  3  92.53.93.113 (92.53.93.113)  1.072 ms ae16-296.RT.KM.SPB.RU.retn.net (87.245.252.114)  1.058 ms 92.53.93.113 (92.53.93.113)  1.196 ms
>  4  * ae16-296.RT.KM.SPB.RU.retn.net (87.245.252.114)  1.171 ms *
>  5  GW-Xtend.retn.net (87.245.253.194)  11.368 ms ae1-3.RT.MR.MSK.RU.retn.net (87.245.232.128)  11.453 ms  11.447 ms
>  6  GW-Xtend.retn.net (87.245.253.194)  11.431 ms * *
>  7  * * *
>  8  * * *
>  9  * * *
> 10  * * *
> 11  * * *
> 12  * * *
> 13  * * *
> 14  * * *
> 15  * * *
> 16  * * *
> 17  * * *
> 18  * * *
> 19  * * *
> 20  * * *
> 21  * * *
> 22  * * *
> 23  * * *
> 24  * * *
> 25  * * *
> 26  * * *
> 27  * * *
> 28  * * *
> 29  * * *
> 30  * * *

**Comment by kirill-znamenskiy** [comment]
> GET /openapi/portfolio HTTP/1.1
> User-Agent: GuzzleHttp/6.5.3 curl/7.64.0 PHP/7.3.14-1~deb10u1
> Host: api-invest.tinkoff.ru
> Date: Mon, 15 Jun 2020 09:23:51 GMT
> Authorization: Bearer t.MRuvlM62m00VjR9oeuEpdU7AiYAysyVPmKQgcVzNDfLqmW6dVqlYV35hHEtPDm3sJWgqVf5EDR2AduSXP9viSQ
> Content-Type: application/json;charset=UTF-8
> Accept: application/json


> HTTP/1.1 500 Internal Server Error
> Server: nginx
> Date: Mon, 15 Jun 2020 09:23:56 GMT
> Transfer-Encoding: chunked

**Comment by kirill-znamenskiy** [comment]
> GET /openapi/portfolio HTTP/1.1
> User-Agent: GuzzleHttp/6.5.3 curl/7.64.0 PHP/7.3.14-1~deb10u1
> Host: api-invest.tinkoff.ru
> Date: Mon, 15 Jun 2020 09:23:51 GMT
> Authorization: Bearer t.xxxxxxxx
> Content-Type: application/json;charset=UTF-8
> Accept: application/json

> HTTP/1.1 500 Internal Server Error
> Server: nginx
> Date: Mon, 15 Jun 2020 09:23:56 GMT
> Transfer-Encoding: chunked

**Comment by NikitaMelnikov** [comment]
@kirill-znamenskiy засветился токен

**Comment by kirill-znamenskiy** [comment]
> @kirill-znamenskiy засветился токен
благодарю! сразу же сам заметил и уже перевыпустил

**Comment by doroginin** [comment]
У меня в 12:39 все починилось

**Comment by vrubanov** [comment]
> 
> 
> У меня в 12:39 (по МСК) все починилось

А оно нестабильно сейчас работает. То работает, то не работает, при чем по-разному не работает - на случайных различных вызовах bad response генерит. Сервера пляшут какой-то сатанинский танец)

**Comment by NikitaMelnikov** [comment]
Со своей стороны не наблюдаем проблем, есть срабатывания рейт лимитов, обратите внимание на ответ сервера

**Comment by vrubanov** [comment]
@NikitaMelnikov Не могу согласиться. Днем действительно был момент, когда все сработало. Но вот прям осейчас опять запустил и опять проблемы:
// до этого несколько сотен таких же bad response
bad response to https://api-invest.tinkoff.ru/openapi/market/candles?figi=BBG000BFNR17&from=2013-01-09T23%3A00%3A00Z&interval=day&to=2020-06-13T23%3A00%3A00Z code=429, body=
can't do request to : Get "https://api-invest.tinkoff.ru/openapi/market/candles?figi=BBG000BFNR17&from=2013-01-08T23%3A00%3A00Z&interval=day&to=2020-06-13T23%3A00%3A00Z": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
can't do request to : Get "https://api-invest.tinkoff.ru/openapi/market/candles?figi=BBG000BFNR17&from=2013-01-07T23%3A00%3A00Z&interval=day&to=2020-06-13T23%3A00%3A00Z": dial tcp 178.248.239.55:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
can't do request to : Get "https://api-invest.tinkoff.ru/openapi/market/candles?figi=BBG000BFNR17&from=2013-01-06T23%3A00%3A00Z&interval=day&to=2020-06-13T23%3A00%3A00Z": context deadline exceeded

Последнее понятно, но вопрос откуда берутся первичные bad response на запрос свечи?

Повторяю - код не менялся и до 11 июня отлично работал. И каким-то чудом сработал сегодня днем разок. Но недолго музыка играла...

**Comment by vrubanov** [comment]
@NikitaMelnikov ошибка с bad response при получении исторических свечей стабильно продолжает быть. Как это исправить?

**Comment by u35tpus** [comment]
@vrubanov , в OpenAPI есть ограничения  на кол-во запросов в  минуту. 429 возвращается когда превышен лимит.

**Comment by NikitaMelnikov** [comment]
@u35tpus все верно отметил

**Comment by vrubanov** [comment]
@u35tpus спасибо! Действительно, количество данных выросло и 120 запросов перестало хватать для анализа портфеля. Пришлось тупо вставлять минутную паузу в ответ на эту ошибку, чтобы анализ сработал полностью. Но почему текст ошибки говорит не содержит текста Too many requests?

**Comment by vrubanov** [comment]
Но сегодня новый фокус:

**Comment by vrubanov** [comment]
На всякий случай:
tracert api-invest.tinkoff.ru
Трассировка маршрута к api-invest.lb.tinkoff.ru [178.248.239.55]
с максимальным числом прыжков 30:
  1    <1 мс    <1 мс    <1 мс  rt [192.168.0.1]
  2     1 ms     1 ms     1 ms  broadband-90-154-77-179.ip.moscow.rt.ru [90.154.77.179]
  3     2 ms     1 ms     1 ms  77.37.250.194
  4     2 ms     2 ms     2 ms  77.37.250.249
  5     3 ms     2 ms     2 ms  m9-cr04-be104.1121.msk.mts-internet.net [212.188.12.100]
  6     2 ms     2 ms     2 ms  212.188.22.211
  7     2 ms     2 ms     2 ms  178.248.239.55

Трассировка завершена.

**Comment by NikitaMelnikov** [comment]
@vrubanov ответили в другом тикете
