### ISSUE TITLE
Ребята, 1.5К 500ых ошибок за 3 месяца - это ужасно

### ISSUE THREAD

**Issue by scythargon** [TinkoffCreditSystems/invest-openapi#257]
Скриншот из Sentry, следящего за проектом.
Запрос просто на получение свечей. Случается и днем и ночью. Можно сделать апи более стабильным, пожалуйста?
![image](https://user-images.githubusercontent.com/1755870/84633469-1cb5fd00-aef9-11ea-9748-5c237c1e7ede.png)

**Comment by NikitaMelnikov** [comment]
Добрый день, не связано ли это с превышением лимитов на запросы?

**Comment by mvkasatkin** [comment]
Подтверждаю. Очень много 500. Не всегда, но часто. (И это не связано с лимитами, на которые прилетает 429)
![image](https://user-images.githubusercontent.com/3389061/84641177-e4c4af00-af24-11ea-9b32-7df527b5fa5a.png)

**Comment by Dazlonar** [comment]
Сейчас уже минимум 30 минут вылетает 500 ошибка на запросе свечей и портфолио каждый раз. Бот простаивает без дела.

**Comment by NikitaMelnikov** [comment]
Сегодня утром были проблемы с частичной недоступностью сервисов.

**Comment by NikitaMelnikov** [comment]
Для детального разбора ситуаций, если он необходим, обратитесь, пожалуйста, в поддержку. 
Для разбора понадобятся дополнительные персональные данные, которые не хочется светить тут :)

**Comment by BusinessDuck** [comment]
А какой у вас Лимит на запросы ?  - 3 или 5? Я просто уже сделал в случае 500 - через 10 минут ищу сделку в истории, если ее нет делаю повторную заявку. Так что бы вы думали? В течении 3х ретраев 500. Не утром а в основную сессию!

**Comment by BusinessDuck** [comment]
Сейчас буду делать защиту третьего уровня уже по косвенным признакам, что на балансе есть бумага запрошеной лотности, тут уже прям совсем некрасиво, но вы вынуждаете просто!

**Comment by NikitaMelnikov** [comment]
Мы взяли в работу ситуацию с сервисом операций, будем приводить в порядок

**Comment by mlshvdv** [comment]
@NikitaMelnikov добрый вечер, есть ли новости по этой проблеме? Уже полтора часа список операций отдает 500-ку после 1 минутного таймаута:
`/operations?brokerAccountId=<id>&from=2020-07-28T15:00:00Z&to=2020-07-28T16:00:00Z` — срез по дате маленький . Операций там штук 10-20 за сутки. 

Перезапрашиваю операции каждые 2-10 секунд.

**Comment by NikitaMelnikov** [comment]
@mlshvdv она исправлена

**Comment by Fatal1ty** [comment]
Сегодня с утра снова стало сыпаться много 500х ошибок
<img width="339" alt="image" src="https://user-images.githubusercontent.com/323962/89625707-fb421380-d8a0-11ea-9b1a-b540362e0879.png">

**Comment by NikitaMelnikov** [comment]
@Fatal1ty обсуждали здесь https://github.com/TinkoffCreditSystems/invest-openapi/issues/315

**Comment by EJohnF** [comment]
я начал уже просто игнорировать 500 ошибки и убрал их оповещения об ошибках, иначе иные реальные ошибки работы бота просто теряются. 
Хотя в целом кажется это единственная подобная платформа за что вам спасибо!

**Comment by NikitaMelnikov** [comment]
@EJohnF спасибо за фидбек 🙏 
Работу со статус-кодами и ошибками мы проведем в следующей версии api
