### ISSUE TITLE
Источник объемов торгов в /market/candles

### ISSUE THREAD

**Issue by ShapeShifter08** [TinkoffCreditSystems/invest-openapi#258]
Хотелось бы понять из какой статистики взяты объемы торгов по тикетам?
К примеру на тикете M 12.06.20 23:55 объем 2.4м (investing) / 47.194к (tradingview) / 133360 (тинькофф)

**Comment by NikitaMelnikov** [comment]
Добрый день, данные по объему предоставляются биржей
