### ISSUE TITLE
Неверная цена бумаги в портфеле

### ISSUE THREAD

**Issue by Yuryi1806** [TinkoffCreditSystems/invest-openapi#26]
С периодичностью возвращается не цена бумаги в портфеле, а цена бумаги на бирже

averagePositionPrice->value

Ошибка повторяется 2 дня 24 и 25 октября утром. Поэтому позиции на продажу выставляются дешевле чем были куплены. Приходится цены писать в файл и считывать с утра из-за этой ошибки

**Comment by NikitaMelnikov** [comment]
Добрый день,

Напишите, пожалуйста, мне на рабочую почту n.v.melnikov@tinkoff.ru, попробуем разобраться 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NikitaMelnikov** [comment]
Подскажите, сейчас воспроизводится ситуация?

**Comment by Yuryi1806** [comment]
Добрый день !

За прошлую неделю ни разу. Проблема была в том, что у некоторых бумаг просто не было свойства averagePositionPrice. Дело не в API а в самом приложении Тинькофф также не было цен на некоторых позициях

Но сейчас все исправили, за прошлую неделю ошибка не повторялась.

Спасибо Вам
