### ISSUE TITLE
504 ошибка при попытке получить список операций

### ISSUE THREAD

**Issue by betslus1** [TinkoffCreditSystems/invest-openapi#260]
Добрый день,
504 ошибка при попытке получить список операций.
Раньше тоже бывало, даже пришлось сокращать обороты (хотя имхо 15000 сделок за месяц не так и много), вместо того чтобы увеличивать. 
Сейчас не дает выгрузить ни за какой период (запрос раз в 2 минуты, раньше тоже встречалась, уменьшал период выгрузки)
Возможно связано с https://github.com/TinkoffCreditSystems/invest-openapi/issues/200 (вот совершенно они не нужны в выгрузке, первое что приходится делать, удалять из массива отмененные операции - 95% данных).
На сайте/телефоне/терминале/отчетах уже давно все умерло и скорее всего навсегда, только API более менее работало и давало посмотреть движение средств (кроме дивидендов #215) и какие были сделки, сейчас совсем не знаю что там на счете творится...

Если нужна помощь в дебаге (или конф. данные) то tinkoff@slus.name
Умерло 17.06  в 11:46 по москве.

```
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.15.5</center>
</body>
</html>
```

```
  var now  = new Date();
  var to   = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 23, 59);
  var from = new Date();
  from.setDate(to.getDate() - 2);
  try {
    await sleep(190);
    var operationNow = await api.operations({
      'from' : ISODateString(from),
      'to'   : ISODateString(to),
    });
    
  }catch(err){
    log('Не удалось получить последние операции ', 'itog');
    log(err, 'itog');
  }
```

**Comment by Dazlonar** [comment]
Подтверждаю в настоящий момент, ловлю туже ошибку, при загрузке сегодняшней истории, в которой всего 1 сделка.

**Comment by NikitaMelnikov** [comment]
Добрый день, ситуация исправлена

**Comment by vrubanov** [comment]
Оказывается не я один такой. Только вот у меня эту ошибку выдает прямо сейчас. @NikitaMelnikov не совсем она выходит исправлена...

**Comment by NikitaMelnikov** [comment]
@vrubanov напишите, пожалуйста, в поддержку. Мы видим 504 ошибки, коллеги занимаюсь исправлением

**Comment by betslus1** [comment]
Подтверждаю, только не 504, а internal error сегодня, тоже отпишусь в поддержку.
