### ISSUE TITLE
operations перестал работать

### ISSUE THREAD

**Issue by Antitesla** [TinkoffCreditSystems/invest-openapi#262]
Отвечает Required fields are empty на запрос operations, который раньше работал.

**Comment by Antitesla** [comment]
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.15.5</center>
</body>
</html>

сам сокет вот что отвечает

**Comment by dlinnozmey** [comment]
> <title>504 Gateway Time-out</title>
> # 504 Gateway Time-out
> nginx/1.15.5
> сам сокет вот что отвечает

Да, до сих пор такой ответ. При этом, если запрос через sandbox, то ответ нормальный приходит.

**Comment by Antitesla** [comment]
> > <title>504 Gateway Time-out</title>
> > # 504 Gateway Time-out
> > nginx/1.15.5
> > сам сокет вот что отвечает
> 
> Да, до сих пор такой ответ. При этом, если запрос через sandbox, то ответ нормальный приходит.

А через sandbox можно получить сделки реального счета или только, которые в песочнице? Просто нужно что-то делать, раз разработчики не реагируют - у меня в пятницу убыток, система закупила акции, которые не управлялись из-за того, что система не могла получить информацию по сделкам... Как-то несерьезно на такую критическую ошибку 3 дня нет реакции...

**Comment by vrubanov** [comment]
У меня ошибка 504 Gateway Time-out при попытке получить список операций

**Comment by dlinnozmey** [comment]
> > > <title>504 Gateway Time-out</title>
> 
> > > # 504 Gateway Time-out
> 
> > > nginx/1.15.5
> 
> > > сам сокет вот что отвечает
> 
> > 
> 
> > Да, до сих пор такой ответ. При этом, если запрос через sandbox, то ответ нормальный приходит.
> 
> 
> 
> А через sandbox можно получить сделки реального счета или только, которые в песочнице? Просто нужно что-то делать, раз разработчики не реагируют - у меня в пятницу убыток, система закупила акции, которые не управлялись из-за того, что система не могла получить информацию по сделкам... Как-то несерьезно на такую критическую ошибку 3 дня нет реакции...

Насколько я понял, через sandbox только то, что заявлялось в sandbox, на то он и sandbox. Проблема есть, комментариев вот пока что нет, а жаль.

**Comment by Antitesla** [comment]
null передавать вместо figi

**Comment by homm** [comment]
@NikitaMelnikov Будет какая-то реакция? До сих пор не работает же

**Comment by NikitaMelnikov** [comment]
Работаем над этим

**Comment by NikitaMelnikov** [comment]
Проверьте на своей стороне, пожалуйста

**Comment by Antitesla** [comment]
Сейчас работает.

**Comment by ddmrtc** [comment]
с 16:06 сегодня снова 504 на каждый запрос
```
16:06:24.541 - _make_request - DEBUG - https://api-invest.tinkoff.ru:443 "GET /openapi/operations?from=2019-06-24T16%3A06%3A09.510629%2B00%3A00&to=2020-06-23T16%3A06%3A09.510629%2B00%3A00&figi=BBG000BLCPY4 HTTP/1.1" 504 127
16:06:24.541 - get_operations - DEBUG - response: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.15.5</center>
</body>
</html>

```

**Comment by ddmrtc** [comment]
заработало

**Comment by ddmrtc** [comment]
а, нет, все равно 504 проскакивают

**Comment by ddmrtc** [comment]
503 теперь
```
16:21:11.741 - _make_request - DEBUG - https://api-invest.tinkoff.ru:443 "GET /openapi/operations?from=2019-06-24T16%3A21%3A11.710330%2B00%3A00&to=2020-06-23T16%3A21%3A11.710330%2B00%3A00&figi=BBG000BLCPY4 HTTP/1.1" 503 143
16:21:11.741 - get_operations - DEBUG - response: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.15.5</center>
</body>
</html>
```
