### ISSUE TITLE
INTERNAL_ERROR при чтении сделок

### ISSUE THREAD

**Issue by truedmitri** [TinkoffCreditSystems/invest-openapi#263]
Добрый день!

В череде одинаковых запросов на чтение сделок, получаю ошибку от API
payload={'message': 'INTERNAL_ERROR', 'code': 'INTERNAL_ERROR'} status='Error' tracking_id='cf9cf7ba3df27138'
Помогите, пожалуйста, понять причину

**Comment by NikitaMelnikov** [comment]
Добрый день, подскажите, сейчас воспроизводится?

**Comment by truedmitri** [comment]
Добрый день! Нет, ошибка плавающая, вылезает примерно раз в день. Я предполагал, что вы по tracking_id сможете посмотреть в чем дело

**Comment by NikitaMelnikov** [comment]
Если сегодня повторится, то давайте попробуем найти по trackingId новый кейс

**Comment by betslus1** [comment]
@NikitaMelnikov 
> Если сегодня повторится, то давайте попробуем найти по trackingId новый кейс

Сегодня что-то новенькое, пропала только Московская биржа, питерская отображается в списке сделок.
Создавать новый запрос в поддержку? (старый еще не закрыли)

**Comment by NikitaMelnikov** [comment]
Давайте через поддержку решим, нужны будут дополнительные данные

**Comment by truedmitri** [comment]
Сегодня повторилось:
{'trackingId': 'ea4695737e15086c', 'payload': {'message': 'INTERNAL_ERROR', 'code': 'INTERNAL_ERROR'}, 'status': 'Error'}
