### ISSUE TITLE
Любой запрос к API выкидывает InternalError или SocketTimeoutException [Java SDK]

### ISSUE THREAD

**Issue by KonstantinHudyakov** [TinkoffCreditSystems/invest-openapi#265]
Здравствуйте! Столкнулся с проблемой, что любой запрос к API возвращает InternalError или SocketTimeoutException. Пишу сюда, поскольку проблема скорее всего не в SDK, а в самом API.
Может быть у вас сервис слёг?

**Comment by felixrap** [comment]
Он теперь по понедельникам лежит.  У меня тоже ошибки

**Comment by jonny1960** [comment]
С их API нужно работать со вторника по пятницу. В понедельник после выходных им тяжело раскачаться.

**Comment by doroginin** [comment]
Те же проблемы весь день: `net/http: request canceled (Client.Timeout exceeded while awaiting headers)` timeout 30 секунд установлен

**Comment by jk100magnys** [comment]
Подписываюсь. Такая же ситуация.

**Comment by Mastic0re** [comment]
аналогично, к сожалению

**Comment by NikitaMelnikov** [comment]
Сейчас все должно восстановиться, проверьте, пожалуйста

**Comment by KonstantinHudyakov** [comment]
Заработало.

**Comment by Mastic0re** [comment]
Запрос по операциям выдает ошибку:
`<html>

<head>
	<title>502 Bad Gateway</title>
</head>

<body>
	<center>
		<h1>502 Bad Gateway</h1>
	</center>
	<hr>
	<center>nginx/1.15.5</center>
</body>

</html>`
