### ISSUE TITLE
Ошибка 500 без ответного json

### ISSUE THREAD

**Issue by s0501007** [TinkoffCreditSystems/invest-openapi#266]
Весь день ошибка при запросе аккаунтов. Что в сэндбоксе (https://api-invest.tinkoff.ru/openapi/sandbox/user/accounts), что на проде.
Около 8 утра по МСК ещё нормально было.

**Comment by yellow444** [comment]
Response пустой идет

**Comment by NikitaMelnikov** [comment]
Могли бы попробовать через `curl -v` сделать запрос и скинуть лог?

**Comment by s0501007** [comment]
Сейчас работает.
Что-то вы там починили :)
Если в будущем повторится - проверю, что curl показывает
