### ISSUE TITLE
Планируется ли открывать CORS для REST API?

### ISSUE THREAD

**Issue by toastyboost** [TinkoffCreditSystems/invest-openapi#269]
Здравствуйте, планируется ли открывать CORS для кросс-доменных запросов к REST API? :)

```Access to fetch at 'https://api-invest.tinkoff.ru/openapi/user/accounts' from origin 'https://toastyboost.github.io' has been blocked by CORS policy: Request header field mode is not allowed by Access-Control-Allow-Headers in preflight response.```

**Comment by l1bbcsg** [comment]
Похоже, `Access-Control-Allow-Headers: *` прикрутили, но только для ответов с 200.

429 все ещё падают с ошибками CORS.

**Comment by NikitaMelnikov** [comment]
@l1bbcsg вы все верно описали, пока что не планируем менять поведение

**Comment by l1bbcsg** [comment]
Может всё-таки подумаете о том чтобы поменять?

Браузеры с CORS ведь даже код ответа прочитать не смогут. Нет возможности узнать отвалилось оно с 429, 500 или ещё чем-то.
