### ISSUE TITLE
История по тикеру

### ISSUE THREAD

**Issue by o1st** [TinkoffCreditSystems/invest-openapi#27]
Доброго времени суток.
Подскажите пожалуйста, есть ли возможность получать историю изменения цены по бумаге на определенном интервале? Будет ли такая возможность добавлена?

**Comment by o1st** [comment]
Если я правильно понимаю, то на данный момент альтернатива - "Получение исторических свечей по FIGI". 
Хотелось бы иметь возможность получать выборку на произвольном интервале в виде [{t,v}], где t-время, v-цена в момент времени.

**Comment by lightning95** [comment]
Здравствуйте, как Вы представляете 
> историю изменения цены
и
> v-цена в момент времени.
?

Моменты времени, в которые цена достигала заданную?

**Comment by o1st** [comment]
Возможно немного не так выразился.
Допустим хочу получить изменение цены по SBER на интервале 10.10.2019 - 12.10.2019 с заданной частотностью. Возможный ответ мог бы выглядеть как массив точек ({t,v}), каждая из которых представляла бы цену бумаги(v) в момент времени(t).

**Comment by NikitaMelnikov** [comment]
@o1st в данный момент мы отдаем только свечи по историческим данным, issue пока не буду закрывать, так как возможно такая функциональность появится позже

**Comment by o1st** [comment]
Спасибо, я собственно это и хотел услышать
