### ISSUE TITLE
Не возвращает свечи для облигации RU000A101QF7

### ISSUE THREAD

**Issue by vrubanov** [TinkoffCreditSystems/invest-openapi#270]
Перестали возвращаться дневные свечи по инструменту:
Ticker: RU000A101QF7
Name: Евроторг 001P-01
FIGI: TCS00A101QF7

**Comment by NikitaMelnikov** [comment]
В системе зарегистрированы две бумаги под этот бонд, посмотрим

**Comment by NikitaMelnikov** [comment]
Актуальный FIGI для этого инструмента BBG00V92X4F6

**Comment by vrubanov** [comment]
@NikitaMelnikov спасибо! Только что ж он в операции выдает именно этот TCS00A101QF7. Хардкодить что ли преобразование одного кода в другой...

**Comment by vrubanov** [comment]
@NikitaMelnikov сегодня столкнулся с аналогичной проблемой для RU000A100D89 (Республика Беларусь выпуск 7). Какой там корректный FIGI нужно хардкодить для получения свечей?

**Comment by vrubanov** [comment]
Нужный FIGI нашел. Похоже, эта проблема существует для тех облигаций, по которым Тинькофф участвовал в размещении. При этом в списке операций и в позиции портфеля используется TCS00A100D89, а вот свечи посмотреть возможно только по BBG00TQHNK64. Аналогично для Евроторга.

**Comment by NikitaMelnikov** [comment]
Да, дело в том, что при первичном размещении облигаций на рынке фактически не существует. Поэтому для таких кейсов нужно искать FIGI по тикеру

**Comment by Andrey-VLV** [comment]
Проблема повторилась. Поиск по тикеру возвращает 2 инструмента, которые являются одной бумагой.


{
    "trackingId": "10f2a84b77c685e4",
    "payload": {
        "instruments": [
          {
            "figi": "TCS00A101QF7",
            "ticker": "RU000A101QF7",
            "isin": "RU000A101QF7",
            "minPriceIncrement": 0.1,
            "faceValue": 1000,
            "lot": 1,
            "currency": "RUB",
            "name": "Евроторг 001P-01",
            "type": "Bond"
          },
          {
            "figi": "BBG00V92X4F6",
            "ticker": "RU000A101QF7",
            "isin": "RU000A101QF7",
            "minPriceIncrement": 0.1,
            "faceValue": 1000,
            "lot": 1,
            "currency": "RUB",
            "name": "Евроторг 001P-01",
            "type": "Bond"
          }
        ],
      "total": 2
    },
  "status": "Ok"
}
