### ISSUE TITLE
Ошибка отмены поручения

### ISSUE THREAD

**Issue by koshik34** [TinkoffCreditSystems/invest-openapi#271]
А в чем причина ошибки то?
Пару дней назад работало без ошибок, сейчас довольно часто падает.
{ message: 'Ошибка отмены поручения', code: 'OrderCancelError' }

**Comment by NikitaMelnikov** [comment]
Добрый день, обратитесь, пожалуйста, в поддержку, нужны дополнительные данные для разбора
