### ISSUE TITLE
запрос к /portfolio выдает записи с balance: 0

### ISSUE THREAD

**Issue by kniknak** [TinkoffCreditSystems/invest-openapi#273]
Если я делаю запрос к `/portfolio`, то в результате приходит только 100 записей, хотя в документации нет никакой информации о пагинации

Пример с node.js api:
```
return (api as any).makeRequest('/portfolio', { params: { brokerAccountId } })
```

Как сделать так, чтобы получить список всех позиций в портфолио?

**Comment by NikitaMelnikov** [comment]
Добрый день, 

В портфеле отображаются бумаги из базового каталога, возможно дело в этом?

**Comment by kniknak** [comment]
вряд ли в этом, так как в ответ не попадают позиции в конце списка по алфавиту, например YNDX или PMSBP.

Также 100 записей - лимит как для обычного портфеля, так и для ИИС, т.е. маловероятное совпадение

**Comment by lightning95** [comment]
это с биржевым токеном или в сендбоксе?

**Comment by kniknak** [comment]
с биржевым

**Comment by kniknak** [comment]
@NikitaMelnikov я понял в чем проблема. Оказалось, что ошибка в другом месте.
По ряду позиций мне приходит `balance: 0`, хотя в реальности он больше нуля (что естественно для `/portfolio`)

Примеры тикеров с такой проблемой (их пара десятков):
YNDX
RTKMP
TGKBP
PMSBP
PMSB
OBUV
