### ISSUE TITLE
В списке операций отсутствуют записи по покупке акций Dropbox (DBX)

### ISSUE THREAD

**Issue by vrubanov** [TinkoffCreditSystems/invest-openapi#275]
Обнаружил сегодня, что в возвращаемом через API списке операций отсутствуют записи по покупке акций Dropbox (DBX)... От слова совсем. А должно быть 5 штук. В приложении операции видны. Со всеми остальными бумагами все в порядке.

**Comment by vrubanov** [comment]
ADD: еще и в списке позиций Portfolio DBX оказалось отсутствует.

**Comment by vrubanov** [comment]
Операции появились. Что это был за глюк - непонятно. Но может вам этот отчет поможет что-то улучшить.

**Comment by betslus1** [comment]
Часто бывают задержки, обычно не более 3-х часов, с этим видимо придется смириться :(

**Comment by NikitaMelnikov** [comment]
Операции в списке могут появляться не сразу, мы работаем над этим
