### ISSUE TITLE
API только для чтения. Когда?

### ISSUE THREAD

**Issue by ano-dpo-snta** [TinkoffCreditSystems/invest-openapi#276]
Добрый день.
Невозможно делать какие-либо внешние сервисы для других людей, пока ваш API и для чтения и для торговли
Разделите ключи, пожалуйста.

Есть уже готовый сервис, но люди шарахаются от необходимости отдавать такой токен.

**Comment by NikitaMelnikov** [comment]
Есть открытый тикет по этому вопросу, пока что не планировали дату
