### ISSUE TITLE
Неверные тикеры валют

### ISSUE THREAD

**Issue by mishannn** [TinkoffCreditSystems/invest-openapi#277]
При получении списка валют в поле `ticker` возвращается ISIN.

При получении списка через библиотеку приходит такой ответ, с помощью которого трудно достаточно сгенерировать нормальную таблицу курсов валют:
![image](https://user-images.githubusercontent.com/15077672/85947625-8cde6d00-b954-11ea-9e80-b5a6be2e1e65.png)

При этом в веб-версии все корректно (тикер - USDRUB, который легко можно преобразовать в таблицу):
![image](https://user-images.githubusercontent.com/15077672/85947661-c4e5b000-b954-11ea-952d-69df36436da8.png)

**Comment by NikitaMelnikov** [comment]
Добрый день, 
Могли бы подробней рассказать почему неудобно? Для удобного отображения есть поле `currency`

P.S. Использовать получение данных не из OpenApi крайне не рекомендую, так как обратную совместимость протокола гарантировать мы не можем.

**Comment by mishannn** [comment]
@NikitaMelnikov, для создания таблицы курса валюты, я беру тикер (пока что из API веб-версии) и делю его на 2 части, например, USDRUB - USD -> RUB, USDEUR - USD -> EUR и т. д., на данный момент в OpenAPI возвращаются вместо тикера значения USD000UTSTOM и EUR_RUB__TOM, которые весьма непросто подобным образом распарсить, других способов получить курс валюты в OpenAPI не нашел.

**Comment by NikitaMelnikov** [comment]
Для валют рекомендую использовать кастомную логику
