### ISSUE TITLE
Дубликаты в /market/bonds

### ISSUE THREAD

**Issue by volth** [TinkoffCreditSystems/invest-openapi#278]
В /market/bonds две облигации "Республика Беларусь выпуск 7" с отличающимися figi: "TCS00A100D89" и "BBG00TQHNK64"
isin у них одинаковый RU000A100D89

**Comment by vrubanov** [comment]
Да, похоже, эта проблема существует для тех облигаций, по которым Тинькофф участвовал в размещении. При этом в списке операций и в позиции портфеля выдается TCS00A100D89, а вот свечи посмотреть возможно только по BBG00TQHNK64.

**Comment by conferno** [comment]
Кстати, "Беларусь 7" и в Альфабанке тоже раздвоен (для одного из инструментов свечи доступны только до середины июня, а для другого только после).

**Comment by NikitaMelnikov** [comment]
@vrubanov все верно, такое поведение для первичного размещения

**Comment by vrubanov** [comment]
Ну то есть workaround реально хардкодить таблицы преобразования TCS00A100D89 <-> BBG00TQHNK64? А не будет ли фиксом после размещения заменять временный TCS00A100D89 на постоянный и общепринятый BBG00TQHNK64 везде в системе? @NikitaMelnikov

**Comment by NikitaMelnikov** [comment]
Метод /market/search-by-ticker возвращает несколько значений, при поиске облигаций можно использовать его чтобы автоматизировать
