### ISSUE TITLE
В чем разница InstrumentType

### ISSUE THREAD

**Issue by ivanNzhukov** [TinkoffCreditSystems/invest-openapi#280]
В чем разница ru.tinkoff.invest.openapi.models.portfolio.InstrumentType и ru.tinkoff.invest.openapi.models.market.InstrumentType ? 

Зачем было создано 2 одинаковых класса в разных пакетах?

**Comment by NikitaMelnikov** [comment]
Техническая особенность построения описания API, аккуратно поправим в будущих версиях

**Comment by ivanNzhukov** [comment]
А есть предположения, какая из них останется, чтобы сейчас уже перевести завязку на необходимый пакет.

**Comment by NikitaMelnikov** [comment]
Пока лучше на это не ориентироваться

**Comment by kitMP** [comment]
Вообще говоря, ru.tinkoff.invest.openapi.models.market.InstrumentType более общий вариант, т.к. тип инструмента существует вне зависимости от того, есть портфель или нет. В своём коде я могу вообще не использовать портфель, но при этом получать тип инструмента и свечи с данным тикером или фиги.

**Comment by ivanNzhukov** [comment]
Более общее это да, но приходится делать конвертер, на данный момент, между этими 2 типами. Я бы тоже использовал из пакета вне портфеля
