### ISSUE TITLE
Как нормально получить свечу в реальном времени?

### ISSUE THREAD

**Issue by jonny1960** [TinkoffCreditSystems/invest-openapi#287]
Подскажите, можно добавить в получение исторических данных (/market/candles) также текущую свечу, которая торгуется сейчас и которую можно получить поток "event": "candle:?

Так как в исторические данные отстают и данная свеча приходит спустя 1-2 минуты

Как у вас получать текущую свечу через и максимум 6 потоков не понятно.

Когда получаешь одну вроде все более менее - только периодически возникает  429 Too Many Requests, но это ладно.
Но когда начинаешь получать свечи сразу для нескольких тикеров, ответы возращаются ни пойми как. Для одного инструмента возвращает данные другого. Как я понял надо делать сначала подписку потом сразу отписку.

Можно просто получать эту последнюю свечу сразу с историческими данными, чтобы не было путаницы?

**Comment by Dazlonar** [comment]
Стоит понимать что для одного соединения вы можете делать несколько подписок и тогда действительно данные будут приходить от всех подписок в одно место и ваша задача их разделить.
Это достаточно просто вы можете просто сравнивать Figi ответа и понимать к кому инструменту относится эта свеча. 
Вам необязательно делать для каждой подписки отдельное соединение и упираться в лимит.

**Comment by jonny1960** [comment]
А нельзя отдавать текущую свечу также через api-invest.tinkoff.ru/openapi, чтобы она приходила точно которая нужна и чтобы не сравнивать и не ждать в подписке появление нужно ответа?
Или лучше всего добавить текущую свечу к историческим данным?

**Comment by NikitaMelnikov** [comment]
Для актуальных данных с биржи лучше использовать стриминг все же
