### ISSUE TITLE
получение цены каждую секунду

### ISSUE THREAD

**Issue by dulimov** [TinkoffCreditSystems/invest-openapi#288]
На данный момент у нас получается только смотреть цену в стакане раз в минуту.

1 можно ли получать стакан каждую секунду ?
2 можно ли получать рыночную цену каждую секунду ?

**Comment by Dazlonar** [comment]
Вы пробовали использовать streaming протокол? Который работает как подписка на обновление стакана через WebSocket?

**Comment by NikitaMelnikov** [comment]
Спасибо @Dazlonar за ответ, все действительно так. В случае @dulimov надо использовать streaming-протокол
