### ISSUE TITLE
Как выкачать часовые данные за большой период времени (больше года)

### ISSUE THREAD

**Issue by rlz** [TinkoffCreditSystems/invest-openapi#289]
Свечи по дням обычно показывают некорректные данные. Мне говорили, что это потому, что вы их получаете от биржи и косяк на их стороне, а все что меньше — считаете сами.

Для воркэраунда я решил выкачать часовые данные и сделать свой агрегат. Но их можно качать максимум за 7 дней. Я побил на семидневные интервалы год — меня отбило по 'Too many request'.

Как же быть? Мне нужны точные дневные свечи. А то сейчас некоторые показывают значения, в которых акции вообще не были за день.

**Comment by NikitaMelnikov** [comment]
Добрый день, рейт лимиты описаны на странице https://tinkoffcreditsystems.github.io/invest-openapi/rest/
Вам нужно использовать троттлинг запросов на своей стороне, как пример для этого использовать счетчик запросов, при достижении 120 запросов ждать 1 минуту
