### ISSUE TITLE
Тикер TCS. Дневные свечи. Close равен Open

### ISSUE THREAD

**Issue by EvgenyBatalin** [TinkoffCreditSystems/invest-openapi#290]
Добрый день.
Начиная с июля по тикеру TCS дневные свечи расчитываются некорректно. Close всегда равен Open.

Такое же поведение иногда встречается по другим тикерам. Как минимум некорректно отображается Close.

Не уверен правда что это баг именно API. В мобильном приложении тоже самое.

**Comment by lightning95** [comment]
А почему вы считаете, что равенство Open и Close - некорректно?

**Comment by EvgenyBatalin** [comment]
> А почему вы считаете, что равенство Open и Close - некорректно?
> 
> > Добрый день.
> > Начиная с июля по тикеру TCS дневные свечи расчитываются некорректно. Close всегда равен Open.
> > Такое же поведение иногда встречается по другим тикерам. Как минимум некорректно отображается Close.
> > Не уверен правда что это баг именно API. В мобильном приложении тоже самое.
> 
> @EvgenyBatalin

Потому что я торгую на бирже. Так само собой бывает, но не 10 дней подряд.

Свежий пример - закрытие 14.07.2020
Свеча D - закрытие 20.57
Свеча H4 (и меньше) - закрытие 21.5

Итог - Close у свечей не совпадает.

Еще раз - до июля проблем нет. Проблемы начались с июля.

**Comment by EvgenyBatalin** [comment]
Проблему поправили (я так понимаю проблема была не в API, а где-то ниже). Issue можно закрыть. Спасибо.
