### ISSUE TITLE
Отрицательное значение в свойстве blocked

### ISSUE THREAD

**Issue by olsh** [TinkoffCreditSystems/invest-openapi#292]
При запросе `/portfolio` у позиции с тикером `USD000UTSTOM` возвращаетя отрицательное значение в поле `blocked`.
Это допустимо или баг? 
Как при этом интерпретировать отрицательное значение?

**Comment by NikitaMelnikov** [comment]
Вчера наблюдалось некорректное поведение системы, сейчас такого поведения не должно быть

**Comment by mlshvdv** [comment]
@NikitaMelnikov если проблема повторится, то всё же как это отрицательное значение интерпретировать?

**Comment by NikitaMelnikov** [comment]
Как критическую ошибку
