### ISSUE TITLE
Идентификаторы заявок на текущий актив в портфеле

### ISSUE THREAD

**Issue by BusinessDuck** [TinkoffCreditSystems/invest-openapi#293]
Получаю в ответ на создание заявки - "Торговая система в данный момент недоступна", вот пруф
![image](https://user-images.githubusercontent.com/10143411/87692060-fef7e400-c793-11ea-932a-ead3ca475870.png)

При этом в портфеле появился актив - то есть сделка выполнилась. Дальше согласно нормальному поведению робот делает повторную попытку создания маркет заявки - и актив удваивается в портфеле. 

От этой проблемы никуда не деться, если проблема внутри брокера, так что предлагаю решать у себя.

Ну например добавить в стриминг открытие и закрытие сделок, возможность подписаться на них. Или же добавить куда-то ид последней заявки при добавлении в портфель, в тот же `ProftolioPosition` или еще как-то

**Comment by Fatal1ty** [comment]
> Дальше согласно нормальному поведению робот делает повторную попытку создания маркет заявки - и актив удваивается в портфеле.

Я у себя на каждой итерации проверки состояния заявок (и операций) первым делом смотрю, какие заявки по бумаге есть, и отменяю те, которые по моим данным не должны быть. Если цена в заявке ощутимо отличается от рыночной, которая была в предыдущую итерацию, то шанс, что такая заявка выполнится до того, как я ее успею отменить, мизерный.

Рекомендую так делать. К тому же Тинькофф обещал раздельные счета сделать, поэтому на выделенном для бота счете лишние заявки будут только те, что созданы вот в таких вот ситуациях.

**Comment by Fatal1ty** [comment]
Пардон, не заметил, что у вас бот рыночные заявки делает, а не лимитные. Тогда да, это еще одна проблема в копилку проблем с рыночными заявками. После нескольких словленных проскальзываний, я переписал всю логику на лимитные.

**Comment by BusinessDuck** [comment]
Я наоборот ушёл от лимитных к маркет заявкам. Тк на них проблем мне показалось ещё больше. Маркет заявка проскальзывает, но свою задачу решает. С лисиными у меня были проблемы, что цена могла уйти и заявка не закрылась, зависла и заборчика весь алгоритм, в такой момент заявка двигалась с определённой частотой под рынок, но все равно вызывала так или иначе проскальзывание. Далее заявки такие нужно прослеживать чтобы переносились корректно между днями торговыми и выходными. Но больше всего зависания таких заявок конечно останавливают от перехода обратно к лимитным

**Comment by BusinessDuck** [comment]
@NikitaMelnikov ну так не делается, это функционал ключевой. Ошибки будут ещё и не один раз, и были они уже раз 10, дайте нормальную возможность проверять открытие сделок, сейчас только косвенно можно узнать по портфелю сравнив количество и тикер.

**Comment by mlshvdv** [comment]
Плюсуюсь. Проблему по-хорошему нужно разрешить.

**Comment by NikitaMelnikov** [comment]
Проблема решается на стороне нашего брокера
