### ISSUE TITLE
Scopes for tinkoff API tokens

### ISSUE THREAD

**Issue by nrukavkov** [TinkoffCreditSystems/invest-openapi#295]
`github: Scopes let you specify exactly what type of access you need. Scopes limit access for OAuth tokens. They do not grant any additional permission beyond that which the user already has.`

Сделайте скоупы, чтобы можно было читать портфель. Но при этом нельзя было совершать сделки. Это позволит передавать ключ на чтение 3-м лицам или программам с реальным портфелем для анализа, какой то аналитики без возможности совершать сделки.

**Comment by Fatal1ty** [comment]
Было уже https://github.com/TinkoffCreditSystems/invest-openapi/issues/12

**Comment by nrukavkov** [comment]
Закрываю тогда как дубликат
