### ISSUE TITLE
Время обновления данных по закрытым свечам

### ISSUE THREAD

**Issue by felixrap** [TinkoffCreditSystems/invest-openapi#296]
Добрый день.
Делаю запрос на получение последней свечи:
 - время отправки запроса **2020-07-22 17:22:02**
 - получаю минутную свечку с датой **2020-07-22 14:21:00**
Т.е разница в минуту, ОК. Повторяю запрос через минуту:
 - время отправки запроса **2020-07-22 17:23:02**
 - получаю минутную свечку с _той же самой датой, как и предыдущая_ **2020-07-22T14:21:00**
Делаю следующий запрос через минуту
 - время отправки запроса  **2020-07-22 17:24:02**
 - получаю минутную свечку с датой **2020-07-22T14:23:00** ( тут всё ок)

В программе сделал намеренно задержку в 2 секунды, чтобы не отсылать запрос ровно в 17:01:00, 17:02:00..., потому что в таком случае всегда получаю свечу с запозданием в 2 минуты. 
С программной задержкой в 2 секунды он работает 50/50 - иногда получаешь актуальную информацию, иногда - нет.

Что нужно сделать, чтобы получить актуальную последнюю закрытую свечу без программной задержки в 2+ секунды?

**Comment by mlshvdv** [comment]
Присоединяюсь к вопросу, тоже актуален.

**Comment by koshik34** [comment]
В sdk js есть метод candle.
Метод для подписки на данные по свечному графику инструмента.
Я отслеживаю параметр time, если он изменился значит образовалась новая свеча.

**Comment by NikitaMelnikov** [comment]
Для получение актуальных последних свечей лучше использовать стриминг протокол, если попасть в ~xx:xx:00 в REST метод, то можно получить неактуальную свечу
