### ISSUE TITLE
Ошибка при получении валютных активов в портфеле

### ISSUE THREAD

**Issue by mlshvdv** [TinkoffCreditSystems/invest-openapi#297]
Начиная с 2020-07-23 20:22:31.588Z в **боевом** окружении в течении 10 минут (потом просто остановил сервис) валилась следующая ошибка при попытке получить валютные активы портфеля через js sdk:

```
{
	trackingId: '01e5fd75a37db026',
	payload: {
		message: 'Cannot find user',
		code: 'GATEWAY_REQUEST_DATA_ERROR'
	},
	status: 'Error'
}
```

Спустя час ситуация нормализовалась.

Полагаю, что это нестандартная ситуация, учитывая, что где-то на беке потерялся пользователь? Каковы причины такого поведения? Насколько это может быть частым явлением?

**Comment by NikitaMelnikov** [comment]
Добрый день, вчера наблюдались проблемы в системе авторизации, ситуация была исправлена
