### ISSUE TITLE
Возможность получить все операции по аккаунту

### ISSUE THREAD

**Issue by gregzhadko** [TinkoffCreditSystems/invest-openapi#299]
На данный момент через API невозможно (либо я не нашел) возможности получить информации по всем операциями. Аналог на в пользовательском интерфейсе: вкладка события.

**Comment by betslus1** [comment]
Если не передавать figi, то покажет по всему аккаунту.
Другой вопрос, что часто не работает. (например сейчас)

**Comment by lightning95** [comment]
Если у клиента достаточное число операций, то будет эффективнее делать запрос с более коротким интервалом времени и/или фильтровать по инструменту.
