### ISSUE TITLE
Цена исполненного лимитного приказа отличается от исходной

### ISSUE THREAD

**Issue by mlshvdv** [TinkoffCreditSystems/invest-openapi#300]
Это довольно частый случай в **боевом** окружении.

Пример:
Исходная цена приказа: 216.95
Приказ исполнен по: 217.05

2020-07-28T10:19:53.245+03:00 Отправляю приказ через официальный js-sdk в метод создания **лимитного приказа** в следующем виде по цене 216.95:
```
{
	figi: 'BBG004730N88',
	lots: 1,
	operation: 'Sell',
	price: 216.95
}
```

2020-07-28T10:19:53.462+03:00 В ответ возвращается объект приказа:
```
{
	orderId: '20836586593',
	operation: 'Sell',
	status: 'New',
	requestedLots: 1,
	executedLots: 0,
	commission: {
		currency: 'RUB',
		value: 0
	}
}
```

В итоге в операциях отражено, что приказ был выполнен по другой цене (217.05):
```
{
	"operationType": "Sell",
	"date": "2020-07-28T10:19:53.394305+03:00",
	"isMarginCall": false,
	"instrumentType": "Stock",
	"figi": "BBG004730N88",
	"quantity": 10,
	"price": 217.05,
	"payment": 2170.5,
	"currency": "RUB",
	"commission": {
		"currency": "RUB",
		"value": -1.09
	},
	"trades": [{
		"tradeId": "3246507106",
		"date": "2020-07-28T10:19:53.394305+03:00",
		"quantity": 10,
		"price": 217.05
	}],
	"status": "Done",
	"id": "20836586593"
}
```

В чем может быть причина такого поведения?

**Comment by mlshvdv** [comment]
Еще один пример:

2020-07-28T12:11:32.015+03:00 отправляю приказ:
```
{
	figi: 'BBG004730N88',
	lots: 1,
	operation: 'Buy',
	price: 216.69
}
```

Получаю в ответ:
```
{
	orderId: '20839219936',
	operation: 'Buy',
	status: 'New',
	requestedLots: 1,
	executedLots: 0,
	commission: {
		currency: 'RUB',
		value: 0
	}
}
```

2020-07-28T12:11:32.492Z+03:00 Запрашиваю список активных приказов и этот приказ выглядит так:
```
{
	orderId: '20839219936',
	figi: 'BBG004730N88',
	operation: 'Buy',
	status: 'New',
	requestedLots: 1,
	executedLots: 0,
	price: 216.69,
	type: 'Limit'
}
```

Пока всё хорошо, цена отправленного приказа равняется цене созданного.

После исполнения приказа в операциях вижу, что цена отличается на 2 копейки (216.67 вместо 216.69):
```
{
	"operationType": "Buy",
	"date": "2020-07-28T12:11:32.21233+03:00",
	"isMarginCall": false,
	"instrumentType": "Stock",
	"figi": "BBG004730N88",
	"quantity": 10,
	"price": 216.67,
	"payment": -2166.7,
	"currency": "RUB",
	"commission": {
		"currency": "RUB",
		"value": -1.08
	},
	"trades": [{
		"tradeId": "3246881337",
		"date": "2020-07-28T12:11:32.21233+03:00",
		"quantity": 10,
		"price": 216.67
	}],
	"status": "Done",
	"id": "20839219936"
}
```

Ну как так?)

**Comment by kitMP** [comment]
Со вторым случаем, понятно цена продажи ниже вашей заявки, а с первым что не так?
Продали бумагу по цене большей чем вы просили, нормальное явление когда цена убегает выше вашей заявки, и она исполняется по лучшей для вас текущей цене. Или в портфеле у вас прибавилось не на 2170.5-1.09?

**Comment by mlshvdv** [comment]
Разве лимитный приказ не должен исполняться по указанной цене?

**Comment by mlshvdv** [comment]
Так, посмотрел, в первой случае цена получается так же выгоднее выставленной. Вопрос закрыт. Всё ок)

**Comment by kitMP** [comment]
Если случилось проскальзывание, то заявка исполнится по текущей цене. У меня всегда так было и в терминале и в мобильном клиенте. Один раз я случайно ошибся в цифре лимитной заявки где-то на +сотню рублей в покупке, заявка мгновенно исполнилась по текущей рыночной.
