### ISSUE TITLE
Доработать метод MarketCandlesAsync.

### ISSUE THREAD

**Issue by kitMP** [TinkoffCreditSystems/invest-openapi#301]
Сейчас в методе, если from = to, выдаётся ошибка Error 500:
{
  "trackingId": "cc5c406ae2f84106",
  "payload": {
    "message": "[to]: Bad candle interval: from=2020-07-24T00:00:00Z to=2020-07-24T00:00:00Z expected from 1 day to 1 year",
    "code": "VALIDATION_ERROR"
  },
  "status": "Error"
}
Причём в ошибке дата сдвинута относительно запроса на один день. 
Хотелось бы в таком случае для дневных свечей просто получать одну свечу в указанную дату.

**Comment by NikitaMelnikov** [comment]
Добрый день, вы наверно имеете ввиду csharp-sdk?

**Comment by kitMP** [comment]
Добрый день, да.

**Comment by NikitaMelnikov** [comment]
По вопросам SDK лучше создать тикет в соответствующем репозитории, коллеги посмотрят

**Comment by kitMP** [comment]
> По вопросам SDK лучше создать тикет в соответствующем репозитории, коллеги посмотрят

На самом деле, ошибка есть и в swagger-е, ну ок, открою ещё и там...
