### ISSUE TITLE
Расшифровка полей в событии tradestat

### ISSUE THREAD

**Issue by gregory-calco** [TinkoffCreditSystems/invest-openapi#303]
Где можно посмотреть расшифровку полей для события tradestat в websocket'е ?
Планируется ли его включение в оф. документацию?
```
{
	"s":"SBER_TQBR",
	"nt":11943,
	"v":997575,
	"to":2162521208,
	"vl":1,
	"lp":217.07,
	"ba":951,
	"aa":624,
	"bq":674864,
	"aq":546979
}
```

**Comment by NikitaMelnikov** [comment]
https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/#candlesubscribe
