### ISSUE TITLE
Instrument is disabled for trading

### ISSUE THREAD

**Issue by felixrap** [TinkoffCreditSystems/invest-openapi#305]
Получаю ошибку **Instrument is disabled for trading** при операциях c TCS Group, хотя бумага приходит в списке торгуемых инструментов. Через сайт проблем нет. В чем может быть дело?
isin='TCS7238U2033'
tracking_id='ffabb2b26b5297c2'

**Comment by NikitaMelnikov** [comment]
По техническим причинам торговля TCSG через OpenApi отключена, надеемся в будущем дать возможность торговать и через OpenApi
