### ISSUE TITLE
Проблема с выставлением заявок на покупку на некоторые позиции американского рынка:

### ISSUE THREAD

**Issue by denislukinykh** [TinkoffCreditSystems/invest-openapi#306]
Добрый день. 
Проблема с выставлением заявок на покупку на некоторые позиции американского рынка:

NYSE:DAL
`curl -s -X POST "https://api-invest.tinkoff.ru/openapi/orders/limit-order?brokerAccountId=XXX&figi=BBG000R7Z112" -H "accept: application/json" -H "Authorization: Bearer t" -H "Content-Type: application/json" -d "{\"lots\":5,\"operation\":\"Buy\",\"price\":25,5}" | jq
`

NASDAQ:JKHY
`curl -s -X POST "https://api-invest.tinkoff.ru/openapi/orders/limit-order?brokerAccountId=XXX&figi=BBG000BMH2Q7" -H "accept: application/json" -H "Authorization: Bearer t" -H "Content-Type: application/json" -d "{\"lots\":1,\"operation\":\"Buy\",\"price\":176,5}" | jq
`

NASDAQ:PODD
`curl -s -X POST "https://api-invest.tinkoff.ru/openapi/orders/limit-order?brokerAccountId=XXX&figi=BBG000R7XX87" -H "accept: application/json" -H "Authorization: Bearer t" -H "Content-Type: application/json" -d "{\"lots\":1,\"operation\":\"Buy\",\"price\":118,5}" | jq
`

При этом проблем с заявками на, например, NYSE:BRO и NASDAQ:CHDN нет.
Что порекомендуете?

**Comment by mlshvdv** [comment]
@denislukinykh может проблема в том, что у вас невалидный json, так как `price` у вас идет со знаком `,`, вместо `.`:
`"price":25,5` вместо `"price":25.5`

**Comment by denislukinykh** [comment]
Благодарю, ошибка именно в этом.
