### ISSUE TITLE
Дробление акций

### ISSUE THREAD

**Issue by mlshvdv** [TinkoffCreditSystems/invest-openapi#308]
В конце августа акции Apple будут раздроблены 4 к 1.
Вопрос: будет ли эта операция как-либо отражена в операциях? Если да, то какой тип у такой операции?
Можно привести пример объекта такой операции как он бы выглядел в API?

**Comment by NikitaMelnikov** [comment]
Дополнительной записи в операция не появится, но все операции в истории изменятся, то есть уже у созданных операций будут новые значения

**Comment by mlshvdv** [comment]
@NikitaMelnikov а как именно изменятся? Как-то так?
Было:
```
"quantity": 1,
"quantityExecuted": 1,
"price": 217.66,
"payment": -2176.6,
```

Станет:
```
"quantity": 4,
"quantityExecuted": 4,
"price": 217.66,
"payment": -2176.6, // общий размер платежа не изменится при этом?
```

**Comment by NikitaMelnikov** [comment]
Да, примерно так

**Comment by mlshvdv** [comment]
@NikitaMelnikov благодарю
