### ISSUE TITLE
Проблемы со временем

### ISSUE THREAD

**Issue by ZergsLaw** [TinkoffCreditSystems/invest-openapi#31]
Неуверен, что все верно понимаю

Но в верном ли формате возвращается время?

При запросе /market/candles мне возвращается время в таком виде

`"2019-10-29T07:00Z"`

**Comment by NikitaMelnikov** [comment]
Добрый день,

Уже есть открытый тикет, починим, проблема на нашей стороне

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
