### ISSUE TITLE
Перестают приходить данные по websocket при подписке на instrument_info о более чем 114-ти инструментах

### ISSUE THREAD

**Issue by t3chn0pr13st** [TinkoffCreditSystems/invest-openapi#310]
Подписываюсь на instrument_info, хочу получить статус сразу по всем, но после 114-го инструмента входящие данные перестают поступать.
При этом аналогично подписан на обновления свечей (candle:subscribe) для всех 1396-ти инструментов (только акции), всё приходит нормально. Но если подписаться на обновления instrument_info, после 114-го любые данные перестают приходить, и по свечам тоже. Пробовал и вместе с другими данными (в рамках одного websocket-соединения) подписываться, и отдельно только на обновления инфы об инструментах - поступает информация о первых 114-ти инструментах, и всё. Больше в рамках этого соединения данных никаких не приходит, приходится переподключаться.

**Comment by NikitaMelnikov** [comment]
Напишите, пожалуйста, в поддержку, нам нужны будут дополнительные данные для разбора ситуации
