### ISSUE TITLE
portfolio сегодня

### ISSUE THREAD

**Issue by dulimov** [TinkoffCreditSystems/invest-openapi#312]
Hi

Как я понимаю высчитывать текущий профит "сегодня" нужно своими силами api не передает ?

пытались высчитать профит "все" как в приложении даже этого не удалось, может подскажите формулу ?

**Comment by koshik34** [comment]
Я вижу 2 варианта.
1. Собирать данные по сделкам и считать профит там (исключая открытые сделки).
`/operations`
```
- много запросов если хочешь иметь актуальные данные, особенно если за весь период.
+ точные данные указывается комиссия по операции
```
2. Отслеживать свой портфель постоянно, в случае уменьшения количества акций считать разницу между ценой продажи и средней умноженной на количество
`/portfolio`
```
+ не упираемся в лимиты по запросам
+ данные приходят почти сразу после продажи
- нет возможности получить комиссию
```

**Comment by dulimov** [comment]
спасибо, будем пробовать
