### ISSUE TITLE
Медленная работа + много internal error

### ISSUE THREAD

**Issue by betslus1** [TinkoffCreditSystems/invest-openapi#315]
Добрый день, сегодня наблюдается 
Медленное снятие (навскидку по 4-5 секунд), добавление заявок. (навскидку по 4-5 секунд)
Много Internal Error может 50/50
Начинать дебажить чтобы предоставить больше информации, или в курсе проблемы?

Это ошибка говорит что пришел не JSON а html 50x обычно или пустой запрос.
`(node:19403) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://api-invest.tinkoff.ru/openapi/orders reason: Unexpected end of JSON input
`

Или вот например, отобразился id.
```
Не удалось совершить Buy по 1130.25 4 шт
{ trackingId: '7d5ac4a67d087df5',
  payload: { message: 'INTERNAL_ERROR', code: 'INTERNAL_ERROR' },
  status: 'Error' }
trackingId        payload          status
----------------  ---------------  ------
7d5ac4a67d087df5  [object Object]  Error 

```

Обычно к orders в пике могло до 80 RPM доходить, сегодня и 15 не дает сделать.

**Comment by NikitaMelnikov** [comment]
Добрый день, видим, решаем

**Comment by betslus1** [comment]
Хорошо, спасибо, напишите пожалуйста о завершении работ.

**Comment by IvanAgafonov** [comment]
Тоже самое, отпишитесь как будет исправлено! Еще крайне неприятный баг случался при выставлении заявок через REST API: сервер возвращал 500 Internal Errror, но при этом заявка выставлялась. И т.к. не возможно было получить id выставленной заявки, то случалось двойное выставление (а это уже возможные материальные потери. Понимаю, что в договоре хитро написано, что вы не несете никакую ответственность за мои потери при ваших технических неполадках, но все же).

**Comment by NikitaMelnikov** [comment]
Работа восстановлена

**Comment by NikitaMelnikov** [comment]
@IvanAgafonov эта ситуация затронула в 70% клиентов openapi из-за дублирующих запросов на выставление/отмену уже исполненных сделок
Список активных заявок вы можете запросить через `/orders/`, так же если сделка уже прошла, то она изменится состояние портфеля, рекомендую поставить проверку в случае падения запроса "на всякий случай"

**Comment by mlshvdv** [comment]
@NikitaMelnikov а нельзя дать возможность получить статус заявки в любом её состоянии (новая, в процессе, исполненная, отмененная)? Получается, что чтобы удостовериться в статусе заявки нужно дергать список активных заявок, список активов в портфеле и список операций, как-то это между собой согласовывать и определять статус выполнения.

**Comment by NikitaMelnikov** [comment]
@mlshvdv задача такая есть, мы сделаем

**Comment by EJohnF** [comment]
Такая же ошибка была сегодня утром:
```
"name":"FetchError","message":"invalid json response body at https://api-invest.tinkoff.ru/openapi//orders/limit-order?figi=BBG00MJDR6J9 reason: Unexpected end of JSON input","type":"invalid-json"
```
И тоже привело к двойному выставлению заявок (благо была на продажу, и вторая не прошла так как не хватало активов для второй сделки)

**Comment by IvanAgafonov** [comment]
@EJohnF Да, там пустой body в ответе на 500 ошибку, поэтому у вас ошибка с json. По-хорошему сервер должен отправлять json в любом случае. Может позже исправят

**Comment by NikitaMelnikov** [comment]
@EJohnF дополнительно у себя в библиотеке было бы здорового логировать тело ответа, сейчас трудно сказать что именно произошло
