### ISSUE TITLE
Instrument not found

### ISSUE THREAD

**Issue by BaryshevS** [TinkoffCreditSystems/invest-openapi#316]
Получаем список инструментов, в т.ч. новые "* AG"
А при запросе свечей ругается, что фиги не найден.
/market/candles

{"trackingId":"33f354b007210655","payload":{"message":"[figi]: Instrument not found by figi=BBG000BW93R1","code":"VALIDATION_ERROR"},"status":"Error"}

"UVV", "BBG000BW93R1"
"TGLD",  "BBG222222222"
"CRTX", "BBG00BTK1DT8"
"RCII",  "BBG000BHQJX3"

**Comment by NikitaMelnikov** [comment]
Таких инструментов в OpenApi нет
Проверить доступность инструмента можно через https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_search_by_figi
