### ISSUE TITLE
api.operations

### ISSUE THREAD

**Issue by koshik34** [TinkoffCreditSystems/invest-openapi#317]
Для примера берем историю продажи акции
```
{
  operationType: 'Sell',
  date: '2020-08-06T16:40:23.733117+03:00',
  isMarginCall: false,
  instrumentType: 'Stock',
  figi: 'BBG000F2XXP2',
  quantity: 1,
  quantityExecuted: 1,
  price: 20.06,
  payment: 20.06,
  currency: 'USD',
  commission: { currency: 'USD', value: -0.01 },
  trades: [
    {
      tradeId: '1227480770',
      date: '2020-08-06T16:42:42.986455+03:00',
      quantity: 1,
      price: 20.06
    }
  ],
  status: 'Done',
  id: '150565136440'
}
```
Мы видим что акция была продана по 20.06 в количестве 1 штука + комисия 0.01.
Было бы здорово если бы здесь хранилось средняя цена покупки  что бы была возможность посчитать профит.
А сейчас нужно искать покупки этой акции, а они могут быть не в диапазоне запрос, а это доп запросы...

**Comment by NikitaMelnikov** [comment]
Поддерживаю @mlshvdv, надо делать подобную статистику на своей стороне
