### ISSUE TITLE
Отсутствуют сведения о внебиржевых операциях и позициях

### ISSUE THREAD

**Issue by vrubanov** [TinkoffCreditSystems/invest-openapi#318]
Впервые купил акции на внебиржевом рынке для квалифицированных инвесторов. Через OpenAPI о них не возвращается никакой информации - ни в списке операций, ни в списке позиций портфеля...

**Comment by vrubanov** [comment]
И как узнать FIGI внебиржевой бумаги (Deutsche Telekom AG)? Чтобы хоть последнюю котировку через свечи суметь достать...

**Comment by NikitaMelnikov** [comment]
Внебирживых позиций в OpenApi нет, пока не планируем добавлять
