### ISSUE TITLE
RequestValidation: Цена не попадает в допустимый интервал

### ISSUE THREAD

**Issue by oldnavy1989** [TinkoffCreditSystems/invest-openapi#319]
При попытке создать следующую лимитную заявку:

figi: BBG000QCW561
lots: 1
operationType: buy
price: 0.5

Получаю 500 с ошибкой:
RequestValidation: Цена не попадает в допустимый интервал от 0.79 до 2.37 (ce7dd1adc59fb47a).

1) Как заранее узнать допустимый интервал по figi?
2) Почему 500, а не 400?

**Comment by NikitaMelnikov** [comment]
1. Для MOEX есть limit_up, limit_down https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/#instrument_infosubscribe
2. Баг со статус-кодом, поправим
