### ISSUE TITLE
Support multi figi

### ISSUE THREAD

**Issue by alextaaa** [TinkoffCreditSystems/invest-openapi#320]
Pls add support multi figi for orderbookGet method

```
api.orderbookGet({ figi: 'BBG000HLJ7M4,BBG002293PJ4,BBG000BPL8G3', depth: 10 })
```

**Comment by ZigGreen** [comment]
@NikitaMelnikov is it possible to support multiple figi with `/market/orderbook` method?

**Comment by NikitaMelnikov** [comment]
Поддержку нескольких фиги не планируем
