### ISSUE TITLE
Не выставляется рыночный ордер

### ISSUE THREAD

**Issue by erdnikuleshov** [TinkoffCreditSystems/invest-openapi#321]
Добрый вечер!
Пытаюсь купить или продать 1 доллар, но не выставляется рыночный ордер ни на продажу, на на покупку, хотя в портфеле обе валюты есть

`usdFigi = 'BBG0013HGFT4'`
`client = openapi.api_client(token)`
`body = {
        'lots': 1,
        'operation': 'Buy'
}`
`order = client.orders.orders_market_order_post(figi=usdFigi, market_order_request=body)`

В ответ прилетает:
`HTTP response body: {"trackingId":"2c83a0034b9ed1de","payload":{"message":"Недостаточно активов для сделки","code":"OrderNotAvailable"},"status":"Error"}`
Для Sell то же самое

При этом, как уже сказал, в портфеле имеются и доллар, и рубли
![image](https://user-images.githubusercontent.com/69470387/89797381-8afef080-db33-11ea-8b46-f8962d5a04e2.png)

**Comment by lightning95** [comment]
```
{
        "figi": "BBG0013HGFT4",
        "ticker": "USD000UTSTOM",
        "minPriceIncrement": 0.0025,
        "lot": 1000,
        "currency": "RUB",
        "name": "Доллар США",
        "type": "Currency"
      },
```
В OpenApi можно торговать долларом только с лотностью 1000
