### ISSUE TITLE
operations не возвращает операции с погашенной облигацией

### ISSUE THREAD

**Issue by xantnef** [TinkoffCreditSystems/invest-openapi#324]
здравствуйте,

заметил, что в ответе /operations не хватает некоторых операций, точнее всех операций с облигациями RU000A0JUQF8.
Тот выпуск уже погашен, и сделан новый, возможно дело в этом?
При этом в официальном мобильном клиенте операции в событиях присутствуют.

**Comment by NikitaMelnikov** [comment]
RU000A0JUQF8 недоступен в опенапи, проверить можно тут
https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_search_by_ticker
