### ISSUE TITLE
Блокировка активов после лимитной заявки с Internal error

### ISSUE THREAD

**Issue by ve108** [TinkoffCreditSystems/invest-openapi#325]
Не первый раз замечаю
1. Отправляю лимитную заявку на продажу
2. Результат
    {'trackingId': 'a76bcdf184d62c7c', 'payload': {'message': 'Internal error', 'code': 'INTERNAL_ERROR'}, 'status': 'Error'}
3. После этого актив блокируется (вместе с комиссией), как будто заявка выставлена. В приложении тоже замочек стоит, но, очевидно, без заявки в стакане.
4. Повторно та жа самая лимитная заявка через 5 минут
{'trackingId': '94212285fe87680a', 'payload': {'message': 'Недостаточно активов для сделки', 'code': 'OrderNotAvailable'}, 'status': 'Error'}
Обычно блокировка от одной минуты до пары часов
Но сегодня уже больше 15 часов

**Comment by EJohnF** [comment]
Тоже замечал такую ошибку

**Comment by NikitaMelnikov** [comment]
Добрый день, по этому вопросу напишите, пожалуйста, в поддержку
