### ISSUE TITLE
непонятные цены в стакане для российских бумаг в 18-40

### ISSUE THREAD

**Issue by mkaynov** [TinkoffCreditSystems/invest-openapi#326]
через стрим начиная с 18-40 по российским бумагам приходит ордербук с bid больше чем ask. market order-а при этом работают но заявки конечно проходят по совершенно другим ценам.
вот как выглядит стрим ордербука глубины 1 для SBER:

```
ts, bid, ask
1597246799044,240.7,240.71
1597246802707,240.73,237.48   <---- 18-40
1597246803514,249.1,237.48
1597246803559,249.1,237.48
1597246803885,249.1,237.48
1597246804170,249.1,237.48
1597246804497,249.1,237.48
1597246804902,249.1,237.48
1597246807274,249.1,237.48
```

в поддержке сказали что это некий аукцион и стакан может выглядеть странно... но как с этим жить понятнее не стало. можно как-то не стримить неактуальные цены?

**Comment by NikitaMelnikov** [comment]
Добрый день,

@mkaynov приведите полный ответ поддержки, пожалуйста, чтобы предметно говорить

**Comment by mkaynov** [comment]
Добрый день @NikitaMelnikov. Предмет вопроса в том почему в 18-40 bid больше чем ask в стакане (по крайней мере такие данные приходят через stream api). Что это может значить? Пример данных из стрима привел выше. Там bid резко возрастает, ask снижается; bid становится больше чем  ask, что не возможно. 

Ответ поддержки:

> Основная торговая сессия на Московской бирже заканчивается в 18:40.
> 
> С 18:40 до 18:50 проходит аукцион закрытия.
> 
> В нём как правило участвовать нельзя, однако, из-за технических особенностей, через терминал или апи некоторые сделки могут пройти.
> 
> Во время этого аукциона, стакан цен может выглядеть странно.

**Comment by NikitaMelnikov** [comment]
@mkaynov все верно, вот тут подробней описано https://www.moex.com/s1709
