### ISSUE TITLE
Хотелось бы найти апи для ПУЛЬСА. 

### ISSUE THREAD

**Issue by nikitozeg** [TinkoffCreditSystems/invest-openapi#327]
пытался засниффить мобильный траффик через прокси с сертификатом, но приложение палит этот сертификат и отказывается отправлять запросы. 

подскажите пожалуйста.. остается только реверс-инжинирнуть apk файл

**Comment by dulimov** [comment]
подписаться на всех пульсян, и выяснить что за опг пампит мосбиржу 😂😂😂

**Comment by NikitaMelnikov** [comment]
Добрый день,

1. Пульс не планируем открывать в ОпенАпи
2. Если вы используете не публичное апи, то мы не гарантируем обратную совместимость, поддержку, ограничения по запросам
