### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by ZergsLaw** [TinkoffCreditSystems/invest-openapi#33]
URL = https://api-invest.tinkoff.ru/openapi/sandbox/market/portfolio

Возврат 500 ошибка

В ответе нет тела, так что подробностей не скажу

**Comment by NikitaMelnikov** [comment]
`https://api-invest.tinkoff.ru/openapi/sandbox/market/portfolio`

Такого метода у нас нет, возможно `market` лишний

**Comment by ZergsLaw** [comment]
Понял, билдер URL сломался, благодарю
