### ISSUE TITLE
Не отображаются операции старше 3 недель.

### ISSUE THREAD

**Issue by betslus1** [TinkoffCreditSystems/invest-openapi#333]
Добрый день, решил выгрузить себе в БД все свои операции за год,
чтобы не мучить сервера брокера, и вести аналитику у себя, так как ни один из инструментов брокера уже не тащит.
Выгружаю интервалами по одному дню (чтобы снизить нагрузку), дальше 21 дня не дает выгрузить.

примерный код:

```
  var from = new Date('2020-08-03 00:00:00');
  var to   =new Date('2020-08-03 23:59:59');

  var operationNow = await api.operations({
      'from' : ISODateString(from),
      'to'   : ISODateString(to),
  });
```

Возвращает пустой массив.
t.3_w7XDJExt1r

**Comment by betslus1** [comment]
Вроде бы сегодня все хорошо.

**Comment by NikitaMelnikov** [comment]
@betslus1 очень странная ситуация
То есть 2 дня назад операций не было, но сейчас они есть?

**Comment by betslus1** [comment]
Да, 2 дня назад я запускал скрипт, он выгрузил данные за 21 день (1 день за 1 запрос), а за старшие дни писал, что нет операций (хотя они есть). В тот же день и налоговый отчет с сайта я выгрузить не мог, обычно с 10 раза он генерируется. 

Вчера запустил тот же скрипт, выгрузило все (я надеюсь) с 2017 года. И налоговый отчет с 10 раза через сайт сделался.
В выходные буду проверять насколько там корректные данные в плане FIFO, так как у меня сайт не сходился с брокерским отчетом.

**Comment by NikitaMelnikov** [comment]
Добавьте пожалуйста логирование trackingId у себя в скрипте, чтобы далее детальней можно было понять что происходило
Пока закрываю тикет
