### ISSUE TITLE
Признак выплаты дивидендов.

### ISSUE THREAD

**Issue by kitMP** [TinkoffCreditSystems/invest-openapi#335]
Не знаю, было ли, но просьба добавить в дневные свечи признак выплаты дивидендов. Либо значение выплаты, например, 2$ на акцию.
0 - значит дивидендов не было. 
В мобильном приложении и в терминале эти данные есть.

**Comment by NikitaMelnikov** [comment]
В OpenApi не планируем реализовывать, думаю что дивиденды должны быть отдельно
