### ISSUE TITLE
В списке операций отсутствуют сделки и дивиденды по внебиржевым бумагам

### ISSUE THREAD

**Issue by KolyBelostotsky** [TinkoffCreditSystems/invest-openapi#336]
Если получить все операции типов Buy, ByCard, Sell со статусом Done, в полученном списке не будет сделок по внебиржевым бумагам.
Если получить все операции типа Dividend, то информации о дивидендах тоже не будет. Это сильно затрудняет ведение учёта прибыльности сделок и денежного потока.

**Comment by NikitaMelnikov** [comment]
@KolyBelostotsky внебирживые инструменты недоступны в OpenApi
Поддержка отображения в портфеле появится в задаче https://github.com/TinkoffCreditSystems/invest-openapi/issues/331, операции так же добавим
