### ISSUE TITLE
В списке операций нет сделок по тикеру HIIQ

### ISSUE THREAD

**Issue by KolyBelostotsky** [TinkoffCreditSystems/invest-openapi#337]
В 2019-начале 2020 года у меня было несколько сделок с бумагой HIIQ. Впоследствии этот тикер был переименован в BFYT, после чего у меня было несколько сделок уже с новым тикером.
Если получить список операций по тикеру HIIQ, то ничего не вернётся.
Если получить список операций по тикеру BFYT, то самая ранняя сделка будет датирована 24.04.2020, то есть, информации по сделкам с HIIQ в новом тикере также нет.

**Comment by NikitaMelnikov** [comment]
@KolyBelostotsky подскажите, операции в мобильном приложении отображаются?

**Comment by KolyBelostotsky** [comment]
> @KolyBelostotsky подскажите, операции в мобильном приложении отображаются?

Нет, в мобильном приложении не отображаются. В брокерских отчётах есть.

**Comment by NikitaMelnikov** [comment]
Обратитесь, пожалуйста, в поддержку, коллеги помогут разобраться, проще будет если укажете, что данных нет в мобильном приложении
