### ISSUE TITLE
Отсутствует баланс по валютам отличным от RUB USD EUR

### ISSUE THREAD

**Issue by agaspher** [TinkoffCreditSystems/invest-openapi#338]
Почему метод https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/portfolio/get_portfolio_currencies возвращает данные только по RUB USD EUR, а по CHF (для примера) нет, хотя:

`{'currency': 'EUR', 'balance': 0}`

 и логичнее было бы его не возвращать?

**Comment by nonamegithub** [comment]
Похоже, что взаимосвязано с  https://github.com/TinkoffCreditSystems/invest-openapi/issues/176
