### ISSUE TITLE
Новости по инструменту (набору инструментов)

### ISSUE THREAD

**Issue by tyomasun** [TinkoffCreditSystems/invest-openapi#340]
Возможно ли получить новостную ленту по инструменту? 
В идеале по набору инструментов (портфелю) и в режиме подписки.

**Comment by NikitaMelnikov** [comment]
Добрый день, такой возможности нет

**Comment by FedorSymkin** [comment]
А планируется в будущем? Для создания торговых роботов это было очень полезной фичей

**Comment by AlexanderVolkovTCS** [comment]
Пока выгрузка новостей не планируется
