### ISSUE TITLE
Странный ответ по ручке /orders

### ISSUE THREAD

**Issue by Fatal1ty** [TinkoffCreditSystems/invest-openapi#342]
Как нам и обещали, осенью начали работу над API 💪 Посыпались старые добрые дисконнекты и коннекшн эрроры, теперь API отдает ошибку при отмене уже отмененной заявки, что приятно. Но меня интересует, что случилось с ручкой **/orders** аккурат 1 сентября в 10:18:09, когда я получил вот такой payload:
```json
{
  "accounts": [
    {
      "benefits": {
        "currency": "'RUB'",
        "value": "0"
      },
      "brokerAccountId": "***",
      "brokerAccountType": "Tinkoff",
      "expectedYield": {
        "currency": "'RUB'",
        "value": "***"
      },
      "expectedYieldPerDay": {
        "currency": "'RUB'",
        "value": "***"
      },
      "expectedYieldPerDayRelative": ***,
      "expectedYieldRelative": ***,
      "totalAmount": {
        "currency": "'RUB'",
        "value": "***"
      }
    }
  ],
  "totals": {
    "benefits": {
      "currency": "RUB",
      "value": ***
    },
    "expectedYield": {
      "currency": "RUB",
      "value": ***
    },
    "expectedYieldPerDay": {
      "currency": "RUB",
      "value": ***
    },
    "expectedYieldPerDayRelative": ***,
    "expectedYieldRelative": ***,
    "totalAmount": {
      "currency": "RUB",
      "value": ***
    }
  }
}
```

Что это было? Неудачная миграция? Скоро появится возможность создавать отдельные брокерские счета? 👀

P.S. Такое было только один единственный раз, несмотря на то что я хожу в **/orders** каждые две секунды.

**Comment by Fatal1ty** [comment]
А еще, что примечательно, тут в accounts значение brokerAccountId было совсем не то, которое отдается по ручке **/user/accounts**. Да и totalAmount какой-то странный, если я правильно понимаю его назначение.

**Comment by NikitaMelnikov** [comment]
Подскажите, а вы используете http/2 или http/1.1?

**Comment by Fatal1ty** [comment]
> Подскажите, а вы используете http/2 или http/1.1?

http/1.1

**Comment by NikitaMelnikov** [comment]
> Скоро появится возможность создавать отдельные брокерские счета?

Я не могу говорить про наши планы :)

По самой ситуации кривого ответа завели внутренний тикет
