### ISSUE TITLE
Аномалия с тикерами TCS и TCSG

### ISSUE THREAD

**Issue by dlinnozmey** [TinkoffCreditSystems/invest-openapi#344]
По ответу от openapi/market/stocks имеются следующие данные:
- тикер TCS - figi BBG005DXJS36, валюта Usd
- тикер TCSG - figi BBG00QPYJ5H0, валюта Rub.

При запросе операций через openapi/operations происходит следующее:
- для figi BBG005DXJS36 возвращаются операции как в Usd, так и в Rub;
- для figi BBG00QPYJ5H0 никаких операций не возвращается.
Проще говоря, сделки по обоим тикерам (и долларовому TCS, и рублёвому TCSG) записываются в операциях, как сделки по тикеру TCS.

Абсолютно такое же поведение замечено в web-терминале и мобильном приложении. Тех.поддержка уже давно пишет, что о проблеме знает, но время идёт, а воз и ныне там. Может, через данный сервис получится разобраться. 
Или вообще, оно работает, как надо, просто я чего-то не понимаю?

**Comment by NikitaMelnikov** [comment]
Добрый день, из-за технических особенностей этих тикеров, сейчас история действительно некорректная
И мы работаем над тем, чтобы привести все к правильному виду. К сожалению, в этом тикете я ничего нового не сообщу, что сообщается поддержка, так как это поведение реализовано внутри брокера и не может быть исправлено на стороне OpenApi.
