### ISSUE TITLE
Пропадает история свечей предыдущего дня начиная с 3х ночи по МСК

### ISSUE THREAD

**Issue by Dazlonar** [TinkoffCreditSystems/invest-openapi#346]
Доброго времени суток!

Заметил очень интересный момент, который происходит каждую ночь, по крайней мере 3 из 3х проверок это повторилось. 
Начиная с 3х ночи по МСК (видимо это как раз новый день по UTC) пропадает история свечей предыдущего дня. Сложно сказать насколько долго она отсутствует, потому как к утру, она обычно уже нормально возвращается.

Но это еще не все - при подписке на стриминговое обновление свечей, возвращается 1 свеча с запрошенным интервалом и эта свеча за предыдущей день (хотя по rest этой истории нет), к тому же обычно, когда завершается торговый день свечи больше не отсылаются при подписке, но начиная с 3х ночи это почему-то начинает работать именно так). Проверял это на различных инструментах.

Теперь объясню почему это для меня проблема. При разрыве соединения, я всегда запрашиваю последнюю историю, что бы избежать ситуации, когда что-то обновилось пока был разрыв и на основе истории происходят и другие важные вычисления, если по какой-то причине сокет упадет после 3х ночи, бот попытается восстановить коннект и запросит последнюю историю и мне отдадут историю в которой будет отсутствовать предыдущей день, что повлечет за собой ошибки в вычислениях и возможные потери денежных средств.

Надеюсь что это проблема на вашей стороне и ее можно исправить)

**Comment by NikitaMelnikov** [comment]
Добрый день, 
Обратитесь, пожалуйста, в поддержку с ссылкой на этот тикет, коллеги передадут данные команде разработки.
Нам нужны будут дополнительные сведения по вашему счету, чтобы разобраться в ситуации.
