### ISSUE TITLE
operations возвращает 400 на корректные from и to

### ISSUE THREAD

**Issue by pikkvile** [TinkoffCreditSystems/invest-openapi#347]
Запрос:

```
curl -X GET 'https://api-invest.tinkoff.ru/openapi/operations?from=2020-07-09T13:33:27.769+03:00&to=2020-09-09T13:33:27.769+03:00' -H 'Authorization: Bearer token' -i -H 'Content-Type: application/json'
HTTP/2 400 
server: nginx
date: Wed, 09 Sep 2020 10:34:16 GMT
content-type: application/json
content-length: 173
cache-control: no-store, no-cache, must-revalidate
access-control-allow-methods: GET,HEAD,POST,DELETE,OPTIONS,PUT,PATCH
access-control-allow-headers: accept, content-type, authorization, access-control-allow-headers, x-requested-with
access-control-allow-origin: *

{"trackingId":"82a483c6f791fd58","payload":{"message":"Неверный формат поля 'from' в запросе","code":"MALFORMED_QUERY_PARAMETER"},"status":"Error"}
```

**Comment by pikkvile** [comment]
Почитал соседние issue и смог таки подобрать правильный формат. Тем не менее, тот, который указан в документации в swagger, не подходит.

**Comment by kitMP** [comment]
@pikkvile 
А какой формат у вас заработал? У вас по дневным свечам эта проблема?

**Comment by pikkvile** [comment]
@kitMP проблема при получении истории операций. Работает вот так: `from=2020-09-01T00:00:00Z&to=2020-10-01T00:00:00Z`

**Comment by AlexanderVolkovTCS** [comment]
Да, сваггер контракт уже был поправлен.

**Comment by ildargafarov** [comment]
На operations  не поправлен

**Comment by ildargafarov** [comment]
@AlexanderVolkovTCS Да https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/operations/get_operations. Примеры `2019-08-19T18:38:33+03:00` для полей from и to тоже не работают. Работают только с `Z`
