### ISSUE TITLE
Будет ли создан SDK для Go? 

### ISSUE THREAD

**Issue by ZergsLaw** [TinkoffCreditSystems/invest-openapi#35]
Если нет, я могу завтра прислать частично готовый вариант, который поэтапно буду развивать, но за текущую неделю смогу довести до ума и покрыть тестами.

**Comment by ZergsLaw** [comment]
Реализовано большая часть методов, если будут замечания и критика, буду только рад :) 

А так, вот SDK для Go https://github.com/ZergsLaw/investor-tinkoff

Пока что версия 0.1.0, поэтапо внесу оставшиеся методы для API и покрытие юнит тестами логику методов.

**Comment by NikitaMelnikov** [comment]
Привет! Отличная работа, спасибо!

Мы в процессе написания go-sdk, но пока что не готовы его показать публично)

Добавлю ссылку на ваш проект в README.md, вы не против?

**Comment by ZergsLaw** [comment]
Буду только рад :) 

Также могу предложить, дабы не разбивать поддержку будущую на две репы, обьединить усилия, я могу в течении недели покрыть оставшиеся методы и дописать тесты и в дальнейшем можно объединить идеи обеих проектов либо в вашей репе, либо в моей, как вам было бы удобно

**Comment by NikitaMelnikov** [comment]
Я сейчас обратив внимание, что у вас реализован только REST-протокол, предлагаю добавить streaming и тогда можно будет в README, что скажете?

**Comment by ZergsLaw** [comment]
Да, конечно 

Я поэтому и отписал, что там лишь часть реализована :)

**Comment by ZergsLaw** [comment]
P.S. Если есть ещё замечания, то по возможности сразу выпишите, я поэтапно сел заканчивать rest методы, как их закончу и покрою тестами + какой либо докой, (с докой пока тяжлее всего) и приступлю к stream методам

**Comment by NikitaMelnikov** [comment]
*ВНЕЗАПНО* сегодня закончили с GO-sdk https://github.com/TinkoffCreditSystems/invest-openapi-go-sdk

**Comment by NikitaMelnikov** [comment]
Предлагаю переключить свои силы на его развитие :)

**Comment by ZergsLaw** [comment]
Ну, я в любом случае закончу свою, так как не хотелось бы на пол пути бросать, когда почти все окончено

Но в этой ситуции, добавление моего варианта SDK в список не возможно, верно понимаю?)

**Comment by NikitaMelnikov** [comment]
В список неофициальных SDK вполне возможно :)

**Comment by ZergsLaw** [comment]
Окей, благодарю :)
