### ISSUE TITLE
Не работает получение списка операций [Error]

### ISSUE THREAD

**Issue by betslus1** [TinkoffCreditSystems/invest-openapi#352]
Добрый день, 
не могу выгрузить список операций за сутки.
Это критическая ошибка (так как иначе список сделок никак не посмотреть, отчеты и сайт не работают уже много месяцев и сказали, что исправляться не будут).

t.3_w7XDJExt

root@robot:~/tinkoff/tests# node operations.js 
(node:16524) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://api-invest.tinkoff.ru/openapi/operations?from=2020-09-17T21%3A00%3A00Z&to=2020-09-18T20%3A59%3A59Z reason: Unexpected end of JSON input
    at /home/bet/tinkoff/node_modules/node-fetch/lib/body.js:48:31
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16524) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:16524) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

HTTP/1.1 500 Internal Server Error
Server: nginx
Date: Fri, 18 Sep 2020 12:46:08 GMT
Content-Length: 0

**Comment by betslus1** [comment]
HTTP/1.1 502 Bad Gateway
Server: nginx
Date: Fri, 18 Sep 2020 12:51:32 GMT
Content-Type: text/html
Content-Length: 157
Cache-Control: no-store, no-cache, must-revalidate

<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.15.5</center>
</body>
</html>

**Comment by betslus1** [comment]
Заработало.

**Comment by NikitaMelnikov** [comment]
Планируем изменить API для получения операций, станет лучше с новым протоколом.
Пока сроков нет
