### ISSUE TITLE
Дополнительные api для получение полной истории сделок

### ISSUE THREAD

**Issue by KindDragon** [TinkoffCreditSystems/invest-openapi#355]
Хотелось бы получить информацию в таком формате:
| Ticker Symbol  | Date   (mm/dd/yyyy) | Shares | Price   | Cost       | Type |
| -------------- | ------------------- | ------ | ------- | ---------- | ---- |
| NasdaqGS:AAPL  | 01/11/2012          | 5      | 596.55  | 2982.69965 | Buy  |
| NasdaqGS:MSFT  | 10/12/2012          | 100    | 26.94   | 2694       | Buy  |
| NYSE:TWTR      | 05/15/2014          | 100    | 32.77   | 3277       | Buy  |
| NasdaqGS:GOOGL | 06/11/2013          | 50     | 1022.75 | 51137.5    | Buy  |
| NYSE:WFC       | 01/09/2015          | 60     | 34.06   | 2043.6     | Buy  |
| NasdaqGS:AAPL  | 10/06/2015          | 20     | 111.31  | 2226.2     | Sell |

Cost - полная стоимость сделка со всеми комиссиями.
Ну и обновлять их потом.

На странице Тинькофф Инвестицией тоже нельзя получить такие данные (у зарубежных брокеров можно https://www.stocktrader.com/how-to-export-trades-from-your-online-broker/).
Эти данные можно было бы использовать на https://simplywall.st/ и других подобных серисах.

**Comment by dlinnozmey** [comment]
А в чём затруднение получить список операций с figi=null и привести его к требуемому виду своими силами?

**Comment by KindDragon** [comment]
Я только начал использовать C# API, но может что то упаскаю. Про какой endpoint вы говорите?

**Comment by dlinnozmey** [comment]
> Я только начал использовать C# API, но может что то упаскаю. Про какой endpoint вы говорите?

/operations. При значении figi равном null возвращает операциии сразу по всем инструментам, кроме того - пополнения, выводы, налоги и прочее.

**Comment by KindDragon** [comment]
Все сработало, но если б реализовали #120 то было бы намного проще реализовывать
