### ISSUE TITLE
423 Locked при более 4 подписках на одно соединение

### ISSUE THREAD

**Issue by GusevAnton** [TinkoffCreditSystems/invest-openapi#358]
Если сделать 4 subscribe на стриминг в рамках одного TCP соединения, то вылетает 423 ошибка. В доке инфо не нашел, поэтому либо добавьте либо пофиксите пожалуйста.

**Comment by NikitaMelnikov** [comment]
Такого ограничения нет, подскажите, могли бы вы отправить какие-то логи?

**Comment by GusevAnton** [comment]
Такая ошибка возникает только при подписке через кастовый клиент Netty, проверил на гризли аналогичная проблема. Но вот на вашем официальном клиенте проверил, все работает, видимо проблема где то у меня.
