### ISSUE TITLE
Ответ сервера 429 [Too Many Requests] при RPM около 30

### ISSUE THREAD

**Issue by betslus1** [TinkoffCreditSystems/invest-openapi#359]
t.3_w7XDJExt1

Добрый день,
какая-то явная проблема сегодня началась (до этого 5 месяцев было нормально) с ограничениями. После ~30-го запроса начинает ругаться на 429.
**Проблема только у /orders запросов.** По данному типу запросов у меня около 30 запросов в минуту.

Что-то менялось? Или после утреннего сбоя? Криво прилепили ограничения по MOEX (150/5=30rpm, без учета spb/moex/неравномерности числа запросов в течении пятиминутки)?

Скорость со своей стороны контролирую, тут нет проблем и раньше все нормально было.
<img src="https://habrastorage.org/webt/al/he/6r/alhe6rtvfq2ljpgwcxk3-cw4nr8.png" />

**Comment by betslus1** [comment]
1/72 DEL: ord.orderId: 21304862694
2020-09-23T10:11:15.093Z
2/72 DEL: ord.orderId: 21304858943
2020-09-23T10:11:15.612Z
3/72 DEL: ord.orderId: 21304852919
2020-09-23T10:11:16.479Z
4/72 DEL: ord.orderId: 21304849153
2020-09-23T10:11:17.400Z
5/72 DEL: ord.orderId: 21304837767
2020-09-23T10:11:18.153Z
6/72 DEL: ord.orderId: 21304823296
2020-09-23T10:11:19.433Z
7/72 DEL: ord.orderId: 162620952510
2020-09-23T10:11:20.195Z
8/72 DEL: ord.orderId: 21304775024
2020-09-23T10:11:22.881Z
9/72 DEL: ord.orderId: 21304774486
2020-09-23T10:11:23.579Z
10/72 DEL: ord.orderId: 162620598120
2020-09-23T10:11:24.442Z
11/72 DEL: ord.orderId: 162620415930
2020-09-23T10:11:25.252Z
12/72 DEL: ord.orderId: 162620282000
2020-09-23T10:11:25.964Z
13/72 DEL: ord.orderId: 162620122180
2020-09-23T10:11:26.668Z
14/72 DEL: ord.orderId: 162620002960
2020-09-23T10:11:27.573Z
15/72 DEL: ord.orderId: 162619963390
2020-09-23T10:11:28.390Z
16/72 DEL: ord.orderId: 21304637820
2020-09-23T10:11:29.199Z
17/72 DEL: ord.orderId: 21304636895
2020-09-23T10:11:29.941Z
18/72 DEL: ord.orderId: 21304624078
2020-09-23T10:11:30.605Z
19/72 DEL: ord.orderId: 21304613616
2020-09-23T10:11:31.278Z
20/72 DEL: ord.orderId: 21304609585
2020-09-23T10:11:32.046Z
21/72 DEL: ord.orderId: 162618626220
2020-09-23T10:11:32.838Z
22/72 DEL: ord.orderId: 162618209480
2020-09-23T10:11:35.104Z
23/72 DEL: ord.orderId: 162618103080
2020-09-23T10:11:36.496Z
24/72 DEL: ord.orderId: 162618020940
2020-09-23T10:11:37.472Z
25/72 DEL: ord.orderId: 162617789850
2020-09-23T10:11:38.238Z
26/72 DEL: ord.orderId: 162617763880
2020-09-23T10:11:38.869Z
27/72 DEL: ord.orderId: 162617697730
2020-09-23T10:11:39.583Z
28/72 DEL: ord.orderId: 21304550832
2020-09-23T10:11:40.198Z
29/72 DEL: ord.orderId: 21304546047
2020-09-23T10:11:40.959Z
==========
STATUS: 429, StatusText: Too Many Requests
==========
30/72 DEL: ord.orderId: 21304537826
2020-09-23T10:11:41.188Z
==========
STATUS: 429, StatusText: Too Many Requests
==========
31/72 DEL: ord.orderId: 21304530120
2020-09-23T10:11:41.440Z
==========
STATUS: 429, StatusText: Too Many Requests
==========
32/72 DEL: ord.orderId: 162616484740
2020-09-23T10:11:41.685Z
33/72 DEL: ord.orderId: 162616316200
2020-09-23T10:11:42.231Z
==========
STATUS: 429, StatusText: Too Many Requests
==========
34/72 DEL: ord.orderId: 162616241330
2020-09-23T10:11:42.464Z
==========
STATUS: 429, StatusText: Too Many Requests
==========
35/72 DEL: ord.orderId: 162616204110
2020-09-23T10:11:42.720Z
==========
STATUS: 429, StatusText: Too Many Requests
==========
36/72 DEL: ord.orderId: 162616152210
2020-09-23T10:11:42.964Z
==========

**Comment by Fatal1ty** [comment]
Подтверждаю. Началось 21 сентября на ручках /orders/*. На клиенте на /orders лимитируются запросы до 120 в минуту. Раньше ни разу не было 429.

**Comment by NikitaMelnikov** [comment]
Добрый день, не успели опубликовать изменения по рейт-лимитам.
Из-за технических проблем пришлось снизить количество запросов к /orders, решаем проблему у себя.

Тикет пока не закрываю, как решим ситуацию, закрою

**Comment by NikitaMelnikov** [comment]
Рекомендую снизить рейт до 30 на какое-то время. Мы понимаем, что это очень мало, мы работаем над стабилизацией и в будущем обязательно вернем, а возможно и поднимем рейт-лимиты

**Comment by NikitaMelnikov** [comment]
@Fatal1ty вы правы, начиная с 21 сентября, мы переключали рейт-лимиты для стабилизации выставления заявок от роботов, многие получали таймауты на выставление и отмену заявок

**Comment by NikitaMelnikov** [comment]
https://github.com/TinkoffCreditSystems/invest-openapi/commit/b37bc0366f5b398ea16fb65dfcc0a3016cf9b053

**Comment by Fatal1ty** [comment]
@NikitaMelnikov Кажется, что у вас там алгоритм подсчета количества запросов сломался. Простой тест говорит о том, что текущий лимит далеко не 30 запросов в минуту:

```
0.000: request#1 -> ok
0.167: request#2 -> ok
0.229: request#3 -> ok
0.268: request#4 -> ok
0.311: request#5 -> ok
0.347: request#6 -> ok
0.415: request#7 -> ok
0.455: request#8 -> ok
0.496: request#9 -> ok
0.544: request#10 -> ok
0.588: request#11 -> ok
0.639: request#12 -> ok
0.686: request#13 -> ok
0.722: request#14 -> ok
0.783: request#15 -> ok
0.824: request#16 -> ok
0.870: request#17 -> ok
0.908: request#18 -> ok
0.945: request#19 -> ok
0.993: request#20 -> ok
1.036: request#21 -> ok
1.090: request#22 -> ok
1.129: request#23 -> ok
1.192: request#24 -> ok
1.240: request#25 -> ok
1.301: request#26 -> ok
1.379: request#27 -> ok
1.422: request#28 -> ok
1.487: request#29 -> ok
1.533: request#30 -> ok
60.191: request#31 -> ok
60.386: request#32 -> ok
60.424: request#33 -> ok
60.477: request#34 -> ok
60.533: request#35 -> ok
60.614: request#36 -> ok
60.651: request#37 -> ok
60.687: request#38 -> ok
60.718: request#39 -> ok
60.784: request#40 -> 429
60.795: request#41 -> 429
60.806: request#42 -> 429
60.816: request#43 -> 429
60.825: request#44 -> 429
60.834: request#45 -> 429
60.844: request#46 -> 429
61.107: request#47 -> 429
61.123: request#48 -> 429
61.136: request#49 -> 429
61.145: request#50 -> 429
61.154: request#51 -> 429
61.165: request#52 -> 429
61.174: request#53 -> 429
61.435: request#54 -> 429
61.448: request#55 -> 429
61.458: request#56 -> 429
61.469: request#57 -> 429
61.477: request#58 -> 429
61.490: request#59 -> 429
61.752: request#60 -> ok
120.218: request#61 -> ok
120.400: request#62 -> ok
120.436: request#63 -> ok
120.725: request#64 -> ok
120.779: request#65 -> ok
120.818: request#66 -> ok
120.867: request#67 -> ok
120.910: request#68 -> ok
120.978: request#69 -> ok
121.011: request#70 -> ok
121.051: request#71 -> ok
121.105: request#72 -> ok
121.164: request#73 -> ok
121.203: request#74 -> ok
121.241: request#75 -> ok
121.291: request#76 -> ok
121.326: request#77 -> ok
121.370: request#78 -> ok
121.409: request#79 -> ok
121.449: request#80 -> ok
121.497: request#81 -> ok
121.539: request#82 -> ok
121.594: request#83 -> ok
121.648: request#84 -> 429
121.657: request#85 -> 429
121.667: request#86 -> 429
121.678: request#87 -> 429
121.690: request#88 -> 429
121.699: request#89 -> 429
121.963: request#90 -> 429
180.452: request#91 -> ok
180.613: request#92 -> ok
180.687: request#93 -> ok
180.972: request#94 -> ok
181.037: request#95 -> ok
181.082: request#96 -> ok
181.119: request#97 -> ok
181.164: request#98 -> ok
181.198: request#99 -> ok
181.233: request#100 -> ok
181.289: request#101 -> ok
181.323: request#102 -> ok
181.360: request#103 -> ok
181.426: request#104 -> ok
181.458: request#105 -> 429
181.467: request#106 -> 429
181.487: request#107 -> 429
181.496: request#108 -> 429
181.507: request#109 -> 429
181.515: request#110 -> 429
181.524: request#111 -> 429
181.788: request#112 -> 429
181.804: request#113 -> 429
181.815: request#114 -> 429
181.824: request#115 -> 429
181.837: request#116 -> 429
181.847: request#117 -> 429
181.855: request#118 -> 429
181.866: request#119 -> 429
182.131: request#120 -> 429
```

Мне и остальным не очень бы хотелось словарь бан по IP за 429 ошибки, как это делалось по крайней мере раньше, поэтому раскройте алгоритм или назовите реальный лимит, пожалуйста.

**Comment by betslus1** [comment]
Спасибо за ответ, надеюсь на скорое и приоритетное решение этой проблемы. И раньше лимитов не хватало сильно, а сейчас совсем беда.

Так же обратите внимание пожалуйста еще на тикет 
https://github.com/TinkoffCreditSystems/invest-openapi/issues/200
Он связан с этой проблемой, так как решение той проблемы, снизит нагрузку на orders вдвое.

**Comment by NikitaMelnikov** [comment]
@betslus1 да, это должно помочь, но пока что у нас нет честного редактирования, то есть действия будут неатомарными и могут привести к снятию заявки без ее выставления

**Comment by NikitaMelnikov** [comment]
@Fatal1ty у нас алгоритм всегда был таким, лимиты просто не строго-консистентные

**Comment by nonamegithub** [comment]
Подкину еще заявку на оптимизацию. На данный момент, для отрисовки полноценного стакана необходимо одновременное выполнение запросов OrderBook и Orders . Обновление стакана раз в секунду = 60 запросов Orders.
Появление нового метода/запроса  (например OrderBookExtended) с дополнительной информацией о своих заявках могло бы снизить возможную нагрузку на ваши сервера.

**Comment by betslus1** [comment]
Добрый день,
Скорость ответа порезана специально или это баг?

**Comment by KirillKaverin** [comment]
@betslus1 у меня такая же проблема с RPM сегодня, при этом в 10:00 - 10:20 ещё около 30 RPM выдавало, после 10:30 меньше 10 RPM. Также раньше сервера отвечали намного быстрее, сейчас 500+ мс на большинство запросов, хотя у меня пинг до серверов (по крайней мере судя по стримингу) около 1 мс.

**Comment by Fatal1ty** [comment]
API стало отдавать много 429 при 30 запросах в минуту. Я так в бан попаду по IP скоро.

**Comment by betslus1** [comment]
@Fatal1ty я думаю они до 10 RPM снизили.
Телегу сделайте кто-то неофициальную и ссылку...

**Comment by lolpoi** [comment]
> @betslus1 у меня такая же проблема с RPM сегодня, при этом в 10:00 - 10:20 ещё около 30 RPM выдавало, после 10:30 меньше 10 RPM. Также раньше сервера отвечали намного быстрее, сейчас 500+ мс на большинство запросов, хотя у меня пинг до серверов (по крайней мере судя по стримингу) около 1 мс.

Время в стриминге врёт, оно там просто отдаёт время когда был сгенерирован и отправлен пакет и не имеет ничего общего со временем самого события.

Весь нынешний апи вообще на вынос.

**Comment by KirillKaverin** [comment]
> > @betslus1 у меня такая же проблема с RPM сегодня, при этом в 10:00 - 10:20 ещё около 30 RPM выдавало, после 10:30 меньше 10 RPM. Также раньше сервера отвечали намного быстрее, сейчас 500+ мс на большинство запросов, хотя у меня пинг до серверов (по крайней мере судя по стримингу) около 1 мс.
> 
> Время в стриминге врёт, оно там просто отдаёт время когда был сгенерирован и отправлен пакет и не имеет ничего общего со временем самого события.

ну время сервера vs моё локальное время разница в 1мс

**Comment by 41nt** [comment]
В документации лимиты в 30 запросов к /orders, по факту 429 начинается уже при 10 RPM. Что вообще происходит?..

**Comment by NikitaMelnikov** [comment]
Разделили лимиты на чтение/запись https://tinkoffcreditsystems.github.io/invest-openapi/rest/

**Comment by csharpdeveloperuk** [comment]
> Разделили лимиты на чтение/запись https://tinkoffcreditsystems.github.io/invest-openapi/rest/

Применил данные лимиты еще вчера вечером, дополнительно сократил по 1 запросу в каждом типе запросов и все равное приходят 429 TooManyRequests :(

**Comment by ApCeHu4** [comment]
10 лимиток в минуту это временное ограничение?

**Comment by csharpdeveloperuk** [comment]
точно ли для /orders лимит равен 100, уж больно цифра выбивается между 120 и 10, как у остальных, может причина TooManyRequests в этом?

**Comment by jonny1960** [comment]
совсем API стало не пригодно для работы

**Comment by csharpdeveloperuk** [comment]
> совсем API стало не пригодно для работы

Присоединяюсь.

**Comment by NikitaMelnikov** [comment]
@ApCeHu4 да, это временное ограничение, снимем его скорее всего уже на следующей неделе

**Comment by na88git** [comment]
Сейча 429 TooManyRequests проскакивает даже при текущих ограничениях :(
В тестовом режиме установил интервал 6,5 сек между любыми запросами, а это реже, чем 10 раз в минуту и славливаю эпизодически ненавистную 429

**Comment by ApCeHu4** [comment]
Наблюдаю ограничение в 5 заявок в минуту. Это вы так сняли ограничение в 10 заявок?

**Comment by storuky** [comment]
> Наблюдаю ограничение в 5 заявок в минуту. Это вы так сняли ограничение в 10 заявок? В документации ограничение по-прежнему 10.

Присоединяюсь. Это не нормально. 
Зачем вообще нужен такой API? Мало того, что аптайм страдает (да-да, попробуйте в течении дня раз в минуту попинговать этот злосчастный API, удивитесь такому низкому аптайму), так теперь вообще работать невозможно из-за лимитов.

**Comment by ApCeHu4** [comment]
Кстати, отмечали, что лимиты в АПИ введены в угоду пользователей приложения и терминала, я в терминале заявки почти не ставлю, а в приложении совсем не ставлю, почему бы мои лимиты из терминала не разделить с АПИ?

**Comment by betslus1** [comment]
Ладно вам, потерпите еще немного, обещают же поправить скоро...

>  почему бы мои лимиты из терминала и приложения не разделить с АПИ?

Я так понимаю потому, что проблема не у каждого конкретного лица своя, а фундаментальная у всех клиентов компании и цель снизить общее RPS по всей компании. Если RPS не снижать или кому-то делать исключение, то у всех пользователей начнется ерунда в брокерских отчетах (хотя и при сниженных лимитах это наблюдается)

**Comment by ApCeHu4** [comment]
Я здесь имел ввиду не конкретно себя. Есть кто торгует только в терминале, есть кто только в АПИ и т.д., есть различные комбинации на эту тему. Я проверял и точно могу из терминала ставить 30 заявок в минуту, но этим не пользуюсь, и многие другие не пользуются. Так почему лимит не общий? Не ставишь в терменале - значит можешь в АПИ. Израсходовал лимит в АПИ - значит и в терминале будь добр подождать. Или чего теперь плагин для браузера городить, который будет заявки ставить?

**Comment by storuky** [comment]
Открыл инспектор в терминале. Вместо легковесных вебсокетов делают ~10 запросов на свой API-сервер https://api-invest.tinkoff.ru раз в 5 секунд, собирая всю статистику (ордера, позиции, маржа и тд). Причем, ответ со статусом 200, а не 304. Сами себя ддосят.
Конечно, с такой архитектурой железа не напасешься, и 5 rpm звучит как панацея.

Легально ли использовать https://api-invest.tinkoff.ru для торгового бота?

**Comment by NikitaMelnikov** [comment]
> Открыл инспектор в терминале. Вместо легковесных вебсокетов делают ~10 запросов на свой API-сервер https://api-invest.tinkoff.ru раз в 5 секунд, собирая всю статистику (ордера, позиции, маржа и тд). Причем, ответ со статусом 200, а не 304. Сами себя ддосят.

Это никак не относится к текущей ситуации

**Comment by NikitaMelnikov** [comment]
В прошлый четверг обновили ограничения до 50 на запросы https://tinkoffcreditsystems.github.io/invest-openapi/rest/

```
/orders | 100 | 1 минута
-- | -- | --
/orders/limit-order | 50 | 1 минута
/orders/market-order | 50 | 1 минута
/orders/cancel | 50 | 1 минута
```

**Comment by NikitaMelnikov** [comment]
> Легально ли использовать https://api-invest.tinkoff.ru для торгового бота?

@storuky это будет нарушением регламента.

**Comment by jonny1960** [comment]
> > Легально ли использовать https://api-invest.tinkoff.ru для торгового бота?
> 
> @storuky это будет нарушением регламента.

А в чем тогда вообще смысл вашего API?

**Comment by KirillKaverin** [comment]
> > > Легально ли использовать https://api-invest.tinkoff.ru для торгового бота?
> > 
> > 
> > @storuky это будет нарушением регламента.
> 
> А в чем тогда вообще смысл вашего API?

Легально использовать OpenAPI (https://api-invest.tinkoff.ru/openapi/), но не https://api-invest.tinkoff.ru (то, что используется в официальном терминале, мобильных приложениях)

**Comment by NikitaMelnikov** [comment]
@KirillKaverin все верно, спасибо
