### ISSUE TITLE
Пустые свечи, если получать за короткое время

### ISSUE THREAD

**Issue by trackname01** [TinkoffCreditSystems/invest-openapi#360]
Здравствуйте, недавно столкнулся с такой проблемой: если получать свечи за, например, 30 минут то приходит пустой candles. Не выводит ошибку, но candles пустая. Можно узнать с чем это связанно, и как это исправить?? Заранее спасибо.

**Comment by betslus1** [comment]
Возможно не было сделок за период по неликвидным бумагам.

**Comment by trackname01** [comment]
Я уже разобрался, оказывается я передавал время UTC, вместо Московского.
