### ISSUE TITLE
Максимальное количество подписок по streaming API

### ISSUE THREAD

**Issue by dadmin-admin** [TinkoffCreditSystems/invest-openapi#362]
Ограничено ли чем-то количество подписок по streaming API, кроме как пропускной способностью моей сети? Могу ли, я к примеру, подписаться на все инструменты сразу при хорошей пропускной способности или же есть какие-то другие ограничение со стороны брокеры/технические?

**Comment by andrei-karpov** [comment]
Проверено, ограничения нет, однако в рамках подключения веб-сокета вам нужно успевать обрабатывать все сообщения, иначе связь будет обрываться, наибольшая нагрузка проявляется при подписке на orderbook.
