### ISSUE TITLE
Отсутствуют значения averagePositionPrice 

### ISSUE THREAD

**Issue by na88git** [TinkoffCreditSystems/invest-openapi#365]
Запрашиваю с сервера значение портфеля, получаю следующее содержимое:
`{"trackingId":"937f98f7c716825f","payload":{"positions":[{"figi":"BBG000BLCPY4","ticker":"HP","isin":"US4234521015","instrumentType":"Stock","balance":1,"lots":1,"expectedYield":{"currency":"USD","value":0},"name":"Helmerich & Payne"},{"figi":"BBG000BKTFN2","ticker":"HAL","isin":"US4062161017","instrumentType":"Stock","balance":1,"lots":1,"expectedYield":{"currency":"USD","value":0},"name":"Halliburton"},{"figi":"BBG000BBGGQ1","ticker":"VLO","isin":"US91913Y1001","instrumentType":"Stock","balance":1,"lots":1,"expectedYield":{"currency":"USD","value":0},"name":"Valero Energy Corporation"},{"figi":"BBG000BKD3K9","ticker":"BLDR","isin":"US12008R1077","instrumentType":"Stock","balance":1,"lots":1,"expectedYield":{"currency":"USD","value":0},"name":"Builders FirstSource Inc"},{"figi":"BBG000CPBCL8","ticker":"OII","isin":"US6752321025","instrumentType":"Stock","balance":5,"lots":5,"expectedYield":{"currency":"USD","value":0},"name":"Oceaneering International Inc"},{"figi":"BBG007DLZ601","ticker":"RYTM","isin":"US76243J1051","instrumentType":"Stock","balance":1,"lots":1,"expectedYield":{"currency":"USD","value":0},"name":"Rhythm Pharmaceuticals Inc"},{"figi":"BBG000BW6P59","ticker":"USM","isin":"US9116841084","instrumentType":"Stock","balance":1,"lots":1,"expectedYield":{"currency":"USD","value":0},"name":"United States Cellular Corp"},{"figi":"BBG000BDDN94","ticker":"OIS","isin":"US6780261052","instrumentType":"Stock","balance":8,"lots":8,"expectedYield":{"currency":"USD","value":0},"name":"Oil States International Inc"},{"figi":"BBG00P33SY72","ticker":"PNTG","isin":"US70805E1091","instrumentType":"Stock","balance":1,"lots":1,"expectedYield":{"currency":"USD","value":0},"name":"Pennant Group Inc"},{"figi":"BBG000LR8515","ticker":"SBH","isin":"US79546E1047","instrumentType":"Stock","balance":2,"lots":2,"expectedYield":{"currency":"USD","value":0},"name":"Sally Beauty Holdings Inc"},{"figi":"BBG000BF6LY3","ticker":"CCL","isin":"PA1436583006","instrumentType":"Stock","balance":1,"lots":1,"expectedYield":{"currency":"USD","value":0},"name":"Carnival"},{"figi":"BBG00R2NHQ65","ticker":"OVV","isin":"US69047Q1022","instrumentType":"Stock","balance":2,"lots":2,"expectedYield":{"currency":"USD","value":0},"name":"Ovintiv Inc."},{"figi":"BBG00GTWPCQ0","ticker":"DLPH","isin":"JE00BD85SC56","instrumentType":"Stock","balance":1,"lots":1,"name":"Delphi Technologies"},{"figi":"BBG0013HGFT4","ticker":"USD000UTSTOM","instrumentType":"Currency","balance":97.75,"lots":0,"expectedYield":{"currency":"RUB","value":58.31},"averagePositionPrice":{"currency":"RUB","value":77.39},"name":"Доллар США"}]},"status":"Ok"}`

Одни нули и пустое значение averagePositionPrice

**Comment by csharpdeveloperuk** [comment]
Подтверждаю, что если после заключения сделок запрашиваешь портфолио, то AveragePostionPrice по новым позициям нулевой

**Comment by NikitaMelnikov** [comment]
Данные могут приходить с задержкой, решаем ситуацию в самом брокере
