### ISSUE TITLE
Пустые ответы при выставлении limit order

### ISSUE THREAD

**Issue by na88git** [TinkoffCreditSystems/invest-openapi#367]
Добрый день! Помогите, что я могу делать не так??? Каждый раз при запросе на сервер мне приходит пустой ответ при выставлении лимитного ордера.
Количество запросов не более 120 в минуту, сократил промежуток между запросами на 3 сек! В результате только с 3 или 4го раза получаю результат:

Выставляем 0 заявку на пониженную цену:
12:34:36.854032
(Пусто)
Выставляем 0 заявку на пониженную цену:
12:34:39.950111
(Пусто)
Выставляем 0 заявку на пониженную цену:
12:34:43.048798
{"trackingId":"9fb01b77d7aac4f5","payload":{"orderId":"165756306590","operation":"Sell","status":"New","requestedLots":1,"executedLots":0,"commission":{"currency":"USD","value":0}},"status":"Ok"}

По факту получается, что после даннго успешно выставленного ордера, ответ от следующего успешного ордера придет только через 10 секунд после 3х запросов с промежутком в 3 секунды.

**Comment by NikitaMelnikov** [comment]
Добрый день, связано с https://github.com/TinkoffCreditSystems/invest-openapi/issues/359
