### ISSUE TITLE
API v2: пожелание

### ISSUE THREAD

**Issue by lolpoi** [TinkoffCreditSystems/invest-openapi#368]
Помимо всего другого уже озвученного, хотелось бы манипуляции заявками проводить не через REST, а вебсокеты -- соединение-то уже установлено, мы авторизованы, в итоге меньше раундтрипов и просто удобнее.
Спасибо.

**Comment by NikitaMelnikov** [comment]
Добрый день, будет grpc 
https://github.com/TinkoffCreditSystems/invest-openapi/issues/268
