### ISSUE TITLE
Передача токена третьим лицам

### ISSUE THREAD

**Issue by oldnavy1989** [TinkoffCreditSystems/invest-openapi#369]
В соответсвии с документом 
http://acdn.tinkoff.ru/static/documents/0df03ca6-a35e-4b7b-a94c-928490a40151.pdf
пользователям open api запрещается передавать токен третьим лицам.

Это означает, что приложение не может знать о токенах и соответсвенно использовать Open API.
Есть ли рекомендация на этот счет?
Как разработать приложение, чтобы пользователям не пришлось нарушать правила использования сервиса?

**Comment by NikitaMelnikov** [comment]
Добрый день, 

>  Есть ли рекомендация на этот счет?
Пока рекомендаций нет, но мы планируем работать над тем, как подключать другие компании, которые могут управлять данными клиентов

>  Как разработать приложение, чтобы пользователям не пришлось нарушать правила использования сервиса?
Сейчас -  использовать OpenApi для себя

**Comment by moofik** [comment]
есть ли новая информация по возможности использования токена сторонними компаниями которые могут управлять данными клиентов?

**Comment by AlexanderVolkovTCS** [comment]
@moofik пока нет
