### ISSUE TITLE
/orders/market-order ограничение 10 запросов	1 минута

### ISSUE THREAD

**Issue by jonny1960** [TinkoffCreditSystems/invest-openapi#370]
Здравствуйте.

А какой смысл делать ограничение на 10 запросов в 1 минуту через /orders/market-order 

Зачем тогда вообще нужен ваш API?

Если вы не справляетесь с техническими нагрузками может надо их решить?

**Comment by csharpdeveloperuk** [comment]
Присоединяюсь.

**Comment by kitMP** [comment]
АПИ даже исторические свечи неправильно выдаёт(саse уже старше квартала), а вы о тех. нагрузках. Не тянет тинькофф звание финтеха.

**Comment by NikitaMelnikov** [comment]
https://github.com/TinkoffCreditSystems/invest-openapi/issues/359
