### ISSUE TITLE
Получение совершённых операций

### ISSUE THREAD

**Issue by a1div0** [TinkoffCreditSystems/invest-openapi#373]
Здравствуйте!
Сегодня дёргаю запрос на получение операций и мне возвращается всё время одна - последняя. До этого получал все операции. Есть какие-то ограничения или особенности или просто поломалось всё временно?

``` go
import (
    sdk "github.com/TinkoffCreditSystems/invest-openapi-go-sdk"
)
. . .
msk, err := time.LoadLocation("Europe/Moscow")
if err != nil {
    panic(err)
}
dt0 := time.Date(2020, 10, 13, 0, 0, 0, 0, msk)
dt1 := time.Now()
operations, err := client.Operations(ctx, cfg.AccountId, dt0, dt1, "")
if err != nil {
    return errorHandle(err)
}
```

**Comment by NikitaMelnikov** [comment]
Добрый день, никаких ограничений нет
Проверьте счет, по которому вы получаете операции и дату
