### ISSUE TITLE
Отсутствуют границы заявки в instrument_info streaming event

### ISSUE THREAD

**Issue by AnotherSava** [TinkoffCreditSystems/invest-openapi#375]
Использую реализацию из java-sdk для подписки на instrument_info. Типичный пример события, получаемого для торгуемых на MOEX инструментов:

`tradeStatus='normal_trading', minPriceIncrement=0.2, lot=1, figi='BBG006L8G4H1'`

Упоминаемые в документации поля `limit_up` и `limit_down` не возвращались ни разу. Что я делаю не так?

**Comment by NikitaMelnikov** [comment]
Добрый день, эти поля возвращаются только для MOEX

**Comment by AnotherSava** [comment]
@NikitaMelnikov да, именно так в документации и написано, чем и был вызван мой вопрос, но как раз для MOEX эти поля и не приходят:
```
(tradeStatus='opening_auction', minPriceIncrement=0.02, lot=10, figi='BBG000BN56Q9')
(tradeStatus='opening_auction', minPriceIncrement=0.00010, lot=1000, figi='BBG00475K2X9')
(tradeStatus='opening_auction', minPriceIncrement=0.01, lot=10, figi='BBG004730JJ5')
(tradeStatus='opening_auction', minPriceIncrement=0.2, lot=1, figi='BBG007N0Z367')
(tradeStatus='opening_auction', minPriceIncrement=0.05, lot=10, figi='BBG004S68DD6')
(tradeStatus='opening_auction', minPriceIncrement=0.05, lot=10, figi='BBG001BBGNS2')
(tradeStatus='opening_auction', minPriceIncrement=0.02, lot=100, figi='BBG000NL6ZD9')
(tradeStatus='opening_auction', minPriceIncrement=0.001, lot=100, figi='BBG004S68614')
```

а вот инструменты с SPBEX, там поля на месте:
```
(tradeStatus='not_available_for_trading', minPriceIncrement=0.01, lot=1, limitUp=176.02, limitDown=159.34, figi='BBG000BHLYP4')
(tradeStatus='not_available_for_trading', minPriceIncrement=0.01, lot=1, limitUp=55.45, limitDown=47.15, figi='BBG000BLY663')
(tradeStatus='not_available_for_trading', minPriceIncrement=0.01, lot=1, limitUp=88.3, limitDown=82.32, figi='BBG000BRXP69')
(tradeStatus='not_available_for_trading', minPriceIncrement=0.01, lot=1, limitUp=299.67, limitDown=263.53, figi='BBG000C17X76')
```

**Comment by NikitaMelnikov** [comment]
@AnotherSava все верно, прошу прощения, перепутал

**Comment by AnotherSava** [comment]
@NikitaMelnikov можно всё-таки уточнить, есть ли способ получить значения `limit_up` и `limit_down` для торгуемых на MOEX инструментов? или только опытным путём - отправить лимитную заявку заведомо вне ценового диапазона и распарсить ответ?

**Comment by NikitaMelnikov** [comment]
@AnotherSava можно использовать стакан в качестве ориентира
