### ISSUE TITLE
получение статуса заявки через api

### ISSUE THREAD

**Issue by realization** [TinkoffCreditSystems/invest-openapi#376]
Есть orderId заявки, выставленной через /orders/limit-order. 
чтобы получить статус заявки = {"активная"/"неактивная"} - достаточно поискать ее в /orders,
но нужна детальная информация по неактивной заявке...узнать сколько по ней было куплено/продано.

/operations не возвращает orderId, а матчить по цене и времени (как-то не оптимально).

пожелание-1: чтобы /operations возвращал orderId заявки, на основании которой он был исполнен.
пожелание-2: чтобы не делать 2 запроса (в /orders & /operations) и не нагружать rest-api - добавить новую функцию для получения статуса заявки по orderId.
             
приблизительный вариант ответа (который мог бы быть в новой функции):
```
             {
               "status": 0,  // {1-active, 0-inactive}
               "requested_lots": 100, //в заявке было 100 лотов
               "executed_lots": 5, //по заявке исполнилось 5 лотов
             }
```

**Comment by andrewshkovskii** [comment]
Вроде как в operations есть orderId -- это поле id, ну или по-крайней мере оно совпадает с order id в большинстве случаев.

**Comment by NikitaMelnikov** [comment]
@andrewshkovskii все верно
