### ISSUE TITLE
openapi/portfolio Authorization error

### ISSUE THREAD

**Issue by jonny1960** [TinkoffCreditSystems/invest-openapi#377]
Как обычно новая проблема. Все работало всегда. Сегодня утром после открытия торгов сразу portfolio начало выдавать Authorization error. Остальные запросы работают.

Планируете починить?

**Comment by jonny1960** [comment]
/user/accounts GET тоже выдаете тоже Authorization error

надо что то сделать

**Comment by jonny1960** [comment]
оказалось вы мне само произвольно обновили токен в личном кабинете. При том что по старому токену работало все кроме portfolio и user.

**Comment by jonny1960** [comment]
а почему у вас в принципе работают все старые токены? какой смысл тогда делать новые? в чем безопасность?

**Comment by NikitaMelnikov** [comment]
Старые токены можно отозвать самостоятельно, это описано в документации https://tinkoffcreditsystems.github.io/invest-openapi/auth/#_3
