### ISSUE TITLE
404 при регистрации в сэндбоксе

### ISSUE THREAD

**Issue by ILAgent** [TinkoffCreditSystems/invest-openapi#378]
Пытаюсь использовать апи на  Дарте. Сгенерил код по openapi. Вроде бы всё складно. Но пре регистрации в сэндбоксе получаю вот такую картину. Может есть идеи, в чём может быть проблема?
![image](https://user-images.githubusercontent.com/3390938/96511033-2238a080-1267-11eb-960b-a8bb6db64876.png)

**Comment by NikitaMelnikov** [comment]
Вам нужно вызывать `/sandbox/sandbox/registration`

**Comment by ILAgent** [comment]
тогда надо поправить swagger.yaml, потому что там `sandbox/register`

**Comment by tomateit** [comment]
> тогда надо поправить swagger.yaml, потому что там `sandbox/register`

Не надо править swagger, сам сталкивался: дублирование /sandbox/sandbox получается так как есть два неймспейса: `/` и `/sandbox/` для работы с sandbox токеном. Следовательно неймспейс более низкого уровня `/sandbox/register` находится внутри `/sandbox/` оттого и задвоение, в `/` он находиться не может. Потому просто удостоверяемся, что используем корневую ссылку которая оканчивается на `/sandbox` и всё ок работает.

**Comment by ILAgent** [comment]
@tomateit да, точно, спасибо
