### ISSUE TITLE
Close price в свечах. REST

### ISSUE THREAD

**Issue by Maxim-Fil** [TinkoffCreditSystems/invest-openapi#379]
Добрый день!
Почему в стриме в свечах в качестве close_price возвращается last_price, а в рест именно close_price?
Каким образом можно получить last_price по дням за годовой период?

**Comment by Maxim-Fil** [comment]
Добрый день!
Интересно, будет ли здесь какая-нибудь реакция?
Связывался с поддержкой, ответили что в рест передается close_price, при этом на других площадках, в т.ч. на МОЕХ все передают last_price. В чем смысл искажать данные в API?

**Comment by andrei-karpov** [comment]
А в чем по-вашему разница между close_price и last_price, в рамках последней свечи?

**Comment by Maxim-Fil** [comment]
Пример: FXUS за 09.10.2020 close_price 4890, last_price 4863. Стрим выдает 4863, MOEX 4863, другие источники аналогично. REST выдает 4890.

**Comment by andrei-karpov** [comment]
Вроде бы логично, rest выдает информацию о закрытой свече, стрим же отображает информацию на текущий момент времени, где свеча еще не закрыта, и в ней любая last price является также и close price, до того, пока свеча не закроется.

**Comment by Maxim-Fil** [comment]
В таком случае в rest выпадает весь постмаркет. 
Повторюсь, MOEX и другие площадки выдают в rest дневную свечу включая постмаркет, все кроме Тинькова.

**Comment by andrei-karpov** [comment]
Это да, проблема, я себе ее решил получением свечей на минуту, после 24:00

**Comment by AlexanderVolkovTCS** [comment]
В нашем API в close_price формируется без учета постмаркета. Можно решить проблему, как посоветовал andrei-karpov.
