### ISSUE TITLE
Количество (не лоты) в API

### ISSUE THREAD

**Issue by Naskalin** [TinkoffCreditSystems/invest-openapi#381]
Добрый день, пример:
Есть инструмент - USD_RUB, figi: BBG0013HGFT4
1 лот = $1000

В веб версии терминала (https://www.tinkoff.ru/invest-terminal/) можно приобрести "не полный лот", выбрав "Рыночную заявку", где можно ввести в поле лоты - например $5.
При этом выполняется запрос к api /market-order  {quantity: 5}

В Open API инвестиций метод marketOrder позволяет заполнить только поле lots
https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/master/src/OpenAPI.ts#L248

Вопрос - каким образом используя API, можно приобрести "не полный лот" как в веб версии?

**Comment by MaximKiselev** [comment]
у меня такое ощущение что в текущей версии никак... Тем более а зачем? Вы собираетесь торговать USDRUB парой? Поставить можно уведомление например на курс - а потом вручную купить.

**Comment by Naskalin** [comment]
Да, хотел суммы делить, по $1000 сейчас не так эффективно для меня, вручную это история не про API. Похоже, что в данный момент используя только api - это реализовать не получится.

**Comment by MaximKiselev** [comment]
> Это, в общем было в качестве примера. Вручную - это история не про API. Можно рассмотреть другую ситуацию при которой нужно докупить $200 для покупки акций другого инструмента.
> 
> Похоже, что в данный момент используя только API - это реализовать не получится.
> **Пожалуйста, рассмотрите возможность добавления этого функционала в API.**

не ну в качестве примера неудачный выбор. одно дело докупать валюты .. другое дело покупать части лотов. аля 0.5 акции или половину акции из лота например на 10. для последних есть фонды. ну в целом идея конешно прикольная чтобы можно было докупать по суммам или частям. в принципе адекватно для недорогих лотов с большим количеством акций.

**Comment by NikitaMelnikov** [comment]
Валюты в OpenApi торгуются только полным лотом

**Comment by ethicfinance** [comment]
Спасибо за ответ! Ребят, ну это мягко говоря не айс. Вопрос явно политический, а не технический:) Вот, скажем, есть у управляющего, который через вас работает пачка клиентов и он должен каждому сказать: "дорогой, купи себе валюты ручками. Или я куплю тебе иностранные бумаги за рубли на 1% дороже". Получается вы сами себе трафик режете и теряете на комиссии. В чем проблем добавить эту возможность в API хотя бы для валюты. Если вопрос не по адресу, скажите куда стучать, предлагаю коллективно этот вопрос пушить. Думаю банк заинтересован в росте комиссионных доходов.
