### ISSUE TITLE
При получении операций через REST API возвращаются некорректные данные

### ISSUE THREAD

**Issue by paillechat** [TinkoffCreditSystems/invest-openapi#386]
Если выполить два параллельных запроса с разными интервалами, то результаты соотвествующие первому запросу могут быть возвращены и для второго запроса.

Пример для тестирования:
```bash
curl --request GET -sL \
     -H 'Authorization: Bearer put your key' \
     'https://api-invest.tinkoff.ru/openapi/operations?from=2000-01-01T00%3A00%3A00Z&to=2020-11-06T00%3A00%3A00Z' | jq '(.trackingId), (.payload.operations | length)' &

curl --request GET -sL \
     -H 'Authorization: Bearer <put your key>' \
     'https://api-invest.tinkoff.ru/openapi/operations?from=2020-11-06T00%3A00%3A00Z&to=2020-11-06T13%3A51%3A22%2B07%3A00' | jq '(.trackingId), (.payload.operations | length)'
```

Для своего ключа, выполняя выше представленные запросы, я получаю ответы:
trackingId: "cb475a18349a8bd8"
count: 1301

trackingId:"3a36b237ab23e649"
count: 1301

Правильный дата сет для второго запроса не должен содержать никаких данных, что и происходит если выполнить этот запрос независимо (или не параллельно) от первого.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, проблема актуальна? Если да - повторяется ли на Сваггере?

**Comment by paillechat** [comment]
Все еще актуальна.
Что значит повторяется ли на сваггере?

**Comment by AlexanderVolkovTCS** [comment]
https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/

**Comment by paillechat** [comment]
Конечно там не воспроизведется ведь сваггер не отправит запросы параллельно.

**Comment by AlexanderVolkovTCS** [comment]
Да, есть такая проблема, запрос не рекомендован для параллельного выполнения, зафиксится в новой версии.

**Comment by paillechat** [comment]
Так может вы и закроете issue когда версия выйдет?
Где-то в документации есть информация о том что запрос не рекомендован для параллельного выполнения?

**Comment by AlexanderVolkovTCS** [comment]
В документации информации нет.
Новая версия API - это не просто багфикс, а полностью новая реализована на совсем другом транспорте (gRPC вместо REST) и этот баг, ровно как и метод его проверки, станет неактуальным.
