### ISSUE TITLE
Проблемы с AveragePositionPrice (по тикеру MATX 09.11.2020, но возможно и по другим)

### ISSUE THREAD

**Issue by csharpdeveloperuk** [TinkoffCreditSystems/invest-openapi#388]
Возможно и по некоторым другим, но точно по тикеру MATX не корректно сегодня обновляется AveragePositionPrice. В результате сделки в убыток. Пожалуйста проверьте.

**Comment by csharpdeveloperuk** [comment]
Дополнение: между открытием сделки и закрытием сделки прошло 11 минут, то есть проблему, думаю, реально будет воспроизвести.

**Comment by EJohnF** [comment]
Сегодня вообще катастрофа!!! Многие операции имею 0 стоимость в истории
Куча ошибок типо {"name":"FetchError","message":"invalid json response body at https://api-invest.tinkoff.ru/openapi//operations?from=2020-11-07T05%3A03%3A47.672Z&to=2020-11-10T14%3A59%3A40.377Z&figi=BBG000BSJK37 reason: Unexpected end of JSON input","type":"invalid-json"} 

не говоря уж о другого рода задержках

**Comment by NikitaMelnikov** [comment]
Добрый день, за деталями можно обратиться в поддержку.
Проблема не на OpenApi
