### ISSUE TITLE
Цена покупки в /operation

### ISSUE THREAD

**Issue by mik-hail** [TinkoffCreditSystems/invest-openapi#389]
Добрый день,
Подскажите, пожалуйста, а есть возможность в операциях для сделок Sell получать информацию о цене по FIFO, по которой была сделана покупка этой позиции?
Спасибо

**Comment by polkila** [comment]
Аналогичный вопрос: я заметил, что при вызове "/orders/market-order" сервер не указывает информацию о цене и пишет, что комиссия 0
`{
  "trackingId":"e99f05dbe48d37c6",
  "payload":
    {
    "orderId":"171669040420",
    "operation":"Buy",
    "status":"Fill",
    "requestedLots":1,
    "executedLots":1,
    "commission":{"currency":"USD","value":0}
    },
  "status":"Ok"
}`

**Comment by NikitaMelnikov** [comment]
Добрый день,
Задача такая на брокере есть, займемся

@polkila в данный момент песочница не в полной мере симулирует поведение системы
