### ISSUE TITLE
В последний час началились массовые ошибки "OrderCancelError: Ошибка отмены поручения"

### ISSUE THREAD

**Issue by csharpdeveloperuk** [TinkoffCreditSystems/invest-openapi#390]
В последний час начались массовые ошибки "OrderCancelError: Ошибка отмены поручения". Пожалуйста обратите внимание. Что характерно, это наблюдается в основном для американских акций.

**Comment by NikitaMelnikov** [comment]
Добрый день,
Ограничений на OpenApi не было, вероятно было связано с летенси работы с биржей
