### ISSUE TITLE
OrderNotAvailable: Недостаточно активов для сделки

### ISSUE THREAD

**Issue by csharpdeveloperuk** [TinkoffCreditSystems/invest-openapi#391]
Как по российским, так и по американским акциям всегда приходят данные ошибки, когда например остаются последние 6 долларов и робот пытается купить на 4 доллара, то есть денег больше чем на 50% от требуемой позиции. Замечу, что маржинальная торговля на счете отключена.

**Comment by NikitaMelnikov** [comment]
При этом нет заблокированных средств?

**Comment by csharpdeveloperuk** [comment]
Да, нет заблокированных средств. То есть если условно свободно 200$, заявок выставлено на сумму 190$ (о чем свидетельствует иконка замочка напротив суммы 190$ в мобильном приложении), и выставляем заявку на сумму 4$ при фактически свободных 10$, то получаем данную ошибку. Суммы приведены для примера. 100% это происходит при попытке открыть позицию на 400 рублей при свободных 600-800 рублях.

**Comment by csharpdeveloperuk** [comment]
Прошу прощения, думаю косяк на моей стороне. Закрываю тикет.
