### ISSUE TITLE
Не выставляются заявки на продажу на американском рынке сегодня

### ISSUE THREAD

**Issue by csharpdeveloperuk** [TinkoffCreditSystems/invest-openapi#392]
Российский рынок работает штатно, все API работает штатно, но заявки по американскому рынку отправляемые на продажу не попадают в стакан и не отображаются в мобильном приложении сегодня. Выходной в США же был вчера, SNP500 двигается, стаканы шевелятся в мобильном приложении. При попытке выставить лимитную заявку вручную в мобильном приложении отображается сообщение "Выставлен запрет на уровне администратора". В чем может быть дело?

**Comment by csharpdeveloperuk** [comment]
Заявки стали выставляться ровно в 23-48 МСК по американскому рынку. Если это было только у меня, дайте пожалуйста пояснение, с чем невыставление заявок на протяжении всего дня было связано?

**Comment by NikitaMelnikov** [comment]
Добрый день, за деталями необходимо обратиться в поддержку. Со стороны OpenApi ограничений не было
