### ISSUE TITLE
Страница с примерами запросов

### ISSUE THREAD

**Issue by Sunozov** [TinkoffCreditSystems/invest-openapi#393]
Добрый день, возможно непонятно опишу, но ранее  натыкался на страницу, где можно было авторизоваться и делать примеры запросов к API и получать ответы, сейчас не могу найти подобное, может есть ссылка?

**Comment by tomateit** [comment]
Не эта? https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/

**Comment by Sunozov** [comment]
Спасибо больше, оно самое)
