### ISSUE TITLE
Некорректное отображение плеча

### ISSUE THREAD

**Issue by luxrost** [TinkoffCreditSystems/invest-openapi#394]
Всем привет.

При наличии отрицательных остатков денежных средств портфеле (плечо), portfolio не возвращает рублёвую позицию (RUB).
Остатки USD и EUR (в тч наличие плеча) возвращает корректно.

Использовал sdk от [https://github.com/daxartio/tinvest](url). Разработчик направил к вам [https://github.com/daxartio/tinvest/issues/130](url).

**Comment by ddmrtc** [comment]
Портфолио вообще не возвращает рублевую позицию, нужно отдельно запрашивать
валюты get portfolio/currencies


Пн, 16 нояб. 2020 г. в 12:36, Rostislav Lushnikov <notifications@github.com

**Comment by luxrost** [comment]
Будем искать и пробовать. спасибо.
Странно, что при этом показывает как плечи, так и собственную позиции по иностранным валютам.
Почему рубль не считается активом в портфеле - непонятно.

**Comment by luxrost** [comment]
Удалось получить текущие остатки валют и рублей, как плечи, так и собственные.

Прошу рассмотреть возможность:
1. либо исключения данных по валютам их портфеля (и передавать только через get portfolio/currencies);
2. либо включение в portfolio всех позиций по денежным средствам (в тч RUB), тк это тоже актив портфеля.

С рублями в основном портфеле (опция [2]), полагаю, будет сложнее, тк у него нет figi.

Так подход будет унифицирован.

**Comment by polkila** [comment]
Просим из текущей версии API  ничего не исключать. Просим придерживаться политике только добавления.
Потому что уже приросли к этой версии, и некоторые задачи решаем тем, что есть. Пускай даже иногда при помощи костылей. Если что-то убирать, тогда посыпятся клиентские приложения.

**Comment by NikitaMelnikov** [comment]
Все валютные позиции возвращаются через `portfolio/currencies`, пока что менять не планируем
