### ISSUE TITLE
При редактирование order не сохраняется ссылка на родительский order.

### ISSUE THREAD

**Issue by RWander** [TinkoffCreditSystems/invest-openapi#395]
В терминале есть возможность редактирования order:

![image](https://user-images.githubusercontent.com/2590778/99254884-80d44880-282c-11eb-842e-16ef008f087b.png)

После редактирования текущий order отменяется и создается новый order.
Новый order должен иметь ссылку на своего родителя (начальную версию) - parentOrderId.

**Comment by NikitaMelnikov** [comment]
Редактирование заявки - это отмена и выставление новой

**Comment by RWander** [comment]
Механизм редактирования понятен. Можно все же добавить в новый order поле parentOrderId? Чтобы была логическая связь между отмененным и новым order?

**Comment by KirillKaverin** [comment]
@RWander я думаю никто это реализовывать не будет, т.к. везде (брокер, биржа, терминал) это делается через 2 запроса (отмена и выставление нового ордера). Если же вам нужен parentOrderId, то можете у себя на клиенте дописать код и хранить номера родительских ордеров

**Comment by RWander** [comment]
@KirillKaverin, @NikitaMelnikov 
Номера ордеров у меня сохраняются на клиенте. В этом нет проблемы. Проблема в том, чтобы уметь связывать два ордера между собой, отмененного и нового, которые концептуально являются одним ордером. Когда ордер только один, логически не сложно понять, что отмененный и новый - это один и тот же ордер. Но когда их несколько для одного инструмента, то понять, что ордер был отредактирован, а не просто отменен - невозможно, если нет связи между. 
Поэтому я предлагаю добавить всего лишь одно дополнительное поле parentOrderId. 
Или в rejected reason указать нормальную причину отмены - что order был отменен по причине редактирования, а не просто Rejected.
