### ISSUE TITLE
Получение полной истории всех операций.

### ISSUE THREAD

**Issue by polkilokanfet** [TinkoffCreditSystems/invest-openapi#397]
Столкнулся с проблемой получения полной истории всех операций. 
При /operations с figi = null не приходят некоторые операции. Например:
1. Операции по фонду с тикером EMBE (он из расширенного списка).
2. Операции по облигации с ISIN XS0783242877 (облигации погашены в 2019 году).

Есть ли возможность достать вообще все операции?

**Comment by NikitaMelnikov** [comment]
Добрый день, в данный момент в OpenApi бумаги только из базового каталога, подумаем над расширением
