### ISSUE TITLE
https://api-invest.tinkoff.ru/openapi/operations – 503 service unavailable

### ISSUE THREAD

**Issue by svetlyak40wt** [TinkoffCreditSystems/invest-openapi#40]
Стабильно пятисотит ручка.

Доколе!? Почините!

**Comment by svetlyak40wt** [comment]
@NikitaMelnikov у вас там мониторинги есть?

**Comment by svetlyak40wt** [comment]
![](https://media.gettyimages.com/photos/businessman-seated-at-flaming-office-desk-picture-id92983130)

**Comment by NikitaMelnikov** [comment]
> @NikitaMelnikov у вас там мониторинги есть?

Есть, проблема не на OpenApi

**Comment by NikitaMelnikov** [comment]
Вы используете операции для проверки статуса заявки?

**Comment by NikitaMelnikov** [comment]
https://github.com/TinkoffCreditSystems/invest-openapi/issues/42

**Comment by svetlyak40wt** [comment]
У меня ботик на основании операций считает среднюю цену каждой бумаги в портфолио и показывает разницу между ней и текущей ценой. Из этого понятно, выгодно ли её сейчас продавать.

Примерно так это выглядит:

![2019-11-01_18-41-37](https://user-images.githubusercontent.com/24827/68036778-6ab62180-fcd7-11e9-9983-7a42d111fe0f.png)

**Comment by NikitaMelnikov** [comment]
Понятно, спасибо за кейс
