### ISSUE TITLE
Разъяснения по частично исполненной отклоненной заявке.

### ISSUE THREAD

**Issue by RWander** [TinkoffCreditSystems/invest-openapi#400]
Коллеги, подскажите, пожалуйста:

1. Если order выполнился частично, скажем произошла покупка 6 из 10 лотов, при вызове /operations операция уже будет создана? Если да, то какой у нее будет статус?
2. В swagger-документации есть статус Progress. В каком случае мы получаем такую операцию?
![image](https://user-images.githubusercontent.com/2590778/100209418-4c931300-2f23-11eb-9f5b-4eca619a45a2.png)
3. Как распознать (по каким полям) частично исполненную но отклоненную заявку в /operations (6 из 10 лотов были исполнены, но затем ордер был отклонен)?

**Comment by NikitaMelnikov** [comment]
Добрый день,
1. Будет создана, будет статус Done
2. В случае наполнения операции сделками, но сейчас это работает несколько не так
3. Не все лоты будут исполнены

**Comment by polkila** [comment]
> Добрый день,
> 
> 1. Будет создана, будет статус Done
> 2. В случае наполнения операции сделками, но сейчас это работает несколько не так
> 3. Не все лоты будут исполнены

Вообще-то нет. В списке операций заявка появляется, только когда пролностью исполняется, или отменяется. Прямо сейчас так.
