### ISSUE TITLE
Как узнать суммарную коммиссию по сделке?

### ISSUE THREAD

**Issue by chernish2** [TinkoffCreditSystems/invest-openapi#401]
У меня тариф трейдер, за первую операцию в расчётном месяце взимается плата 290р + коммиссия 0.05%, за последующие - только коммиссия за сделку.
Каким образом с помощью API можно определить, будет ли списана плата за тариф 290р?
Спасибо.

**Comment by ddmrtc** [comment]
Дату ServiceCommission можно проверить в операциях, если больше 30 дней
назад, то будет списана

Чт, 26 нояб. 2020 г. в 16:07, Alexey Chernysh <notifications@github.com>:

**Comment by chernish2** [comment]
Это понятно, хотелось бы более прямого и независимого от тарифа (тариф может изменяться) пути - сказать какой ордер собираюсь ставить и увидеть, какие будут расходы.

**Comment by ddmrtc** [comment]
Не могу представить зачем это, дату servicecommission можно узнать,
комиссия за сделку известна из тарифа, тариф влияет только на размер

Чт, 26 нояб. 2020 г. в 17:02, Alexey Chernysh <notifications@github.com>:

**Comment by chernish2** [comment]
Хотелось бы получить официальный ответ разработчиков API на поставленный вопрос.
Спасибо.

**Comment by NikitaMelnikov** [comment]
Пока что такого метода на OpenApi нет, можно смотреть на сервисную комиссию в истории как упоминал @ddmrtc
