### ISSUE TITLE
Возвращает комиссию по сделке "0" после исполнения рыночной заявки (не песочница)

### ISSUE THREAD

**Issue by polkila** [TinkoffCreditSystems/invest-openapi#402]
Лог:
path /orders/market-order
statusCode 200
statusMessage OK
body {
    "trackingId": "536227311c362d4f",
    "payload": {
        "orderId": "21958806802",
        "operation": "Buy",
        "status": "Fill",
        "requestedLots": 1,
        "executedLots": 1,
        "commission": {
            "currency": "RUB",
            "value": 0
        }
    },
    "status": "Ok"
}

PS Было бы здорово добавить среднюю цену, тк заявка уже исполнилась.

**Comment by NikitaMelnikov** [comment]
Добрый день,
Была ситуация на брокере, когда средняя цена не успевала обновляться и отображался 0
