### ISSUE TITLE
Открытие терминала с нужной ЦБ по ссылке

### ISSUE THREAD

**Issue by skillbox-koutja** [TinkoffCreditSystems/invest-openapi#403]
Подскажите, как создать ссылку, перейдя по которой откроется invest-terminal с нужной ценной бумаги для залогиненного пользователя? 
Например, нужно чтобы открывался терминал, и была выбрана акция AAPL. Для этого ссылка могла вглядеть так
~~~
https://www.tinkoff.ru/invest-terminal/?ticker=AAPL_SPB.SPB23
~~~

У ВТБ так можно сделать, если пользователь залогинен, то перейдя по ссылке ниже можно выставить заявку на покупку 
~~~
https://lk.olb.ru/Trade/CreatePredefinedOrder?tradeAcckey=&boardCode=SPB23&marketCode=EQF&exchangeCode=MICEX&isBuyOperation=true&price=215.15&volume=0&securityCode=AAPL_SPB.SPB23
~~~

**Comment by NikitaMelnikov** [comment]
Добрый день,
По терминалу лучше задать вопрос тут https://invest-terminal.useresponse.com/topics
