### ISSUE TITLE
Информация по НКД

### ISSUE THREAD

**Issue by GoodWasHere** [TinkoffCreditSystems/invest-openapi#405]
Здравствуйте.
Нужна информация о НКД бумаги на текущий момент.
Или хотя бы исходные данные о купонах, из которых можно эту цену вычислить.

**Comment by Dazlonar** [comment]
Если посмотреть документацию: https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/portfolio/get_portfolio
То можно увидеть что есть _averagePositionPrice_ - средняя цена c нкд и _averagePositionPriceNoNkd_ - средняя цена без нкд. Cоответственно _NKD_ = _averagePositionPrice_ - _averagePositionPriceNoNkd_

**Comment by GoodWasHere** [comment]
Но это цены на момент покупки, не на текущий момент.

**Comment by Dazlonar** [comment]
Для облигаций - _averagePositionPrice_ постоянно обновляется вместе с нкд, а вот _averagePositionPriceNoNkd_ - это цена покупки. Только что проверил на своих облигациях.
![image](https://user-images.githubusercontent.com/17353727/100874046-086cb900-34b5-11eb-8c2a-53c7350d5451.png)

Как видно _averagePositionPriceNoNkd_ - 1011.74, что соответствует нкд из приложения 11.7 рублей

  | Name | Value | Type
-- | -- | -- | --
  | Value | 1011.74 | decimal



  | Name | Value | Type
-- | -- | -- | --
  | Value | 1011.74 | decimal

**Comment by GoodWasHere** [comment]
Правильно ли я понял, что текущая стоимость облигации это
`Orderbook.lastPrice + (Position.AveragePositionPrice.value - Position.AveragePositionPriceNoNkd.value)`?
Останется ли эта формула верной после выплаты купонов?

**Comment by Dazlonar** [comment]
У вас тут не самая простая ситуация, потому как опираться на _AveragePositionPrice_ своего портфолио не самое лучшее решение для вашей задачи. Очень часто AveragePositionPrice может приходить пустым сразу после покупки, оно бывает обновляется несколько минут. Чисто навскидку могу предложить использовать streaming протокол, а именно подписаться на _instrument_info_ - https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/#instrument_infosubscribe
Через него можно достать _payload.accrued_interest_ - в документации сказано что это _"НКД. Возвращается только для бондов"_ И если все работает так как я представляю, то каждый раз когда что-то в инструменте будет меняться, вам будут сразу приходить данные и вы можете сделать какое-то поле _currentNkd_ и обновлять его из коллбека, только обратите внимание на то что подписка на веб сокет осуществляется глобально и если вы сделаете подписку на разные инструменты, то вам в каждый колл бек будут приходить данные всех инструментов и вам их нужно фильтровать по вашему текущему FIGI. Хотя я на 100% не знаю как у вас все устроено, поэтому может и не нужно. Ну и хорошо бы позаботиться о потокобезопасности для поля которое будет хранить текущий нкд (_currentNkd_), все зависит от того языка с которым вы работаете.

**Comment by GoodWasHere** [comment]
Спасибо за развёрнутый ответ, попробую так.

**Comment by Dazlonar** [comment]
@GoodWasHere Вообще похоже мы зря тут мучились. Судя по всему в цену уже включен НКД, по крайней мере сейчас, когда выставляю облигацию по той цене которую хочу, там автоматом добавляется НКД в стоимость.

**Comment by GoodWasHere** [comment]
Я хочу узнать текущую стоимость бумаги не выставляя её на продажу.
Т.е. "на сколько пополнится мой счёт если я продам её сейчас по рыночной заявке" (без учёта комиссий)
