### ISSUE TITLE
Цена премаркета перед ОС NYSE через OpenAPI

### ISSUE THREAD

**Issue by Maradonna360** [TinkoffCreditSystems/invest-openapi#407]
Добрый день!
Не нашел в документации как на JScript через OpenAPI получить цену американского премаркета по инструменту. Например акция Apple за час до ОС. 
Можно ли в реальном времени видеть изменение этой цены? Спасибо.

**Comment by deniro98** [comment]
Это уж точно не через OpenApi) OpenApi работает с Tinkoff, а на сколько я знаю, Tinkoff не показывает отдельно премаркет
