### ISSUE TITLE
Возвращает ошибку 500 /openapi/orders

### ISSUE THREAD

**Issue by deniro98** [TinkoffCreditSystems/invest-openapi#408]
**Пример 1.**
Кусочек кода для наглядности

```
>>> headers = {"Authorization": "Bearer " + token}
>>> url = "https://api-invest.tinkoff.ru/openapi/orders"
>>> requests.get(url, headers = headers).content
```

```b'{"trackingId":"58d80e56ac76e2d3","payload":{"message":"INTERNAL_ERROR","code":"INTERNAL_ERROR"},"status":"Error"}```

**Пример 2.**
При использовании @Awethon/open-api-python-client
``` Error (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Fri, 04 Dec 2020 11:57:22 GMT', 'Content-Type': 'application/json', 'Content-Length': '113', 'Cache-Control': 'no-store, no-cache, must-revalidate', 'access-control-allow-methods': 'GET,HEAD,POST,DELETE,OPTIONS,PUT,PATCH', 'access-control-allow-headers': 'accept, content-type, authorization, access-control-allow-headers, x-requested-with', 'access-control-allow-origin': '*'})
HTTP response body: {"trackingId":"30a1aad71e658518","payload":{"message":"INTERNAL_ERROR","code":"INTERNAL_ERROR"},"status":"Error"}```

**Comment by deniro98** [comment]
@NikitaMelnikov Поможете разобраться?)

**Comment by deniro98** [comment]
До сих пор конкретно на моем аккаунте не работает, та же ошибка. Количество запросов на токен и на ip не превышено по этой операции, есть другие способы узнать список открытых ордеров? 

Можно ли использовать обычную api(которая с терминала/сайта), пока не работает openapi?

**Comment by NikitaMelnikov** [comment]
Добрый день,
Подскажите, у вас есть открытая заявка на первичное размещение?

**Comment by deniro98** [comment]
Добрый день!
Да есть, даже две было, сейчас одна (Белуга).

Я кажется понял к чему вы клоните) Список заявок не открывается, потому что где-то ошибка по этой заявке
