### ISSUE TITLE
Терминал перестал работать в FireFox

### ISSUE THREAD

**Issue by nleo** [TinkoffCreditSystems/invest-openapi#409]
Прошу прощения, что сюда, но мне кажется сюда лучше чем в чат.

Пару месяцев не заходил, а тут такое

![image](https://user-images.githubusercontent.com/800970/101175812-b06db800-3656-11eb-8f71-2279b9f82329.png)

**Comment by nleo** [comment]
А ещё у меня FF старый 75.0, я его залочил, т.к. последние обновления не радуют. Если в этом проблема тогда претензий нет.

**Comment by NikitaMelnikov** [comment]
Добрый день, 
Лучше сюда https://invest-terminal.useresponse.com/
Этот репозиторий не про терминал, подсказать причины такого поведения в Firefox, к сожалению, не сможем
