### ISSUE TITLE
Возможно ли создать в песочнице несколько аккаунтов?

### ISSUE THREAD

**Issue by Neonlady** [TinkoffCreditSystems/invest-openapi#416]
пытаюсь исполнить подобный код
`xx = SandboxRegisterRequest(broker_account_type=BrokerAccountType.tinkoff)`
`client.register_sandbox_account(xx)`
`xx = SandboxRegisterRequest(broker_account_type=BrokerAccountType.tinkoff)`
`client.register_sandbox_account(xx)`
Думая, что он создает двух юзеров в песочнице. Однако, вызывая `client.get_accounts()` я вижу, что у меня создался только один аккаунт. 

> ...payload=UserAccounts(accounts=[UserAccount(broker_account_type=<BrokerAccountType.tinkoff: 'Tinkoff'>, broker_account_id='SB2311305')])

Возможно ли вообще сделать несколько аккаунтов в песочнице?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, нет, нельзя: register создает только один счет и повторные вызовы будут возвращать его же.

**Comment by bahrustim** [comment]
client = tinvest.SyncClient(SANDBOX_TOKEN, use_sandbox=True)
client.register_sandbox_account(BrokerAccountType.tinkoff)
response = sandbox_client.get_portfolio()
Что не так,? Почему не получается создать сэндбокс аккаунт, пожалуйста подскажите
