### ISSUE TITLE
Пересечение MA50 и MA200

### ISSUE THREAD

**Issue by WurgBASH** [TinkoffCreditSystems/invest-openapi#417]
Здравствуйте, возможно ли с помощью вашего API отследить пересечение MA50 и MA200 на интервале 1 минута? И какие методы для этого лучше использовать?
Может что-то добавить или нормально?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, технические индикаторы Вам необходимо реализовать самостоятельно, а все методы получения и исторических котировок и потока свечей для минутного интервала есть:

https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/
https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/
