### ISSUE TITLE
Возможность получать информацию об ИИС через API

### ISSUE THREAD

**Issue by andre487** [TinkoffCreditSystems/invest-openapi#418]
API используется не только для торговли, но и для аналитики портфеля. Интересно было бы получать сделки и состав портфеля для ИИС, можно без возможности торговать там через API

**Comment by KonstantinValenti** [comment]
Достаточно получить список счетов "/user/accounts". Сейчас API возвращает два счета (если есть ИИС) Tinkoff и TinkoffIis.  При запросе портфеля или операций, подставлять в поле brokerAccountId = TinkoffIis. В этом случае вы будете получать бумаги и сделки именно по ИИС счету.
Удачи!

**Comment by andre487** [comment]
Работает, спасибо!
