### ISSUE TITLE
Токен только для чтения

### ISSUE THREAD

**Issue by hostbox2** [TinkoffCreditSystems/invest-openapi#421]
Нужна возможность создавать токен с правами только для чтения.
Т.е. можно было-бы считывать портфель, прошлые сделки и другие показатели.
Но нельзя было бы манипулировать заявками.

Эта возможность нужна для анализа своего портфеля, а также портфелей других пользователей.
В планах создать небольшой аналитический сервис, где каждый пользователь тинькоф инвестиций мог бы дать доступ с помощью передачи токена только для чтения и получить аналитику по портфелю (текущие и прошлые сделки)

**Comment by AlexanderVolkovTCS** [comment]
#12
