### ISSUE TITLE
Отображения возмещения дохода по дивидендам в списке операций

### ISSUE THREAD

**Issue by Tirondzo** [TinkoffCreditSystems/invest-openapi#423]
В списке операций отсутствует списание средств за дивиденды, так понимаю, при торговле в шорт. 
Операция присутствует в сгенерированном отчёте excel, и называется "Возмещение дохода по дивидендам - списание".

Мне важно иметь возможность восстановить полную историю операций, для детальной аналитики своего портфеля. Без части операций, расчёты с использованием API не сходятся, и аналитика получается некорректной. В то же время, нет простого способа скачивать excel отчёт автоматически.

**Comment by AlexanderVolkovTCS** [comment]
Пока операции по шортам, в тч возмещение дивидендов не поддерживаются в openAPI. Учтено в #279
