### ISSUE TITLE
Неполные лоты и мало валют contextReal.MarketCurrenciesAsync

### ISSUE THREAD

**Issue by ethicfinance** [TinkoffCreditSystems/invest-openapi#424]
Добрый день! Не видно возможности торговли неполными лотами по валюте (и другим активам). В мобильном приложении есть возможность неполных лотов по "USDRUB".

'Все валюты.
        Dim MarketCurrencies = Await contextReal.MarketCurrenciesAsync()

возвращает только 2 валюты:

![image](https://user-images.githubusercontent.com/76777043/103351378-1f063000-4ab4-11eb-9194-0f270349ea27.png)
 
'Лимитный ордер.
![image](https://user-images.githubusercontent.com/76777043/103352157-7ad1b880-4ab6-11eb-9de5-49930379e27d.png)

1)Правильно ли я понимаю, что ограничение по количеству валют связано с типом счета "неквал"?
2)А неполные лоты вообще недоступны через API, т.к. тип переменной lots может быть только integer? При этом тикера "USDRUB" (так отражается в мобильном приложении) найти через API не удается. Помогите, пожалуйста, пофиксить этот вопрос.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день,
1. В OpenApi в данный момент только RUB, USD, EUR
2. Только полные лоты. Обсуждалось в #381
