### ISSUE TITLE
Покупка/продажа currency без слота

### ISSUE THREAD

**Issue by TomySmit** [TinkoffCreditSystems/invest-openapi#426]
Будет ли возможность торговать валютой без ограничений в 1000 ед на 1 слот.
Как в приложении?
[https://help.tinkoff.ru/trading-account/buy-currency/currency-limits/](https://help.tinkoff.ru/trading-account/buy-currency/currency-limits/)

**Comment by AlexanderVolkovTCS** [comment]
Пока такой возможности нет, в будущем будет, но по срокам не отвечу.
