### ISSUE TITLE
Информация о бирже в котрой торгуется инструмент 

### ISSUE THREAD

**Issue by digimortl** [TinkoffCreditSystems/invest-openapi#428]
При расчета финансового результата нужно знать календарь рабочих дней биржи на которой торгуется инструмент, ибо расчет рублевого финансового результата по иностранным ценым бумагам происходит не по курсу доллара дня заключения контракта, а по курсу дня расчета по схеме T+2. В данном API мне не удалось найти такой информации о бирже (код биржи).

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, сейчас через openAPI этого узнать нельзя, но отмечу, что сейчас представленные в openAPI бумаги иностранных эмитентов торгуются через СПБ и посмотреть биржу листинга бумаги можно через ее сайт: https://spbexchange.ru/ru/stocks/inostrannye/Instruments.aspx
