### ISSUE TITLE
Sandbox вопрос в начальных стадиях

### ISSUE THREAD

**Issue by bahrustim** [TinkoffCreditSystems/invest-openapi#430]
client = tinvest.SyncClient(SANDBOX_TOKEN, use_sandbox=True)
xx = tinvest.schemas.SandboxRegisterRequest(broker_account_type=tinvest.schemas.BrokerAccountType.tinkoff)
client.register_sandbox_account(xx)
response = client.get_portfolio()
print(response.payload)
Обязательно ли вот так обращаться к schemas или можно покороче?

**Comment by daxartio** [comment]
Можешь импортировать сущности, тогда будет покороче.
`from tinvest import *`
Вместо `*` лучше указать явное имя

**Comment by bahrustim** [comment]
Спасибо! А можно где нибудь увидеть документацию с более подробным описанием и примерами или может быть у Вас есть заготовки. Буду боагодарен если сможете поделиться!

**Comment by AlexanderVolkovTCS** [comment]
Документация только та, что есть. 
Примеры можете посмотреть в SDK на нужных языках программирования, список здесь: https://github.com/TinkoffCreditSystems/invest-openapi

**Comment by daxartio** [comment]
https://daxartio.github.io/tinvest/tinvest/clients/
