### ISSUE TITLE
Как корректно остановить streaming API?

### ISSUE THREAD

**Issue by stepochkin** [TinkoffCreditSystems/invest-openapi#432]
У меня есть GUI поток и поток asyncio, в котором запущен tinvest.Streaming.run.
Как мне из потока графического интерфейса (например по нажатию кнопки) остановить и корректно закрыть streaming API?

**Comment by daxartio** [comment]
Это вопрос надо задать в [tinvest issues](/daxartio/tinvest/issues).

Графический интерфейс с помощью чего написан?
Qt, web, flexx, tkinter?

**Comment by stepochkin** [comment]
Переадресовал в tinvest issues.
