### ISSUE TITLE
Instrument is disabled for trading: что это значит?

### ISSUE THREAD

**Issue by hl16** [TinkoffCreditSystems/invest-openapi#434]
После порядка 10 попыток создать лимитную заявку внезапно стал получать эту ошибку. Попробовал несколько разных акций, результат один и тот же. Через приложения те же самые акции удалось купить. Что эта ошибка означает?

**Comment by AlexanderVolkovTCS** [comment]
Instrument is disabled for trading появилась после 10 успешных попыток или все попытки были с этой ошибкой? Можете привести примеры бумаг?

**Comment by hl16** [comment]
На данный момент попробовал купить TCSG - ошибка та же.

**Comment by AlexanderVolkovTCS** [comment]
TCSG запрещен: https://tinkoffcreditsystems.github.io/invest-openapi/

**Comment by hl16** [comment]
Не обратил внимание, спасибо
