### ISSUE TITLE
Добавить метод Операций (events)

### ISSUE THREAD

**Issue by Zoktog** [TinkoffCreditSystems/invest-openapi#435]
Было бы удобно иметь метод как в приложении ( операции) или как ссылка в ЛК десктопной версии https://www.tinkoff.ru/invest/broker_account/events/ что бы можно было увидеть что было сделано по профилю,  что было удержано комиссией,  сколько и когда начисляли.  Очень нужный метод для аналитики.

**Comment by ddmrtc** [comment]
GET /operations Получение списка операций

Сб, 9 янв. 2021 г. в 02:27, Roman <notifications@github.com>:

**Comment by Zoktog** [comment]
спасибо
