### ISSUE TITLE
индикатор RSI формула

### ISSUE THREAD

**Issue by cadrules** [TinkoffCreditSystems/invest-openapi#436]
добрый день .  по какой формуле в терминале вычисляется индикатор RSI ?  вычисляю по https://ignat.trading/post/indicator-rsi-beginning/  у меня данные не сходятся .

**Comment by AlexanderVolkovTCS** [comment]
В openAPI индикаторы не строятся, вероятно, Вы используете какой-то SDK. Рекомендую адресовать вопрос туда.

**Comment by cadrules** [comment]
через openapi я получаю свечи , по ним по вышеузказанной формуле я произвожу расчет rsi.  данные свечей с терминалом сходятся  , а вот значение rsi с терминалом разнится .вот в связи с этим возникает вопрос по какой формуле в терминале вычисляется индикатор RSI ?

**Comment by AlexanderVolkovTCS** [comment]
Не подскажу, вопрос по терминалу лучше задать через его техподдержку.

**Comment by Dazlonar** [comment]
@cadrules Значение RSI зависит от предыдущих значений, в некотором смысле это значит что вам нужно рассчитывать его на всей истории свечей или хотя бы на очень большой год-два. Также в вашей формуле используется обычное среднее, а в терминале скорей всего SMMA для подсчета СU/CD И еще проверьте правильно ли вы поняли что CU это только положительные значения (если Сj-Cj-1 >0) и CD только отрицательные.

**Comment by OdCheban** [comment]
rotected override decimal Calculate(List<decimal> nums, int len)
        {
            if (nums.Count <= 2) return 0;

            List<decimal> upCandle = new List<decimal>();
            List<decimal> downCandle = new List<decimal>();
            for (int i = Math.Max(nums.Count - len, 1); i < nums.Count; i++)
            {
                decimal u = Math.Max(nums[i] - nums[i - 1],0);
                decimal d = Math.Max(nums[i-1] - nums[i],0);
                upCandle.Add(u);
                downCandle.Add(d);
            }
            up.Solve(upCandle, len);
            down.Solve(downCandle, len);
            if (down.R() != 0)
            {
                decimal rs = up.R() / down.R();
                return 100 - 100 / (1 + rs);
            }
            else
                return 100;
        }
        
        где up,down - SMMA
        upCandle,downCandle - положительная и отрицательная разница между свечами

**Comment by Dazlonar** [comment]
Алгоритм с виду выглядит правильно. Тогда скорей всего проблема с подсчетом SMMA, SMMA можно представить как EMA со значением alpha = 1 / interval
Сам алгоритм простой: emaValue = alpha * values[i] + (1 - alpha) * previousEmaValue;
previousEmaValue это предыдущее посчитанное ema, если предыдущего не существует, то обычно принимают равным первому значению цены. 
Нужно понять что сам алгоритм предполагает что вы будете считать его начиная с самого начала всей истории, иначе результат будет отличаться, если вы решите посчитать его только за неделю. Предыдущее значение ema можно сохранить и не пересчитывать каждый раз все. Но вам нужно иметь достаточно большую историю что бы значение стремилось к правильному, хотя бы за год, первый раз вам нужно будет посчитать RSI для годовой истории и сохранить посчитанные SMMA значения, можно делать это через параметр (ref decimal cachedUp, ref decimal cachedDown).

**Comment by cadrules** [comment]
нелогично что значение RSI будет зависеть не только от периода но и начальной точки отсчета.   я пробовал и с SMA и SMMA ,  EMA но данные не сходятся ни с терминалом ни с например finvizом(причем терминал с финвизом сходятся!!). Думаю что можно так выбрать начальный интервал отсчета что значения будут практически противоположные.  Все таки думаю что зависеть RSI  должен только от периода , т.е  от определенного колличества предыдущих значений цен. За совет спасибо , буду дальше пробовать найти где у меня глюк.
Заметил у вас ошибочку , когда предидущая  цена равна текущей нужно также добавлять нулевые значения в upCandle и
downCandle. , len при сглаживании не должен меняться.

**Comment by cadrules** [comment]
public decimal CalculateSMA(List<decimal> itemlist)
        {
            if (itemlist.Count==0)
            {
                return  0;
            }
            decimal result = 0m;
            for (int i = 0; i < itemlist.Count; i++)
            {       
                result += itemlist[i];
            }
            return result/itemlist.Count;
        }

        public decimal CalculateSMMA(List<decimal> itemlist)
        {
            if (itemlist.Count == 0)
            {
                return 0;
            }
            decimal smma = 0m;
            decimal smmap = 0m;
            for (int i = 0; i < itemlist.Count; i++)
            {                
                if (i==0)
                {
                    smma=CalculateSMA(itemlist);
                    smmap = smma;
                }
                else
                {
                    smma = ((smmap * (itemlist.Count - 1m) + itemlist[i]) / itemlist.Count);
                    smmap = smma;
                }                
            }
            return smma;
        }
        public decimal CalculateEMA(List<decimal> itemlist)
        {
            
            if (itemlist.Count == 0)
            {
                return 0;
            }
            decimal ema = 0m;
            decimal emap = 0m;
            decimal a = 2m / (itemlist.Count + 1);
            for (int i = 0; i < itemlist.Count; i++)
            {
                if (i == 0)
                {
                    ema = CalculateSMA(itemlist);
                    emap = ema;
                }
                else
                {
                    ema = (a * itemlist[i] + (1m - a) * emap);
                    emap = ema;
                }
            }
            return ema;
        }

**Comment by OdCheban** [comment]
> @Dazlonar нелогично что значение RSI будет зависеть не только от периода но и начальной точки отсчета. я пробовал и с SMA и SMMA , EMA но данные не сходятся ни с терминалом ни с например finvizом(причем терминал с финвизом сходятся!!). Думаю что можно так выбрать начальный интервал отсчета что значения будут практически противоположные. Все таки думаю что зависеть RSI должен только от периода , т.е от определенного колличества предыдущих значений цен. За совет спасибо , буду дальше пробовать найти где у меня глюк.
> @OdCheban** Заметил у вас ошибочку , когда предидущая цена равна текущей нужно также добавлять нулевые значения в upCandle и
> downCandle. , len при сглаживании не должен меняться.

при нулевых значениях - upCandle,downCandle так же заполняется, не вижу ошибки.
Len - да, константа

**Comment by cadrules** [comment]
> > @Dazlonar нелогично что значение RSI будет зависеть не только от периода но и начальной точки отсчета. я пробовал и с SMA и SMMA , EMA но данные не сходятся ни с терминалом ни с например finvizом(причем терминал с финвизом сходятся!!). Думаю что можно так выбрать начальный интервал отсчета что значения будут практически противоположные. Все таки думаю что зависеть RSI должен только от периода , т.е от определенного колличества предыдущих значений цен. За совет спасибо , буду дальше пробовать найти где у меня глюк.
> > @OdCheban** Заметил у вас ошибочку , когда предидущая цена равна текущей нужно также добавлять нулевые значения в upCandle и
> > downCandle. , len при сглаживании не должен меняться.
> 
> при нулевых значениях - upCandle,downCandle так же заполняется, не вижу ошибки.
> Len - да, константа

действительно Math.Max(0.0,0.0) возвращает 0 , я глюканул
