### ISSUE TITLE
Не проходит регистрация в sandbox.

### ISSUE THREAD

**Issue by kitMP** [TinkoffCreditSystems/invest-openapi#437]
Пробую через свагер:
curl -X POST "https://api-invest.tinkoff.ru/openapi/sandbox/register" -H "accept: application/json" -H "Authorization: Bearer мой токен" -H "Content-Type: application/json" -d "{\"brokerAccountType\":\"Tinkoff\"}"
Получаю ответ:
Undocumented | TypeError: Failed to fetch

Авторизация токеном проходит.

**Comment by AlexanderVolkovTCS** [comment]
Вероятно, Вы пытаетесь авторизоваться на песочнице с обычным(торговым) токеном, а нужен отдельный токен для песочницы. Сделать его можно там же, в личном кабинете.

**Comment by kitMP** [comment]
Нет, я всегда  использую только подключение к sandbox и соответствующий токен. В моих приложениях настроена валидация именно sandbox токена, и до недавнего времени всё было в порядке. 10 минут назад сгенерировал новый sandbox токен и теперь всё в порядке и в свагере и моих приложениях. Есть ли какое-то время жизни у токенов? До этого у меня был sandbox токен, который сгенерирован самым первым. И, кстати, на сайте по указанной ссылке  https://id.tinkoff.ru/account/security в списке не было Тинькофф Инвестиции OpenApi(sandbox) из чего я заключаю, что в этом и была проблема - по какой-то причине этот доступ пропал. Хотелось бы понять причину пропажи токена.

**Comment by AlexanderVolkovTCS** [comment]
Время жизни - 1 год.

**Comment by kitMP** [comment]
Ну тогда у вас и у нас какие-то проблемы. Sandbox токен был создан 31-го марта 2020-г.
