### ISSUE TITLE
Вывод FIGI, в другом формате.

### ISSUE THREAD

**Issue by Zoktog** [TinkoffCreditSystems/invest-openapi#438]
на данный момент при вызове ​/operations или /portfolio я получаю данные по бумаге и одно из полей это FIGI, в документации не указанно какой тип figi возвращается.  методом проб и ошибок удалось выяснить что это FIGI Composite, но если бы было просто figi, то было бы удобнее( точнее) понимать о какой бумаге идёт речь.
Например:  
выполняя запрос /portfolio я получаю в ответ : 
```
...
            {
                "figi": "BBG000BBJQV0",
                "ticker": "NVDA",
                "isin": "US67066G1040",
                "instrumentType": "Stock",
                "balance": 1,
                "lots": 1,
                "expectedYield": {
                    "currency": "USD",
                    "value": 13.73
                },
                "averagePositionPrice": {
                    "currency": "USD",
                    "value": 517.98
                },
                "name": "NVIDIA"
            }, ...
```

из данного вывода не понятно на какой бирже торгуется данная бумага,  берём figi из этого запроса и выполняем запрос : https://api-invest.tinkoff.ru/openapi/market/search/by-figi?figi=BBG000BBJQV0
и получаем в ответе : 
```
{
    "trackingId": "56cbd41230bd98bb",
    "payload": {
        "figi": "BBG000BBJQV0",
        "ticker": "NVDA",
        "isin": "US67066G1040",
        "minPriceIncrement": 0.01,
        "lot": 1,
        "currency": "USD",
        "name": "NVIDIA",
        "type": "Stock"
    },
    "status": "Ok"
}
```

и мы так же ничего не получаем ( как мы знаем что isin не уникальны и мы не можем по нему искать конкретную бумагу ) 

Мы знаем сервис https://www.openfigi.com. Но если мы будем искать по тикеру BBG000BBJQV0, то получим список бумаг которые торгуются на разных биржах по миру.  Но если мы возьмём BBG000BBK0R0,  то сразу будет понятно что эта бумага торгуется на UW что соответствует NASDAQ Global Select по маппингу. 

На данным момент апи выдает FIGI Composite ( и этого уточнения нет в документации ) по которому невозможно точно понять на какой бирже торгуется бумага.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, сейчас через openAPI этого узнать нельзя, но отмечу, что сейчас представленные в openAPI бумаги иностранных эмитентов торгуются через СПБ и посмотреть биржу листинга бумаги можно через ее сайт: https://spbexchange.ru/ru/stocks/inostrannye/Instruments.aspx
