### ISSUE TITLE
Возможно ли получить последнюю цену выбранной бумаги

### ISSUE THREAD

**Issue by exelsior** [TinkoffCreditSystems/invest-openapi#439]
Добрый вечер. Такой вопрос, при запросе портфеля я могу получить тикер бумаги. Можно ли посмотреть текущую рыночную цену этой бумаги, когда биржа закрыта?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, можно, например получив из свечи за последний торговый день цену закрытия.
