### ISSUE TITLE
API portfolio маржинальные позиции

### ISSUE THREAD

**Issue by jonny1960** [TinkoffCreditSystems/invest-openapi#444]
Подскажите, можно как то разделить маржинальные позиции и купленные за собственные средства. Ну или хотя бы выводите очень кол-во маржинальных позиций в портфолио. В идеале сделать какие нибудь отдельные группу куда можно было покупать окции и отслеживать их отдельно от остальных. Считать разные средние в том числе.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, пока никак. В будущем это можно будет сделать например через мультисчета.
