### ISSUE TITLE
Пустые ответы через REST

### ISSUE THREAD

**Issue by dtinside** [TinkoffCreditSystems/invest-openapi#446]
Добрый день.
Неделю назад писали о подобном странном поведении, уже и в ТП написали, но никакого ответа не последовало. Может быть сейчас прольётся какой-то свет на данную проблему.
Синхронный REST клиент на C#. Посылаем запрос, получаем пустой ответ. Проверяем через Swagger - ответ есть, сделки отображаются. Наблюдается данная проблема систематически, однако иногда (неизвестно почему), мы получаем нормальные данные. 
На данный момент логика такая: берётся (текущее время - 6 секунд) (это старт запроса), текущее время (конец запроса). В следующей итерации начальное время - становится предыдущее конечное, конечным временем -становится текущий таймстэмп. Пробелов между запросами нет.

Результаты видны ниже.
 
![Swagger UI - Opera 2021-01-19 22 29 29](https://user-images.githubusercontent.com/4015892/105084518-7f7f0080-5aa7-11eb-822f-3198cec05868.png)
) 
![D__NITELaB_NITELaBPro_CSharp_DogTrader_Mark1_bin_D](https://user-images.githubusercontent.com/4015892/105084602-9c1b3880-5aa7-11eb-9754-f5b77292f454.png)

**Comment by AlexanderVolkovTCS** [comment]
Операции могут приходить с опозданием.
Вы в итоге получили на дальнейших шагах информацию об операции 194380623170? Во сколько?

**Comment by dtinside** [comment]
До сих пор не получили. 
Скорее всего придёт потом пачкой. Это вообще нормально? Временное явление или нет?
И если это норма, чем посоветуете пользоваться для торговых ботов, которым информацию надо получать оперативно, а не с большим опозданием?

**Comment by AlexanderVolkovTCS** [comment]
Уточните, в итоге операции пришли пачкой?
Если да, они вышли за лимиты запрашиваемого интервала?

**Comment by dtinside** [comment]
Эти так и не увидели, но теоретически они могли прийти, когда наш сервер не работает (ещё проводим отладку). Но пришли другие тоже пачкой. Сегодня в 10:45 пришли частично операции за вчерашний день (которые вчера не были отловлены).
Границы запроса: 	01.21.2021 10:45:35.724412 - 01.21.2021 10:45:31.612894, время запроса с сервера: 2021-01-21_10:45:35.7262762, ответ с сервера прикреплён к сообщению. Там операции за вчерашний день. В swagger опять ничего подобного нет. 

[REST_Log_21.01.2021.txt](https://github.com/TinkoffCreditSystems/invest-openapi/files/5850088/REST_Log_21.01.2021.txt)

**Comment by dtinside** [comment]
Пролился свет на данную ситуацию. Когда в терминале делаем рыночную заявку - ответ приходит моментально. Когда делаем лимитную - ответа нет. Сделали несколько пробных сделок - везде именно так. 
Причём в swagger видны все операции и никаких различий в структуре там (между лимитными и рыночными) мы не видим.

**Comment by KirillKaverin** [comment]
@dtinside лимитные заявки и так не должны моментально отображаться в операциях. Они отобразятся в операциях только при исполнении лимитного ордера. Рыночные ордера отображаются моментально (почти, бывает лаг) в операциях, т.к. они моментально исполняются по рыночной цене. Чтобы посмотреть текущие лимитные ордера используйте /orders.

**Comment by dtinside** [comment]
> @dtinside лимитные заявки и так не должны моментально отображаться в операциях. Они отобразятся в операциях только при исполнении лимитного ордера. Рыночные ордера отображаются моментально (почти, бывает лаг) в операциях, т.к. они моментально исполняются по рыночной цене. Чтобы посмотреть текущие лимитные ордера используйте /orders.

Справедливо, но они же исполняются и через Swagger я же вижу их именно через /operations. Разве не так?

**Comment by KirillKaverin** [comment]
@dtinside попробуйте
1) исполнить одинаковые запросы через swagger и через c# sdk. Особенно обратите внимание на формат дат, swagger использует немного другой формат. И сравните ответы.
2) Попробуйте запрашивать большие интервалы операций, например за последний час (или даже день).

**Comment by dtinside** [comment]
> @dtinside попробуйте
> 
> 1. исполнить одинаковые запросы через swagger и через c# sdk. Особенно обратите внимание на формат дат, swagger использует немного другой формат. И сравните ответы.
> 2. Попробуйте запрашивать большие интервалы операций, например за последний час (или даже день).

Суть в том, что мне эта информация нужна для бота и опоздание даже на 10 минут делает данные бесполезными. Мой вопрос в том, почему в swagger я вижу эти данные сразу, а используя этот же запрос из клиента получаю пустые ответы.

**Comment by mlshvdv** [comment]
@dtinside еще обратите внимание, что запрос /operations с фильтрацией по figi и без может отображать данные по интересующему инструменту с задержкой. То есть, если указать figi, то /operations возвращает данные по совершенным сделкам по инструменту с меньшим лагом, чем без figi. По наблюдениям разница в обновлении данных может достигать нескольких минут.
 
> Мой вопрос в том, почему в swagger я вижу эти данные сразу, а используя этот же запрос из клиента получаю пустые ответы.

Вы на 100% уверены, что запросы идентичные по всем параметрам? Сравнивали по какому-либо логу?

**Comment by dtinside** [comment]
> @dtinside еще обратите внимание, что запрос /operations с фильтрацией по figi и без может отображать данные по интересующему инструменту с задержкой. То есть, если указать figi, то /operations возвращает данные по совершенным сделкам по инструменту с меньшим лагом, чем без figi. По наблюдениям разница в обновлении данных может достигать нескольких минут.
> 
> > Мой вопрос в том, почему в swagger я вижу эти данные сразу, а используя этот же запрос из клиента получаю пустые ответы.
> 
> Вы на 100% уверены, что запросы идентичные по всем параметрам? Сравнивали по какому-либо логу?

Смотрите, наш клиент прост как табуретка. Он работает по такому принципу: отправляет запрос, получает ответ, парсит его. Границы запроса: старт: текущее время -4 секунды >>> конец: текущее время. На следующей итерации через 4 секунды в качестве  старта берётся предыдущее время конца, а в качестве конца - снова текущее время. Это цикл, без пробелов в запросах, то есть пропустить что-то просто невозможно. 

Мы логируем абсолютно всё, что происходит с нашим клиентом. 
Проверяем на свежем обратном примере, когда в клиент данные приходят, а в swagger пусто: в 2021-01-22_19:21:08.1649999 сервер отправляет запрос со следующими границами времени:

- 01.22.2021 19:21:03.816218
- 01.22.2021 19:21:08.126221

Весь запрос: https://api-invest.tinkoff.ru/openapi/operations?from=2021-01-22T19%3A21%3A03.816218%2B03%3A00&to=2021-01-22T19%3A21%3A08.126221%2B03%3A00

Получаем ответ: 

![_____DogTrader_Log txt – Блокнот 2021-01-22 19 53](https://user-images.githubusercontent.com/4015892/105520299-93b33f80-5ceb-11eb-88b8-4a317e1ba834.png)

В нём есть операции, начиная с 16:31 и до момента запроса. 

Посылаем запрос через Swagger: 

![Swagger UI - Opera 2021-01-22 19 59 21](https://user-images.githubusercontent.com/4015892/105521024-70d55b00-5cec-11eb-96a3-5175a3a23483.png)

Вуа-ля! Пусто. 

Если это мы где-то тупорылим, было бы неплохо, если бы кто-то ткнул нас носом и сказал, что не так.

**Comment by mlshvdv** [comment]
@dtinside Если я не ошибаюсь, то ваш клиент пытается запрашивать операции в периоде 2021-01-22 19:21:03.816218 — 2021-01-22 19:21:08.126221 по Мск, но при этом в ответе клиента почему-то фигурируют более ранние операции, а в свагерре при этом пусто. 

Насколько возможна ситуация, что URL из лога "Prepare request.." в реальности не совпадает с тем, что отправляет ваш клиент в реальности? Так как при указании периода from-to ответ должен быть пустым в /operations, если судить по тому, что возвращается в логах вашего клиента. И сваггер эту гипотезу подтверждает.

**Comment by dtinside** [comment]
> @dtinside Если я не ошибаюсь, то ваш клиент пытается запрашивать операции в периоде 2021-01-22 19:21:03.816218 — 2021-01-22 19:21:08.126221 по Мск, но при этом в ответе клиента почему-то фигурируют более ранние операции, а в свагерре при этом пусто.
> 
> Насколько возможна ситуация, что URL из лога "Prepare request.." в реальности не совпадает с тем, что отправляет ваш клиент в реальности? Так как при указании периода from-to ответ должен быть пустым в /operations, если судить по тому, что возвращается в логах вашего клиента. И сваггер эту гипотезу подтверждает.

Всё верно, я и пытаюсь выяснить, почему мне приходят операции, которые давно завершены.

По поводу корректности запроса. 
Во-первых, строка, которую вы видите в логе и отправляется как запрос на сервер без каких либо изменений.
Во-вторых, если бы ваша гипотеза была верна, для рыночных заявок я бы тоже получал пустые ответы, но с ними всё работает без проблем. Мы специально сделали серию покупок рыночная завяка / лимитная (около 6 операций). 3 с рыночными заявками пришли в клиент, 3 с лимитными - пропали.

**Comment by AlexanderVolkovTCS** [comment]
У коллег ошибка не воспроизводится, аналогичный запрос операций возвращает пустой массив.
Вчера или сегодня проблема была?

**Comment by dtinside** [comment]
Вчера утром в 11:08 купили по рыночной заявке, дальше весь день по лимитным. Рыночная пришла, лимитные - ни одна.

**Comment by dtinside** [comment]
В 13.03 пришла вся вчерашняя пачка.

**Comment by AlexanderVolkovTCS** [comment]
Ситуация с выходом за интервал не воспроизводится, коллеги проверили код - выхода за границы запрашиваемого интервала даже теоретически нет. Жалоб от других пользователей на подобные ошибки тоже не поступало.
Просьба проверить проблему в архитектуре решения на вашей стороне. Используете ли многопоточность? 

Попробуйте написать отдельный максимально простой однопоточный скрипт, который непрерывно опрашивает operation раз в несколько секунд и выводит результат в лог. Проверим, повторится ли ошибка там.

**Comment by KirillKaverin** [comment]
@AlexanderVolkovTCS возможно данный баг схож с моим. Попробую описать:
в течение всего дня я запрашиваю /operations без figi с одинаковым интервалом (от начала дня до конца, например 2021-02-01:00:00:00 -- 2021-02-02:00:00:00). При торговле в течение дня количество операций должно только расти. Но иногда данный запрос возвращает намного меньше операций (в основном разница около 2-ух раз), хотя следующий запрос буквально через секунду возвращает правильные данные. Вчера вечером вообще вместо условных 1000 операций вернуло 3, следующий запрос вернул уже 1000.

**Comment by AlexanderVolkovTCS** [comment]
@KirillKaverin 
> возможно данный баг схож с моим. 
не факт, так как там выход за интервал запрашиваемых дат, а у вас пропуск данных

> возвращает намного меньше операций
просьба - пришлите по операции с пропуском данных полные логи запроса и ответа, с указанием трекинг айди, мы проверим.

**Comment by KirillKaverin** [comment]
@AlexanderVolkovTCS 

Запрос: operations?from=2021-02-02T00%3a00%3a00.0000000%2b03%3a00&to=2021-02-03T00%3a00%3a00.0000000%2b03%3a00

2021-02-02 13:13:14.859 +03:00 --- вернулось 7620 операций (трекинг 31271fa11ac31d91, статус ОК)
2021-02-02 13:13:17.541 +03:00 --- вернулось 7617 операций (трекинг 36821bf7439b82d6, статус ОК)

**Comment by KirillKaverin** [comment]
@AlexanderVolkovTCS 

Запрос: operations?from=2021-02-02T00%3a00%3a00.0000000%2b03%3a00&to=2021-02-03T00%3a00%3a00.0000000%2b03%3a00

2021-02-02 13:21:34.267 +03:00 --- вернулось 7990 операций (трекинг 38b6fffac4604a8b, статус ОК)
2021-02-02 13:21:37.035 +03:00--- вернулось 7804 операций (трекинг b45933f8a5e0385f, статус ОК)

**Comment by AlexanderVolkovTCS** [comment]
@KirillKaverin Можете сделать diff и указать, какие операции не дошли?
+ прикрепить полный ответ сервера

**Comment by KirillKaverin** [comment]
@AlexanderVolkovTCS не доходят утренние операции. Конкретно сейчас (около 14:00 МСК), бывает не доходят операции до 10:57 МСК

**Comment by dtinside** [comment]
Похоже, наконец-то, разобрались в данной проблеме. Признаём своё рукожопство и приносим извинения @AlexanderVolkovTCS за потраченное время. 

В чём суть. Проверяя swagger мы смотрели на дату открытия лимитной заявки, то есть в конкретном примере это 21:10:08. В это время мы забираем ответы с сервера и, конечно же, не видим данной операции, потому что её там ещё нет.
```
  "payload": {
    "operations": [
      {
        "date": "2021-02-08T21:10:08.654669+03:00",
        },
        "trades": [
          {
            "date": "2021-02-08T21:11:59.06519+03:00",
```
Заявка закрывается в 21:11:59 и именно в этот момент мы можем наблюдать её в swagger, но со временем 21:10:08. Наше ПО отпрашивает только последние несколько секунд и поэтому уже не может забрать эту операцию. Именно поэтому мы получаем пустой ответ, а в swagger эта операция есть. 

Для получения оперативных данных по операциям теперь приходится забирать весь массив операций, накапливать их ID и проверять период вчера-сегодня для того, чтобы операции не дублировались при отправке клиенту. 

Ещё раз спасибо всем, кто пытался помочь:)
