### ISSUE TITLE
Изменили тип операции "BrokerCommission" 

### ISSUE THREAD

**Issue by Sairys777** [TinkoffCreditSystems/invest-openapi#447]
Раньше GET запрос https://api-invest.tinkoff.ru/openapi/operations возвращал вот такую структуру операции по типу "BrokerCommission"

![image](https://user-images.githubusercontent.com/45635941/105140297-89851b80-5b08-11eb-8f02-f7c5a14efd89.png)

Начиная с 18 01 2021 года структура изменилась на такую
![image](https://user-images.githubusercontent.com/45635941/105140609-03b5a000-5b09-11eb-907b-32545d0db476.png)

Вопрос. Как при новой структуре определить, по какой именно бумаге была произведена комиссия брокера ?

**Comment by AlexanderVolkovTCS** [comment]
Баг пофиксили, для новых операций теперь все ок, а на восстановление FIGI в пропущенных необходимо еще время.

**Comment by AlexanderVolkovTCS** [comment]
Старые операции тоже восстановлены.
