### ISSUE TITLE
Streaming API: FIGI  not found

### ISSUE THREAD

**Issue by Tupbich** [TinkoffCreditSystems/invest-openapi#448]
Используется C# Sdk
Окружение sandbox.

FIGI BBG006L8G4H1 (на самом деле любой)
Получение свечей по REST ошибку не выдает.
Поиск инструмента по Figi так же инструмент выдает.

ниже шарповские модели запросов-ответов
При подписке на свечи
 {"Event":"candle:subscribe","Figi":"BBG006L8G4H1","Interval":4,"RequestId":"c32e60b9-7554-439c-bb86-df876bbd5de8"}

Получаю
{"Response":{"Event":"error","Payload":{"Error":"Subscription candle:subscribe. **FIGI  not found**","RequestId":"c32e60b9-7554-439c-bb86-df876bbd5de8"},"Time":"2021-01-20T07:34:11.2652825Z"}}

**Comment by AlexanderVolkovTCS** [comment]
В стриминге последнее время подобных проблем не замечено.
Рекомендую задать вопрос в issue используемого SDK

Кстати, у нас есть интервал 4 часа, но указывать надо "4hour"
Описание форматов: https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/

**Comment by Tupbich** [comment]
Спасибо, дело оказалось в нюансах используемого JSON сериализатора в sdk.
p.s. я специально указал что это модели из sdk, под капотом они сериализуются согласно контракту и в openApi идет с "4hour"
