### ISSUE TITLE
В некоторых случаях некорректно возвращается список свечей

### ISSUE THREAD

**Issue by ToPal** [TinkoffCreditSystems/invest-openapi#45]
Запрашиваем список свечей с месячным интервалом с 2019-07-02 по 2019-11-02:
https://api-invest.tinkoff.ru/openapi/sandbox/market/candles?figi=BBG001D8R5D0&from=2019-07-02T13%3A23%3A49.709091%2B03%3A00&to=T13%3A23%3A49.708990%2B03%3A00&interval=month

Возвращается 3 свечи:
2019-08-01
2019-09-01
2019-10-01

Меняем `from` на 2019-10-02, получаем недостающую четвертую свечу:
https://api-invest.tinkoff.ru/openapi/sandbox/market/candles?figi=BBG001D8R5D0&from=2019-10-02T13%3A23%3A49.709091%2B03%3A00&to=2019-11-02T13%3A23%3A49.708990%2B03%3A00&interval=month

Проявляется не на всех инструментах, но на figi=BBG001D8R5D0 повторяется стабильно

**Comment by NikitaMelnikov** [comment]
Могли бы полный запрос привести? В первом примере нет даты

**Comment by ToPal** [comment]
Прошу прощения, в запросе действительно некорректно указан `to`.
Делаю "догрузку" инфо о свечах, которых не хватает в локальной БД.

Оказалось, что проблема немного другая: запрос
https://api-invest.tinkoff.ru/openapi/sandbox/market/candles?figi=BBG000HSLV70&from=2019-07-08T10%3A05%3A51.375586%2B03%3A00&to=2019-10-01T06%3A59%3A59Z&interval=month

возвращает ответ:
{"trackingId":"7f0781a2e58c50fd","payload":{"candles":[{"o":21.37,"c":21.37,"h":21.37,"l":21.37,"v":666746,"time":"2019-10-01T07:00:00Z","interval":"month","figi":"BBG000HSLV70"}],"interval":"month","figi":"BBG000HSLV70"},"status":"Ok"}

У запроса время to установлено - 2019-10-01T06:59:59Z
Время возвращаемой свечи - 2019-10-01T07:00:00Z

`from` и `to` работают с какой-то погрешностью?

**Comment by NikitaMelnikov** [comment]
Время при получении свеч округляется, постараемся написать об особенностях в документации

**Comment by ToPal** [comment]
Округляется до минут?

**Comment by NikitaMelnikov** [comment]
@ToPal если кратко, то округляется до интервала свечи
