### ISSUE TITLE
Как получить свечи за последний час?

### ISSUE THREAD

**Issue by Fricodelco** [TinkoffCreditSystems/invest-openapi#450]
Пытаюсь получить пятиминутные свечки за последний час торгов, но API возвращает пустой объект. Максимум получается получить свечи трёхчасовой давности, как можно получить свечки за недавнее время ?

**Comment by Fricodelco** [comment]
Запрашиваемое время выглядит следующим образом, временная зона соблюдена
2021-01-29 10:59:34.572978+03:00
2021-01-29 11:29:34.572978+03:00

**Comment by igor-i-plotnikov** [comment]
@Fricodelco, обозначенной проблемы не наблюдаю, как вы передаете период?

**Comment by Fricodelco** [comment]
через SDK для python от daxarito, использую метод get_market_candles()

**Comment by igor-i-plotnikov** [comment]
Указываете явно tz=utc?

**Comment by Fricodelco** [comment]
get_market_candles(self, figi, from_, to, interval) async

async def main():
    client = AsyncClient(TOKEN, use_sandbox=True)
    await client.get_market_candles(figi, from_, to, interval)
Вот в такой форме передается запрос from_ и to строки времени указанные выше, временную зону четко не указываю, видимо в этом проблема ?

**Comment by igor-i-plotnikov** [comment]
Вероятно

Попробуйте передать в метод `datetime.now(tz=utc) - timedelta(hours=1)` и `datetime.now(tz=utc) `в нужном формате

Проблема не в API точно
