### ISSUE TITLE
Нулевые показатели по позиции портфеля

### ISSUE THREAD

**Issue by vrubanov** [TinkoffCreditSystems/invest-openapi#451]
Для облигаций Республика Беларусь выпуск 7 (RU000A100D89) стало выдавать нулевое количество в портфеле (/portfolio). В интерфейсе клиента Tinkoff все в порядке, именно через API проблема.

**Comment by AlexanderVolkovTCS** [comment]
Напишите запрос в техподдержку, пожалуйста, проверим изнутри.
