### ISSUE TITLE
limit-order. Rejected. Цена вне лимитов по инструменту

### ISSUE THREAD

**Issue by polkila** [TinkoffCreditSystems/invest-openapi#452]
Сегодня в 00:00 на отчёте подскочил EBAY, и ещё минут 10 была сильная волатильность между 61 и 63,5.
Пытался через openapi создать заявку, но неудачно — статус 'Rejected'.
Не знаю, какие в этот момент были верхняя и нижняя границы. Но при формировании заявки брал ближайшую цену покупки из стакана из stream. Тем не менее, сервер отклонил заявку (6 попыток с разными ценами из стакана из stream).

Лог:
query: {
  url: 'https://api-invest.tinkoff.ru/openapi/orders/limit-order?figi=BBG000C43RR5',
  body: { lots: 1, operation: 'Buy', price: 62.71 } 
},
response: {
  trackingId: '134463aabea3f706',
  payload: {
  orderId: 'VON62592578512N0jSC8',
     operation: 'Buy',
     status: 'Rejected',
     rejectReason: 'Unknown',
     message: 'Цена вне лимитов по инструменту',
     requestedLots: 1,
     executedLots: 0 
  },
  status: 'Ok'
}

**Comment by AlexanderVolkovTCS** [comment]
>message: 'Цена вне лимитов по инструменту'

Это ответ биржи, в данном случае была волатильность и проблемы с limitUp/limitDown на их стороне.
