### ISSUE TITLE
candleinterval 4 часа

### ISSUE THREAD

**Issue by cadrules** [TinkoffCreditSystems/invest-openapi#453]
Добрый день , в Tinkoff.Trading.OpenApi.Models.CandleInterval пропущен интервал 4 часа . Как получить 4 часовые свечи ?

**Comment by AlexanderVolkovTCS** [comment]
Вы вероятно имеете ввиду один из SDK. Рекомендую написать в issue самого SDK или предложить там pull request.

Отмечу, что интервал в 4 часа применим только к streaming, в REST его нет.
