### ISSUE TITLE
Напутаны даты свечей при запросе /market/candles

### ISSUE THREAD

**Issue by rezident** [TinkoffCreditSystems/invest-openapi#454]
Доброго дня.

Запрашиваю дневные свечи за год. Если дата from не далеко ушла от сегодняшней даты (год-два), то дата первой свечи будет равна дате from, а последней свечи to минус 1 день.

Например, для figi=BBG000BB5006
параметр from=2019-02-04T03:00:00.000+03:00 - первая свеча имеет дату 2019-02-04T07:00:00.000+00:00
параметр to=2020-02-04T03:00:00.000+03:00 - последняя свеча имеет дату 2020-02-03T07:00:00.000+00:00

Такое поведение, в целом, ожидаемо и объяснимо. Но если дату from взять подальше (4-5 лет от сегодняшней), то дата первой свечи будет from плюс 1 день, а последней свечи равна параметру to

Пример для того же figi
параметр from=2015-02-04T03:00:00.000+03:00 - первая свеча имеет дату 2015-02-05T07:00:00.000+00:00
параметр to=2016-02-04T03:00:00.000+03:00 - последняя свеча имеет дату 2016-02-04T07:00:00.000+00:00

Что уже немного странно. Погонял с разными figi - даты, с которых начинается расхождения разные.
Планируется это как-то исправляться или есть ли какое-то разумное объяснение происходящего? Высокосный год, летнее/зимнее время или что-то типа того...

**Comment by kitMP** [comment]
Смотрите #341 
Не могут устранить эту проблему более полугода. Финтех, такой финтех...

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, проблема изложена в тикете #341, для бектестинга на дневной истории рекомендуем из времени брать только DATE и контролировать граничные дни.
