### ISSUE TITLE
История котировок бумаги

### ISSUE THREAD

**Issue by sneakybeaky18** [TinkoffCreditSystems/invest-openapi#456]
Добрый вечер, всё что можно перерыл но не могу найти этой возможности. Она вообще предусмотрена? 

Я имею ввиду возможность получения истории цен на акции в указываемых датах, плюс хотелось бы чтобы в этих наборах данных были даты дивидендов. 

У вас же есть графики, на сайте, в приложении.. Там есть отметки о дивидендах - значит эти данные хранятся где-то, значит их можно получить. Очень хотелось бы. Есть ли такая возможность внутри API?

**Comment by kitMP** [comment]
История цен есть, но получить её, те ещё пляски с бубном. Смотри #341 . Когда я спрашивал про даты дивов и их значение, отвечали, что добавлять не собираются, такая вот клиентоориентированность. Над API, мобильным клиентом и терминалом работают разные команды, самая худшая, по-видимому, в API..

**Comment by sneakybeaky18** [comment]
> История цен есть, но получить её, те ещё пляски с бубном. Смотри #341 . Когда я спрашивал про даты дивов и их значение, отвечали, что добавлять не собираются, такая вот клиентоориентированность. Над API, мобильным клиентом и терминалом работают разные команды, самая худшая, по-видимому, в API..

Понятно. Спасибо большое за ответ и информацию. Буду иметь ввиду. Очень странно, что так получается... Даже у финама есть экспорт котировок, кривой-косой, но экспорт, даже клиентом быть не надо. Думал мб у тинькофф есть что-то удобное в формате апи. 

Я вроде как нашел как их получить, кстати. В [этом ](https://github.com/Fatal1ty/tinkoff-api) апи для питона, последний пример использования. По идеи это оно и есть. Осталось лишь понять, что там к чему. Судя по всему полезной информации в этих данных немного.

**Comment by Drenalol** [comment]
Историю цен можно выгрузить по свечам (https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_candles), но есть ограничения, точно не помню, но если свеча дневная то максимум за год, неделя - 2 года, месяц - 10 лет.

Но там не будет информации по дивам.

**Comment by AlexanderVolkovTCS** [comment]
@Drenalol спасибо, все верно.
