### ISSUE TITLE
Вопрос по StreamingEvent

### ISSUE THREAD

**Issue by DmiProps** [TinkoffCreditSystems/invest-openapi#457]
Задача: оперативно получать текущие цены акций.
Что сделал:
1. По инструкции https://github.com/TinkoffCreditSystems/invest-openapi-java-sdk склонировал данные рекозиторий, сделал команду mvn clean package.
2. Заменил App.java на пример кода из этой же инструкции (раздел А если вкратце?). Подставил тикет сандбокса.
3. Дополнительно в каждое событие листенера (onComplete, onSubscribe, onNext, onError) проставил запись в лог чтобы посмотреть порядок срабатывания. Выставил интервал 1 min. Указал figi=BABA (также пробовал figi= BBG006G2JVL2).
4. Других изменений не проводил.

Что получаю в итоге:
1. Сначала срабатывает событие onSubscribe, после в логе вижу события вида:
"INFO: Streaming API клиент #1 подключён" от StreamingContextImpl
И все, тишина. Больше ничего вообще не происходит. Что тут не так?

**Comment by zlumyo** [comment]
Проверил. На момент написания этих строк всё работает. Сделал следующее:

1. выкачал свежий репозиторий `git clone ...`
2. скомпилировал `mvn compile`
3. собрал jar-пакет `mvn package`
4. запустил `cd example/target && java -jar openapi-java-sdk-example-0.6-SNAPSHOT.jar <sandbox_token> BABA 1min true`

Обнаружил недочёт в примере: 39 строка файла example/src/main/java/ru/tinkoff/invest/openapi/example/App.java всегда запускает режим песочницы, поэтому использование "боевого" токена вызывет ошибку.
Вторым параметром нужно передать `parameters.sandboxMode`.
