### ISSUE TITLE
Расчет налога на дивиденды для рос эмитентов

### ISSUE THREAD

**Issue by MaximKiselev** [TinkoffCreditSystems/invest-openapi#458]
Привет парни, понимаю что пишу не совсем сюда. Не могли ли вы уточнить у своих коллег какая точная формула расчета налога на дивиденды для российских эмитентов?
заранее спасибо

**Comment by Dazlonar** [comment]
НДФЛ 13% вычитают в обычном случае. И с 1 января 2021 года, 15% в случае если ваш общий доход превышает 5 млн рублей.

**Comment by MaximKiselev** [comment]
> НДФЛ 13% вычитают в обычном случае. И с 1 января 2021 года, 15% в случае если ваш общий доход превышает 5 млн рублей.

ну это да. но меня интересуют округления и прочие тонкости.. те кроме x*0.13 там еще что-то должно идти...😁

**Comment by AlexanderVolkovTCS** [comment]
Можете обратиться с этим вопросом в поддержку. Здесь консультируем только по API.
