### ISSUE TITLE
Пересоздание заявки на новую цену. Учёт лотов заявки.

### ISSUE THREAD

**Issue by android738** [TinkoffCreditSystems/invest-openapi#459]
1. Посылаю запрос на получение активных заявок.
2. Начинаю циклом перебирать заявки, сравнивая FIGI актива с тем, что мне нужен.
3. Получаю информацию о заявке, в которой стоит 5 лотов запрошено и 0 исполнено.
4. Беру ID данной заявки и посылаю запрос на её отмену, чтобы переставить заявку на новую цену.

Но пока выполнялся данный код, исполнился 1 лот из заявки на 5 лотов. 
И при выставлении новой заявки у меня это не учтено, так как в пункте (3) я записал в переменные информацию о том, что 5 лотов запрошено и 0 исполнено.

Как быть в данной ситуации? Может быть реализовать в API ответ запроса на отмену, в котором будет информация о запрошенных лотах и исполненных?
В данный момент я понимаю так, что успешный ответ запроса на отмену заявки содержит пустоту, а не успешный информацию об ошибке.

**Comment by AlexanderVolkovTCS** [comment]
>Может быть реализовать в API ответ запроса на отмену, в котором будет информация о запрошенных лотах и исполненных?

Подобное синхронное решение, основанное на ожидании статуса отмены, увеличит время выполнения запроса на отмену ордера для всех решений, в т.ч. для работающих асинхронно. Мы же рекомендуем это делать на стороне клиента: реализовывать механику, допускающую лаг между биржей и брокером: например, выставить следующий ордер, дождавшись выполнения или исключения текущего из списка ордеров.

**Comment by android738** [comment]
> > Может быть реализовать в API ответ запроса на отмену, в котором будет информация о запрошенных лотах и исполненных?
> 
> Подобное синхронное решение, основанное на ожидании статуса отмены, увеличит время выполнения запроса на отмену ордера для всех решений, в т.ч. для работающих асинхронно. Мы же рекомендуем это делать на стороне клиента: реализовывать механику, допускающую лаг между биржей и брокером: например, выставить следующий ордер, дождавшись выполнения или исключения текущего из списка ордеров.

Вы закрыли тикет не успев разобраться в ситуации. Я же спросил "Как мне быть в данной ситуации?".
Мне нужно срочно переставить частично исполненную заявку на другую цену. Я получаю Executed и Requested, считаю, а затем сразу же посылаю запрос на отмену и после его успешности ставлю новую заявку. Код на GO всё равно не успевает это сделать.

**Comment by AlexanderVolkovTCS** [comment]
Отловить подобный сценарий можно запросом списка операций (/operations) с минимальным таймфреймом - и если там увидим совершенные сделки - то пересчитать количество. В будущем запланирован стрим событий по исполнениям поручений.
