### ISSUE TITLE
Один и тот же энум отличается в rest API и в Stream

### ISSUE THREAD

**Issue by ZergsLaw** [TinkoffCreditSystems/invest-openapi#46]
В rest возвращается поле tradeStatus 

в stream возвращается trade_status

И тоже самое касается и содержания этих энумов

Возможно это как-то синхронизировать? А то приходим к ситуации, когда порождаем тонну "дублирующися" объектов

**Comment by NikitaMelnikov** [comment]
Обсудим в https://github.com/TinkoffCreditSystems/invest-openapi/issues/46

**Comment by ZergsLaw** [comment]
Но #46 это же эта ишью 0_о

**Comment by fxrlv** [comment]
речь про #47 AFAIK
