### ISSUE TITLE
/sandbox/orders/market-order возвращает "Broker account not found for type=Tinkoff"

### ISSUE THREAD

**Issue by chernovars** [TinkoffCreditSystems/invest-openapi#460]
Делаю запрос через сваггер используя свои токен песочницы и зарегистрированный счет:

`curl -X POST "https://api-invest.tinkoff.ru/openapi/sandbox/orders/market-order?figi=BBG004730N88&brokerAccountId=<BROKER_ID>" -H "accept: application/json" -H "Authorization: Bearer <TOKEN>" -H "Content-Type: application/json" -d "{\"lots\":10,\"operation\":\"Buy\"}" `

Возвращает 

```
{
  "trackingId": "c6ee9ba7e4c958f0",
  "payload": {
    "message": "Broker account not found for type=Tinkoff",
    "code": "USER_ERROR"
  },
  "status": "Error"
}
```

**Comment by reetou** [comment]
Вместо вашего попробуйте URI `https://api-invest.tinkoff.ru/openapi/sandbox/sandbox/orders/market-order`, там два sandbox)

**Comment by AlexanderVolkovTCS** [comment]
BROKER_ID вы берете из /openapi/sandbox/user/accounts?

**Comment by chernovars** [comment]
@reetou 

Спасибо за совет, не добавление второго sandbox не помогло, ошибка 404
{
  "trackingId": "c785d4cfc1fedca2",
  "payload": {
    "message": "Cannot find route",
    "code": "UNDEFINED_ROUTE"
  },
  "status": "Error"
}

**Comment by chernovars** [comment]
@AlexanderVolkovTCS 

Да, номер счета такой же как в теле ответа /openapi/sandbox/user/accounts

{
  "trackingId": "f9fbe5362ecffad0",
  "payload": {
    "accounts": [
      {
        "brokerAccountType": "TinkoffIis",
        "brokerAccountId": "<BROKER_ID>"
      }
    ]
  },
  "status": "Ok"
}

Кстати, а здесь пишут, что тип аккаунта TinkoffIis, в отличие от того, что написано в первом сообщении: "not found for type=Tinkoff"

**Comment by AlexanderVolkovTCS** [comment]
Странно, такие базовые функции через сваггер работают корректно. Уточните, Вы последовательно вызываете регистрацию, выставляете баланс счета и отправляете рыночную заявку?

**Comment by chernovars** [comment]
Вообще да, используя библиотеку в питоне я всё это делал, минимальный пример тут https://github.com/daxartio/tinvest/issues/179.  

Попробовал я все операции в сваггере и к моему удивлению всё прошло нормально. Причем в сваггере выдался новый номер счета SB2603588. Но когда я запустил пример на питоне, который у меня падал, то он тоже отработал нормально. Сейчас прилетают осмысленные результаты типа NOT_ENOUGH_BALANCE. Но пример в питоне показывает мне старый номер счета, с которым у меня первоначально ничего не работало SB2513652.

Кажется, есть идея, почему всё так произошло.

1. Сначала я зарегистрировал счет с типом TinkoffIis, просто потому что пример из документации библиотека питона так делал.
2. С типом счета TinkoffIis у меня не получалось размещать рыночную заявку, потому что не было основного (обычного счета), мне сразу кидали USER_ERROR.
3. По вашему совету, я в сваггере снова зарегался, но там мне уже выдали новый нормальный счет с типом Tinkoff.
4. Видимо из-за проверки на наличие обычного счета в каком-то месте на вашем стороне, заявка на мой первоначальный счет TinkoffIis прошла дальше на обработку, и теперь все мои примеры работают.

Спасибо за помощь
