### ISSUE TITLE
Лимиты использования API

### ISSUE THREAD

**Issue by jonny1960** [TinkoffCreditSystems/invest-openapi#462]
Сегодня снова что ли урезали лимиты использования API. Постоянно появляются ошибки превышения. Вы может продавайте какие-нибудь пакеты лимитов подключению. Ну так не возможно совсем работать.

**Comment by AlexanderVolkovTCS** [comment]
Нет, лимиты не изменялись, но конкретно вчера наблюдались локальные проблемы с доступом.
