### ISSUE TITLE
Уточнения по условиям использования API физическим лицом

### ISSUE THREAD

**Issue by FedorSymkin** [TinkoffCreditSystems/invest-openapi#463]
Я хотел бы попробовать OpenAPI для получения котировок с Московской и СПБ бирж как физическое лицо в целях самообразования и личных экспериментов. Хотел бы уточнить некоторые моменты, которые не удалось сразу понять из документации:

1. Правильно я понял, что минутные свечи как по российским, так и по иностранным акциям отдаются в реальном времени, с задержкой не более 1-2 минут? Если да, то почему это бесплатно, учитывая, что аналогичная услуга у мосбиржи платная? Предусмотрены ли сейчас или в будущем какие-то скрытые или явные платежи за использование API клиентом Тинькофф Инвестиции? 

2. Данные отдаются во время премаркета и постмаркета?

3. В документации видел ограничения 120 запросов в минуту для REST-версии API. Если нужно получать данные в реальном времени более чем за 120 активов, я могу воспользоваться streaming-версией и получать свечи раз в минуту более чем для 120 активов по одному соединению без ограничений? 

4. Наверняка есть органичения на распространение и коммерческое использование данных? Сейчас для меня это неактуально, но просто интересно для общего понимания (например для получения данных от мосбиржи нужно подтвердить оферту, и там явно указаны эти ограничения, а также цена за коммерческое использование данных с биржи)

5.  Правильно ли я понял, что для российских акций данные берутся с мосбиржи, а для иностранных с СПБ-биржи? (здесь в issues уже про это писали, просто уточняю, не изменилось ли)

6. Есть ли какие-то ещё органичения на постояное использование API физическим лицом в объёме на уровне десятков запросов в /market/candles в минуту (или получение этих данных через streaming)?

**Comment by AlexanderVolkovTCS** [comment]
Добрый вечер,
1. Да, задержка небольшая. Услуга бесплатна. В будущем возможно введение тарифов с дополнительными лимитами запросов. Скрытых платежей нет.
2. Если Вы имеете ввиду внебиржевую торговлю - то она пока не поддерживается. Исторические данные можно получать в режиме 24/7.
3. Да, ограничение в стриминге есть только на количество одновременных подключений - 6
4. Да, ограничения есть и изложены в https://www.tinkoff.ru/invest/disclaimers/basic-information/
5. Верно
6. Дополнительных ограничений нет, но в стриминге необходимо помнить - если не успевать забирать данные из вебсокета, то возможен разрыв соединения со стороны сервера.

**Comment by FedorSymkin** [comment]
Спасибо. 

Насчёт п.2 имею ввиду дополнительные вечерние торги некоторыми активами после завершения основного рабочего времени биржи или перед её открытием утром. Сейчас проверил - да, в этот период данные отдаются.
