### ISSUE TITLE
Получение снапшота котировок сразу по всем акциям -- одним запросом

### ISSUE THREAD

**Issue by gikeberyfinn** [TinkoffCreditSystems/invest-openapi#465]
Привет!

Экстремально нужен запрос возвращающий реал-тайм котировки с СПб биржи сразу по всем акциям. Лучший бид, аск и цена последней сделки для всех акций сразу.

И с лимитами ограничениями тоже надо что-то делать -- очень тяжко работать. Очень прошу сделайте платные тарифы с кратно увеличенными лимитами.

**Comment by nrukavkov** [comment]
Тут люди годами ждут. Экстремально не получится =)

**Comment by gikeberyfinn** [comment]
> Тут люди годами ждут. Экстремально не получится =)
Я понимал под этим важность, а не скорость. Хотя не вижу проблемы сделать нормальные платные тарифы и реализовать эти пустяковые вещи.

**Comment by AlexanderVolkovTCS** [comment]
#41
