### ISSUE TITLE
Работа с отрицательными позициями в песочнице

### ISSUE THREAD

**Issue by alexushub** [TinkoffCreditSystems/invest-openapi#468]
Здравствуйте.
Есть ли возможность в песочнице эмулировать продажу в шорт?
На данный момент если пытаюсь продать позицию, которой нет на счете, то получаю ошибку, что недостаточно средств.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, пока такой возможности нет

**Comment by alexushub** [comment]
А в работе с реальным АПИ шорт открывать есть возможность?

**Comment by AlexanderVolkovTCS** [comment]
Да
