### ISSUE TITLE
Отличия ответа

### ISSUE THREAD

**Issue by ZergsLaw** [TinkoffCreditSystems/invest-openapi#47]
В rest и stream json объектах отличаются json тегами

В rest везде camelCase
в stream везде snake_case

Это создает безумное колличество неудобств, при написании кастомных SDK

**Comment by zevis** [comment]
Как разработчик разработчику - лучше продублировать и изолировать свой код от объектов, приходящих из АПИ, просто как минимум это не первые нюансы, а твой бизнес-код должен стабильно переживать новые версии апи и, как максимум, твой код может не только это апи использовать. Этот коммент никак не оправдывает неудобство)

**Comment by ZergsLaw** [comment]
Я ни капли не отрицаю этого, и в итоге так и сделал, разбил на два независимых куска

Но извиняюсь конечно, но это как минимум "странно", когда нам одна API возвращает один и тот же объект с разными json именами

**Comment by NikitaMelnikov** [comment]
@ZergsLaw я с вами согласен, обсудим варианты переезда стриминга на camelCase

**Comment by ZergsLaw** [comment]
Есть ориентировачная дата переезда?

**Comment by NikitaMelnikov** [comment]
Пока нет

**Comment by NikitaMelnikov** [comment]
Пока что не будем делать
