### ISSUE TITLE
Аналитик в Тинькове с уведомлениями

### ISSUE THREAD

**Issue by metvel** [TinkoffCreditSystems/invest-openapi#470]
В общем, вопрос такой:
Всем кулпрограммерам респект.
Можно ли подключить к приложению Тинькофф аналитика, который может отправлять уведомления в приложении, и добавлять акции в избранное. Который будет искать акции по изменению котировок в течении короткого периода, которого нет в скриннере (в скриннере минимум день).
Если что, у меня нет мозгов по  программированию, поэтому если можно попроще.

**Comment by AlexanderVolkovTCS** [comment]
Приветствую! Поддержки "избранного" в приложении через API пока не планируется, ровно как и отправки уведомлений.
