### ISSUE TITLE
Исполнение рыночных ордеров в Sandbox происходит не по рыночной цене

### ISSUE THREAD

**Issue by artemiysmekhov84** [TinkoffCreditSystems/invest-openapi#473]
При покупке американских акций в Sandbox'е с баланса списывается 100 долларов за каждый лот, вне зависимости от реальной стоимости. Проблему обнаружил, используя неофициальную Python библиотеку, но потом перепроверил через 
Swagger и получил тот же результат.

---
Порядок действий:

1. Очистил портфель, выполнив /sandbox/clear.

2. Пополнил баланс на 1000 USD, выполнив /sandbox/currencies/balance с параметром {"currency": "USD", "balance": 1000}.

3. Запросил портфель, выполнив /portfolio. Получил в ответе:
```
{
  "trackingId": "a08176e39e366077",
  "payload": {
    "positions": [
      {
        "figi": "BBG0013HGFT4",
        "ticker": "USD000UTSTOM",
        "instrumentType": "Currency",
        "balance": 1000,
        "blocked": 0,
        "lots": 1,
        "name": "Доллар США"
      }
    ]
  },
  "status": "Ok"
}
```

4. Купил 1 акцию MSFT (примерная рыночная цена $231), выполнив /orders/market-order с параметром {"lots": 1, "operation": "Buy"}.

5. Запросил портфель, выполнив /portfolio. Получил в ответе:
```
{
  "trackingId": "496f55e05705ced5",
  "payload": {
    "positions": [
      {
        "figi": "BBG000BPH459",
        "ticker": "MSFT",
        "isin": "US5949181045",
        "instrumentType": "Stock",
        "balance": 1,
        "blocked": 0,
        "lots": 1,
        "name": "Microsoft Corporation"
      },
      {
        "figi": "BBG0013HGFT4",
        "ticker": "USD000UTSTOM",
        "instrumentType": "Currency",
        "balance": 900,
        "blocked": 0,
        "lots": 0,
        "name": "Доллар США"
      }
    ]
  },
  "status": "Ok"
}
```
---

Кроме неправильного баланса, для активов не возвращается средняя цена и текущий P/L.

**Comment by AlexanderVolkovTCS** [comment]
Верно, цена в песочнице не привязывается к рыночной цене бумаги, ордера исполняются для любой цены.
Соответственно средняя и PL не поддерживаются.
Предназначение песочницы - получить общее представление о работе API и проверить работу кода.
