### ISSUE TITLE
Получение новостей по бумаге через rest/streaming

### ISSUE THREAD

**Issue by nightphobos** [TinkoffCreditSystems/invest-openapi#474]
Подскажите, планируется ли добавить возможность получать через API, в идеале через streaming новости по бумаге, например как на этой странице - https://www.tinkoff.ru/invest/stocks/SBER/news/ ?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, в ближайшее время выгрузки новостей в API не планируется.
