### ISSUE TITLE
Задержка в пару минут при получении свечей с интервалом 1min через /openapi/market/candles

### ISSUE THREAD

**Issue by nonamegithub** [TinkoffCreditSystems/invest-openapi#475]
У меня одного последняя свеча, при использовании /openapi/market/candles c интервалом в 1min, двухминутной "свежести"?

**Comment by nonamegithub** [comment]
малость скорректирую: последняя возвращаемая свеча всегда за предыдущую минуту, то есть запрашивать чаще одного раза в минуту нет смысла?

**Comment by AlexanderVolkovTCS** [comment]
Да, запрашивать чаще раза в минуту смысла нет.
Кстати,  для получения последних свечей лучше использовать стрим.
