### ISSUE TITLE
Как можно получить данные о балансе всех валют в портфеле? 

### ISSUE THREAD

**Issue by Izbrodin** [TinkoffCreditSystems/invest-openapi#476]
Запрос "https://api-invest.tinkoff.ru/openapi/portfolio/" на данный момент возвращает только 2 валюты в массиве positions: 

тикеры: "EUR_RUB__TOM" и "USD000UTSTOM"

Получается, что нельзя полностью получить все активы из портфеля? Только доллары и евро?
Возможно, в openapi есть ещё незадокументированный запрос для получения этих данных?

**Comment by ddmrtc** [comment]
GET /portfolio/currencies
Получение валютных активов клиента



вс, 14 мар. 2021 г. в 22:11, Mikhail Izbrodin ***@***.***>:

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, пока только доллары и евро, да.
