### ISSUE TITLE
Отложенные заявки.

### ISSUE THREAD

**Issue by DeadMorose777** [TinkoffCreditSystems/invest-openapi#477]
Здравствуйте! 
Пытался некоторое время реализовать через ваш API отложенные заявки: стоп лосс, тейк профит, трейлер стоп и другие. Вышло весьма костыльно и не удобно. Будут ли они добавлены в ближайшее время? 
Просто вместо того, чтобы писать непосредственно стратегии и роботов, приходиться тратить время на разработку и поддержку сервисов, которые как бы уже должны быть даны брокером. 
К тому же из за крайне низких ограничений на запросы не выходит написать что либо стабильно работающее в критических ситуациях(когда приходит большое количество операций в секунду). Лимиты тают на глазах, а после робот упирается в них и просто отваливается. 
Планируется ли увеличивать лимиты до вменяемых? 
Очень бы не хотелось переводить деньги на других брокеров, у них все слишком не удобно и дорого, по мимо API. 
И если все таки эти фичи планируются, то когда примерно они будут реализованы? Понимаю что к моменту выхода API v2.0 , но хотелось бы какую нибудь хотя бы примерную дату. Хотя бы год)

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, повышение лимитов планируется в ближайшее время, SL\TP будет реализовано позже.
>Хотя бы год)

Год могу назвать уверенно. Этот. =)
