### ISSUE TITLE
orderID 

### ISSUE THREAD

**Issue by chkyratov** [TinkoffCreditSystems/invest-openapi#479]
привет!!! нужна помощь!
при выставлении маркет ордера:
client.orders.orders_market_order_post(figi=figis, market_order_request=body).payload.order_id
прилетает order_id(формата 220459299920), а при закрытии ордера через:
client.orders.orders_cancel_post(order_id=order_id)
выдаёт ошибку Cannot find order by id 220459299920

как мне найти корректный order_id для закрытия позиции?

**Comment by tumb1er** [comment]
Рыночную заявку на практике отменить невозможно, потому что она исполняется, считай, мгновенно.

**Comment by chkyratov** [comment]
Видимо я не так выразился, как мне закрыть сделку по бумаге и по рыночной цене, код выше вроде как может но ид не верное?

**Comment by tumb1er** [comment]
Вы выставляете заявку на покупку по рыночной цене.
Заявка тут же исполняется по рыночной цене и вследствие этого исчезает из списка активных заявок.
Вы пробуете отменить заявку, но в списке висящих заявок ее нет, поэтому ответ - cannot find order by id.

**Comment by chkyratov** [comment]
С этим теперь понятно спасибо, так как продать купленную акцию, в  openapi python что то не нашел вариантов кроме того что написан выше, а он требует id, подскажите код или где почитать?

**Comment by tumb1er** [comment]
Поставить заявку на продажу а не на покупку, хотя бы через orders_market_order_post

**Comment by chkyratov** [comment]
Это же покупка, как правильно запрос на продажу написать? Извиняюсь за свою глупость.

**Comment by tumb1er** [comment]
Заменить в теле Buy на Sell

**Comment by chkyratov** [comment]
Так просто? Серьёзно? Капец я конечно. Спасибо громадное
