### ISSUE TITLE
Вопрос о работе Stream

### ISSUE THREAD

**Issue by ZergsLaw** [TinkoffCreditSystems/invest-openapi#48]
Я верно понимаю, что stream должен работать по типу:

1)Подписался на обновление, к примеру, candle
2)Мне непрерывно должно идти поток 

Верно? Так как на данный момент ощущение, что идет "имитация" rest, когда устанавливаем соединение и через него один запрос с одним ответом идет 

Или так и должно быть?

**Comment by NikitaMelnikov** [comment]
Привет,

> Верно? Так как на данный момент ощущение, что идет "имитация" rest, когда устанавливаем соединение и через него один запрос с одним ответом идет

А могли бы пример логами привести?

**Comment by ZergsLaw** [comment]
Запрос: 
{"event":"candle:subscribe","figi":"BBG000BTNGZ4","interval":"hour"}


Ответ: 
{"event":"candle","payload":{"o":74.19,"c":74.19,"h":74.19,"l":74.19,"v":13935,"time":"2019-11-05T21:00:00Z","interval":"hour","figi":"BBG000BTNGZ4"}}
2019/11/06 13:09:16 [123 34 111 34 58 55 52 46 49 57 44 34 99 34 58 55 52 46 49 57 44 34 104 34 58 55 52 46 49 57 44 34 108 34 58 55 52 46 49 57 44 34 118 34 58 49 51 57 51 53 44 34 116 105 109 101 34 58 34 50 48 49 57 45 49 49 45 48 53 84 50 49 58 48 48 58 48 48 90 34 44 34 105 110 116 101 114 118 97 108 34 58 34 104 111 117 114 34 44 34 102 105 103 105 34 58 34 66 66 71 48 48 48 66 84 78 71 90 52 34 125]
И ответ прилетает лишь один раз

Меня просто ввело в ступор название метода, а именно "subscribe", так как я ожидал, что мне в потоке будут присылаться постоянные изменения, или же всё верно и так и должно быть? Один запрос и лишь один ответ?

**Comment by fxrlv** [comment]
попробуй интервал меньше (1-5min)
сразу после подписки присылается последняя цена, потом, в зависимости от интервала, при изменении цены присылается новое сообщение с новой ценой

**Comment by ZergsLaw** [comment]
{"event":"candle:subscribe","figi":"BBG000BTNGZ4","interval":"1min"} 

Прошло уже почти 10 минут 

Ответ точно также лишь один, ЛИБО , я супер удачно подобрал figi, что никак не меняется цена у него :( 

Можете подсказать какую либо из ценных бумаг, которая часто меняет цену?

**Comment by NikitaMelnikov** [comment]
А вы пин-понгами обмениваетесь в стримах? Была похожая проблема в другом вопросе по стримам, к сожалению сейчас не смогу найти

**Comment by ZergsLaw** [comment]
Вот если я начну делать этот запрос в "цикле", то да, мне стрим будет отвечать непрерывно
Но тогда зачем тут нужен вообще стрим и почему он называется subscribe? То есть это буквально превращается в подобие rest, когда нужно непрерывно делать запросы, чтобы получать ответы на них

**Comment by NikitaMelnikov** [comment]
В цикле делать не нужно, ваш вебсокет клиент должен в фоне обмениваться сообщениями ping-pong для поддержки активного соединения.

Можете показать код для подключения и работы с стримом?

**Comment by ZergsLaw** [comment]
Ты не понял, сейчас я просто подключаюсь и жду сообщений, время от времени отправляя запросы

НО, названия subscribe подразумевает, что я должен сделать ОДИН запрос и получать непрерывно обновления, что совершенно не происходит, то есть либо название вводит в заблуждение, либо оно не правильно работает с вашей стороны, так как если вы сейчас скажете, что нужно общаться посредством пинг-понг, то окей, реализую таким образом, но тогда я не понимаю, почему метод называется subscribe

**Comment by ZergsLaw** [comment]
То есть делая subscribe на candle, я ожидаю, что отправлю ему свои параметры и дальше в сокете непрерывно буду получать изменения этой позиции, да хоть что-то, но на один запрос приходит исключительно один ответ, в этой же ситуации и встает вопрос, зачем тогда тут сокеты, если нужно общаться исключительно пинг-понгом?

**Comment by fxrlv** [comment]
пинг-понг [(RFC6455)](https://tools.ietf.org/html/rfc6455#section-5.5.2) нужен чтобы поддерживать коннект в живом состоянии
сейчас все работает как и ожидается методу "subscribe" – подключаемся по вебсокету к брокеру, делаем запрос на подписку, дальше запускаем цикл чтения сообщений из вебсокета
проверьте, что не возвращается сообщение об ошибке

**Comment by ZergsLaw** [comment]
2019/11/06 13:23:06 {"event":"candle:subscribe","figi":"BBG000BTNGZ4","interval":"1min"}
2019/11/06 13:23:06 {"event":"candle","payload":{"o":74.19,"c":74.19,"h":74.19,"l":74.19,"v":13935,"time":"2019-11-05T21:00:00Z","interval":"1min","figi":"BBG000BTNGZ4"}}
2019/11/06 13:23:06 [123 34 111 34 58 55 52 46 49 57 44 34 99 34 58 55 52 46 49 57 44 34 104 34 58 55 52 46 49 57 44 34 108 34 58 55 52 46 49 57 44 34 118 34 58 49 51 57 51 53 44 34 116 105 109 101 34 58 34 50 48 49 57 45 49 49 45 48 53 84 50 49 58 48 48 58 48 48 90 34 44 34 105 110 116 101 114 118 97 108 34 58 34 49 109 105 110 34 44 34 102 105 103 105 34 58 34 66 66 71 48 48 48 66 84 78 71 90 52 34 125]

Коннект держался с половины второго, в итоге он оборвался уже сам, как раз из-за того, что ты описал
2019/11/06 14:45:52 websocket: close 1006 (abnormal closure): unexpected EOF

**Comment by ZergsLaw** [comment]
То есть данный на подписку прилетают только один раз, я попробовал с 3 figi, везде один результат

Есть вероятность, что я супер везучий и подобрал попросту те инструменты, что не менялись на рынке, но тогда можете подсказать тот, который активно меняется, чтобы проверить работоспособность стримов?

**Comment by fxrlv** [comment]
попробуйте этот простой пример их [документации](https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/)
```
package main

import (
    "flag"
    "log"
    "net/http"

    "github.com/gorilla/websocket"
)

var addr = flag.String("addr", "wss://api-invest.tinkoff.ru/openapi/md/v1/md-openapi/ws", "http service address")
var token = flag.String("token", "", "API token")

func main() {
    flag.Parse()

    c, _, err := websocket.DefaultDialer.Dial(*addr, http.Header{"Authorization": {"Bearer " + *token}})
    if err != nil {
        log.Fatal("dial:", err)
    }
    defer c.Close()

    go func() {
        for {
            _, message, err := c.ReadMessage()
            if err != nil {
                log.Println("read: ", err)
                return
            }
            log.Printf("recv: %s\n", message)
        }
    }()

    const sub = `{"event": "orderbook:subscribe", "figi": "BBG004731354", "depth": 10}`
    err = c.WriteMessage(websocket.TextMessage, []byte(sub))
    if err != nil {
        log.Println("write: ", err)
        return
    }

    select {}
}
```

**Comment by ZergsLaw** [comment]
На удивление оказалось, что я действительно очень плохо подобрал figi
так как встави ваш, подписка работает корректно 0_о

**Comment by ZergsLaw** [comment]
Нашел проблему:

 {"event":"candle:subscribe","figi":"BBG000BTNGZ4","interval":"1min"}
 {"event": "candle:subscribe", "figi": "BBG004731354", "interval": "1min"}


Оба json валидный, один написан руками (нижний), второй генерится
