### ISSUE TITLE
Roadmap проекта 🗺️ ❓ 

### ISSUE THREAD

**Issue by olsh** [TinkoffCreditSystems/invest-openapi#480]
Было бы неплохо понимать состояние проекта в целом.
Последний релиз был больше года назад и со стороны выглядит что API заброшен. 🤔 

Может быть использовать [milestones](https://github.com/TinkoffCreditSystems/invest-openapi/milestones), например, или хотя бы описать Roadmap в wiki?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, openAPI годовой давности работает, сейчас идет разработка v2, по срокам мы не ориентируем, milestones / roadmap-ы писать на данном этапе смысла нет, после релиза - да, заведем публичные вехи по дальнейшим доработкам.
