### ISSUE TITLE
Роли для токена (чтение/создание заявок)

### ISSUE THREAD

**Issue by qwertymypass** [TinkoffCreditSystems/invest-openapi#482]
Есть ли возможность добавить для токена роли, чтобы по токену можно было например только делать `get` запросы, которые не инициируют никаких экшенов, было бы намного удобнее, я знаю, что можно включить смс подтверждение и тогда заявки не будут создаваться, как понимаю, но это костыль, ведь я допустим хочу создавать заявки без смс подтверждения (через приложение), но не хочу давать возможность их размещать через апи

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, учтено в #12
