### ISSUE TITLE
Как открыть отложенный ордер TakeProfit

### ISSUE THREAD

**Issue by apa88** [TinkoffCreditSystems/invest-openapi#484]
Хочу открыть отложенный ордер и забыть про сделку до выполнения TakeProfit либо StopLoss'а.
Думал, что можно TakeProfit реализовать через лимитные ордера, но там есть ограничения по цене лимитника относительно текущей цены и времени (нет бессрочных лимитников).
Как кто решает эту проблему?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, пока TakeProfit/StopLoss нет, единственный вариант решения - смотреть близость рыночной цены к желаемой и каждый день переоткрывать позиции.
