### ISSUE TITLE
Как проверить, торгуется ли инструмент в данный момент? 

### ISSUE THREAD

**Issue by DeadMorose777** [TinkoffCreditSystems/invest-openapi#485]
Заголовка достаточно?) 
К примеру MNK уже не торгуется по факту, но подписаться на неё все еще можно. А следовательно, если алгоритм посчитает покупку не торгуемого инструмента хорошим действием, и попробует купить, то ему вернется ошибка:

tinvest.exceptions.UnexpectedError: 500 {"trackingId":"ed8852be58cc1aa8","payload":{"message":"Instrument is disabled for trading","code":"INSTRUMENT_ERROR"},"status":"Error"}

Хотелось бы как нибудь заранее знать, что торгуется а что нет.  
Такая возможность есть? А если нет, то будет ли?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, рекомендуемый способ проверки - сравнивать trade_status в подписке instrumentInfo (https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/) на normal_trading

**Comment by DeadMorose777** [comment]
> Добрый день, рекомендуемый способ проверки - сравнивать trade_status в подписке instrumentInfo (https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/) на normal_trading

Благодарю)

**Comment by DeadMorose777** [comment]
> Добрый день, рекомендуемый способ проверки - сравнивать trade_status в подписке instrumentInfo (https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/) на normal_trading

Проверил через этот метод чек статуса у MNK, и в ответ выводиться что "normal status". 
Хотя очевидно, что оно больше не торгуется. 

`async def get_trade_status(streaming_factory: StreamingFactory, figi) -> tinvest.TradeStatus:
    async with streaming_factory.get_streaming() as streaming:
        await streaming.instrument_info.subscribe(figi)
        instrument_info = None
        async for event in streaming:
            if event.event == tinvest.Event.instrument_info:
                instrument_info = event
                break
            else:
                raise Exception("Strange event")
    return instrument_info.payload.trade_status`

`    logging.debug("%s", await get_trade_status(streaming_factory, "BBG002BHBHM1") )
`
