### ISSUE TITLE
Интервал 4 часа

### ISSUE THREAD

**Issue by Dimantchick** [TinkoffCreditSystems/invest-openapi#487]
Использую javaAPI.
Если правильно понимаю, оно генерирует классы по Swagger.
Насколько мне известно, популярны интервалы 1, 5, 15, 30 минут, 1, 4 часа, день и т.д.
Есть какая-то причина исключения интервала 4 часа?
Я могу поправить руками себе? (Хотя апи на то и апи, чтобы туда не лезть.)
В https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/swagger.yaml имеем интервалы:
CandleResolution:
      description: |
        Интервал свечи и допустимый промежуток запроса:
        - 1min [1 minute, 1 day]
        - 2min [2 minutes, 1 day]
        - 3min [3 minutes, 1 day]
        - 5min [5 minutes, 1 day]
        - 10min [10 minutes, 1 day]
        - 15min [15 minutes, 1 day]
        - 30min [30 minutes, 1 day]
        - hour [1 hour, 7 days]
        - day [1 day, 1 year]
        - week [7 days, 2 years]
        - month [1 month, 10 years]
      type: string
      enum:
        - 1min
        - 2min
        - 3min
        - 5min
        - 10min
        - 15min
        - 30min
        - hour
        - day
        - week
        - month

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, 
>Я могу поправить руками себе?

не надо так, 4hour пока поддерживаться не будет. Рекомендую закачивать и обрабатывать часовые периоды.
