### ISSUE TITLE
Можно ли узнать, доступна ли акция в шорт? 

### ISSUE THREAD

**Issue by DeadMorose777** [TinkoffCreditSystems/invest-openapi#488]
Вопрос в шапке я думаю ясен?) 
Нашел похожий пост полу годичной давности, который вроде бы открыт. Но вдруг за это время появилась подобная возможность. 
Если же её нет, то в каких временных перспективах  она может появится? 

И может у кого нибудь есть "костыль" для решения этой проблема? 
Я пока что думаю что возможны только 2 вариант: 
1) Попытаться разместить лимитную заявку значительно выше рыночной цены, а потом её убрать, в случае если она разместилась. От детектить ошибку, и от неё дальше плясать в логике.
2) Попытаться написать какой либо костыль, к примеру парсить терминал на JS, и смотреть что там отображается. Что так то не маленькая работа.

**Comment by mlshvdv** [comment]
В API пока никак не узнать.

Но можете костыльно узнать.

Открываете https://www.tinkoff.ru/invest/stocks?country=All&orderType=Asc&sortType=ByName, затем смотрите в консоль браузера, изучаете лог запросов и внимательно ищете в ответах то, что вам нужно.

**Comment by AlexanderVolkovTCS** [comment]
Верно, пока никак.
Сроки мы не сообщаем.
Метод @mlshvdv пока работает, но это не публичный API и мы не гарантируем его работоспособность в будущем.
