### ISSUE TITLE
Отсутствует информация по тикеру RU000A102TR4

### ISSUE THREAD

**Issue by rainlabs** [TinkoffCreditSystems/invest-openapi#491]
Запрос к open api `market/search/by-ticker?ticker=RU000A102TR4` вернет пустой массив `instruments`, хотя запрос `https://api-invest.tinkoff.ru/trading/bonds/get?ticker=RU000A102TR4` выполняется корректно

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, все доступные для API облигации возвращаются методом /market/bonds,
а https://api-invest.tinkoff.ru  не относится к публичному API и ориентироваться на него не стоит.

**Comment by AlexanderVolkovTCS** [comment]
Конкретно бумагу RU000A102TR4 - добавили к доступным в опенАПИ.
