### ISSUE TITLE
Получить актуальный портфель в разрезе операций

### ISSUE THREAD

**Issue by rusnasonov** [TinkoffCreditSystems/invest-openapi#494]
Сейчас через `/portfolio` можно получить только общее количество количество позиций (Balance) по инструменту и среднюю цену (AveragePositionPrice), получается что данные агрегированы по инструменту.

```
Name: Apple
Balance: 3
AveragePositionPrice: 127.14
```

Было бы удобно получать текущий портфель, но в виде списка позиций,  когда, и сколько было куплено

```
Name: Apple
Quantity: 1
Date:  2020-01-01
Price: 90.01

Name: Apple
Quantity: 2
Date:  2021-03-02
Price: 127.14
```

В теории конечно можно собрать текущий портфель через `/operations`,  но нужно будет каждый раз выгребать все операции.

**Comment by AlexanderVolkovTCS** [comment]
Метод портфолио нужен для возврата актуального балансового списка позиций, а не списка сделок.
Именно поэтому возвращается FIFO AveragePositionPrice, а если Вам надо собственные метрики - то используйте операции, к томе же там есть фильтр по идентификатору инструмента figi
