### ISSUE TITLE
Тинькофф банк выпуск 1 пропала из выдачи

### ISSUE THREAD

**Issue by EJohnF** [TinkoffCreditSystems/invest-openapi#497]
Облигация 
тикер - RU000A0JXQ85
figi - BBG00GKHR834

Не возвращаются операции по ней, не находиться через прямой поиск по тикеру/figi , и нет в списке /bonds 

Хотя она существуется и в обращении ещё год! 
Несколько дней назад всё приходило нормально по ней.

**Comment by AlexanderVolkovTCS** [comment]
Бумагу вернули в список инструментов openAPI, но покупка бумаги уже запрещена
