### ISSUE TITLE
Не приходят бумаги из расширенного списка

### ISSUE THREAD

**Issue by EJohnF** [TinkoffCreditSystems/invest-openapi#499]
Здравствуйте. 
На аккаунте подключён премиум тариф и подтверждён статус квала.
Но ни в списках акций/облигаций, ни в операциях бумаги из расширенного списка не приходят. 

В частности важно иметь возможность отслеживать ВСЕ операции по счёту, в том числе и премиум бумаги. 
Например CQQQ & SHYG

Когда они могут появиться в операциях получаемых по openapi?

**Comment by AlexanderVolkovTCS** [comment]
На данный момент внебиржевые инструменты не поддерживаются, в будущем будут. Сроки не называем.
