### ISSUE TITLE
Получение нескольких стаканов в одном запросе

### ISSUE THREAD

**Issue by iggor-python** [TinkoffCreditSystems/invest-openapi#503]
Здравствуйте, могу ли я в одном запросе получить стаканы по нескольким компаниям? Если нет, планируете ли добавить эту функцию?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, одним REST запросом нельзя получить стаканы по нескольким бумагам, однако вы можете подписаться сразу на несколько компаний и оперативно получать обновления стакана в режиме stream:  https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/
