### ISSUE TITLE
Неправильное время свечи для дневного интервала

### ISSUE THREAD

**Issue by Dazlonar** [TinkoffCreditSystems/invest-openapi#504]
При получении свечи дневного интервала через _REST_, указано время **4:00:00 UTC**, а через _streaming_ протокол,  приходит **7:00:00 UTC** что является правильным временем, т.к. инструмент не торгуется на утренней сессии. (Проверял на _BBG000C43RR5_)

Посмотрел интервалы меньше дневного для _REST_, там время начала торгов правильное 7:00:00, получается для дневных появляется данная проблема, для интервалов больше дневного не смотрел.

**Comment by Dazlonar** [comment]
_Обновил описание, изначально подумал что в streaming не правильное время, потом понял что наоборот_

**Comment by AlexanderVolkovTCS** [comment]
Для дневных и более интервалов рекомендуем игнорировать время внутри дня и смотреть только на дату

**Comment by Dazlonar** [comment]
Попробую так, но это не очень удобно. Все таки приятно когда код работает одинаково, независимо от интервалов и прочего, а тут придется городить доп проверки, т.к. только в этом случае данные отличаются.
