### ISSUE TITLE
Данные в терминале не соответствуют данным из TinkoffAPI

### ISSUE THREAD

**Issue by OdCheban** [TinkoffCreditSystems/invest-openapi#506]
COIN 19.05 20:41 цена закрытия в TinkoffAPI не соответствует цене закрытия в терминале
![Безымянный](https://user-images.githubusercontent.com/29703030/118865486-a92b2580-b8e9-11eb-9d9e-dfb42794ca53.png)

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, не вижу расхождений с [ответом ](https://api-invest.tinkoff.ru/openapi/market/candles?figi=BBG00ZGF7771&from=2021-05-19T20%3A41%3A00.000000%2B03%3A00&to=2021-05-19T20%3A42%3A00.000000%2B03%3A00&interval=1min)openAPI:

"payload": {
    "candles": [
      {
        "o": 224.49,
        "c": 223.86,
        "h": 224.5,
        "l": 223.86,
        "v": 1479,
        "time": "2021-05-19T17:41:00Z",
        "interval": "1min",
        "figi": "BBG00ZGF7771"
      }
    ],
    "interval": "1min",
    "figi": "BBG00ZGF7771"

Прошу переоткрыть тикет, приложив запрос openAPI, если проблема актуальна.

**Comment by AlexanderVolkovTCS** [comment]
Не могу сказать, с нашей стороны проблем не видно.

**Comment by OdCheban** [comment]
Хорошо, спасибо за ответ.
