### ISSUE TITLE
TSPV Instrument is disabled for trading

### ISSUE THREAD

**Issue by rame0** [TinkoffCreditSystems/invest-openapi#507]
Здравствуйте, пытаюсь тестировать бота на TSPV.
Получаю ответ "Instrument is disabled for trading"
В списке исключений (https://tinkoffcreditsystems.github.io/invest-openapi/) его нет.

Инструмент исключен из торговли или у меня что то работает не так?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, да, спасибо, обновили https://tinkoffcreditsystems.github.io/invest-openapi/
