### ISSUE TITLE
Как получить значения индикаторов?

### ISSUE THREAD

**Issue by masterandru** [TinkoffCreditSystems/invest-openapi#508]
Добрый день.

Подскажите пожалуйста как получить значения индикаторов.
В частности интересует RSI.

Искал в инструментах MarketContext(а) и прочих контекстах.
`openApiClient.getMarketContext().searchMarketInstrumentsByTicker("CRSI")`
Но увы.

**Comment by mlshvdv** [comment]
@masterandru вам нужно:

1. Получить исторические данные по инструменту за нужный вам отрезок с нужным вам интервалом (1 мин, 1 час, 1 день и так далее) из Open API;
2. Найти библиотеку для расчета показателей технических индикаторов на нужном для вас языке программирования;
3. Скормить библиотеке исторические данные и получить результат расчета;

**Comment by masterandru** [comment]
Спасибо вам за оперативный и развернутый ответ.
Поищу библиотеку.

**Comment by AlexanderVolkovTCS** [comment]
Спасибо за ответ @masterandru, все верно, индикаторы надо строить самостоятельно
