### ISSUE TITLE
неверный статус операции (status=done, payment=0)

### ISSUE THREAD

**Issue by fxpester** [TinkoffCreditSystems/invest-openapi#509]
1) при исполнении заявки ее статус в /operations переходит в done но расчеты не отображаются, т.е. payment=0
в мобильном приложении в этот момент заявка в статусе "обрабатывается"

кажется что в этот момент заявка должна быть в статусе "processing" и в openapi ?

**Comment by AlexanderVolkovTCS** [comment]
Если в мобилке статус "обрабатывается", то и в openapi должен быть Progress.
Уточните, это локальная разовая проблема или наблюдалась систематически?
Есть ли trades в ответе? Если есть возможность, укажите целиком json ответа от /operations

**Comment by fxpester** [comment]
наблюдалось все утро с множеством операций, сейчас уже все "пропроцессилось"

пример: 
```
{
  "trackingId": "d9704081286d6e14",
  "payload": {
    "operations": [
      {
        "operationType": "Buy",
        "date": "2021-05-24T11:32:14.133421+03:00",
        "isMarginCall": false,
        "instrumentType": "Stock",
        "figi": "BBG000T88BN2",
        "quantity": 3,
        "quantityExecuted": 3,
        "price": 0,
        "payment": 0,
        "currency": "USD",
        "trades": [
          {
            "tradeId": "4479972330",
            "date": "2021-05-24T12:29:25.111802+03:00",
            "quantity": 3,
            "price": 64.43
          }
        ],
        "status": "Done",
        "id": "251324365810"
      },
```

**Comment by AlexanderVolkovTCS** [comment]
Тогда это локальная сегодняшняя проблема -  были инциденты с задержками.
