### ISSUE TITLE
Стоимость акции не из портфеля

### ISSUE THREAD

**Issue by BorodachevPavel** [TinkoffCreditSystems/invest-openapi#512]
Каким методом можно узнать стоимость акции, которой нет в моем портфеле?

**Comment by AlexanderVolkovTCS** [comment]
Здравствуйте, узнать текущий курс можно, например, получив close в последней свече методом get_market_candles: https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_candles
