### ISSUE TITLE
Missing minQuantity field in server reply for https://api-invest.tinkoff.ru/openapi/market/stocks request

### ISSUE THREAD

**Issue by al-martyn1** [TinkoffCreditSystems/invest-openapi#513]
Reply looks like this:

    {"trackingId":"c793dd5622ac467e","payload":{"instruments":[{"figi":"BBG000HLJ7M4","ticker":"IDCC","isin":"US45867G1013","minPriceIncrement":0.01,"lot":1,"currency":"USD","name":"InterDigItal Inc","type":"Stock"},{"figi":"BBG000BDSLD7","ticker":"SAP","isin":"US8030542042","minPriceIncrement":0.01,"lot":1,"currency":"USD","name":"АДР SAP","type":"Stock"},{"figi":"BBG002293PJ4","ticker":"RH","isin":"US74967X1037","minPriceIncrement":0.01,"lot":1,"currency":"USD","name":"RH","type":"Stock"},{"figi":"BBG000CTQBF3","ticker":"SBUX","isin":"US8552441094","minPriceIncrement":0.01,"lot":1,"currency":"USD","name":"Starbucks Corporation","type":"Stock"},

**Comment by sergeymavrin** [comment]
minQuantity is not required field. You may switch from example value to schema in success response and follow red asterisks to view mandatory fields
