### ISSUE TITLE
неправильные данные для свечи day - close

### ISSUE THREAD

**Issue by jonny1960** [TinkoffCreditSystems/invest-openapi#514]
Здравствуйте.

На примере тикера SNGSP через API у вас
последняя часовая свеча [time] => 2021-05-27 23:00:00 [c] => 46.445
дневная свеча для того же дня 2021-05-27 [c] => 46.2

на tradingview закрытие [c] => 46.445

вы почему то считаете  закрытие дня не по последней свече?

**Comment by AlexanderVolkovTCS** [comment]
На свечах таймфреймом до дня ценой close является цена последней сделки в рамках этого периода, а в свечах ото дня - цена аукциона закрытия.
Есть задача привести котировки в консистентный вид.
