### ISSUE TITLE
Улучшение про среднюю по бумагам

### ISSUE THREAD

**Issue by sergeymavrin** [TinkoffCreditSystems/invest-openapi#516]
Очень хотелось бы в streaming для instrument_info получать события при изменении средней по бумаге, т.к. средняя рассчитывается с запаздыванием.
При покупке с нуля - поле со средней отсутствует, если сразу запросить инструменты в портфеле.
При усреднении или когда частичное исполнение ордера на продажу, когда бумага покупалась по разным ценам.

Сейчас приходится рассчитывать среднюю самому, что не очень удобно, а если периодически проверять портфель, то непонятно - уже пересчиталась средняя или ещё нет.

**Comment by AlexanderVolkovTCS** [comment]
Задача instrument_info  - транслировать котировочную информацию - лимиты цен и статус торговли инструментом.
Трансляции средней пока не планируется, но планируется стрим по операциям. Да, есть проблема с эпизодической задержкой расчета средней, поэтому сейчас мы алготрейдерам рекомендуем реализовать расчет средней самостоятельно.

**Comment by AlexanderVolkovTCS** [comment]
Для расчета средней нужно историю запрашивать через operations, в этом случае расхождения быть не должно.
