### ISSUE TITLE
Имена счетов

### ISSUE THREAD

**Issue by DaaGER** [TinkoffCreditSystems/invest-openapi#517]
Здравствуйте.
Может не туда смотрел, но имена счетов еще никак не получить?

**Comment by AlexanderVolkovTCS** [comment]
Да, возвращаются только тип и идентификатор.

**Comment by DaaGER** [comment]
Это есть в планах на какое-то обозримое будущее?

**Comment by AlexanderVolkovTCS** [comment]
В текущей версии не планируется, в следующей - будет
