### ISSUE TITLE
Разные interval у rest и streaming протоколов

### ISSUE THREAD

**Issue by ZaValera** [TinkoffCreditSystems/invest-openapi#518]
Два метода, который работают с идентичными сущностями, почему-то имеют разные типы поля interval.
Отличаются значениями 2hour и 4hour.
И не совсем понятно, почему в rest не принимает эти значения, хотя API, в который ходит клиент https://www.tinkoff.ru/invest-terminal, прекрасно с ними работает. Правда там другая апишка в принципе, но не суть.
Хочется единообразия

**Comment by Dazlonar** [comment]
От интервалов 2 и 4 часа в OpenAPI отказались, их лучше не использовать. 
Можете поискать в Closed Issues этот вопрос задавали уже не раз)
Вот пример: https://github.com/TinkoffCreditSystems/invest-openapi/issues/487

**Comment by ZaValera** [comment]
А есть планы, чтобы "отказались" стало явью?
Ведь они все еще присутствуют в документации https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/ и очевидно в коде.
Они все еще присутствуют в SDK https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk
И их присутствие вносит дополнительные трудности при типизации, так как типы поля `interval` у методов, которые ходят в rest и streaming получаются разными.

**Comment by AlexanderVolkovTCS** [comment]
>А есть планы, чтобы "отказались" стало явью?

Специально для совместимости типов удалять поддержку 2х и 4х часовых из стримов - планов нет, чтобы не нарушить совместимость уже написанного клиентского кода, но потребности в стриме таких свечей обычно не должна возникать.

А REST реализует 2х и 4х свечи через агрегаты от часовых, поэтому максимальный интервал запроса у этих периодов одинаковый и смысла в загрузке только 2х / 4х - тоже мало.

>И их присутствие вносит дополнительные трудности при типизации

Рекомендуем брать за основу interval от REST
