### ISSUE TITLE
Пустой ответ от wss://api-invest.tinkoff.ru/openapi/md/v1/md-openapi/ws (candle) для некоторых тикеров

### ISSUE THREAD

**Issue by kroton555** [TinkoffCreditSystems/invest-openapi#520]
Для некоторых тикеров получение свечи через сокет-соединение возвращает пустой ответ. Обычно это происходит, когда биржа закрыта, в выходные, но иногда и в открытое время в неосновную сессию. В основную (16:30 мск - 23:00 мск) этот баг не встречается.

Например сейчас, в 10:40 мск, возвращаются пустые свечи для VEEV и HCSG, для остальных тикеров (порядка 60, AAPL/ABT/ACN/AKNX/AKSP/TCS/ADBE/BMY/etc) все работает нормально.

В выходные, субботу и воскресенье, не возвращались свечи для AKNX, AKSP, VTBA, TCS

**Comment by kroton555** [comment]
Можете подсказать, как правильно получать текущую цену тикера с такими условиями:
1. Если эта акция сейчас торгуется - возвращать последнюю свечу/цену
2. Если не торгуется/биржа закрыта - возвращать свечу/цену закрытия предыдущего торгового дня
3. Если торугется, но еще не было ни одной сделки в эту сессию - как в п.2, возвращать цену закрытия предыдущего дня

Сейчас я делаю это через сокет-соединение, вот так (схематично) -
1. websocket->candleSubscribe();
2. response = websocket->receive();
3. candle = response->parse();
4. websocket->candleUnsibscibe();

В целом оно работает, но для некоторых тикеров на шаге 2 (response = websocket->receive()) ответ пустой. Если не закрывать соединение и в цикле несколько ответов получить, то для некоторых тикеров они все равно все пустые (я проверял для цикла с 10 итерациями)

Второй вариант получения последней цены - через REST-api, запросом /market/candles с интервалом в 1 мин. Но тут проблема, при открытом рынке цены менее точные, чем через сокет-соединение, а при закрытом рынке возвращаются пустые свечи. Т.е. нужно высчитывать, когда биржа открыта, это неудобно.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день,
>сокет-соединение возвращает пустой ответ
Стрим нужен, чтобы получать поток свечей в торговую сессию, когда есть активные сделки. В случае отсутствия сделок метод может возвращать пустой ответ.

>Если эта акция сейчас торгуется
То рекомендуется использовать стриминг свечей

>Если не торгуется/биржа закрыта
>Если торугется, но еще не было ни одной сделки в эту сессию
То рекомендуется брать цену закрытия у свечи за последнюю сессию.

В будущем будет реализован метод, возвращающий last price по группе инструментов.
