### ISSUE TITLE
Error executing HTTP request to Tariff module

### ISSUE THREAD

**Issue by sergeymavrin** [TinkoffCreditSystems/invest-openapi#522]
Подскажите что означает данная ошибка при выставлении лимитного ордера на продажу
Code: TariffModuleError, Message: Error executing HTTP request to Tariff module

**Comment by AlexanderVolkovTCS** [comment]
Это наша внутренняя ошибка, изредка бывает при инцидентах, скоро пройдет / уже прошла.
