### ISSUE TITLE
/operations перестали возвращать ранние события?

### ISSUE THREAD

**Issue by nleo** [TinkoffCreditSystems/invest-openapi#523]
У меня резко перестала правильно считаться реальная средняя. Ещё пару дней назад она была 10.10 и вдруг стала 9.81

По лотам тоже не бьётся, как будто я купил 518, продал 48, но держу сейчас при этом 670.

FOLD 10.24
buys: -5104.12 518
sells: 497.2 48
broker_commission -2.33
real_average 9.81
lots 670

В приложении на андройд также самая первая покупка от 2021-03-31 за 9.7 как и в апи. Хотя я помню, что входить в позицию начал где-то с 10.7. Т.е. затронуто и приложение и апи.

Приложение показывает среднюю 10.07. Моя реальная средняя полюбому должна быть больше, т.к. по FIFO я скидывал дорогие и приложение считает серднюю меньше чем она есть.

**Comment by ordyakov** [comment]
Возвращаются операции с 1 апреля 2021, хотя запрашиваю с более ранней даты

**Comment by AlexanderVolkovTCS** [comment]
Скоро коллеги поправят.

**Comment by nleo** [comment]
вроде работает

**Comment by ordyakov** [comment]
> вроде работает

еще меньше операций стало возвращаться
