### ISSUE TITLE
Не отображаются операции ранее апреля.

### ISSUE THREAD

**Issue by radostb** [TinkoffCreditSystems/invest-openapi#526]
Добрый день!
Перестали отображаться операции до апреля 2021 года.
Также нет данных о прибыли и выручке компаний (раньше все работало).

**Comment by kitMP** [comment]
Поделитесь, как вы получали данные о прибыли выручке?

**Comment by radostb** [comment]
Ошибся, данные о прибыли и выручке получал через апи yfinance
