### ISSUE TITLE
SPB по ночам просыпается

### ISSUE THREAD

**Issue by tumb1er** [TinkoffCreditSystems/invest-openapi#527]
Каждую ночь по иностранным акциям в районе 3 часов ночи открывается торговля.

2021-06-10 в 03:29:32 по INTC через WebSocket приходит что-то такое:
```
{
   "increment": 0.01,
   "limit_down": 0,
   "limit_up": 0,
   "lot": 1,
   "status": "normal_trading"
}
```
В 03:42:44 закрывается обратно:
```
{
   "increment": 0.01,
   "limit_down": 56.19,
   "limit_up": 57.79,
   "lot": 1,
   "status": "not_available_for_trading"
}
```

Откуда вот это берется? Бот просыпается и пытается что-то купить, получает свои 500-е и начинает мерзко пищать.

**Comment by polkila** [comment]
См. здесь https://github.com/TinkoffCreditSystems/invest-openapi/issues/461

**Comment by AlexanderVolkovTCS** [comment]
@polkila верно, спасибо, проверили, изменение статуса транслируется с биржи.
