### ISSUE TITLE
Для сервисных операций предоставлять ID

### ISSUE THREAD

**Issue by koshkoshka** [TinkoffCreditSystems/invest-openapi#53]
Хотелось бы уникальный ID для сервисной операции брокера. Сейчас даёт -1
Например, 
```
{
  operationType: 'PayIn',
  date: '2018-06-25T19:23:12+03:00',
  isMarginCall: false,
  quantity: 0,
  payment: 4.91,
  currency: 'USD',
  status: 'Done',
  id: '-1'
}
```

**Comment by NikitaMelnikov** [comment]
На сколько я помню, вопрос решили в почте?

**Comment by fdimok** [comment]
> На сколько я помню, вопрос решили в почте?

каково решение вопроса? тоже интересует ID в операциях, например при пополнении счета. Существует номер поручения или заявки для однозначной идентификации этой операции?

**Comment by NikitaMelnikov** [comment]
Скоро будет :)

**Comment by nonamegithub** [comment]
Ну наконец-то, сделали!

**Comment by NikitaMelnikov** [comment]
@nonamegithub "скоро" у нас понятие растяжимое :)
