### ISSUE TITLE
В /portfolio и /portfolio/currencies нет купленных валют кроме USD,EUR

### ISSUE THREAD

**Issue by BaryshevS** [TinkoffCreditSystems/invest-openapi#540]
В /portfolio и /portfolio/currencies нет купленных валют кроме USD,EUR

Не столь нужно выполнение ордеров, сколько просто выведите кол-во и среднюю цену.
Иначе суммарный баланс активов не сходится, как буд-то их просто нет.

**Comment by mlshvdv** [comment]
@BaryshevS https://tinkoffcreditsystems.github.io/invest-openapi/faq_marketdata/

**Comment by BaryshevS** [comment]
Да это понятно. Мне же не нужны скальперские сделки , банально баланс бы получить :)

**Comment by AlexanderVolkovTCS** [comment]
Уже есть в #478
