### ISSUE TITLE
Авторизация браузерного Websocket клиента. Информация для разработчиков Tinkoff. 

### ISSUE THREAD

**Issue by nonamegithub** [TinkoffCreditSystems/invest-openapi#541]
**front-end:**   ws = new WebSocket('wss://api-invest.tinkoff.ru/openapi/md/v1/md-openapi/ws', 'token');
**back-end​:**   proxyReq.setHeader('Authorization', \`Bearer ${req.headers['sec-websocket-protocol']}\`);
Не устраивает? Нужны аргументированные возражения.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, передачу токена в поле протокола считаем неправильным и небезопасным, но отмечу, что вопрос в любом случае теряет свою актуальность из-за перехода на стримы gRPC в следующей версии.
