### ISSUE TITLE
Добавить в API, при выставлении ордера на покупку, К-маржинальности

### ISSUE THREAD

**Issue by talexeyft** [TinkoffCreditSystems/invest-openapi#547]
Есть следующая задача:

Я хочу купить 10 акции разных компаний с плечом 5х каждую. Т.е. покупаю 10 компаний по одной акции по 10 рублей = 100 рублей, из которых своих средств я хочу использовать 20 рубей, остальные 80 предоставляет биржа.

Проблема следующая:

В текущем виде, что в терминале, что в API-интерфейсе, маржинальная торговля автоматически используется, если я покупаю на сумму больше, чем остаток на счете. Таким образом я могу купить только акции одной компании с использовании заемных средств. Купить последующие не получиться, т.к. после покупка хотя бы одной с учетом маржиналки, возможна только с обнулением текущего счета.

Решение:

Добавить к-маржинальности для покупок. По дефолту он стоит = 1. т.е. при любых сделаках используются только свои средства. Если >1, то в соответсвующи пропорциях списываются собственные средства + заемные. Таким образом, по задаче выше, я устанавлияю к-маржинальности = 5, покупаю 1 акцию за 10 р, из которых с моего счета спишется 2 рубля, 8 предоставит биржа, дальше я могу купить еще 9 акций на 18 руб.

В api запросе добавить соовтесвующий параметр при выставлении ордеров на покупку (возможно и на продажу, но об этом я не думал)

**Comment by AlexanderVolkovTCS** [comment]
При маржинальной торговле вы используете заемные средства не биржи, а брокера. Внутри торгового поручения никакого разделения на собственные и заемные средства нет. Стоимость переноса непокрытой позиции зависит только от суммы, а не от распределения заемных денег между бумагами.

https://help.tinkoff.ru/margin-trade/long/cost/
https://help.tinkoff.ru/margin-trade/long/what-is/
