### ISSUE TITLE
Почему цена при покупке везде 100 USD, а average_position_price всегда None? (python)

### ISSUE THREAD

**Issue by ezra-wick** [TinkoffCreditSystems/invest-openapi#548]
Добрый день, не могу понять почему при покупке с помощью метода post_orders_market_order всегда цена равна 100 долларов у любого актива? 
И почему average_position_price всегда возвращает None. Как быть? 

`positions=[PortfolioPosition(name='Momo', average_position_price=None, average_position_price_no_nkd=None, balance=Decimal('1'), blocked=Decimal('0'), expected_yield=None, figi='BBG007HTCQT0', instrument_type=<InstrumentType.stock: 'Stock'>, isin='US60879B1070', lots=1, ticker='MOMO'), PortfolioPosition(name='Доллар США', average_position_price=None, average_position_price_no_nkd=None, balance=Decimal('1900.0'), blocked=Decimal('0'), expected_yield=None, figi='BBG0013HGFT4', instrument_type=<InstrumentType.currency: 'Currency'>, isin=None, lots=1, ticker='USD000UTSTOM')]
`

> BBG00YM3BX27
OperationTypeWithCommission.buy
price: 100.0
payment: -100.0
quantity: 1

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, https://tinkoffcreditsystems.github.io/invest-openapi/faq_sandbox/
