### ISSUE TITLE
Не видны поздневечерние свечи через историю на бирже СПБ, хотя стриминговая прилетает

### ISSUE THREAD

**Issue by koshkoshka** [TinkoffCreditSystems/invest-openapi#55]
Например, мой лог даёт
`BBG006G2JVL2 Свеча из истории 2019-11-08T22:39:00Z Свеча из стрима 2019-11-08T23:18:00Z Интервал 1min`

Видно, что торги по инструменту закрылись в 23:18 по Зулу.
А последняя свеча в 22:39 с истории. 
То есть не все прилетают.

**Comment by NikitaMelnikov** [comment]
Могли бы привести запросы в рест чтобы мы могли воспроизвести ситуацию?

**Comment by koshkoshka** [comment]
`https://api-invest.tinkoff.ru/openapi/sandbox/market/candles?figi=BBG006G2JVL2&from=2019-11-07T23%3A18%3A00Z&to=2019-11-08T23%3A18%3A00Z&interval=1min`

**Comment by NikitaMelnikov** [comment]
Похоже что проблем на нашей стороне, будем разбираться

**Comment by NikitaMelnikov** [comment]
https://spbexchange.ru/ru/stocks/inostrannye/raspisanie/ 
до 01:45 Период стандартной дополнительной ликвидности

Так как вы отправляете время по UTC, то 01:45 - это как раз 22:45

**Comment by koshkoshka** [comment]
> https://spbexchange.ru/ru/stocks/inostrannye/raspisanie/
> до 01:45 Период стандартной дополнительной ликвидности
> 
> Так как вы отправляете время по UTC, то 01:45 - это как раз 22:45

А почему же свеча из стрима более поздняя?

**Comment by NikitaMelnikov** [comment]
В Стрим прилетают данные с Биржи, в том числе в период дополнительной ликвидности.
Возможно мы добавим на своей стороне проверку на это, обсудим с коллегами
