### ISSUE TITLE
другая цена при покупке

### ISSUE THREAD

**Issue by PestovIgnat** [TinkoffCreditSystems/invest-openapi#550]
Добрый день. 
Делаю запрос openapi/market/orderbook где получаю **lastPrice** - Я правильно понимаю что это текущая цена по которой можно купить акции?
Сразу же делаю запрос на покупку акций /openapi/orders/market-order на который уходит несколько 0.3 секунды.

Как итог Цена lastPrice = 0,1486 руб, а цена покупки почему то 0,1498 как такое может быть?

Вот, что показывает приложение в точке покупки 
![image](https://user-images.githubusercontent.com/23117205/124442845-cfb3fb80-dd85-11eb-9c13-75e4c1690f29.png)

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, lastPrice – цена последней сделки на бирже на момент запроса.
Цена последующих сделок будет отличаться, ориентируйтесь на список встречных предложений из биржевого стакана.

**Comment by PestovIgnat** [comment]
А как мне узнать цену по которой я куплю или продам акцию ?

**Comment by AlexanderVolkovTCS** [comment]
Для рыночных заявок - никак. Они гарантированно будут исполнены по максимально выгодной цене из пула встречных заявок в стакане.

Если вам нужно купить или продать бумаги по точной цене - подавайте лимитную заявку. Она встанет в стакан и будет ждать встречных заявок для исполнения по указанной вами цене.

**Comment by PestovIgnat** [comment]
> Для рыночных заявок - никак. Они гарантированно будут исполнены по максимально выгодной цене из пула встречных заявок в стакане.
> 
> Если вам нужно купить или продать бумаги по точной цене - подавайте лимитную заявку. Она встанет в стакан и будет ждать встречных заявок для исполнения по указанной вами цене.

Спасибо большое
