### ISSUE TITLE
Авторизация браузерного Websocket клиента. Часть IV.

### ISSUE THREAD

**Issue by nonamegithub** [TinkoffCreditSystems/invest-openapi#551]
Часть III [здесь.](https://github.com/TinkoffCreditSystems/invest-openapi/issues/543)
1) Старые клиенты никуда не отвалятся, так как можно сделать отдельную "точку входа" (порт или url) для откостыленных браузерных WebSoсket-клиентов
2) Костыль не накладывает никаких ограничений "на допустимые символы токена(запятые)", так как запятые являются недопустимыми символами в токенах, передаваемых в HTTP-заголовках.
3) ограничения по призванным нагнать страх на обывателя "инфраструктурным причинам" расцениваю как отсутствие фундаментальных контраргументов.

Там работы максимум на полчаса. До конца недели успеете?

**Comment by AlexanderVolkovTCS** [comment]
Решили вопрос с поддержкой старых клиентов, реализовали без прокси.

**Comment by nonamegithub** [comment]
Вот это другое дело, а то предыдущие ответы были из серии "лучше бы я на сварку смотрел"...
Да, подтверждаю, авторизация через 'sec-websocket-protocol' действительно заработала. Потоковые данные нормально идут. Заработала, но не до конца:
new WebSocket('wss://api-invest.tinkoff.ru/openapi/md/v1/md-openapi/ws','token')  из браузера не устанавливает соединение(
 Если же прогнать через мой старый прокси  (уже без модификации заголовков), то все ок. Как я понимаю, проблема в том, что backend для случая "токен в 'sec-websocket-protocol'" выдает ответ, отличный от необходимого по стандарту, либо,  проблема может быть у меня с моим конкретным фронтендом. Предлагаю немного поднажать и добить вопрос. Конечной точкой будет подтверждение с вашей стороны, что удалось авторизоваться через браузер по новой схеме и получить потоковые данные. Отклики от тех, кто ждал WebSocket-авторизацию через браузер, крайне приветствуются.
Сразу озвучиваю идею использования варианта типа 
var ws = new WebSocket("ws://example.com/path", ["protocol1", "protocol2"]) 
в качестве альтернативного решения.

**Comment by AlexanderVolkovTCS** [comment]
через например https://websocketking.com/ работает?

**Comment by nonamegithub** [comment]
через websocketking.com не стал пробовать -  накидал скрипт, прогнал через chrome, все ок.
Сейчас буду копать, что не так в моем клиенте, а точнее, что именно ему не нравится в ответе вашего backenda.

**Comment by nonamegithub** [comment]
ставлю финальную точку: проблема была связана с WebKit библиотекой - "уговорил" ее в конце концов установить ssl-соединение с api-invest.tinkoff.ru
С браузерами Edge, Chrome, IE все ровно, с остальными не пробовал, но, с большой вероятностью, тоже будет работать.
