### ISSUE TITLE
Некорректный стакан по подписке.

### ISSUE THREAD

**Issue by nonamegithub** [TinkoffCreditSystems/invest-openapi#552]
Для начала, выражаю признательность за решение [вопроса по "нестандартной" авторизации браузерного WebSocket клиента](https://github.com/TinkoffCreditSystems/invest-openapi/issues/551).
Теперь следующий вопрос.
Временами, стакан по подписке начинает жить своей жизнью и выдает данные, [которые рядом не стояли с реальными](https://github.com/TinkoffCreditSystems/invest-openapi/issues/323). 
Не  правильнее ли будет вообще перестать стримить такие "безумные" стаканы, или, в конце концов, немного поднатужиться и решить вопрос так же оперативно, как и упомянутый выше? Скоро ведь год как будет проблеме...

**Comment by AlexanderVolkovTCS** [comment]
К сожалению, также быстро этот вопрос не решить, только в новой версии. Оставляю вопрос в тикете 323

**Comment by nonamegithub** [comment]
Гнать по хорошему вас всех надо из банка. Перед Олегом с Оливером щеки раздуваете от собственной важности, а по факту еще те "специалисты"

**Comment by BaryshevS** [comment]
Это ладно... там несколько очередей с данными и они в стакане суммируются..
Вот ты ставишь лимитку... на 100, цена уходить на 90 (т.е. ты готов платить на 10 выше рынка), а тебя не исполняют. 
В поддержке оказалось, что там 2 очереди и вот ордер попал в ту, где таких заявок нет :)))))))))))))))))))))))))))))))))))
Минут через 30-40 исполнилось... И ладно была акция фиговая какая... Это была MSFT правда в вечернюю сессию, около 21:00, но все же.

**Comment by BaryshevS** [comment]
> Это ладно... там несколько очередей с данными и они в стакане суммируются..
> Вот ты ставишь лимитку... на 100, цена уходить на 90 (т.е. ты готов платить на 10 выше рынка), а тебя не исполняют.
> В поддержке оказалось, что там 2 очереди и вот ордер попал в ту, где таких заявок нет :)))))))))))))))))))))))))))))))))))
> Минут через 30-40 исполнилось... И ладно была акция фиговая какая... Это была MSFT правда в вечернюю сессию, около 21:00, но все же.


вот ответ поддержки
28.04.2021, 12:25
Существует 2 пула ликвидности: Внутренний поток заявок - биржа СПБ. Внешний поток заявок - биржи NYSE и NASDAQ Если подать заявку до 14:30 (15:30 зимнее время), то она попадёт во внутренний пул ликвидности. После 14:30 (15:30 зимнее время) система проверяет, где условия исполнения заявки лучше. Она может попасть во внутренний или внешний пул ликвидности. В стакане отображаем заявки из обоих пулов ликвидности. Заявка, выставленная во внутреннем пуле, не может быть исполнена во внешнем пуле ликвидности и наоборот. Заявки на СПБ бирже сводятся по паритету. Порядок регистрации заявок на бирже не важен. Заявка на покупку или продажу сводится между инвесторами, которые выставили встречные заявки с подходящими условиями.

**Comment by nonamegithub** [comment]
Удивляться нечему(  [Писал один человек](https://github.com/TinkoffCreditSystems/invest-openapi/issues/146#issuecomment-614943242), что заявка попадает неизвестно куда, и я с ним согласен. Разок вкинул крупный пакет по рынку в плотный стакан, а заявка исполнилась сильно дешево. Тогда пришел ровно к тому же выводу, что "заявки варятся где-то на серверах Тинькова и пытаются закрыться с заявками других пользователей Тинькова".  "Кривые" стаканы со стриминга только подкрепляют мою уверенность в этом.

**Comment by polkila** [comment]
Ещё я добавлю немного своих впечатлений. На вечерке выставляю заявку на продажу 1 лота по какой-то N цене и наблюдаю за стаканом. Вижу, что заявки дороже моей исполняются, меняется last_price у инструмента, а вот моя заявка которая дешевле чего-то ждёт и не исполняется. Может висеть и 10 и 20 минут. И как бы всё там понятно с разными пулами, что система выбирает, где выгоднее эту заявку исполнить — в теории всё **супер рационально**. А вот на практике (мой пример) работает **не рационально**.

**Comment by nonamegithub** [comment]
А теперь давайте представим, что у кого-то (не будем озвучивать здесь у кого) есть возможность купить в одном стакане подешевле и продать в другом подороже? Как вам такой вариант, а?

**Comment by BaryshevS** [comment]
> А теперь давайте представим, что у кого-то (не будем озвучивать здесь у кого) есть возможность купить в одном стакане подешевле и продать в другом подороже? Как вам такой вариант, а?

Ну вот пока используем "что есть" и только лимитками.
Растем и переходим к другому брокеру. 
Хотя там тоже приколов много.
По этом сильно растем до Private Banking ну и норм...

**Comment by BaryshevS** [comment]
Этот тикета закрыли нет толку в него писать. Пишите в https://github.com/TinkoffCreditSystems/invest-openapi/issues/323

**Comment by AlexanderVolkovTCS** [comment]
@polkila да, такое может быть, если биржа поставила заявку в один пул, а движение в вашу сторону потом пошло в другом пуле.
Совет: если видите подобную ситуацию - то можете для оперативности исполнения отменить заявку и перепоставить заново. С очень высокой вероятностью повторная заявка встанет в более выгодный пул.
