### ISSUE TITLE
Обьёмы торгов

### ISSUE THREAD

**Issue by AndoInvest** [TinkoffCreditSystems/invest-openapi#553]
Здравствуйте!
При получении исторических свечей также приходят данные по объёму. Это данные по объёму с Санкт-Петербургской биржи или только из тинькофф инвестиций? И в чем объем измеряется в количестве операций по покупке/продаже или это оборот в $?

**Comment by Protectorlok** [comment]
Оборот измеряется в количестве лотов. 
Данные по объёму с СПБ биржи. Вроде как.

**Comment by AlexanderVolkovTCS** [comment]
@Protectorlok спасибо, все верно, это объемы в лотах с соответствующей биржи(spb/moex).
