### ISSUE TITLE
Пулы ликвидности в исторических данных

### ISSUE THREAD

**Issue by DiktatorDNS3018** [TinkoffCreditSystems/invest-openapi#554]
Добрый день, как написано в "HOW-TO": "Вся же биржевая информация (свечи, стаканы) транслируются агрегируя информация со всех пулов ликвидности.",  но это очень неудобно при "прогоне" роботов по историческим данным, подбор параметров происходит по данным, которые не соответствуют действительности, ведь заявки могут находиться только в 1 пуле ликвидности. 
По поводу того, что система с пулами работает мягко говоря не очень, это вопрос к бирже СПБ, но могли бы вы разделить эти данные? Хотя-бы, предоставлять объём торгов отдельно по внутреннему пулу, а в идеале конечно полное разделение данных, это было бы очень полезно для понимания того, какие заявки с большей вероятностью и в каком объёме будут исполнены.
Спасибо.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, пока СПБ не транслирует раздельные потоки данных, мы прорабатываем совместно с биржей этот вопрос, но  пока ничего определенного не скажем.
