### ISSUE TITLE
Перечень ликвидного имущества со ставками риска

### ISSUE THREAD

**Issue by DiktatorDNS3018** [TinkoffCreditSystems/invest-openapi#555]
Для удобства, было бы неплохо иметь возможность выгружать актуальную таблицу ликвидных ЦБ со ставками внутри API, а то копировать или парсить таблицу с https://www.tinkoff.ru/invest/margin/equities/ , не слишком технологично на мой взгляд, или есть более удобные пути?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, да, будет #11
