### ISSUE TITLE
Добавьте пожалуйста в API возможность выставлять тейк-профит и стоп-лосс

### ISSUE THREAD

**Issue by Freeongoo** [TinkoffCreditSystems/invest-openapi#556]
Существующий API очень скудный и есть только самый минимум. Как по мне, так наличие тейк-профит и стоп-лосс это основные функции при автоматиации торгов через API и его крайне не хватае.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, пока TakeProfit/StopLoss нет, но будет, пока единственный вариант решения - смотреть близость рыночной цены к желаемой и каждый день переоткрывать позиции.
#145
