### ISSUE TITLE
Не подтягивается категория у бумаги OGN

### ISSUE THREAD

**Issue by nd-jar** [TinkoffCreditSystems/invest-openapi#558]
У бумаги OGN не подтягивается категория, на странице сайта:

https://www.tinkoff.ru/invest/stocks/OGN/

Из списка категорий прилетает:
`{"eng":"HealthCare","rus":"Здравоохранение"}`

А у OGN выглядит как `Healthcare`
(Маленькая буква "c", вероятно, поэтому не отображается)

Возможно, проблема не только у OGN и в других бумагах/секторах тоже

**Comment by AlexanderVolkovTCS** [comment]
Спасибо, передали информацию о проблеме коллегам. 
Отмечу, что вопросы работы непубличного API мы не комментируем)
