### ISSUE TITLE
REST: Вопрос по portfolio / positions

### ISSUE THREAD

**Issue by ayurushev** [TinkoffCreditSystems/invest-openapi#56]
Должны ли при работе с sandbox токеном при запросе портфеля /portfolio
прилетать поля

"expectedYield,
averagePositionPrice,
averagePositionPriceNoNkd"

по каждому инструменту? Т.к они пустые (вернее их нет в ответах от REST).

все что прилетает:
{"figi":"BBG004730RP0","ticker":"GAZP","isin":"RU0007661625","instrumentType":"Stock","balance":20,"blocked":0,"lots":2},

Swagger указывает, что вроде как должны.
https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/portfolio/get_portfolio

**Comment by koshkoshka** [comment]
Нет, доходность в песочнице всегда нулевая
