### ISSUE TITLE
ошибка при исполнении запроса

### ISSUE THREAD

**Issue by pzxmtx** [TinkoffCreditSystems/invest-openapi#561]
При попытке отправить лимитную заявку на покупку НЕ в песочнице по инструменту BBG004S682Z6 (RTKM), получаю сообщение об ошибке:

июл. 15, 2021 5:38:36 PM ru.tinkoff.invest.openapi.okhttp.BaseContextImpl handleResponse
SEVERE: Ошибка при исполнении запроса, trackingId = 1a0838f40cc2bc66

Пример кода отправки запроса:

LimitOrderRequest request = new LimitOrderRequest();
request.setLots(volume);
request.setPrice(unitPrice); 
request.setOperation(operation);
this.unitPrice = unitPrice;
CompletableFuture<PlacedLimitOrder> orderJob = api.getOrdersContext().placeLimitOrder(figi, request, this.brokerAccount);

**Comment by AlexanderVolkovTCS** [comment]
Проверьте пожалуйста, корректный ли аккаунт передается в this.brokerAccount, ибо видим ошибку Unknown account
Если корректный - прошу создать запрос в техподдержку, разберемся.
