### ISSUE TITLE
Получение информации по будущим и прошедшим дивидендам

### ISSUE THREAD

**Issue by superbotan** [TinkoffCreditSystems/invest-openapi#563]
Хочется иметь по каждому figi информацию по дивидендам (где они были и есть)
Список выплаченных (с указанием суммы на акцию, суммы на лот, цена акции на тот момент, дата последней покупки)
Список предстоящих (флаг утверждённая или ориентировочная сумма, дата до которой участвуешь в дивидендах и сумма)

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, планируем, обсуждался в #65
