### ISSUE TITLE
Блокируется IP при подключении к стаканам всего лишь нескольких (17) инструментов через streaming

### ISSUE THREAD

**Issue by Aspirationtocode** [TinkoffCreditSystems/invest-openapi#564]

**Comment by AlexanderVolkovTCS** [comment]
Айпи адрес статический и только ваш? Может есть роботы, которые с него делают любые другие запросы на сервисы Тинькофф?

**Comment by Aspirationtocode** [comment]
Да, статический и только мой.

> Айпи адрес статический и только ваш? Может есть роботы, которые с него делают любые другие запросы на сервисы Тинькофф?

**Comment by AlexanderVolkovTCS** [comment]
Максимальное количество REST-запросов на айпи привезено на странице https://tinkoffcreditsystems.github.io/invest-openapi/rest/

Отмечу, что если у вас с этого айпи идут запросы на любые другие сервисы Тинькофф, включая терминал, то они тоже учитываются в этой тысяче.

Если вы уверены, что у вас количество запросов меньше, просьба написать в техподдержку, указав айпи адрес, методику определения блокировки и приблизительное время, когда ловили бан по айпи.
