### ISSUE TITLE
Python stream websocket.

### ISSUE THREAD

**Issue by nuzhnoff** [TinkoffCreditSystems/invest-openapi#565]
Ребята здравствуйте! Слушайте ну чайник я. ну уже сил нету. Можете написать строчку( спагетти методом) кода без классов, как передать вам сокет и подписку через websocket python. мне тутошние sdk не нужны и в них ну намудренно для профи. а я хочу всего лишь проанализировать исторические свечи. Спасибо заранее. могу даже задонатить, мне не в тягость.

**Comment by sergeymavrin** [comment]
Зачем для анализа исторических свечей streaming протокол?

**Comment by nuzhnoff** [comment]
Мне казалось, что только через stream?

**Comment by sergeymavrin** [comment]
https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_candles

**Comment by nuzhnoff** [comment]
```
import asyncio
import websockets
list = []
token = "my token"
#Получение исторических свечей по FIGI
candle_subs = {'figi': 'BBG000C6GN04', 'from': '2021-08-14T10:00:00+03:00','to': '2021-08-14T18:00:00+03:00','interval': 'hour'}

async def hello():
    uri = "wss://api-invest.tinkoff.ru/openapi/md/v1/md-openapi/ws/market/candles"
    candle_subs = {'figi': 'BBG000C6GN04', 'from': '2021-08-14T10:00:00+03:00','to': '2021-08-14T18:00:00+03:00','interval': 'hour'}
    async with websockets.connect(uri, {'Authorization: Bearer' + token'}) as ws:
        msg = await ws.recv(candle_subs)
        #await websocket.send("Hello world!")
        #await websocket.recv()
        print(msg)
        list.append(msg)
        print(list)
asyncio.get_event_loop().run_until_complete(hello())
```

**Comment by nuzhnoff** [comment]
Вот, что я смог родить.  но ответ сервера - 403

**Comment by Fatal1ty** [comment]
https://github.com/Fatal1ty/tinkoff-api#historical-data
