### ISSUE TITLE
Появится ли возможность получать данные профилей?

### ISSUE THREAD

**Issue by Sindr0me** [TinkoffCreditSystems/invest-openapi#566]
Здравствуйте. Интересует возможность получения данных из своего профиля в пульсе по апи, посты, покупка, продажа бумаг. Планируется реализация?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день
>данных из своего профиля в пульсе по апи

пока не планируется

>покупка, продажа бумаг

давно реализована, https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/orders/post_orders_limit_order

**Comment by Sindr0me** [comment]
Имелось ввиду получение исторических данных по покупке/продаже из своего аккаунта.

**Comment by AlexanderVolkovTCS** [comment]
Метод https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/operations/get_operations вернет список ваших операций
