### ISSUE TITLE
Websocket Странные объемы M1 2021-07-20

### ISSUE THREAD

**Issue by ssaraikin** [TinkoffCreditSystems/invest-openapi#567]
Подписка на минутки AMZN. Обратил внимание на странные объемы в сравнении с данными из терминала. Вчера был какой-то сбой? Это уже исправлено ? 
 
Залогированные данные от Тинькофф:

`
{"v":1,"t":1626792840000,"o":3559.05,"h":3559.05,"l":3559.05,"c":3559.05}, Tue Jul 20 2021 14:54:00 GMT+0000 (Всемирное координированное время)
{"v":3,"t":1626792900000,"o":3559.5,"h":3559.61,"l":3559.5,"c":3559.61}, Tue Jul 20 2021 14:55:00 GMT+0000 (Всемирное координированное время)
{"v":23,"t":1626792960000,"o":3557.48,"h":3557.48,"l":3557.27,"c":3557.27}, Tue Jul 20 2021 14:56:00 GMT+0000 (Всемирное координированное время)
{"v":52,"t":1626793020000,"o":3558.03,"h":3558.03,"l":3558.03,"c":3558.03}, Tue Jul 20 2021 14:57:00 GMT+0000 (Всемирное координированное время)
{"v":153,"t":1626793080000,"o":3556.1,"h":3556.3,"l":3556.1,"c":3556.18}, Tue Jul 20 2021 14:58:00 GMT+0000 (Всемирное координированное время)
{"v":10,"t":1626793140000,"o":3556.17,"h":3556.17,"l":3556.17,"c":3556.17}, Tue Jul 20 2021 14:59:00 GMT+0000 (Всемирное координированное время)
{"v":5,"t":1626793200000,"o":3557.07,"h":3557.07,"l":3557.06,"c":3557.06}, Tue Jul 20 2021 15:00:00 GMT+0000 (Всемирное координированное время)
{"v":175,"t":1626793260000,"o":3555.83,"h":3556.19,"l":3555.83,"c":3556.16}, Tue Jul 20 2021 15:01:00 GMT+0000 (Всемирное координированное время)
{"v":4,"t":1626793320000,"o":3553.91,"h":3553.91,"l":3553.91,"c":3553.91}, Tue Jul 20 2021 15:02:00 GMT+0000 (Всемирное координированное время)
{"v":132,"t":1626793380000,"o":3554.7,"h":3555.06,"l":3554.7,"c":3555.06}, Tue Jul 20 2021 15:03:00 GMT+0000 (Всемирное координированное время)
{"v":44,"t":1626793440000,"o":3554.94,"h":3555.2,"l":3554.94,"c":3555.2}, Tue Jul 20 2021 15:04:00 GMT+0000 (Всемирное координированное время)
`

**Comment by mvkasatkin** [comment]
Да, тоже наблюдал проблемы с объемами на ws вчера и позавчера

**Comment by nonamegithub** [comment]
удивляться нечему. [для меня давно уже не секрет](https://github.com/TinkoffCreditSystems/invest-openapi/issues/323), что где-то на серверах тинькова идут свои, параллельные основным, торги.

**Comment by AlexanderVolkovTCS** [comment]
Несколько последних дней наблюдалась нестабильность в стримах, вероятно с этим и связана описываемая проблема, так как объемы считаются на сервере стриминга накопительным итогом.
Посмотрите пжлст: если сегодня или в будущем снова будут аналогичные проблемы, то прошу переоткрыть тикет.
