### ISSUE TITLE
Websocket Странные объемы M1 2021-07-20. Part II.

### ISSUE THREAD

**Issue by nonamegithub** [TinkoffCreditSystems/invest-openapi#569]
[Открываю снова](https://github.com/TinkoffCreditSystems/invest-openapi/issues/567#issuecomment-885510972). В [стримах черт знает, что творится](https://feedback.tinkoff.ru/terminal/topic/2016-%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B0%D0%B5%D1%82-%D0%BD%D0%B5%D0%BA%D0%BE%D1%80%D1%80%D0%B5%D0%BA%D1%82%D0%BD%D1%8B%D0%B5-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC%D1%8B-%D0%B7%D0%B0-%D0%B4%D0%B5%D0%BD%D1%8C), позор.

**Comment by AlexanderVolkovTCS** [comment]
В этом Гитхабе принимаются вопросы по работе публичного API, а не брокера или биржи в целом. Поэтому если данные в ws-встриме соответствуют терминалу, то вопрос корректней адресовать брокеру или бирже. Если есть расхождения (причем только по прошествии большего времени, чем запрашиваемый интервал) между API и терминалом - то дайте знать.

**Comment by nonamegithub** [comment]
И еще. Я жду ответа на [вот этот вопрос](https://github.com/TinkoffCreditSystems/invest-openapi/issues/323#issuecomment-881202191). Имеет ли смысл накалять ситуацию молчанием?

**Comment by nonamegithub** [comment]
А если совсем не доходит, то объясню попроще: лучше вообще не стримить, чем стримить непонятно что.

**Comment by nonamegithub** [comment]
И открой этот тикет - закроешь, когда пойдут нормальные потоковые данные или я дам добро на это.

**Comment by nonamegithub** [comment]
При приеме на работу до вас довели, что клиенты торгуют не на демо-счетах?

**Comment by nonamegithub** [comment]
Завтра постараюсь вызвонить тебя, хочу послушать твои объяснения. А то ловко петляешь здесь
