### ISSUE TITLE
/market/* Со временем меняются и отдает разные FIGI по инструменту

### ISSUE THREAD

**Issue by BaryshevS** [TinkoffCreditSystems/invest-openapi#575]
Почему Ваше OpenAPI отдает со временем разные figi?
Запрос в эндпоинты /market/* (и акции и бонды)

Раньше выдавало так
{
    "lot": 1,
    "figi": "US98980B1035",
    "isin": "US98980B1035",
    "name": "ZipRecruiter Inc",
    "type": "Stock",
    "ticker": "ZIP",
    "currency": "USD",
    "minPriceIncrement": 0.01
}
сейчас это:
{
    "lot": 1,
    "figi": "BBG010JBYV98",
    "isin": "US98980B1035",
    "name": "ZipRecruiter Inc",
    "type": "Stock",
    "ticker": "ZIP",
    "currency": "USD",
    "minPriceIncrement": 0.01
}

Раньше вот такое было:
{
    "lot": 1,
    "figi": "BBG000F0KF42",
    "isin": "IE00B58JVZ52",
    "name": "Seagate",
    "type": "Stock",
    "ticker": "STX",
    "currency": "USD",
    "minPriceIncrement": 0.01
}
а сейчас выдает:
{
    "lot": 1,
    "figi": "BBG0113JGQF0",
    "isin": "IE00BKVD2N49",
    "name": "Seagate",
    "type": "Stock",
    "ticker": "STX",
    "currency": "USD",
    "minPriceIncrement": 0.01
}

Есть еще какие-то  начинающиеся с "TCS", тоже заменяются со временем

{
    "lot": 1,
    "figi": "TCS00A102GD1",
    "isin": "RU000A102GD1",
    "name": "ДОМ.РФ Ипотечный агент 08",
    "type": "Bond",
    "ticker": "RU000A102GD1",
    "currency": "RUB"
}

{
    "lot": 1,
    "figi": "TCS00A102DK3",
    "isin": "RU000A102DK3",
    "name": "МаксимаТелеком выпуск 2",
    "type": "Bond",
    "ticker": "RU000A102DK3",
    "currency": "RUB",
    "faceValue": 1000,
    "minPriceIncrement": 0.1
}

Вопрос такой: 
1. Если Вы меняете figi, а isin и ticker не меняете, то это замена? Когда вы это делаете? Надеюсь не в часы работы биржи.
2. Если правильно понимаю, что   "figi": "TCS" это Ваш костыль, т.к. другого у Вас нет. 
3. Один инструмент на разных биржах В Вашем случае имеет один figi или в Вашем случае могут быть разные номера?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, все верно, при корпоративных событиях(КС) создается новый идентификатор, пример: https://spbexchange.ru/ru/listing/news.aspx?news=24049 
https://spbexchange.ru/ru/listing/news.aspx?news=24293

1. Нет, не замена, а добавление нового и скрытие старого. Обычно на период КС торги по бумаге на бирже приостанавливаются
2. FIGI - это идентификатор бумаги. Алгоритм именования не комментируем
3. Разные.

**Comment by BaryshevS** [comment]
> Добрый день, все верно, при корпоративных событиях(КС) создается новый идентификатор, пример: https://spbexchange.ru/ru/listing/news.aspx?news=24049
> https://spbexchange.ru/ru/listing/news.aspx?news=24293
> 
> 1. Нет, не замена, а добавление нового и скрытие старого. Обычно на период КС торги по бумаге на бирже приостанавливаются
> 2. FIGI - это идентификатор бумаги. Алгоритм именования не комментируем
> 3. Разные.

При этом, если были бумаги в портфеле, то им будет назначен новый figi. Верно?

**Comment by AlexanderVolkovTCS** [comment]
Да
