### ISSUE TITLE
Портфолио и операции не возвращает CNY

### ISSUE THREAD

**Issue by telikey** [TinkoffCreditSystems/invest-openapi#576]
Собственно проблема в сабже 
Приложение показывает что все есть, а API возвращает что нет. Ни валюты ни операции покупки.

Пытался подождать вдруг сервер не обновил данные, но нет спустя 8 часов все тоже самое.
Попробую еще подождать) 
Может разрабы починят или сервер обновит данные)

**Comment by BaryshevS** [comment]
В их вселенной в апи только 3 валюты.. и балансы и операции по ним не нужно отдавать :(

**Comment by telikey** [comment]
В этом и прикол 
Выдает все только для Евро, доллары и рубли все остальное нет.
Хотя в документации к API написано что CNY тоже должен быть

**Comment by BaryshevS** [comment]
Ждем @AlexanderVolkovTCS , что скажет,  что так все и задумано.

**Comment by AlexanderVolkovTCS** [comment]
Пока действительно поддерживаются только USD и EURO.
Уже есть тикет #478
