### ISSUE TITLE
Что у Вас с этими FiGI почему у них одинаковый номер?

### ISSUE THREAD

**Issue by BaryshevS** [TinkoffCreditSystems/invest-openapi#577]
Что у Вас с этими FiGI почему у них одинаковый номер?

{"lot": 1, "figi": "BBG000C8NJ10", "isin": "US73179P1066", "name": "PolyOne Corp", "type": "Stock", "ticker": "POL", "currency": "USD", "minPriceIncrement": 0.01}

{"lot": 1, "figi": "BBG000C8NJ10", "isin": "US05368V1061", "name": "Avient Corporation", "type": "Stock", "ticker": "AVNT", "currency": "USD", "minPriceIncrement": 0.01}

@AlexanderVolkovTCS спасай...

**Comment by BaryshevS** [comment]
Попарные хеши - 34 штуки.

{"lot": 1, "figi": "BBG000P1B7C8", "isin": "US7438151026", "name": "Providence Service Corp The", "type": "Stock", "ticker": "PRSC", "currency": "USD", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG000P1B7C8", "isin": "US60783X1046", "name": "ModivCare Inc.", "type": "Stock", "ticker": "MODV", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000BHJWG1", "isin": "US05464C1018", "name": "Axon Enterprise Inc", "type": "Stock", "ticker": "AAXN", "currency": "USD", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG000BHJWG1", "isin": "US05464C1018", "name": "Axon Enterprise Inc", "type": "Stock", "ticker": "AXON", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000C8NJ10", "isin": "US73179P1066", "name": "PolyOne Corp", "type": "Stock", "ticker": "POL", "currency": "USD", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG000C8NJ10", "isin": "US05368V1061", "name": "Avient Corporation", "type": "Stock", "ticker": "AVNT", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000BGLRN3", "isin": "US1567001060", "name": "CenturyLink", "type": "Stock", "ticker": "CTL", "currency": "USD", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG000BGLRN3", "isin": "US1567001060", "name": "CenturyLink", "type": "Stock", "ticker": "LUMN", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 10, "figi": "BBG001BBGNS2", "isin": "RU000A0JXKG3", "name": "Обувь России", "type": "Stock", "ticker": "OBUV", "currency": "RUB", "minPriceIncrement": 0.05}	{"lot": 10, "figi": "BBG001BBGNS2", "isin": "RU000A0JXKG3", "name": "Обувь России", "type": "Stock", "ticker": "ORUP", "currency": "RUB", "minPriceIncrement": 0.05}
{"lot": 1, "figi": "BBG000C8NJ10", "isin": "US05368V1061", "name": "Avient Corporation", "type": "Stock", "ticker": "AVNT", "currency": "USD", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG000C8NJ10", "isin": "US73179P1066", "name": "PolyOne Corp", "type": "Stock", "ticker": "POL", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG00VCY76T1", "isin": "RU000A101QE0", "name": "ОФЗ 26234", "type": "Bond", "ticker": "RU000A101QE0", "currency": "RUB"}	{"lot": 1, "figi": "BBG00VCY76T1", "isin": "RU000A101QE0", "name": "ОФЗ 26234", "type": "Bond", "ticker": "SU26234RMFS3", "currency": "RUB", "faceValue": 1000, "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000FQXC75", "isin": "US7240781002", "name": "Piper Jaffray Cos", "type": "Stock", "ticker": "PJC", "currency": "USD"}	{"lot": 1, "figi": "BBG000FQXC75", "isin": "US7240781002", "name": "Piper Jaffray Cos", "type": "Stock", "ticker": "PIPR", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000DHXTF1", "isin": "DE0005785802", "name": "Fresenius Medical Care AG & Co", "type": "Stock", "ticker": "FME", "currency": "EUR"}	{"lot": 1, "figi": "BBG000DHXTF1", "isin": "DE0005785802", "name": "Fresenius Medical Care AG & Co", "type": "Stock", "ticker": "FME@DE", "currency": "EUR", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000GM6Y84", "isin": "DE000A0HN5C6", "name": "Deutsche Wohnen SE", "type": "Stock", "ticker": "DWNI", "currency": "EUR"}	{"lot": 1, "figi": "BBG000GM6Y84", "isin": "DE000A0HN5C6", "name": "Deutsche Wohnen SE", "type": "Stock", "ticker": "DWNI@DE", "currency": "EUR", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000BS3CD1", "isin": "DE0005785604", "name": "Fresenius SE", "type": "Stock", "ticker": "FRE", "currency": "EUR"}	{"lot": 1, "figi": "BBG000BS3CD1", "isin": "DE0005785604", "name": "Fresenius SE", "type": "Stock", "ticker": "FRE@DE", "currency": "EUR", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000D54JC4", "isin": "DE0005493092", "name": "Borussia Dortmund GmbH & Co KG", "type": "Stock", "ticker": "BVB", "currency": "EUR"}	{"lot": 1, "figi": "BBG000D54JC4", "isin": "DE0005493092", "name": "Borussia Dortmund GmbH & Co KG", "type": "Stock", "ticker": "BVB@DE", "currency": "EUR", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000C8L273", "isin": "DE0006231004", "name": "Infineon Technologies AG", "type": "Stock", "ticker": "IFX", "currency": "EUR"}	{"lot": 1, "figi": "BBG000C8L273", "isin": "DE0006231004", "name": "Infineon Technologies AG", "type": "Stock", "ticker": "IFX@DE", "currency": "EUR", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000BD9FD1", "isin": "DE0008430026", "name": "Muenchener Rueckversicherungs-Gesellschaft AG", "type": "Stock", "ticker": "MUV2", "currency": "EUR"}	{"lot": 1, "figi": "BBG000BD9FD1", "isin": "DE0008430026", "name": "Muenchener Rueckversicherungs-Gesellschaft AG", "type": "Stock", "ticker": "MUV2@DE", "currency": "EUR", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "TCS00A101XD8", "isin": "RU000A101XD8", "name": "МаксимаТелеком выпуск 1", "type": "Bond", "ticker": "RU000A101XD8", "currency": "RUB", "faceValue": 1000, "minPriceIncrement": 0.1}	{"lot": 1, "figi": "TCS00A101XD8", "isin": "TCS00A101XD8", "name": "МаксимаТелеком выпуск 1", "type": "Bond", "ticker": "TCS00A101XD8", "currency": "RUB"}
{"lot": 1, "figi": "TCS00A101XD8", "isin": "TCS00A101XD8", "name": "МаксимаТелеком выпуск 1", "type": "Bond", "ticker": "TCS00A101XD8", "currency": "RUB"}	{"lot": 1, "figi": "TCS00A101XD8", "isin": "RU000A101XD8", "name": "МаксимаТелеком выпуск 1", "type": "Bond", "ticker": "RU000A101XD8", "currency": "RUB", "faceValue": 1000, "minPriceIncrement": 0.1}
{"lot": 1, "figi": "BBG00VCY76T1", "isin": "RU000A101QE0", "name": "ОФЗ 26234", "type": "Bond", "ticker": "SU26234RMFS3", "currency": "RUB", "faceValue": 1000, "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG00VCY76T1", "isin": "RU000A101QE0", "name": "ОФЗ 26234", "type": "Bond", "ticker": "RU000A101QE0", "currency": "RUB"}
{"lot": 1, "figi": "BBG000C8L273", "isin": "DE0006231004", "name": "Infineon Technologies AG", "type": "Stock", "ticker": "IFX@DE", "currency": "EUR", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG000C8L273", "isin": "DE0006231004", "name": "Infineon Technologies AG", "type": "Stock", "ticker": "IFX", "currency": "EUR"}
{"lot": 1, "figi": "BBG00VY13C74", "isin": "SU29014RMFS6", "name": "ОФЗ 29014", "type": "Bond", "ticker": "SU29014RMFS6", "currency": "RUB", "faceValue": 1000, "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG00VY13C74", "isin": "RU000A101N52", "name": "ОФЗ 29014", "type": "Bond", "ticker": "RU000A101N52", "currency": "RUB"}
{"lot": 1, "figi": "BBG000BGLRN3", "isin": "US1567001060", "name": "CenturyLink", "type": "Stock", "ticker": "LUMN", "currency": "USD", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG000BGLRN3", "isin": "US1567001060", "name": "CenturyLink", "type": "Stock", "ticker": "CTL", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000BD9FD1", "isin": "DE0008430026", "name": "Muenchener Rueckversicherungs-Gesellschaft AG", "type": "Stock", "ticker": "MUV2@DE", "currency": "EUR", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG000BD9FD1", "isin": "DE0008430026", "name": "Muenchener Rueckversicherungs-Gesellschaft AG", "type": "Stock", "ticker": "MUV2", "currency": "EUR"}
{"lot": 1, "figi": "BBG00VY13C74", "isin": "RU000A101N52", "name": "ОФЗ 29014", "type": "Bond", "ticker": "RU000A101N52", "currency": "RUB"}	{"lot": 1, "figi": "BBG00VY13C74", "isin": "SU29014RMFS6", "name": "ОФЗ 29014", "type": "Bond", "ticker": "SU29014RMFS6", "currency": "RUB", "faceValue": 1000, "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000FQXC75", "isin": "US7240781002", "name": "Piper Jaffray Cos", "type": "Stock", "ticker": "PIPR", "currency": "USD", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG000FQXC75", "isin": "US7240781002", "name": "Piper Jaffray Cos", "type": "Stock", "ticker": "PJC", "currency": "USD"}
{"lot": 1, "figi": "BBG000P1B7C8", "isin": "US60783X1046", "name": "ModivCare Inc.", "type": "Stock", "ticker": "MODV", "currency": "USD", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG000P1B7C8", "isin": "US7438151026", "name": "Providence Service Corp The", "type": "Stock", "ticker": "PRSC", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000BT7ZK6", "isin": "US8356993076", "name": "Sony Corp", "type": "Stock", "ticker": "SNE", "currency": "USD", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG000BT7ZK6", "isin": "US8356993076", "name": "Sony Corp", "type": "Stock", "ticker": "SONY", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000DHXTF1", "isin": "DE0005785802", "name": "Fresenius Medical Care AG & Co", "type": "Stock", "ticker": "FME@DE", "currency": "EUR", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG000DHXTF1", "isin": "DE0005785802", "name": "Fresenius Medical Care AG & Co", "type": "Stock", "ticker": "FME", "currency": "EUR"}
{"lot": 1, "figi": "BBG000GM6Y84", "isin": "DE000A0HN5C6", "name": "Deutsche Wohnen SE", "type": "Stock", "ticker": "DWNI@DE", "currency": "EUR", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG000GM6Y84", "isin": "DE000A0HN5C6", "name": "Deutsche Wohnen SE", "type": "Stock", "ticker": "DWNI", "currency": "EUR"}
{"lot": 1, "figi": "BBG000BS3CD1", "isin": "DE0005785604", "name": "Fresenius SE", "type": "Stock", "ticker": "FRE@DE", "currency": "EUR", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG000BS3CD1", "isin": "DE0005785604", "name": "Fresenius SE", "type": "Stock", "ticker": "FRE", "currency": "EUR"}
{"lot": 1, "figi": "BBG000D54JC4", "isin": "DE0005493092", "name": "Borussia Dortmund GmbH & Co KG", "type": "Stock", "ticker": "BVB@DE", "currency": "EUR", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG000D54JC4", "isin": "DE0005493092", "name": "Borussia Dortmund GmbH & Co KG", "type": "Stock", "ticker": "BVB", "currency": "EUR"}
{"lot": 1, "figi": "BBG000BHJWG1", "isin": "US05464C1018", "name": "Axon Enterprise Inc", "type": "Stock", "ticker": "AXON", "currency": "USD", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG000BHJWG1", "isin": "US05464C1018", "name": "Axon Enterprise Inc", "type": "Stock", "ticker": "AAXN", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 10, "figi": "BBG001BBGNS2", "isin": "RU000A0JXKG3", "name": "Обувь России", "type": "Stock", "ticker": "ORUP", "currency": "RUB", "minPriceIncrement": 0.05}	{"lot": 10, "figi": "BBG001BBGNS2", "isin": "RU000A0JXKG3", "name": "Обувь России", "type": "Stock", "ticker": "OBUV", "currency": "RUB", "minPriceIncrement": 0.05}
{"lot": 1, "figi": "BBG000BT7ZK6", "isin": "US8356993076", "name": "Sony Corp", "type": "Stock", "ticker": "SONY", "currency": "USD", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG000BT7ZK6", "isin": "US8356993076", "name": "Sony Corp", "type": "Stock", "ticker": "SNE", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG00ZQRGW24", "isin": "US68622V1061", "name": "Organon & Co.", "type": "Stock", "ticker": "OGN.W", "currency": "USD"}	{"lot": 1, "figi": "BBG00ZQRGW24", "isin": "US68622V1061", "name": "Organon & Co.", "type": "Stock", "ticker": "OGN", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG00ZQRGW24", "isin": "US68622V1061", "name": "Organon & Co.", "type": "Stock", "ticker": "OGN", "currency": "USD", "minPriceIncrement": 0.01}	{"lot": 1, "figi": "BBG00ZQRGW24", "isin": "US68622V1061", "name": "Organon & Co.", "type": "Stock", "ticker": "OGN.W", "currency": "USD"}

**Comment by AlexanderVolkovTCS** [comment]
Для US73179P1066 установлен FIGI TCS000C8NJ10

**Comment by BaryshevS** [comment]
Почему так много "опечаток" у дублей?

{"lot": 1, "figi": "BBG000BT7ZK6", "isin": "US8356993076", "name": "Sony Corp", "type": "Stock", "ticker": "SNE", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000BT7ZK6", "isin": "US8356993076", "name": "Sony Corp", "type": "Stock", "ticker": "SONY", "currency": "USD", "minPriceIncrement": 0.01}

**Comment by AlexanderVolkovTCS** [comment]
Эти позиции возвращались одновременно? Когда это было?

Сейчас BBG000BT7ZK6 в ответе https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_stocks 
только один:

      {
        "figi": "BBG000BT7ZK6",
        "ticker": "SONY",
        "isin": "US8356993076",
        "minPriceIncrement": 0.01,
        "lot": 1,
        "currency": "USD",
        "name": "Sony Corp",
        "type": "Stock"
      },

**Comment by BaryshevS** [comment]
Когда -то на протяжении года. Все что было сохранялось и такого очень много https://github.com/TinkoffCreditSystems/invest-openapi/issues/579
т.е. получается, кто-то или что-то у Вас меняет figi как хочет и непонятно, что можно купить при этом.
