### ISSUE TITLE
КРИТИКАЛ!!!  orderbook по инструменту у Вас вообще что показывает??? 

### ISSUE THREAD

**Issue by BaryshevS** [TinkoffCreditSystems/invest-openapi#578]
2021-08- 04 -13:15:59
figi -BBG011FHF1F7

Почему стаканы кардинально различаются в OpenAPI и в интерфейсе брокера

`{
          'candle' => {
                        'l' => '995.01',
                        'v' => 6,
                        'c' => '995.01',
                        'interval' => '1min',
                        'time' => 1628071140,
                        'o' => '995.01',
                        'figi' => 'BBG011FHF1F7',
                        'h' => '995.01'
                      },
          'ticker' => 'SU26239RMFS2',
          'orderbook' => {
                           'figi' => 'BBG011FHF1F7',
                           'depth' => 20,
                           'bids' => [
                                       [
                                         '995.01',
                                         6
                                       ]
                                     ],
                           'time' => '-62169982217',
                           'asks' => [
                                       [
                                         '995.2',
                                         20
                                       ],
                                       [
                                         '995.4',
                                         20
                                       ],
                                       [
                                         '995.69',
                                         5
                                       ],
                                       [
                                         '995.7',
                                         21
                                       ],
                                       [
                                         '995.8',
                                         20
                                       ],
                                       [
                                         996,
                                         99978
                                       ],
                                       [
                                         '998.39',
                                         90
                                       ],
                                       [
                                         '998.4',
                                         10
                                       ],
                                       [
                                         '998.69',
                                         180
                                       ]
                                     ]
                         },
          'name' => "ОФЗ 26239"
        }
`

![image](https://user-images.githubusercontent.com/44605985/128165175-42fe22be-6424-404a-b6c0-194d5fd225c8.png)

**Comment by AlexanderVolkovTCS** [comment]
Уточните, на картинке терминала 995,01-995,20 и в json тоже. О каких кардинальных различиях речь?

**Comment by BaryshevS** [comment]
посмотрите  только одна цена "bids" на 6 лотов, а в терминале много.


 'bids' => [ [ '995.01', 6 ] ], 'time' => '-62169982217', 'asks' => [ [ '995.2', 20 ], [ '995.4', 20 ], [ '995.69', 5 ], [ '995.7', 21 ], [ '995.8', 20 ], [ 996, 99978 ], [ '998.39', 90 ], [ '998.4', 10 ], [ '998.69', 180 ] ] }

**Comment by AlexanderVolkovTCS** [comment]
Для максимальной скорости стакан доставляется асинхронно, по протоколу без подтверждения прочтения, поэтому очень редко, но бывают пропуски. Также подобная ситуация может быть после старта сервиса (например после перезагрузки) или старта подписки. 
Если же ситуация повторяется периодически  -  просьба переоткрыть тикет с указанием времен подобных инцидентов и бумаг.

**Comment by BaryshevS** [comment]
В терминале стакан меняется, а события не приходят
![image](https://user-images.githubusercontent.com/44605985/128307711-837cb52b-0b5b-465a-903b-f3666b2c86cf.png)
50004 - 995
![image](https://user-images.githubusercontent.com/44605985/128307736-39b11c83-e6e6-414a-9e31-92183b5a0629.png)
50007 - 995

**Comment by mlshvdv** [comment]
@BaryshevS видимо связано с этим #323
