### ISSUE TITLE
Почему так много опечаток и дублей figi

### ISSUE THREAD

**Issue by BaryshevS** [TinkoffCreditSystems/invest-openapi#579]
Почему так много "опечаток" у дублей?

{"lot": 1, "figi": "BBG000BT7ZK6", "isin": "US8356993076", "name": "Sony Corp", "type": "Stock", "ticker": "SNE", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000BT7ZK6", "isin": "US8356993076", "name": "Sony Corp", "type": "Stock", "ticker": "SONY", "currency": "USD", "minPriceIncrement": 0.01}

**Comment by BaryshevS** [comment]
{"lot": 1, "figi": "BBG00ZQRGW24", "isin": "US68622V1061", "name": "Organon & Co.", "type": "Stock", "ticker": "OGN.W", "currency": "USD"}
{"lot": 1, "figi": "BBG00ZQRGW24", "isin": "US68622V1061", "name": "Organon & Co.", "type": "Stock", "ticker": "OGN", "currency": "USD", "minPriceIncrement": 0.01}

**Comment by BaryshevS** [comment]
{"lot": 1, "figi": "BBG000BGLRN3", "isin": "US1567001060", "name": "CenturyLink", "type": "Stock", "ticker": "CTL", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000BGLRN3", "isin": "US1567001060", "name": "CenturyLink", "type": "Stock", "ticker": "LUMN", "currency": "USD", "minPriceIncrement": 0.01}

**Comment by BaryshevS** [comment]
{"lot": 1, "figi": "BBG000BHJWG1", "isin": "US05464C1018", "name": "Axon Enterprise Inc", "type": "Stock", "ticker": "AAXN", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000BHJWG1", "isin": "US05464C1018", "name": "Axon Enterprise Inc", "type": "Stock", "ticker": "AXON", "currency": "USD", "minPriceIncrement": 0.01}

**Comment by BaryshevS** [comment]
{"lot": 1, "figi": "BBG000FQXC75", "isin": "US7240781002", "name": "Piper Jaffray Cos", "type": "Stock", "ticker": "PJC", "currency": "USD"}
{"lot": 1, "figi": "BBG000FQXC75", "isin": "US7240781002", "name": "Piper Jaffray Cos", "type": "Stock", "ticker": "PJC", "currency": "USD"}

**Comment by BaryshevS** [comment]
{"lot": 1, "figi": "BBG000P1B7C8", "isin": "US7438151026", "name": "Providence Service Corp The", "type": "Stock", "ticker": "PRSC", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000P1B7C8", "isin": "US7438151026", "name": "Providence Service Corp The", "type": "Stock", "ticker": "PRSC", "currency": "USD", "minPriceIncrement": 0.01}

**Comment by BaryshevS** [comment]
{"lot": 10, "figi": "BBG001BBGNS2", "isin": "RU000A0JXKG3", "name": "Обувь России", "type": "Stock", "ticker": "OBUV", "currency": "RUB", "minPriceIncrement": 0.05}
{"lot": 10, "figi": "BBG001BBGNS2", "isin": "RU000A0JXKG3", "name": "Обувь России", "type": "Stock", "ticker": "ORUP", "currency": "RUB", "minPriceIncrement": 0.05}

**Comment by AlexanderVolkovTCS** [comment]
Это не опечатки и не дубли, со временем идентификаторы на биржах могут меняться, например:
http://obuvrus.ru/investors/news_events/707/47233/

**Comment by BaryshevS** [comment]
> Это не опечатки и не дубли, со временем идентификаторы на биржах могут меняться, например:
> http://obuvrus.ru/investors/news_events/707/47233/

Очень хочется какой-то инструмент для отслеживания данных вещей (что на что меняется).
Если меняется и тикер, и figi и isin с названием, то вообще сложо понять, что это было.

Вот тут: еслибы и figi поняли был бы эпик фейл

{"lot": 1, "figi": "BBG000P1B7C8", "isin": "US7438151026", "name": "Providence Service Corp The", "type": "Stock", "ticker": "PRSC", "currency": "USD", "minPriceIncrement": 0.01}
{"lot": 1, "figi": "BBG000P1B7C8", "isin": "US60783X1046", "name": "ModivCare Inc.", "type": "Stock", "ticker": "MODV", "currency": "USD", "minPriceIncrement": 0.01}

**Comment by AlexanderVolkovTCS** [comment]
>Очень хочется какой-то инструмент

Подумаем над новостной лентой корпоративных событий

>Если меняется и тикер, и figi и isin с названием, то вообще сложо понять, что это было.


figi - первичный идентификатор и ориентироваться надо на него. Все остальное - параметры бумаги и они могут быть изменены.
