### ISSUE TITLE
Добавить поддержку социальных функций и новостей

### ISSUE THREAD

**Issue by iLeonidze** [TinkoffCreditSystems/invest-openapi#58]
Сейчас отсутствует какая-либо функциональность, связанная с социальными профилями платформы, пульсом, фида, новостями, комментариями, историей сделок. Пока что можно выкрутиться только закрытым API, по которому вся информация закрыта.

**Comment by NikitaMelnikov** [comment]
Могли бы подсказать ваш кейс использования через апи?

**Comment by iLeonidze** [comment]
Получение ленты/комментариев, техническая оценка настроения рынка

**Comment by NikitaMelnikov** [comment]
Пока что мы не готовы к предоставлению социальных функций и фида в OpenApi. 
Сконцентрируемся на функциональности для торговли
