### ISSUE TITLE
Неверное отображение списка аккаунтов

### ISSUE THREAD

**Issue by Freeongoo** [TinkoffCreditSystems/invest-openapi#581]
Создал еще один брокерский аккаунт. Аккаунт успешно оформили. 
Пытаюсь получить список аккаунтов через API: api.getUserContext().getAccounts() и получаю в списке только один брокерский аккаунт. Второй созданный аккаунт не отображается.

**Comment by KirillKaverin** [comment]
суб-счета (кроме основного брокерского и ИИС) не отображаются и не работают в OpenAPI

**Comment by Freeongoo** [comment]
это прям мега неудобно. Когда планируется добавить этот функционал?

**Comment by AlexanderVolkovTCS** [comment]
Да, мультисчета не поддерживаются, функционал будет доступен в новой версии осенью.
