### ISSUE TITLE
Приходят ошибочные цены свеч при подписке на StreamingEvent.Candle

### ISSUE THREAD

**Issue by Freeongoo** [TinkoffCreditSystems/invest-openapi#582]
В 2021-08-04 15:18:05,013 по UTC (2021-08-04 18:18:05,013 по МСК) наблюдал такую картину по тикету 'NVDA', при подписке на стримовую свечу, прилетела цена закрытия равная 199.94$. Если потом обратиться к историческим свечам за это время, то данной цены даже и рядом не было. В этом интервале минимальная цена за 2021-08-04 15:15:00 равна 201.4$ за 2021-08-04 15:20:00 равна 200.79$.

Как бы не совсем понятно откуда такая цена? Может ли это быть баг?

Поскольку данная цена не отображается на исторических свечах, то это вдвойне странно.
Постил эту проблему в invest-openapi-java-sdk, но сказали что это проблема сюда.

**Comment by nonamegithub** [comment]
[На стриминговые данные полагаться нельзя.](https://github.com/TinkoffCreditSystems/invest-openapi/issues/323) Есть мнение, что  потоковые стакан и свечи формируются с помощью ГСЧ. По крайней мере, разработчики до сих пор не ответили на вопрос о природе появления данных в них.

**Comment by BaryshevS** [comment]
Делайте задержки и подтверждения факта до реакции на цену. Работайте лимитками. Априори данные искажены. Вариант еще подключаться к нескольким API и мониторить отовсюду. Другого тут не придумаешь.

**Comment by Freeongoo** [comment]
@nonamegithub вот это поворот) тогда если на эти данные полагаться нельзя и уже давно есть баги по искажениям цен, тогда непонятно зачем вообще этот функционал есть и люди им пользуются. Нужно тогда указать в API, что стриминговыми ценами пользуйтесь только для тестирования или для развлечения, но не для реальных торгов.

**Comment by BaryshevS** [comment]
Самый надежный вариант подключение к конкретным биржам, а это немного другой уровень цен и сложности. По этому иметь REST API от Тинькофф это почти лучшее, что сейчас есть на российском рынке.

**Comment by Freeongoo** [comment]
@BaryshevS не согласен, когда у тебя четкий алгоритм по формированию позиций, а прилетает цена на 1$ ниже и выбивает позиции и статистика портится вся. Тут как бы я не стал говорит, что это нормально и с этим можно жить. Тут нужно допиливать, чтобы этого не было, а не говорит, что "и так сойдет"

**Comment by BaryshevS** [comment]
Вероятность и прилета чего-то не того, а так же реальных проскальзываний из-за ошибок биржи. Все это есть. Твой алгоритм должен это учитывать.Если у тебя арбитраж в зоне 0,5%, ну.. сорян. Нужно и данные по точнее и подключения по быстрее. Я конечно "за все хорошее" и против "всего плохого". 
Тут получается как: 

1) nvidia nasdaq 
2) spb биржа (там 2 очереди заявок.. х.з. зачем. типо внутренняя "форекс" кухня. Типо локальный рынок для россиян и глобальный. Где разместилась заявка х.з.)
3) Очереди Тинькофф (лаги серверов брокера. заявка доставлена брокеру, а на бирже ее еще может и не быть.)

Т.е. как котировки, так и приказы проходят много разных посредников. Так же свечи/стаканы могут по разному считаться.  (в т.ч. из-за питерской биржи. Они сливают 2 стакана - локальный и глобальный в один)

По этому и говорю, что стоит относиться к данный, не как 100% точным. Делать задержку в принятии решения, а так же получать подтверждение полученным данным (10сек, к примеру) При этом выбирать время работы целевой биржи (например насдак), а так же выбирать  часы с правильной волатильностью.

**Comment by nonamegithub** [comment]
> Нужно тогда указать в API, что стриминговыми ценами пользуйтесь только для тестирования или для развлечения, но не для реальных торгов

Я сам отказался от использования потоковых данных в пользу rest-запросов. Мое мнение однозначно: лучше вообще не стримить, чем стримить непонятно что.

**Comment by Freeongoo** [comment]
@nonamegithub да, наверное надежнее использовать rest-запросы. Но у меня алгоритм такой, что нужно мгновенно реагировать на динамику изменения цены и при rest-запросах, получается, что я не укладываюсь в лимит по запросам и все вообще перестает работать, поскольку апи просто перестает отвечать. Печально как-то это все. Тогда бы разрабы увеличили лимиты по запросам.

**Comment by nonamegithub** [comment]
Мгновенно реагировать на динамику изменения цены с rest-запросами никак не получится.  Минимальная дискретность свечи - 1 минута. Причем свеча за предыдущую минуту становится доступной только с пятой-шестой секунды текущей. Увеличение лимитов по запросам не поможет никак(

**Comment by AlexanderVolkovTCS** [comment]
@BaryshevS верно ответил, спасибо, все так.
В других issue (#323) это уже обсуждалось, данные с потоков лучше проверять дополнительно.
