### ISSUE TITLE
Количество подписок на свечи

### ISSUE THREAD

**Issue by Freeongoo** [TinkoffCreditSystems/invest-openapi#585]
Не совсем понятно, в документации указано, что при использовании протокола streaming: "Доступно 6 TCP-соединений на одного пользователя."
То это значит, что можно подписаться не больше чем на 6 различных figi? Если я подпишусь на 12 figi, то будут приходить свечи только по 6 figi или все таки по 12 figi? Или будет приходить по 12 figi, но часть данных будет не приходить, поскольку органичение до 6 TCP?

**Comment by BaryshevS** [comment]
Нет. вы можете подключиться с 6 разных серверов. В каждом подключение Вы можете подписаться на любое кол-во событий/фиги и т.п.. Главное, чтобы Вы успевали их обработать. (есть вариант повторной досылки сообщений. проверяйте time)

**Comment by Freeongoo** [comment]
@BaryshevS так я же не могу управлять количество TCP-соединений. это делает сам API. Что значит подключиться с 6 разных серверов?

**Comment by AlexanderVolkovTCS** [comment]
@Freeongoo на каждого пользователя допускается создание до 6 вебсокет-соединений. В каждом можно подписаться на произвольное количество figi. Рекомендуем до 50 подписок на соединение, а если бумаги высоколиквидные - то до 30.
Но если не будете успевать читать передаваемые данные, соединение будет разрываться сервером.

**Comment by Freeongoo** [comment]
@AlexanderVolkovTCS спасибо!
