### ISSUE TITLE
Цена купли или продажи по истории операций

### ISSUE THREAD

**Issue by Freeongoo** [TinkoffCreditSystems/invest-openapi#586]
Как узнать из списка операций (Operation) по какой цене куплен или продан лот?

В таблице Operation я так понял для этого могут быть два поля:

```
  @JsonProperty("payment")

  private java.math.BigDecimal payment = null;

  @JsonProperty("price")

  private java.math.BigDecimal price = null;
```
вопрос в том, какое из них показывает цену купли или продажи?

**Comment by ddmrtc** [comment]
Если тип операции Buy, то куплен, если тип операции Sell то продан

Price - цена лота
Payment - всего, т.е. Price * lot

Так же тип операции можно понять по знаку payment, отрицательный -
потрачено, т.е. куплено, положительный - начислено, т.е. продано

Еще в trades находится массив конкретных сделок

Что бы узнать за сколько куплено, то нужно сопоставить операции
самостоятельно по FIFO.

Ср, 11 авг. 2021 г. в 14:15, Freeongoo ***@***.***>:

**Comment by Freeongoo** [comment]
@ddmrtc  спасибо!
