### ISSUE TITLE
Операция приходит с ценой 0

### ISSUE THREAD

**Issue by vbwp** [TinkoffCreditSystems/invest-openapi#589]
Добрый день.
Почему в API по указанной операции поля price и payment приходят 0, в то время как в интерфейсе данные есть?
https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/operations/get_operations
![image](https://user-images.githubusercontent.com/89035413/129602504-f4c76a4a-5a48-4aca-8bfa-cea0295ea960.png)

**Comment by Freeongoo** [comment]
тоже столкнуля с этим: https://github.com/TinkoffCreditSystems/invest-openapi/issues/588

**Comment by AlexanderVolkovTCS** [comment]
Во время инцидентов подобные ошибки обычно совпадают и в мобилке и в API, так как источник данных - один. Если подскажете tracking_id запроса - можем посмотреть детальнее.
Общую проблематику оставим в #588
