### ISSUE TITLE
Адекватное отображение выпущенных токенов в личном кабинете

### ISSUE THREAD

**Issue by InsightAppDev** [TinkoffCreditSystems/invest-openapi#59]
Добрый день.
На данный момент токены в [личном кабинете](https://id.tinkoff.ru/account) отображаются как активные сессии. Если есть возможность, добавьте информацию о том, какой это токен - песочница/торговый, когда и с какого ip выпущен.

**Comment by NikitaMelnikov** [comment]
Да, уже работает над этим

**Comment by NikitaMelnikov** [comment]
Fixed
