### ISSUE TITLE
Опубликовал библиотеку на R 

### ISSUE THREAD

**Issue by arbuzovv** [TinkoffCreditSystems/invest-openapi#591]
Опубликовал библиотеку для работы с API на R. Добавьте в список неофициальных, пожалуйста:
https://github.com/arbuzovv/tcsinvest
Выложил на CRAN:
https://cran.r-project.org/web/packages/tcsinvest/index.html

**Comment by AlexanderVolkovTCS** [comment]
Добавил ссылку в документацию
