### ISSUE TITLE
Объемы продажи/покупки

### ISSUE THREAD

**Issue by Pykhto** [TinkoffCreditSystems/invest-openapi#592]
Просьба к разработчикам добавить в данные, выдаваемы по свече, объем продаж и объем покупок, отдельно, а не как сейчас, в виде результирующего.

**Comment by QiXi** [comment]
Если кто-то продал 1 стул, то и кто-то купил 1 стул.

**Comment by BaryshevS** [comment]
Лучше просто дать возможность подписываться на "ленту сделок" по инструментам.

**Comment by Pykhto** [comment]
> Лучше просто дать возможность подписываться на "ленту сделок" по инструментам
Соглашусь, это получше будет.

**Comment by AlexanderVolkovTCS** [comment]
@QiXi все верно

>Лучше просто дать возможность подписываться на "ленту сделок" по инструментам.

есть в #22
