### ISSUE TITLE
В списке операций не приходят операции погашения и купонов для погашенных облигаций

### ISSUE THREAD

**Issue by greymag** [TinkoffCreditSystems/invest-openapi#594]
20/08/2021 была выплата купонов по облигации и ее погашение `SU26217RMFS8`. В ЛК это отображается, но API эти операции не возвращает.

Есть схожая задача #324, там был ответ со смыслом что тикер не доступен в Open API. Я проверил тикер `SU26217RMFS8` - сейчас для него действительно возвращается пустой список 

`{"trackingId":"4e67ffeac5e2a603","payload":{"instruments":[],"total":0},"status":"Ok"}`

Но до погашения данные по тикеру возвращались - у меня остались более ранние выгрузки. 

Т.е. получается очевидный баг: я в принципе не могу получить операции по погашенным облигациям, т.к. после погашения они становятся недоступны. И список операций становится неполным.

**Comment by AlexanderVolkovTCS** [comment]
К сожалению, сейчас бумаги, прошедшие делистинг или уже погашенные недоступны в операциях. 
В новой версии в операциях будет возвращаться все.
