### ISSUE TITLE
Необходим стрим в котором происходит уведомления о всех сделках

### ISSUE THREAD

**Issue by Gordondalos** [TinkoffCreditSystems/invest-openapi#596]
На данный момент если выставить заявку никак нельзя понять выполнилась она или нет, для того чтобы понимать актуальность портфеля нужно все время пере запрашивать портфолио через интервал.
Былобы удобно если бы клиента можно было уведомлять на все сделки происходящие в его портфеле

**Comment by AlexanderVolkovTCS** [comment]
#43
