### ISSUE TITLE
Необходима подписка показывающая реальную сумму брокерского счета

### ISSUE THREAD

**Issue by Gordondalos** [TinkoffCreditSystems/invest-openapi#597]
На данный момент механизм расчета суммы в портфеле (хотя бы итого) не ясен совсем.
Можно конечно как то сложить все бумаги в портфеле перемножив их на последние цены, но результат сильно контрастирует с ценой в мобильном приложении и с ценой в веб версии, в результате нельзя точно сказать сколько сейчас денег в портфеле через апи и приходится смотреть в телефон или веб

**Comment by AlexanderVolkovTCS** [comment]
В существующей версии не отображаются позиции по валютам, отличным от USD и EUR, а также внебиржевые позиции.
В остальном результат вызова метода портфолио должен совпадать с мобилкой/терминалом.
