### ISSUE TITLE
Как связать операции между собой?

### ISSUE THREAD

**Issue by xkrt** [TinkoffCreditSystems/invest-openapi#60]
Привет,

Получив список операций, как их связать между собой? Например, покупку и комиссию брокера за неё. Сейчас, насколько я понимаю, можно связать только эвристически (по figi + дата/времени), что представляется мне ненадёжным и кривым решением (особенно представьте, если за 1 день прошло несколько операций по одной и той же бумаге или в случае каких-то проблем комиссия спишется позже). Хотелось бы видеть во всех "связанных" операциях (таких как BrokerCommission) новое поле, указывающее на id "исходной" операции (покупки/продажи).

Что имеем сейчас.

Покупка:
```json
{
  "operationType": "Buy",
  "date": "2019-10-29T13:29:18.263409+03:00",
  "isMarginCall": false,
  "instrumentType": "Stock",
  "figi": "BBG000C46HM9",
  "quantity": 10,
  "price": 15.5,
  "payment": -155,
  "currency": "USD",
  "commission": {
    "currency": "USD",
    "value": -0.47
  },
  "trades": [
    {
      "tradeId": "159039800",
      "date": "2019-10-29T13:29:18.263409+03:00",
      "quantity": 10,
      "price": 15.5
    }
  ],
  "status": "Done",
  "id": "83533431810"
}
```

Комиссия брокера:
```json
{
  "operationType": "BrokerCommission",
  "date": "2019-10-29T13:29:18.263409+03:00",
  "isMarginCall": false,
  "instrumentType": "Stock",
  "figi": "BBG000C46HM9",
  "payment": -0.47,
  "currency": "USD",
  "status": "Done",
  "id": "-1"
}
```

По операции комиссии однозначно не понятно по какой конкретно операции была эта комиссия.

**Comment by lightning95** [comment]
в самой операции покупки/продажи уже есть размер комиссии соответствующей ей операции-комиссии:
```
 "commission": {
    "currency": "USD",
    "value": -0.47
  },
```
```
"payment": -0.47,
  "currency": "USD",
```
отображение операции с типом "Комиссия брокера" отображается для удобства

**Comment by xkrt** [comment]
@lightning95 в таком случае, в конкретно моём кейсе использования API, необходимости в parentId похоже нет
