### ISSUE TITLE
Добавить хоть какие нибудь новости 

### ISSUE THREAD

**Issue by Gordondalos** [TinkoffCreditSystems/invest-openapi#600]
В своем приложении хочется видеть новости от банка, возможно аналитические истории, прогнозы, подписки и так далее.
Былобы круто иметь подписку или какую то открытую рсс ленту, которую можно вывести и почитать

**Comment by AlexanderVolkovTCS** [comment]
экспорт прогнозов и новостей пока не планируется через api
