### ISSUE TITLE
/user/accounts возвращает не все счета

### ISSUE THREAD

**Issue by AUObukhov** [TinkoffCreditSystems/invest-openapi#603]
У меня зарегистрировано 3 счета, однако метод возвращает только 2 первых (2008941383 и 2000124699)

**Comment by BaryshevS** [comment]
Сейчас возвращается только основой и ИИС. остальные не выводятся в API

**Comment by QiXi** [comment]
Просто взяли и закрыли таску? Если вы планируете это делать, то сообщите человеку.

**Comment by AlexanderVolkovTCS** [comment]
Будет в новой версии. 
Для этого предложения есть активный тикет #533
