### ISSUE TITLE
По акции РУСАЛ невозможно получить данные

### ISSUE THREAD

**Issue by mr-amirka** [TinkoffCreditSystems/invest-openapi#606]
При запросе свечей  за любой период по акции РУСАЛ всегда возвращается пустой массив.
```json
{
  "figi":"BBG008F2T3T2",
  "ticker":"RUAL"
}
```

Метод ``` api.candlesGet ```

По всем остальным акциям всё успешно возвращается.

Посмотрел в приложении Тинькофф Инвестиции. РУСАЛ активно торгуется.
Думаю, это баг.

**Comment by AlexanderVolkovTCS** [comment]
Верно, получить котировки _old бумаг не получится, 
актуальная бумага Русала - BBG008F2T3T2.
Рекомендуем дополнительно проверять доступность бумаг к торгам посредством анализа статуса в подписке instrument_info

**Comment by S-DyX** [comment]
Добрый день, сейчас мне возвращается информация по позициям в портфеле Русал как TCS008F2T3T2, хотя до этого я покупал их как BBG008F2T3T2.
