### ISSUE TITLE
Лимитная заявка без срока давности

### ISSUE THREAD

**Issue by uxumax** [TinkoffCreditSystems/invest-openapi#607]
Как через API сделать лимитную заявку на покупку или продажу без срока давности? Все, что отправляются по дефолту, отменяются через сутки.

**Comment by AlexanderVolkovTCS** [comment]
Все верно, заявки автоматически снимаются биржей по завершении торговой сессии.

Для долгосрочных целей предусмотрены стоп-заявки, их можно:
* подать вручную через приложение или терминал
* подождать новой версии API, там появится интерфейс для их выставления
* выставлять заявку ежедневно через API
