### ISSUE TITLE
Ошибка "Unknown account" и проблема в методе "api.accounts".

### ISSUE THREAD

**Issue by mr-amirka** [TinkoffCreditSystems/invest-openapi#609]
Несколько недель назад я создал второй броекрский счёт в Тинькофф Инвестиции.
При попытке получения всех своих счетов методом "api.accounts", не вижу новый счёт среди перечня всех своих счетов. Отобрадается только два моих счёта: один основной брокеский и один счёт ИИС. Нового брокерского счёта в перечне нет, хотя в приложении Тинькофф Инвестиции он точно есть, и я на него даже перевёл средства.

Через личный кабинет я нашел идентфикатор своего нового брокерского счёта, и попытался установить его текущим с помощью метода "api.setCurrentAccountId". В результате получил ошибку:
```js
{
  trackingId: '93e7c0e9f6667580',
  payload: { message: 'Unknown account', code: 'GATEWAY_REQUEST_DATA_ERROR' },
  status: 'Error'
}
```

Как можно устранить эти проблемы?

**Comment by mlshvdv** [comment]
@mr-amirka https://tinkoffcreditsystems.github.io/invest-openapi/faq_multiaccounts/

> Поддерживаются ли сейчас мультисчета в openAPI?
> **Поддержка мультисчетов в openAPI в процессе разработки**. Работаем над этим.
