### ISSUE TITLE
/market/search/by-ticker не находит некоторые инструменты

### ISSUE THREAD

**Issue by griddic** [TinkoffCreditSystems/invest-openapi#61]
Список тикеров по которым не находится инструмент:
  - [XS1589324075](https://www.tinkoff.ru/invest/bonds/XS1589324075/)
  - [RU000A100JE7](https://www.tinkoff.ru/invest/bonds/RU000A100JE7/)
  - [RU000A100WF7](https://www.tinkoff.ru/invest/bonds/RU000A100WF7/)
  - [RU000A100VQ6](https://www.tinkoff.ru/invest/bonds/RU000A100VQ6/)
  - [RU000A100XP4](https://www.tinkoff.ru/invest/bonds/RU000A100XP4/)
  - [RU000A1004G9](https://www.tinkoff.ru/invest/bonds/RU000A1004G9/)

Например для [RU000A100WF7](https://www.tinkoff.ru/invest/bonds/RU000A100WF7/)
Запрос 
```bash
curl -X GET \
  'https://api-invest.tinkoff.ru/openapi/market/search/by-ticker?ticker=RU000A100WF7' \
  -H 'Authorization: Bearer *****' 
```
Возвращает пустой список:
```json
{
    "trackingId": "448e146834f79b0a",
    "payload": {
        "instruments": [],
        "total": 0
    },
    "status": "Ok"
}
```

По остальным тикерам та же ситуация.

**Comment by lightning95** [comment]
спасибо, эти бумаги теперь добавлены и в OpenAPI
