### ISSUE TITLE
Запрос истории не возвращает последнюю свечу

### ISSUE THREAD

**Issue by BusinessDuck** [TinkoffCreditSystems/invest-openapi#610]
1. Сменилось время с 22:20 на 22:21
2. Запрашиваем свечи до 22:21:30 (+30 секунд прошло)
3. Получаем свечи до 22:20, не закрытая свеча с меткой времени 22:21 не будет в ответе

Бага не в сдк, тк прибавление любого количества секунд и запрос свеч с захлестом на будущее (даже если час прибавить) все равно не решает проблему, очевидно свечи еще нет в бд API

Получается база данных свеч формируется из m1 свечь и нужная свеча появится только на 22:23 временной отметке.
Binance например возвращает все известные данные, даже если свеча не закрыта, он вернет ее в том состоянии в котором она сейчас. Бага похоже не в сдк js версии, бага в самом API. Можно ли это исправить?

Ожидаемое поведение:
Запрос свечи на текущее время `Date.now()` должен возвращать все свечи включая текущую, в ее текущем не закрытом состоянии.

**Comment by nonamegithub** [comment]
https://github.com/TinkoffCreditSystems/invest-openapi/issues/475

**Comment by AlexanderVolkovTCS** [comment]
В rest-ах маркетдаты текущей незакрытой минуты не будет для соблюдения консистентности и возможности кеширования. Для оперативного получения актуальных используйте стрим.
