### ISSUE TITLE
Цена акции через N тиков

### ISSUE THREAD

**Issue by sined23** [TinkoffCreditSystems/invest-openapi#612]
Добрый день. Можете плиз добавить

1) В streaming подписку на цену акции через N тиков. Т.е. прошло N тиков присылаем прайс, прошло ещё N тиков опять присылаем прайс и т.д. N может быть произвольным или, скажем, 50, 100, 150, 200 и т.д.
2) В rest тоже бы добавить возможность получение N тиковых данных за определённый интервал.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день,
привязку к тикам не планируем, рекомендуем подписываться на свечи.
