### ISSUE TITLE
Запрос операций падает если их количество очень большое 

### ISSUE THREAD

**Issue by EJohnF** [TinkoffCreditSystems/invest-openapi#619]
Здравствуйте.

Заметил такую не задукоментированную проблему. 
Если загружать операции через `https://api-invest.tinkoff.ru/openapi/operations` за период больше года, и в выдаче ожидается больше 100к операций - всегда возвращается ответ 
```
{
  trackingId: '4e15c4a97241c27b',
  payload: { message: 'INTERNAL_ERROR', code: 'INTERNAL_ERROR' },
  status: 'Error'
}
```

При этом если уменьшить интервал, например до 3х месяцев, то операции успешно возвращаются (примерно 35к). 
Не искал точной границы, при каком количестве операций произойдёт падение. 

Конечно, есть решение загрузки операций по-месячно, или по-недельно. 
Но и с вашей стороны хотелось бы, пожалуйста, увидеть более говорящую ошибку, нежели просто 'INTERNAL_ERROR' 

А ещё лучше возможность добавления фильтров к запросу операций. Например только те, что со статусом `Done`.
Кстати это и для приложения фильтры были бы полезны - а то когда много отклонённых заявок, список операций становиться не-юзабельным.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день,
Да, в сервисе операций есть ограничения, слишком большие ответы не возвращаются.

В подобном случае рекомендуем или уменьшить запрашиваемый интервал, либо запрашивать список операций по конкретному инструменту (FIGI)
