### ISSUE TITLE
Покупка валюты маленькими лотами.

### ISSUE THREAD

**Issue by griddic** [TinkoffCreditSystems/invest-openapi#62]
В мобильном приложении можно покупать доллар лотами по одной штуке. 

В openapi есть инструмент

```
        "instruments": [
            {
                "figi": "BBG0013HGFT4",
                "ticker": "USD000UTSTOM",
                "minPriceIncrement": 0.0025,
                "lot": 1000,
                "currency": "RUB",
                "name": "Доллар США"
            }
        ],
```
, но у него лот 1000 долларов. 

Скажите пожалуйста, есть ли возможность через openapi покупать/продавать валюту маленькими лотами? И, если есть, какой инструмент для этого использовать?

**Comment by NikitaMelnikov** [comment]
Добрый день, 
В OpenApi можно выставлять заявки на валюту только в полном объеме, для биржи полный лот - это 1000

https://www.moex.com/en/issue/EUR_RUB__TOM/CETS

```
Lot size | 1 000
```
