### ISSUE TITLE
hedging

### ISSUE THREAD

**Issue by Alik-msk** [TinkoffCreditSystems/invest-openapi#620]
Придумайте хоть что нибудь, что бы можно было создавать/закрывать/уменьшать обьем у отдельного ордена.
 Смысл в возможности -хеджирования, так как без этого вся эта торговля превращается в игру однорукого бандита.
Пример: мы имеем на одном инструменте около 12 сделок, где 5 в покупку, остальное в продажу.причем эти сделки имеют разный объем, где то это в покупку 2лота+1 лот+2лота, и в тоже время в шорт 6 лотов+2. Понятное дело, что закрывать мы должны те сделки какие укажем, а не последние.

**Comment by AlexanderVolkovTCS** [comment]
Если суть Вашего запроса в том, чтобы добавить метод, изменяющий параметры уже созданного ордера - то в ближайшее время такого метода не планируется.
