### ISSUE TITLE
Вывод средств на привязанную карту

### ISSUE THREAD

**Issue by merrymaker14** [TinkoffCreditSystems/invest-openapi#622]
Хотелось бы функцию вывода валюты на свою карту (Тинькофф). Например, я торгую только на 300 тысяч, а прочее после продажи возросшего актива хотел бы выводить со счета.

**Comment by AlexanderVolkovTCS** [comment]
Через API вывода средств на карту в ближайшее время не будет.

**Comment by BaryshevS** [comment]
Лучше эту фичу никогда не реализовывать или сделать возможность запретить в аккаунте.
