### ISSUE TITLE
Как получить текущую цену акции?

### ISSUE THREAD

**Issue by merrymaker14** [TinkoffCreditSystems/invest-openapi#623]
Думал, что методы `market/search/..` или `/market/stocks` будут возвращать текущую цену, но ее там нет.

**Comment by akbudarin** [comment]
Привет, узнал?

**Comment by AlexanderVolkovTCS** [comment]
Если под текущей ценой подразумеваете цену последней сделки, то можно:
1) либо запрашивать market/orderbook и там брать lastprice
2) либо подписываться на стрим свечей и получать цену в поле close
