### ISSUE TITLE
Добавить индексы.

### ISSUE THREAD

**Issue by kitMP** [TinkoffCreditSystems/invest-openapi#624]
Добавить данные по индексам S&5 500, Nasdaq и .т.д. Очень не хватает.

**Comment by Alik-msk** [comment]
Согласен. Причем они нужны не только для торговли, сколько для анализа текущей ситуации. Те есть для терминала было бы полезно иметь окно где отображены в миниатюре сразу 3-4индекса s&p500,dax,nikei, brent.

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, индексов пока нет, но продумаем этот вопрос.
А синтетических пар пока точно не будет.

**Comment by kitMP** [comment]
> Добрый день, индексов пока нет, но продумаем этот вопрос. А синтетических пар пока точно не будет.
В мобильном приложении уже есть и индексы и стоимости бочки и золота, серебра, платины, паладия.
