### ISSUE TITLE
Если смысл писать свой настольный терминал на java?

### ISSUE THREAD

**Issue by Alik-msk** [TinkoffCreditSystems/invest-openapi#625]
Мешает  для этого неопределость на валютной секции, так как именно на ней больше всего опыта и понимание того что нужно, но нет у вас.
 -минимальный порог входа для депозита
-отсутствие ГО
-Особой расчет плечей при котором, цена инструмента уменьшается.*
-возможность хеджировния
-добовление новых инструментоввалютных пар,индексов
-торговля внутри банка/песочницы.смысл в уверенности закрытии по указанным ценам.

*1лот 1000$ плечо 1:1, 
*1лот 100$ плечо 1:10, 
*1лот 10$ плечо 1:100, 
*1лот 1$ плечо 1:1000, 
*1лот 0.10$ плечо 1:10000
ЗЫ
Терминал должен быть заточен под валютную  торговлю внутри дня, хеджирование и глубокий анализ сделок.

**Comment by AlexanderVolkovTCS** [comment]
В Тинькофф Инвестициях, в отличие от форекс-брокеров, логика маржинальной торговли иная, почитайте пожалуйста  - https://help.tinkoff.ru/margin-trade/
