### ISSUE TITLE
Кол-во доступных лотов рыночной заявки

### ISSUE THREAD

**Issue by merrymaker14** [TinkoffCreditSystems/invest-openapi#626]
Как самому реализовать функционал рыночной заявки? Есть доллары на счете, нет цены акции (но ее можно спарсить), а как от этого оттлакиваться?

**Comment by AlexanderVolkovTCS** [comment]
Например, взять лучшую цену встречного предложения из market/orderbook и подать лимитную заявку по этой цене.
