### ISSUE TITLE
Request was not processed by the server and should not be retried

### ISSUE THREAD

**Issue by olsh** [TinkoffCreditSystems/invest-openapi#627]
С сегодняшнего дня с 10:00 MSK API начал возвращать ошибки на запрос получения портфеля.
Ошибка либо `Request was not processed by the server and should not be retried` либо пустая строка.

И в приложении заметил что появилась непонятная позиция в портфеле, в истории сделок ее нет. Возможно, что эти события связаны.
![image](https://user-images.githubusercontent.com/3613592/141257413-29cb958e-c1e4-42b9-90fc-c2596afa38d2.png)

**Comment by BaryshevS** [comment]
сказали, что заявку на 
эту багу уже завели

**Comment by olsh** [comment]
Поддержка ответила:
> Компания IBM объявила спин-офф.
Коэффициент распределения 5 к 1. Акционеры получат 1 акцию новой компании Kyndryl Holdings (KD) на каждые 5 акций IBM.

Стало понятно откуда появилась позиция. Но проблема с ошибкой все еще актуальна.

**Comment by olsh** [comment]
Кажется, ошибка ушла. Последнее события было в 11:05.
Спасибо за быстрое реагирование. 👍🏻
