### ISSUE TITLE
Торговля фьючерсами

### ISSUE THREAD

**Issue by XPOMOU** [TinkoffCreditSystems/invest-openapi#629]
Добрый вечер.

А в тинькоф API есть торговля фьючерсами?
Я засыпался на самом начальном этапе, как получить figi по инструменту (например SILV-12.21), как получить текущую цену по нему?

Если кто-то знает ответ, напишите пожалуйста.

**Comment by BaryshevS** [comment]
В это версии api фьючей нет. Обещают в следующей, видимо сразу с опционами :)

**Comment by sergeymavrin** [comment]
@BaryshevS тонко ))
