### ISSUE TITLE
Ошибка RuntimeError: Event loop is closed в python3.8 на Windows

### ISSUE THREAD

**Issue by akudryav** [TinkoffCreditSystems/invest-openapi#630]
На винде возникает ошибка RuntimeError: Event loop is closed
Для решения этого бага нужно добавить перед вызовом asyncio.run

```
if sys.version_info[0] == 3 and sys.version_info[1] >= 8 and sys.platform.startswith('win'):
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

Источник: https://github.com/encode/httpx/issues/914

**Comment by AlexanderVolkovTCS** [comment]
Это в каком SDK?

**Comment by akudryav** [comment]
Python @daxartio
ошибся, перенес issue в тот репозиторий
