### ISSUE TITLE
Получаю пустой массив свечей по ряду инструментов

### ISSUE THREAD

**Issue by crazybee47** [TinkoffCreditSystems/invest-openapi#631]
Добрый день! Я использую golang SDK для выполнения запросов к API. Есть ряд инструментов которые отдают пустой массив свечей за определенные даты, хотя в приложении Тинькофф Инвестиции эти данные есть.

**Разберем на примере тикера SP (SP Plus Corp)**
Запрашиваю свечи за период c `01.11.2020 00:00:00` по `02.11.2020 00:00:00` и получаю пустой ответ candles:[]
URL запроса: `https://api-invest.tinkoff.ru/openapi/market/candles?figi=BBG000BJ91B1&from=2020-11-01T00%3A00%3A00Z&interval=30min&to=2020-11-02T00%3A00%3A00Z`
Ответ: `{"trackingId":"ed14d3fb0c8d738b","payload":{"candles":[],"interval":"30min","figi":"BBG000BJ91B1"},"status":"Ok"}`

Хотя за период после `01.11.2021 00:00:00` я получаю ответ со свечами.

В приложении Тинькофф Инвестиции данные по инструменту SP начинаются с 2012 года, подтверждение на скриншоте ниже.
![2021-11-19 14 14 03](https://user-images.githubusercontent.com/32307323/142613751-79dfa6e5-8512-44c4-8924-bf072e1a3ccf.jpg)

**Вопрос:** могу ли я получить исторические данные по свечам за более ранний период?

P.S. Для разных инструментов разная минимальная дата с результатами.

**Comment by sergeymavrin** [comment]
1.11.2020 - это было воскресенье, торги не велись

**Comment by crazybee47** [comment]
@sergeymavrin я привел эту дату как пример (неудачный). Проблема возникает с любой датой до 01.11.2021. Например мне нужны все данные с 2018 года - пусто.

**Comment by AlexanderVolkovTCS** [comment]
По разным интервалам различная дата начала истории. 
Если Вам нужна истории за более длительный период, то запрашивайте дневные свечи

**Comment by crazybee47** [comment]
@AlexanderVolkovTCS а почему для разных тикеров "длительный период" разный? Я правильно понимаю, что получить часовые/получасовые свечи невозможно для нужных мне инструментов?

**Comment by AlexanderVolkovTCS** [comment]
>а почему для разных тикеров "длительный период" разный?
Разница связана со временем размещения бумаги на бирже, временем начала торгов по данной бумаге в Тинькофф, с корпоративными действиями по этой бумаге и т.д.

>невозможно для нужных мне инструментов?
По большинству бумаг минутная история доступна за 2-3 года
