### ISSUE TITLE
Сервер отвечает код 500

### ISSUE THREAD

**Issue by a1exsan** [TinkoffCreditSystems/invest-openapi#633]
Привет!

Для подключения к ТИнвестиции через API использую python requests, а также пробовал sdk от @daxartio.
Ниже описан примеры запросов и ответы

на запрос:
import requests
import t_tokens

def get_portfolio(token, api):
    headers = {'Authorization': f'Bearer {token}'}
    #response = requests.get(api + 'portfolio', headers=headers).json()
    response = requests.get(api + 'portfolio', headers=headers)
    return response

    api = 'https://api-invest.tinkoff.ru/openapi/'
    token = t_tokens.token_main
    print(get_portfolio(token, api))

получаю ответ:  <Response [500]>

на запрос:
import tinvest 
import t_tokens
token = t_tokens.token_main
client = tinvest.SyncClient(token)
response = client.get_portfolio()

результат:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'SyncClient' object has no attribute 'get_portfolio'

использую торговый токен.
ошибка 500 - это внутренняя ошибка сервера?
В чем может быть проблема?

**Comment by daxartio** [comment]
Используй последнюю версию tinvest
У тебя скорее всего tinvest v2.* из-за python<=3.7. Для последней версии нужно иметь python >= 3.8

**Comment by a1exsan** [comment]
У меня версия 2.3.3 это разве не последняя?

**Comment by a1exsan** [comment]
версия python 3.8.5

**Comment by a1exsan** [comment]
сори версия python 3.7.8

**Comment by a1exsan** [comment]
версия tinvest 3.0.5
