### ISSUE TITLE
ошибка сервера 500 под версией python 3.9.5

### ISSUE THREAD

**Issue by a1exsan** [TinkoffCreditSystems/invest-openapi#634]
Запустил под версией python 3.9.5
Все равно ошибка:

import tinvest
import tokens
TOKEN = tokens.token
client = tinvest.SyncClient(TOKEN)
response = client.get_portfolio() # tinvest.PortfolioResponse
print(response.payload)

Traceback (most recent call last):
File "", line 8, in
File "C:\Users\Alex\PycharmProjects\pythonProject2\venv\lib\site-packages\tinvest\clients.py", line 631, in get_portfolio
return portfolio_get(
File "C:\Users\Alex\PycharmProjects\pythonProject2\venv\lib\site-packages\tinvest\apis.py", line 225, in portfolio_get
return request('GET', '/portfolio', response_model=PortfolioResponse, **kwargs)
File "C:\Users\Alex\PycharmProjects\pythonProject2\venv\lib\site-packages\tinvest\clients.py", line 537, in _request
raise UnexpectedError(response.status_code, response.text)
tinvest.exceptions.UnexpectedError: 500 {"trackingId":"b51ca6ec362c6430","payload":{"message":"Unknown account","code":"GATEWAY_REQUEST_DATA_ERROR"},"status":"Error"}

**Comment by AlexanderVolkovTCS** [comment]
тут может @daxartio подробнее подскажет, но попробуйте указать номер основного торгового счета.

**Comment by daxartio** [comment]
https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/portfolio/get_portfolio

Номер счета необязательный параметр. У клиента нет счета? Я не знаю какая логика на сервере, можно описать поведение?

**Comment by a1exsan** [comment]
У меня ИИС. Система выдает торговый токен

**Comment by daxartio** [comment]
Значит нужно явно передать account id

**Comment by a1exsan** [comment]
Как его передать? И где его взять?

ошибка 500 - это внутренняя проблема сервера?
может быть так, что сервер блокирует мой акаунт?

**Comment by ddmrtc** [comment]
Получить через get accounts

Вт, 23 нояб. 2021 г. в 09:52, a1exsan ***@***.***>:

**Comment by AlexanderVolkovTCS** [comment]
>ошибка 500 - это внутренняя проблема сервера?

Счет по-умолчанию это обычный торговый, а не ИИС.
В Вашем случае его видимо нет, поэтому система возвращает Unknown account


>Получить через get accounts

Да. спасибо.
