### ISSUE TITLE
Отвалился Swagger

### ISSUE THREAD

**Issue by mdima77** [TinkoffCreditSystems/invest-openapi#635]
> В директории src/ хранится документация в формате Markdown. Описание REST-протокола можно отредактировать в src/docs/swagger-ui/swagger.yaml.

Файла src/docs/swagger-ui/swagger.yaml нет, поэтому:

<img width="1423" alt="Снимок экрана 2021-11-26 144132" src="https://user-images.githubusercontent.com/2885819/143568522-56f110a1-bf43-42ca-bb14-59a2bd4232a7.png">

**Comment by AlexanderVolkovTCS** [comment]
Обновили сваггер.

**Comment by sergey-crusher** [comment]
> Обновили сваггер.

Сейчас он по крайней мере не работает

**Comment by BaryshevS** [comment]
ты туда не ходи. сюда ходи 
https://tinkoff.github.io/invest-openapi/swagger-ui/

**Comment by sergey-crusher** [comment]
> ты туда не ходи. сюда ходи https://tinkoff.github.io/invest-openapi/swagger-ui/

Благодарю =)
