### ISSUE TITLE
По streaming перестали приходить данные

### ISSUE THREAD

**Issue by polkila** [TinkoffCreditSystems/invest-openapi#637]
Начиная примерно с 2021-11-30 13:00 перестали приходить данные по streaming протоколу:
-Подписка на orderbook, candles или instrument_info;
-не влияет на ситуацию Token или SanboxToken;

После отправки "subscribe" сразу приходит пустая строка "", и далее — тишина.

**Comment by polkila** [comment]
в 15:03 восстановилось

**Comment by sergeymavrin** [comment]
Подтверждаю - в 12:54:34 разорвало коннект по стриммингу и больше не смогло подключиться - ответы были не в JSON при candle:subscribe

**Comment by polkila** [comment]
TSLA, AAPL, GTHX.
Редко приходят данные:
2021-11-30 18:29:13 orderbook TSLA {
  figi: 'BBG000N9MNX3',
  depth: 1,
  bids: [ [ 1162.17, 280 ] ],
  asks: [ [ 1162.34, 380 ] ]
}
2021-11-30 18:29:55 orderbook TSLA {
  figi: 'BBG000N9MNX3',
  depth: 1,
  bids: [ [ 1162.68, 280 ] ],
  asks: [ [ 1163, 320 ] ]
}
2021-11-30 18:30:41 orderbook TSLA {
  figi: 'BBG000N9MNX3',
  depth: 1,
  bids: [ [ 1164.14, 280 ] ],
  asks: [ [ 1164.17, 12 ] ]
}
2021-11-30 18:31:17 orderbook TSLA {
  figi: 'BBG000N9MNX3',
  depth: 1,
  bids: [ [ 1163.01, 2 ] ],
  asks: [ [ 1163.15, 323 ] ]
}
2021-11-30 18:31:51 orderbook TSLA {
  figi: 'BBG000N9MNX3',
  depth: 1,
  bids: [ [ 1163.24, 110 ] ],
  asks: [ [ 1163.4, 380 ] ]
}
2021-11-30 18:32:12 status TSLA {
  figi: 'BBG000N9MNX3',
  trade_status: 'normal_trading',
  min_price_increment: 0.01,
  lot: 1,
  limit_up: 1189.02,
  limit_down: 1138.98
}

**Comment by ultimatesolution** [comment]
2 декабря 2021, в 12:29 MSK -- перестали перестали приходить данные по streaming протоколу, подписка orderbook:subscribe.

Когда ожидается решение проблемы?

**Comment by polkila** [comment]
Даже раньше: примерно в 12:11. И свечи молчат. Вся подписка молчит.

**Comment by polkila** [comment]
Свечи по-тихоньку ожили, стаканы и статусы молчат.
@AlexanderVolkovTCS , порекомендуйте, пожалуйста, дальнейшие действия. Есть альтернативный стриминг?

**Comment by AlexanderVolkovTCS** [comment]
Было обновление, задевшее часть пользоваталей. 
Сейчас работа стримов нормализовалась.

>дальнейшие действия

1. работаем над уменьшением лага при открытии на старой версии стриминга
2. в v2 таких проблем быть не должно

**Comment by polkila** [comment]
> 1. работаем над уменьшением лага при открытии на старой версии стриминга

В данный момент лаг стабильный по 40 сек:
2021-12-02 18:04:11 MU orderbook
2021-12-02 18:04:52 MU orderbook
2021-12-02 18:05:34 MU orderbook
2021-12-02 18:06:12 MU orderbook
2021-12-02 18:06:53 MU orderbook
