### ISSUE TITLE
Не срабатывает отписка от стакана

### ISSUE THREAD

**Issue by polkila** [TinkoffCreditSystems/invest-openapi#638]
На эти стаканы был предварительно подписан. Затем пробовал отписаться. Отписка не срабатывала. Обновления продолжали приходить.

Когда отправляю с параметром "depth": "1" по [документации](https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/#orderbookunsubscribe). Ответ:
{ payload: 
   { error: 'Subscription orderbook:unsubscribe. Invalid format: {"event": "orderbook:unsubscribe", "figi": "BBG000B9XRY4", "depth": "1"}' },
  event: 'error',
  time: '2021-12-01T10:36:44.546721528Z' 
}

Когда отправляю с параметром "depth": "20". Ответ:
{
  payload: {
    error: 'Subscription orderbook:unsubscribe. Invalid format: {"event": "orderbook:unsubscribe", "figi": "BBG005F1DK91", "depth": "20"}'
  },
  event: 'error',
  time: '2021-12-01T10:44:53.893382947Z'
}

Когда отправляю без параметра depth. Ответ:
{ payload: 
   { error: 'Subscription orderbook:unsubscribe. Invalid depth 0. Should be 0 < x < 20' },
  event: 'error',
  time: '2021-11-30T17:34:42.717079799Z' }

**Comment by AlexanderVolkovTCS** [comment]
Попробуйте 
_"depth": 1_ 
без кавычек

**Comment by polkila** [comment]
> Попробуйте _"depth": 1_ без кавычек

Так срабатывает, спасибо
