### ISSUE TITLE
Ограничение количества запросов

### ISSUE THREAD

**Issue by DiktatorDNS3018** [TinkoffCreditSystems/invest-openapi#641]
Добрый день, прошу рассмотреть возможность увеличения лимита запросов в rest для всех пользователей, или как минимум в индивидуальном порядке для тех, кто этого попросит.
Лично мне это позволило бы включить несколько роботов на счёте сразу, и увеличить обороты в несколько раз соответственно, а пока, давят ограничения, в особенности лимит на выставление и снятие заявок.
В QUIK, к примеру, на московскую биржу уходит до 30 заявок в секунду, на СПБ бирже точные цифры не замерял, но думаю всё-же более 2 в секунду.
Здесь тоже хотелось бы увидеть показатели повыше, это на самом деле будет полезно.

+ Очень жду мультисчета в API

**Comment by BaryshevS** [comment]
Такое не позволят. Делай выставление через единую функцию с расчетом rps по ендпоинтам, будет все хорошо.
Если нужна высокачастотка - это уже лучше прямое подключение к бирже и plaza II, fix/fast.
https://smart-lab.ru/blog/695395.php
https://www.moex.com/s154
Ограничения в части MOEX это внешнее ограничение напрямую от биржи. Тут тоже ничего не смогут сделать.

Тинькофф в данный момент не выдержит подобных нагрузок.
И так-то в пиках нагрузки падает :(
Не нужно API добивать скальпингом.

**Comment by DiktatorDNS3018** [comment]
> Такое не позволят. Делай выставление через единую функцию с расчетом rps по ендпоинтам, будет все хорошо. Если нужна высокачастотка - это уже лучше прямое подключение к бирже и plaza II, fix/fast. https://smart-lab.ru/blog/695395.php https://www.moex.com/s154 Ограничения в части MOEX это внешнее ограничение напрямую от биржи. Тут тоже ничего не смогут сделать.
> 
> Тинькофф в данный момент не выдержит подобных нагрузок. И так-то в пиках нагрузки падает :( Не нужно API добивать скальпингом.

Спасибо, только мне даже и не высокочастотка нужна, просто робот работает на 100-150 акциях одновременно, по каждой 1-2 заявки, и пока заявки утром выставятся, проходит обычно 10-20 минут, а то и больше, когда лаги. Да и часть заявок не с первого раза выставляются, в итоге первый час только на начало работы уходит, это не критично, но неприятно.
А если новые алгоритмы добавлять, и больше инструментов, то совсем грусть будет
Работаю на СПБ бирже в основном

Через апи тинькова удобно получать котировки по куче разных инструментов, от того и использую

**Comment by BaryshevS** [comment]
https://tinkoffcreditsystems.github.io/invest-openapi/rest/
Выставление ордеров 100 в минуту.
Выставили - получили id.
Дальше асинхронно уже проверяйте этот id в orders и operations и отслеживайте статус price и кол-во исполненного.
Выставляются ордера очень резво.

Выставили, если сразу ошибки нет, то и продолжайте выставлять.
ну и выставляйте с 9:50, а не ровно в 10:00 в самый пик.

**Comment by sergeymavrin** [comment]
Ордера выставляются быстро, а вот запрос на баланс кэша в портфеле иногда очень долго - запрос может по 10-15 секунд проходить, а запрашивать его приходится достаточно часто, чтобы знать сколько там свободного кэша.
Сейчас робот работает с 60 инструментами, но планирую увеличивать и лимита будет не хватать. Тоже хотелось бы увидеть увеличение лимитов, причём не на IP, а на аккаунт, т.к. работаю с одного аккаунта

**Comment by BaryshevS** [comment]
Ну portfolio - да. бывает знатно тупит. Ну его и не нужно каждую секунду запрашивать :) Арифметику не нужно перекладывать на Тинькофф. Там все печально с этим. (многое криво считают. средняя по fifo, да и вообще крайне долго обновляют. может быть от прошлых трейдов, потом обновляется)

**Comment by sergeymavrin** [comment]
Когда идёт активная торговля, то может быть и каждую секунду. А со средней - да, тоже засада, но т.к. у моего робота нет БД, а в каждый запуск(хотя это бывает очень редко) вытягивать всю историю по инструменту и высчитывать среднюю - тоже проблематично.

**Comment by BaryshevS** [comment]
Ну храни/обновляй баланс хотя бы в мемкеше или redis. Не полагайся на стабильность работы тинькофф :(

**Comment by sergeymavrin** [comment]
в том то и дело, что не хотелось базу завозить. Ну а на стабильность тинькофф я уже давно не полагаюсь, и так больше половины кода - проверки правильности данных от него ))

**Comment by AlexanderVolkovTCS** [comment]
Скоро будут и увеличенные лимиты и мультисчета (#533 )
