### ISSUE TITLE
Задержка данных в начале вечерней сессии (17.30 Msk) через API

### ISSUE THREAD

**Issue by solalx** [TinkoffCreditSystems/invest-openapi#642]
Последние минимум 2 месяца идет задержка данных в начале вечерней сессии при получении через Tinkoff.Trading.OpenApi
Задержка минимум на 15 минут в течении первого часа (1.5 часа) вечерней сессии (с 17.30 Msk). Переприсоединение не помогает. Дальше, через час (~с 18.30 Msk) мгновенно выравнивается и данные синхронизируются с реальностью.
По видимому, на стороне сервера буфер с устаревшими данными?
Данные получаю в виде подписки на дневные свечи. Тестировал на подписке на дневные свечи даже на одном инструменте.
Получается полностью неработоспособный инструмент!!!
Есть ли перспектива исправления ситуации?

**Comment by rus-art** [comment]
Вопрос не относится к dotnet клиенту, перевожу в основной репозиторий

**Comment by AlexanderVolkovTCS** [comment]
Исправление в процессе, оптимизируем, #636
