### ISSUE TITLE
Выгрузка динамики изменения портфеля

### ISSUE THREAD

**Issue by JonS87** [TinkoffCreditSystems/invest-openapi#645]
Подскажите пожалуйста имеет ли возможность выгрузить данные на основе которых строится график в разделе портфельная аналитика -> портфель? И если есть то как?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, именно эти цифры для построения графика пока выгрузить нельзя, Если нужно узнать стоимость портфеля на определенный момент времени, то можно выгрузить список операций и свечи со стоимостями бумаг на этот момент.

**Comment by BaryshevS** [comment]
Так нельзя....

выгружаются только 3 валюты. не выгружаются фьючерсы. Часть операций не видны в операциях (например овернайты).
