### ISSUE TITLE
Проблема при получении исторических свечей

### ISSUE THREAD

**Issue by Voucik** [TinkoffCreditSystems/invest-openapi#646]
Добрый вечер.
Делю запрос в сваггере:
![image](https://user-images.githubusercontent.com/6031632/146264356-ec80a18a-b812-4318-afa6-e03684a08fb5.png)
Выдает ошибку:
Error: response status is 500
Response body
Download
{
  "trackingId": "aebbad75eb4e81f6",
  "payload": {
    "message": "[to]: Bad candle interval: from=2021-12-20T00:00:00Z to=2021-01-04T00:00:00Z expected from 7 days to 2 years",
    "code": "VALIDATION_ERROR"
  },
  "status": "Error"
}
![image](https://user-images.githubusercontent.com/6031632/146264543-62bc093a-568b-4149-8008-dc3f62bf6d9d.png)
И не понятно, почему в ответе совсем другие даны (не те, которые я указал).

**Comment by Voucik** [comment]
Разобрался, даты надо было в обратном порядке указать, от меньшей к большей

**Comment by sergeymavrin** [comment]
@Voucik поменяй токен и не свети его больше )
