### ISSUE TITLE
Как скоро новый счет становится видим для API?

### ISSUE THREAD

**Issue by zhuchenko-w** [TinkoffCreditSystems/invest-openapi#649]
После открытия нового брокерского счета он невидим для методов API, хотя видим и в мобильном приложении, и в вебе (со времени активации счета прошло полтора часа на момент написания).

Запрос /user/accounts возвращает все счета, кроме нового, запрос /portfolio возвращает ошибку 500:
```
{
  "payload": {
    "message": "Unknown account",
    "code": "GATEWAY_REQUEST_DATA_ERROR"
  },
  "status": "Error"
}
```

Через какое время ожидать появления информации по новому счету в системе?

UPD: спустя сутки после активации счет все еще недоступен в API

**Comment by AlexanderVolkovTCS** [comment]
Поддержки мультисчетов в существующей версии api нет:

#533
