### ISSUE TITLE
MassCancel/Cancel on disconnect

### ISSUE THREAD

**Issue by ffilosoff** [TinkoffCreditSystems/invest-openapi#66]
Хотелось бы иметь возможность отменить все заказы:
1. В случае разрыва соединения
2. Иметь возможность отменить все заказы с помощью специального сообщения

Есть ли/планируется такая функциональность?

**Comment by NikitaMelnikov** [comment]
Добрый день,

Не планируется.

Мотивация:
Потерянное соединение со стороны робота может не означать потерянное соединение со стороны сервера, это может быть довольно продолжительный временной лаг.
Плюс не очень очевидно для сервера, будет ли переподключаться робот или его заявки нужно снимать.
