### ISSUE TITLE
Возможность получать и устанавливать уведомления по цене акций

### ISSUE THREAD

**Issue by newyorrker** [TinkoffCreditSystems/invest-openapi#67]
Хотелось бы видеть в api функционал с помощью которого можно было получить доступ к управлению уведомлениями

- Метод для установки уведомления
- Метод(ы) для получения статуса установленного уведомления (websocket?)

**Comment by NikitaMelnikov** [comment]
Добрый день, уведомление о достижении цены?

**Comment by newyorrker** [comment]
Добрый день, да верно

**Comment by NikitaMelnikov** [comment]
Рассмотрим

**Comment by newyorrker** [comment]
спасибо

**Comment by koshkoshka** [comment]
так ставьте прямо в коде своего робота.

**Comment by NikitaMelnikov** [comment]
Согласен с @koshkoshka, подобная функциональность ложится на простое подключение к стриму и уведомление вас по любому удобному каналу связи.

Пока что решили не реализовывать.
