### ISSUE TITLE
Разные figi для одного тикера

### ISSUE THREAD

**Issue by svladykin** [TinkoffCreditSystems/invest-openapi#68]
Пробую использовать java-sdk. Делаю простую `Strategy` и запускаю в `StrategyExecutor`. 
Для каждого тикера, на который я подписываюсь, приезжают события с разными figi.

Например для яндекса:
```
FIGI | TICKER
BBG000QJW156 | YNDX
BBG000R607Y3 | YNDX
BBG004730N88 | YNDX
BBG004730RP0 | YNDX
BBG004730ZJ9 | YNDX
BBG004731032 | YNDX
BBG004731354 | YNDX
BBG0047315Y7 | YNDX
BBG004RVFCY3 | YNDX
BBG004RVFFC0 | YNDX
BBG004S683W7 | YNDX
BBG004S68473 | YNDX
BBG004S684M6 | YNDX
BBG004S686W0 | YNDX
BBG004S68758 | YNDX
BBG006L8G4H1 | YNDX
BBG008F2T3T2 | YNDX
```
И цены в стакане у них у всех разные.
Это так и было задумано? 
Где можно посмотреть какой figi что значит? Гугл ничего не находит.

При этом, если я делаю `context.searchMarketInstrumentsByTicker("YNDX")` то находится только один с figi `BBG006L8G4H1`.

**Comment by NikitaMelnikov** [comment]
Добрый день, а как воспроизвести поведение? 
Поиск по BBG004730N88 выдает SBER

```
curl -X GET "https://api-invest.tinkoff.ru/openapi/market/search/by-figi?figi=BBG004730N88" -H  "accept: application/json" -H  "Authorization: Bearer {TOKEN}"
```

```
{
  "trackingId": "75b5ec553707d4ee",
  "payload": {
    "figi": "BBG004730N88",
    "ticker": "SBER",
    "isin": "RU0009029540",
    "minPriceIncrement": 0.01,
    "lot": 10,
    "currency": "RUB",
    "name": "Сбербанк России"
  },
  "status": "Ok"
}
```

**Comment by svladykin** [comment]
Это в стриме приходят данные для разных figi.

Сначала делаю `context.searchMarketInstrumentsByTicker("YNDX")` - возвращается один инструмент. 

Создаю  `Strategy` c этим инструментом и запускаю в `StrategyExecutor` - в стратегию начинают приходить события для разных figi с тем же тикером.

Сейчас просто фильтрую события внутри стратегии по figi инструмента.

**Comment by NikitaMelnikov** [comment]
Могли бы привести подробный пример последовательности запуска с командами/кодом? НЕ могу воспроизвести
