### ISSUE TITLE
Нет возможности вывести имя торгового инструмента 

### ISSUE THREAD

**Issue by BVV13** [TinkoffCreditSystems/invest-openapi#71]
Искал долго, но так и не нашел пример получения названия торгового инструмента по его FIFI или ISIN. Предлагаю выложить и этот пример.

**Comment by NikitaMelnikov** [comment]
И вновь не тот репозиторий, https://github.com/TinkoffCreditSystems/invest-openapi-go-sdk/issues/6

**Comment by NikitaMelnikov** [comment]
Добавлено в go-sdk v0.2.1
