### ISSUE TITLE
Сводка прогнозов и идей

### ISSUE THREAD

**Issue by swing1991** [TinkoffCreditSystems/invest-openapi#75]
Было бы полезно иметь возможность получать сводку прогнозов аналитиков и идей, которая выводится в торговом терминале. 
Также было бы круто через ваше API получать сводку новостей по бумаге.

Это нужно, чтобы понимать общее настроение людей с "умными деньгами" и понимать тональность новостей, как один из критериев входа в сделку.

**Comment by NikitaMelnikov** [comment]
На данный момент мы не планируем подобную функциональность в OpenApi, сконцентрируемся на функциональности для торговли.
