### ISSUE TITLE
Непонятный ответ /market/orderbook (облигации) 

### ISSUE THREAD

**Issue by NikitaMelnikov** [TinkoffCreditSystems/invest-openapi#77]
> Метод /market/orderbook возвращает непонятные цены (lastPrice, closePrice) по облигациям (цена/10):
> Например:
> 'BBG00PYL6030' (Белуга Групп)
> /market/bonds
> {'figi': 'BBG00PYL6030', 'ticker': 'RU000A100L63', 'isin': 'RU000A100L63', 'minPriceIncrement': 0.01, 'lot': 1, 'currency': 'RUB', 'name': 'Белуга Групп выпуск 1'}
> /market/orderbook
> {'figi': 'BBG00PYL6030', 'depth': 5, 'tradeStatus': 'NotAvailableForTrading', 'minPriceIncrement': 0.01, 'lastPrice': 105.47, 'closePrice': 105.47, 'bids': [], 'asks': []}
> Хотя в терминале
> image
> 
> Непонятно почему 'lastPrice' = Цена/10
> Также непонятно, как выйти на стоимость отображаемую в терминале и мобильном приложении
> 
> Аналогичная ситуация и по остальным облигациям

https://github.com/TinkoffCreditSystems/invest-openapi-java-sdk/issues/59

**Comment by triamazikamno** [comment]
Это не 1/10, а цена в % от номинальной стоимости, также показывает Московская Биржа: https://www.moex.com/ru/issue.aspx?board=EQOB&code=RU000A100L63

К вопросу присоединяюсь. Неплохо бы хотябы номинальную стоимость получать в ответе, чтобы можно было умножить и получить цену как в терминале.

**Comment by NikitaMelnikov** [comment]
https://github.com/TinkoffCreditSystems/invest-openapi/releases/tag/20.1
