### ISSUE TITLE
Где в API сптяраны фонды (ETF )?

### ISSUE THREAD

**Issue by scythargon** [TinkoffCreditSystems/invest-openapi#78]
Привет, ребята! Спасибо за АПИ!
Ищу по получаемому списку валют и не могу найти FXMM / FXIT фонды. Подскажите пожалуйста - они поддерживаются?
UPD: по ISIN коду тоже не нашел. Есть опасение что фонды АПИ не поддерживает:(

**Comment by maksim77** [comment]
Ничего не понял.
Есть метод GET `/market/etfs` который возвращает список всех ETF. Там есть и FXMM и FXIT. В нём можно посмотреть правильный figi для фонда. Например для FXIT - BBG005HLTYH9.

А дальше уже обычным методом получаем данные о бумаге
