### ISSUE TITLE
candle:subscribe несколько тиков в интервал

### ISSUE THREAD

**Issue by fxfoxy** [TinkoffCreditSystems/invest-openapi#8]
Пробую использовать OpenApi (https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/) **candle:subscribe** для получения данных по тикам. Проблема в том, что на любом интервале (1-3 минуты) тики приходят несколько раз в минуту, а не раз в интервал. Использую тестовый ключ. Прилагаю логи.
[streaming-client.log](https://github.com/TinkoffCreditSystems/invest-openapi/files/3706388/streaming-client.log)

**Comment by NikitaMelnikov** [comment]
Привет!

В стриминге в подписке на свечи всегда последняя свеча на графике транслируется. Меняется она в зависимости от сделок на рынке.
Когда интервал закрывается начинается трансляция новой свечи и так далее.

https://ru.wikipedia.org/wiki/Японские_свечи

**Comment by fxfoxy** [comment]
Привет) Похоже я не понимал концепцию candle:subscribe. Я думал, что результаты можно использовать вроде метронома с заданным интервалом. А она позволяет получать всегда актуальную свечу за заданный интервал. Тогда не совсем понятно, зачем нужны сокеты? Почему не RestApi?

И ещё технический вопрос. Получив данные по текущей свече, я закрываю соединение - отключаюсь. При отключении клиента происходит автоматическая отмена подписки? Или нужно каждый раз вызывать candle:unsubscribe? И что будет, если отключиться и не вызватьunsubscribe?

**Comment by fxrlv** [comment]
сервер хранит подписки для текущего коннекта, если коннект закрыть и восстановить, то подписки нужно восстанавливать

если собрался рвать соединение, то `unsubscribe` делать не нужно

**Comment by NikitaMelnikov** [comment]
>  А она позволяет получать всегда актуальную свечу за заданный интервал. Тогда не совсем понятно, зачем нужны сокеты?

Для того чтобы получать актуальные данные, когда данные приходят с биржи, вы их получите в сокете

**Comment by NikitaMelnikov** [comment]
> И ещё технический вопрос. Получив данные по текущей свече, я закрываю соединение - отключаюсь. При отключении клиента происходит автоматическая отмена подписки? 

@fxrlv прав, при обрыве коннекта, подписки удаляются

**Comment by fxfoxy** [comment]
Спасибо за информацию!
