### ISSUE TITLE
Разрешение свечей на исторических данных

### ISSUE THREAD

**Issue by GolovanovSrg** [TinkoffCreditSystems/invest-openapi#82]
Сейчас максимальное разрешение для свечей на промежутке времени больше дня - один день. Можно сделать хотя бы час? В идеале - минута.

**Comment by NikitaMelnikov** [comment]
Пока что не планируем так делать, предлагаю просто сделать скользящее окно дат и получать в их рамках свечи меньшего разрешения, чем доступно
