### ISSUE TITLE
C# API: не работают некоторые методы

### ISSUE THREAD

**Issue by AndrewRomashkin** [TinkoffCreditSystems/invest-openapi#84]
Пытаюсь разобраться с C# API. Пробую получить историю котировок:

```
SandboxContext context = ConnectionFactory.GetSandboxConnection(<Token>).Context;
MarketInstrument instrument = context.MarketSearchByTickerAsync("AMD").Result.Instruments[0];
DateTime start = DateTime.ParseExact("17.12.2019 16:00:00", "dd.MM.yyyy HH:mm:ss", CultureInfo.InvariantCulture);
DateTime end = DateTime.ParseExact("17.12.2019 17:00:00", "dd.MM.yyyy HH:mm:ss", CultureInfo.InvariantCulture);
CandleList candles = context.MarketCandlesAsync(instrument.Figi, start, end, CandleInterval.Minute).Result;
```

Получаю исключение: MALFORMED_QUERY_PARAMETER: Неверный формат поля 'from' в запросе (b7cd8d9d3d8f1745).

Также пробую выставить лимитную заявку:
`PlacedLimitOrder response = context.PlaceLimitOrderAsync(new LimitOrder(instrument.Figi, 1, OperationType.Buy, 47.1m)).Result;`

Получаю: INTERNAL_ERROR: INTERNAL_ERROR (dec729bea659e37a).

Подскажите, пожалуйста.

**Comment by NikitaMelnikov** [comment]
Добрый день, 

В параметрах `start` и `end` для `/market/candles` нужно передавать TimeZone, посмотрите на пример https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_candles

По лимитной заявке:
Вы выполнили метод регистрации в sandbox? https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/sandbox/post_sandbox_register

**Comment by AndrewRomashkin** [comment]
Заработало, спасибо!
