### ISSUE TITLE
Возможно ли исключить из списка облигаций все, которые относятся к расширенному списку

### ISSUE THREAD

**Issue by InfernumDeus** [TinkoffCreditSystems/invest-openapi#85]
Через MarketBondsAsync() получил список из 399 облигаций.
Обнаружил, что не все облигации из этого списка доступны - ищу по тикеру XS0504954347 - ничего нет.

Выяснил, что это еврооблигация минфина:
https://www.moex.com/ru/issue.aspx?code=XS0504954347

Как понимаю, она входит в расширенный список инструментов.
Возможно ли как-то исключить такие инструменты из имеющегося списка?

**Comment by NikitaMelnikov** [comment]
> Обнаружил, что не все облигации из этого списка доступны

Вы имеете ввиду что бонд доступен в общем списке https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_bonds, но недоступны в https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/market/get_market_search_by_ticker?

**Comment by InfernumDeus** [comment]
Не проверял через /market/get_market_search_by_ticker , но, в мобильном приложении и веб терминале поиск не находит XS0504954347.

Возможно, ошибка в том, что он, на самом деле, должен выводиться в обоих приложениях, но не этого не происходит.

И попутный вопрос. Все ли боды, получаемые через /market/get_market_bonds , доступны без доступа к расширенному списку (тариф премиум)?

**Comment by NikitaMelnikov** [comment]
> Все ли боды, получаемые через /market/get_market_bonds , доступны без доступа к расширенному списку (тариф премиум)?

Расширенный список недоступен
