### ISSUE TITLE
Результат /market/get_market_bonds возвращает не все ОФЗ

### ISSUE THREAD

**Issue by InfernumDeus** [TinkoffCreditSystems/invest-openapi#86]
Записал список, получаемый через `/market/get_market_bonds`: [bonds.txt](https://github.com/TinkoffCreditSystems/invest-openapi/files/4023203/bonds.txt)

Сверил его со сторонним списком российских бондов и обнаружил, что список содержит не все ОФЗ. 

А именно, не были найдены следующие:
ОФЗ 25083 	RU000A0ZYCK6
ОФЗ 26205 	RU000A0JREQ7
ОФЗ 26207 	RU000A0JS3W6
ОФЗ 26209 	RU000A0JSMA2
ОФЗ 26211 	RU000A0JTJL3
ОФЗ 26212 	RU000A0JTK38
ОФЗ 26214 	RU000A0JTYA5
ОФЗ 26215 	RU000A0JU4L3
ОФЗ 26217 	RU000A0JVW30
ОФЗ 26218 	RU000A0JVW48
ОФЗ 26219 	RU000A0JWM07
ОФЗ 26220 	RU000A0JXB41
ОФЗ 26221 	RU000A0JXFM1
ОФЗ 26222 	RU000A0JXQF2
ОФЗ 26223 	RU000A0ZYU88
ОФЗ 26224 	RU000A0ZYUA9
ОФЗ 26225 	RU000A0ZYUB7
ОФЗ 26226 	RU000A0ZZYW2

Смог найти в полученном через OpenAPI списке только долларовый ОФЗ - XS0088543193.

**Comment by InfernumDeus** [comment]
В мобильном приложении и терминале они доступны.

**Comment by NikitaMelnikov** [comment]
Для `RU000A0JS3W6` данные возвращаются, нужно смотреть на поле isin
<img width="1418" alt="Снимок экрана 2020-01-09 в 17 22 46" src="https://user-images.githubusercontent.com/1418845/72075406-bbb04a80-3304-11ea-9466-3f50316dc49a.png">
