### ISSUE TITLE
метод candles время московское? 

### ISSUE THREAD

**Issue by ruzzzz6312** [TinkoffCreditSystems/invest-openapi#88]
Возможно упустил где, пересмотрел все и вся, не нахожу указания, какое время используется.

**Comment by ruzzzz6312** [comment]
вижу в примерах Z, значит ли это, что время UTC?/GMT

**Comment by NikitaMelnikov** [comment]
Привет, Z - это время UTC

https://en.wikipedia.org/wiki/ISO_8601
