### ISSUE TITLE
Поддержка ИИС

### ISSUE THREAD

**Issue by maksim77** [TinkoffCreditSystems/invest-openapi#9]
Очень не хватает поддержки ИИС'а. Например у меня в сервисе брокерский счёт не используется, только ИИС.

**Comment by Grapaf** [comment]
> Привет,
> 
> Такая возможность появится в одном из следующих релизов, мы работаем на этим

А есть какие-то планируемые сроки появления этой фичи? Хотя бы примерные, вида "через 2-3 месяца" или "во второй половине следующего года"...

**Comment by NikitaMelnikov** [comment]
Думаю появится в течение 2 месяцев, возможно раньше

**Comment by maksim77** [comment]
Просто пожелание в догонку к исходному issue. А вы не могли бы передать аналогичный запрос команде что делает Пульс? У многих открыт только ИИС, а он в профиле не отображается.

**Comment by NikitaMelnikov** [comment]
Конечно, отправил коллегам

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 609i** [comment]
До конца года успеем. Я бы хотел успеть закрыть ИИС в открывашке и открыть в Тинькофф.

**Comment by NikitaMelnikov** [comment]
Похоже не успеваем в этом году, появится сразу после НГ

**Comment by NikitaMelnikov** [comment]
> До конца года успеем. Я бы хотел успеть закрыть ИИС в открывашке и открыть в Тинькофф.

OpenApi не мешает открыть ИИС :)

**Comment by andrey-str** [comment]
Привет! Есть новости по теме? Дата релиза? Спасибо.

**Comment by NikitaMelnikov** [comment]
@andrey-str до конца месяца будет релиз, анонс будет в телеграм-канале

**Comment by NikitaMelnikov** [comment]
Released

**Comment by maksim77** [comment]
Отлично! Спасибо.

@NikitaMelnikov возник вопрос по архитектуре этой части API. У каждого пользователя в "Инвестициях" может быть только два счёта - брокерский и ИИС. Во всяком случае так сказала тех. поддержка. Так зачем передавать номер договора как атрибут запроса? Почему не передать тот же самый `brokerAccountType` (`TinkoffIis` или `Tinkoff`)?
Ведь по сути мы делаем лишний запрос чтобы получить цифры ID аккаунта которые нигде толком не нужны и однозначно мапятся на их тип.

P.S. Само собой это не мешает работе с новым API, просто любопытство.

**Comment by NikitaMelnikov** [comment]
Ну сегодня всего два счета, завтра три или пять и одинаковых типов :)

Рекомендую один раз запросить `/user/accounts` и куда-нибудь сохранить его Id, по аналогии с хранением токена

**Comment by maksim77** [comment]
@NikitaMelnikov твои слова да руководству в уши. Я бы очень хотел иметь возможность создать два счёта...

**Comment by asakharov** [comment]
У всех всё работает?)
У меня почему-то /user/accounts работает только с sandbox токеном. Причем возвращает два аккаунта, у обоих тип Tinkoff. Хотя я ожидал TinkoffIis.
А с продакшен токеном просто фейлится с ошибкой
`{
  "trackingId": "83042f21236a8b93",
  "payload": {
    "message": "Unknown account",
    "code": "GATEWAY_REQUEST_DATA_ERROR"
  },
  "status": "Error"
}`

**Comment by maksim77** [comment]
Я проверял в swagger'е. Возвращался нормальный ответ.

**Comment by asakharov** [comment]
@maksim77  я и в швагере, и код написал... Получил ошибку. А в песочнице - работает.

**Comment by NikitaMelnikov** [comment]
@asakharov проверил ваш случай. Действительно есть проблема, если открыт только ИИС без брокерского счета, то возвращается ошибка при получении `/user/account`.

Занимаемся починкой

**Comment by NikitaMelnikov** [comment]
@asakharov починили #102 
Проверьте, пожалуйста
