### ISSUE TITLE
Добавить поле instrumentType для результатов поиска

### ISSUE THREAD

**Issue by maksim77** [TinkoffCreditSystems/invest-openapi#91]
Предлагаю добавить в вывод методов `/market/search/by-figi` и `/market/search/by-ticker` добавить поле `instrumentType` по аналогии с портфелем.

А то найти нашёл, а что это за инструмент нет возможности определить. Конечно можно запросить списки фондов/акций/облигаций и поискать там то что вернулось но как-то это не логично кмк.

**Comment by lightning95** [comment]
Здравствуйте, 
было добавлено поле **type**
