### ISSUE TITLE
Можно ли работать с ИСС?

### ISSUE THREAD

**Issue by swytman** [TinkoffCreditSystems/invest-openapi#95]
Добрый день, у меня есть Брокерский счет и ИСС, при запросе GET /portfolio приходят данные только брокерского счета. Никаких параметров не нашел. Можно ли как-то работать с ИСС?

**Comment by maksim77** [comment]
Посмотрите другие issue. Дубликат с #9. 

Пока нельзя, скоро будет можно.

**Comment by swytman** [comment]
Оу, не заметил, извиняюсь. Спасибо!
