### ISSUE TITLE
Возможно ли получение данных меньшего таймфрема, чем 1 минута?

### ISSUE THREAD

**Issue by proairat** [TinkoffCreditSystems/invest-openapi#97]
Почему если вы используете стандарт ISO 8601 у вас нижняя граница таймфрейма составляет 1 минуту, в то время как этот стандарт предусматривает получение данных вплоть до миллисекунды? Предполагается ли в будущих релизах возможность получения данных меньшего таймфрема, чем 1 минута? Как получить данные меньшего временно таймфрейма посредством вашего OpenAPI?

**Comment by NikitaMelnikov** [comment]
О каких методах получения данных речь?

**Comment by proairat** [comment]
На данный момент, про метод OpenAPI.prototype.candlesGet веду речь. 

Также касаемо стандарта, вы сами приводите в примере по ссылке https://github.com/TinkoffCreditSystems/invest-openapi-js-sdk/blob/master/example/index.js 
 следующий код: "...console.log(
    await api.candlesGet({
      from: '2019-08-19T18:38:33.131642+03:00',
      to: '2019-08-19T18:48:33.131642+03:00',
      figi,
      interval: '1min',
    }) // Получаем свечи за конкретный промежуток времени.
  );...". Почему в этом примере присутствует отсылка к микросекундам 2019-08-19T18:38:33.**131642**+03:00, хотя на деле минимальное значение интервала 1 минута?

**Comment by NikitaMelnikov** [comment]
Потому что это просто формат даты, не больше :)
